"""Ordered merge and reconciliation roots for DPR expansion v2."""

from __future__ import annotations

from w8_biayn.integrations.moonlight_dpr_v2_cases import DprCase, _case


SPARSE_VECTOR_CLONE = _case(
    "control-sparse-vector-dimensional-wrapper", "SparseVectorCancellation", "Sparse vector dimensional wrapper", "control",
    "class SparseVectorCancellation { public: struct Term{std::size_t index;long long value;bool operator==(const Term&o)const{return index==o.index&&value==o.value;}}; static std::optional<std::vector<Term>> merge(std::size_t dimension,const std::vector<std::vector<Term>>& shards); };",
    "std::optional<std::vector<SparseVectorCancellation::Term>> SparseVectorCancellation::merge(std::size_t dimension,const std::vector<std::vector<Term>>& shards){std::map<std::size_t,long long> totals;for(const auto&s:shards){std::size_t previous=0;bool first=true;for(auto t:s){if(t.index>=dimension||(!first&&t.index<=previous))return std::nullopt;first=false;previous=t.index;long long value=0;if(__builtin_add_overflow(totals[t.index],t.value,&value))return std::nullopt;totals[t.index]=value;}}std::vector<Term> out;for(auto t:totals)if(t.second)out.push_back({t.first,t.second});return out;}",
    "std::optional<std::vector<SparseVectorCancellation::Term>> SparseVectorCancellation::merge(std::size_t,const std::vector<std::vector<Term>>&){return std::nullopt;}",
    "using T=SparseVectorCancellation::Term;auto r=SparseVectorCancellation::merge(5,{{{1,4},{3,2}},{{1,-4},{2,7}}});check(r&&*r==std::vector<T>({{2,7},{3,2}}));",
    "using T=SparseVectorCancellation::Term;check(!SparseVectorCancellation::merge(2,{{{2,1}}}));check(!SparseVectorCancellation::merge(3,{{{1,1},{1,2}}}));auto e=SparseVectorCancellation::merge(0,{});check(e&&e->empty());",
    "if(t.second)out.push_back", "out.push_back",
    "one-dimensional wrapper around sorted sparse checked accumulation", "indices are bounded and zero cancellations disappear", "zero residues remain materialized",
)


CASES: tuple[DprCase, ...] = (
    _case(
        "dpr-loser-tree-run-merge", "LoserTreeRunMerge", "Loser tree run merge", "merge",
        "class LoserTreeRunMerge { public: struct Record{long long key;int origin;std::size_t ordinal;bool operator==(const Record&o)const{return std::tie(key,origin,ordinal)==std::tie(o.key,o.origin,o.ordinal);}}; static std::optional<std::vector<Record>> merge(const std::vector<std::vector<Record>>& runs); };",
        "std::optional<std::vector<LoserTreeRunMerge::Record>> LoserTreeRunMerge::merge(const std::vector<std::vector<Record>>& runs){for(std::size_t r=0;r<runs.size();++r)for(std::size_t i=0;i<runs[r].size();++i){if(runs[r][i].origin!=static_cast<int>(r)||runs[r][i].ordinal!=i)return std::nullopt;if(i&&std::tie(runs[r][i].key,runs[r][i].ordinal)<std::tie(runs[r][i-1].key,runs[r][i-1].ordinal))return std::nullopt;}std::vector<std::size_t> at(runs.size());std::vector<Record> out;for(;;){std::size_t winner=runs.size();for(std::size_t r=0;r<runs.size();++r)if(at[r]<runs[r].size()&&(winner==runs.size()||std::tie(runs[r][at[r]].key,r,at[r])<std::tie(runs[winner][at[winner]].key,winner,at[winner])))winner=r;if(winner==runs.size())break;out.push_back(runs[winner][at[winner]++]);}return out;}",
        "std::optional<std::vector<LoserTreeRunMerge::Record>> LoserTreeRunMerge::merge(const std::vector<std::vector<Record>>&){return std::nullopt;}",
        "using R=LoserTreeRunMerge::Record;auto m=LoserTreeRunMerge::merge({{{1,0,0},{3,0,1}},{{1,1,0},{2,1,1}}});check(m&&*m==std::vector<R>({{1,0,0},{1,1,0},{2,1,1},{3,0,1}}));",
        "using R=LoserTreeRunMerge::Record;check(!LoserTreeRunMerge::merge({{{2,0,0},{1,0,1}}}));check(!LoserTreeRunMerge::merge({{{1,2,0}}}));auto e=LoserTreeRunMerge::merge({{}, {}});check(e&&e->empty());",
        "std::tie(runs[r][at[r]].key,r,at[r])<std::tie(runs[winner][at[winner]].key,winner,at[winner])", "std::tie(runs[r][at[r]].key,at[r],r)<std::tie(runs[winner][at[winner]].key,at[winner],winner)",
        "head-only deterministic multi-run tournament merge", "each run owns canonical origin and ordinal metadata", "ties use ordinal before origin",
    ),
    _case(
        "dpr-keyed-conflict-reconcile", "KeyedConflictReconcile", "Keyed conflict reconcile", "merge",
        "class KeyedConflictReconcile { public: struct Entry{std::string key,value;long long revision;int source;}; struct Result{std::map<std::string,std::string> values;std::vector<std::tuple<std::string,int,int>> conflicts;}; static std::optional<Result> merge(const std::vector<std::vector<Entry>>& runs); };",
        "std::optional<KeyedConflictReconcile::Result> KeyedConflictReconcile::merge(const std::vector<std::vector<Entry>>& runs){std::map<std::string,std::vector<Entry>> groups;for(const auto&run:runs){std::string previous;bool first=true;for(auto e:run){if(e.key.empty()||(!first&&e.key<previous))return std::nullopt;first=false;previous=e.key;groups[e.key].push_back(e);}}Result out;for(auto&g:groups){long long best=LLONG_MIN;for(auto&e:g.second)best=std::max(best,e.revision);std::vector<Entry> winners;for(auto&e:g.second)if(e.revision==best)winners.push_back(e);std::sort(winners.begin(),winners.end(),[](auto&a,auto&b){return a.source<b.source;});bool conflict=false;for(auto&w:winners)if(w.value!=winners[0].value)conflict=true;if(conflict)out.conflicts.push_back({g.first,winners[0].source,winners[1].source});else out.values[g.first]=winners[0].value;}return out;}",
        "std::optional<KeyedConflictReconcile::Result> KeyedConflictReconcile::merge(const std::vector<std::vector<Entry>>&){return std::nullopt;}",
        "using E=KeyedConflictReconcile::Entry;auto r=KeyedConflictReconcile::merge({{{\"a\",\"old\",1,0},{\"b\",\"x\",2,0}},{{\"a\",\"new\",3,1}}});check(r&&r->values[\"a\"]==\"new\"&&r->values[\"b\"]==\"x\"&&r->conflicts.empty());",
        "using E=KeyedConflictReconcile::Entry;check(!KeyedConflictReconcile::merge({{{\"b\",\"x\",1,0},{\"a\",\"y\",2,0}}}));auto r=KeyedConflictReconcile::merge({{{\"a\",\"x\",2,3}},{{\"a\",\"y\",2,1}}});check(r&&r->values.empty()&&r->conflicts==std::vector<std::tuple<std::string,int,int>>({{\"a\",1,3}}));",
        "if(conflict)out.conflicts.push_back", "if(conflict)out.values[g.first]=winners.back().value;else if(false)out.conflicts.push_back",
        "highest-revision keyed reconciliation with explicit equal-revision conflict", "runs are key-sorted and conflicting sources are reported ascending", "equal-revision disagreement silently chooses a value",
    ),
    _case(
        "dpr-provenance-interval-union", "ProvenanceIntervalUnion", "Provenance interval union", "merge",
        "class ProvenanceIntervalUnion { public: struct Interval{long long begin,end;unsigned source;}; struct Span{long long begin,end;unsigned long long sources;bool operator==(const Span&o)const{return std::tie(begin,end,sources)==std::tie(o.begin,o.end,o.sources);}}; static std::optional<std::vector<Span>> merge(const std::vector<std::vector<Interval>>& shards); };",
        "std::optional<std::vector<ProvenanceIntervalUnion::Span>> ProvenanceIntervalUnion::merge(const std::vector<std::vector<Interval>>& shards){std::map<long long,std::vector<std::pair<unsigned,bool>>> events;for(const auto&s:shards)for(auto x:s){if(x.begin>x.end||x.source>=64)return std::nullopt;if(x.begin==x.end)continue;events[x.begin].push_back({x.source,true});events[x.end].push_back({x.source,false});}std::array<int,64> count{};std::vector<Span> out;bool have=false;long long previous=0;for(auto&e:events){unsigned long long mask=0;for(unsigned i=0;i<64;++i)if(count[i])mask|=1ULL<<i;if(have&&previous<e.first&&mask){if(!out.empty()&&out.back().end==previous&&out.back().sources==mask)out.back().end=e.first;else out.push_back({previous,e.first,mask});}std::sort(e.second.begin(),e.second.end(),[](auto a,auto b){return a.second<b.second;});for(auto change:e.second)count[change.first]+=change.second?1:-1;previous=e.first;have=true;}return out;}",
        "std::optional<std::vector<ProvenanceIntervalUnion::Span>> ProvenanceIntervalUnion::merge(const std::vector<std::vector<Interval>>&){return std::nullopt;}",
        "using I=ProvenanceIntervalUnion::Interval;using S=ProvenanceIntervalUnion::Span;auto r=ProvenanceIntervalUnion::merge({{{0,4,0}},{{2,6,1}}});check(r&&*r==std::vector<S>({{0,2,1},{2,4,3},{4,6,2}}));",
        "using I=ProvenanceIntervalUnion::Interval;check(!ProvenanceIntervalUnion::merge({{{3,2,0}}}));check(!ProvenanceIntervalUnion::merge({{{0,1,64}}}));auto r=ProvenanceIntervalUnion::merge({{{1,1,0}}});check(r&&r->empty());",
        "out.back().sources==mask", "out.back().sources!=mask",
        "endpoint sweep emitting maximal exact active-source bitsets", "zero-length intervals vanish and end events precede starts", "adjacent spans with different provenance are coalesced",
    ),
    _case(
        "dpr-nonoverlap-hunk-merge", "NonoverlapHunkMerge", "Non-overlap hunk merge", "merge",
        "class NonoverlapHunkMerge { public: struct Hunk{std::size_t begin,end;std::string replacement;int source;bool operator==(const Hunk&o)const{return std::tie(begin,end,replacement,source)==std::tie(o.begin,o.end,o.replacement,o.source);}}; struct Result{std::vector<Hunk> hunks;std::optional<std::size_t> conflict;}; static std::optional<Result> merge(std::size_t base_size,const std::vector<std::vector<Hunk>>& shards); };",
        "std::optional<NonoverlapHunkMerge::Result> NonoverlapHunkMerge::merge(std::size_t size,const std::vector<std::vector<Hunk>>& shards){std::vector<Hunk> all;for(const auto&s:shards)for(auto h:s){if(h.begin>h.end||h.end>size)return std::nullopt;all.push_back(h);}std::sort(all.begin(),all.end(),[](auto&a,auto&b){return std::tie(a.begin,a.end,a.replacement,a.source)<std::tie(b.begin,b.end,b.replacement,b.source);});std::vector<Hunk> out;for(auto h:all){if(!out.empty()&&std::tie(h.begin,h.end,h.replacement)==std::tie(out.back().begin,out.back().end,out.back().replacement))continue;if(!out.empty()&&h.begin<out.back().end)return Result{out,h.begin};out.push_back(h);}return Result{out,std::nullopt};}",
        "std::optional<NonoverlapHunkMerge::Result> NonoverlapHunkMerge::merge(std::size_t,const std::vector<std::vector<Hunk>>&){return std::nullopt;}",
        "using H=NonoverlapHunkMerge::Hunk;auto r=NonoverlapHunkMerge::merge(10,{{{0,2,\"a\",0},{5,7,\"b\",0}},{{0,2,\"a\",1}}});check(r&&!r->conflict&&r->hunks.size()==2);",
        "using H=NonoverlapHunkMerge::Hunk;check(!NonoverlapHunkMerge::merge(3,{{{2,4,\"x\",0}}}));auto r=NonoverlapHunkMerge::merge(10,{{{1,5,\"a\",0}},{{3,7,\"b\",1}}});check(r&&r->conflict==3);auto q=NonoverlapHunkMerge::merge(4,{{{0,2,\"a\",0},{2,4,\"b\",0}}});check(q&&!q->conflict&&q->hunks.size()==2);",
        "h.begin<out.back().end", "h.begin<=out.back().end",
        "sorted identical-deduplicating half-open hunk reconciliation", "touching hunks coexist while true overlap reports earliest coordinate", "touching non-overlapping hunks are reported as conflicts",
    ),
    _case(
        "dpr-asof-stream-join", "AsofStreamJoin", "As-of stream join", "merge",
        "class AsofStreamJoin { public: struct Update{long long time,value;int source;}; struct Query{long long time;int id;}; struct Joined{int id;std::optional<long long> value;bool operator==(const Joined&o)const{return id==o.id&&value==o.value;}}; static std::optional<std::vector<Joined>> join(const std::vector<Query>& queries,const std::vector<std::vector<Update>>& shards); };",
        "std::optional<std::vector<AsofStreamJoin::Joined>> AsofStreamJoin::join(const std::vector<Query>& queries,const std::vector<std::vector<Update>>& shards){for(const auto&s:shards)for(std::size_t i=1;i<s.size();++i)if(std::tie(s[i].time,s[i].source)<std::tie(s[i-1].time,s[i-1].source))return std::nullopt;std::vector<std::size_t> at(shards.size());std::vector<Update> updates;for(;;){std::size_t best=shards.size();for(std::size_t r=0;r<shards.size();++r)if(at[r]<shards[r].size()&&(best==shards.size()||std::tie(shards[r][at[r]].time,shards[r][at[r]].source,r,at[r])<std::tie(shards[best][at[best]].time,shards[best][at[best]].source,best,at[best])))best=r;if(best==shards.size())break;updates.push_back(shards[best][at[best]++]);}std::vector<Joined> out;for(auto q:queries){auto it=std::upper_bound(updates.begin(),updates.end(),q.time,[](long long time,const Update&u){return time<u.time;});std::optional<long long> value;if(it!=updates.begin())value=std::prev(it)->value;out.push_back({q.id,value});}return out;}",
        "std::optional<std::vector<AsofStreamJoin::Joined>> AsofStreamJoin::join(const std::vector<Query>&,const std::vector<std::vector<Update>>&){return std::nullopt;}",
        "using U=AsofStreamJoin::Update;using Q=AsofStreamJoin::Query;using J=AsofStreamJoin::Joined;auto r=AsofStreamJoin::join({{3,1},{0,2}},{{{1,10,0},{3,30,0}},{{3,31,1}}});check(r&&*r==std::vector<J>({{1,31},{2,std::nullopt}}));",
        "using U=AsofStreamJoin::Update;using Q=AsofStreamJoin::Query;check(!AsofStreamJoin::join({},{{{2,1,0},{1,2,0}}}));auto r=AsofStreamJoin::join({{5,7}},{});check(r&&r->size()==1&&!(*r)[0].value);auto q=AsofStreamJoin::join({{2,1}},{{{2,4,1},{2,5,2}}});check(q&&(*q)[0].value==5);",
        "return time<u.time", "return time<=u.time",
        "k-way stable merged update stream with logarithmic latest-not-after selection", "same-time larger source wins and absent history is explicit", "updates exactly at query time are incorrectly excluded",
    ),
    _case(
        "dpr-seamed-tile-assembly", "SeamedTileAssembly", "Seamed tile assembly", "merge",
        "class SeamedTileAssembly { public: struct Tile{int id,top,left,rows,cols;std::vector<int> cells;}; static std::optional<std::vector<int>> assemble(int rows,int cols,const std::vector<Tile>& tiles); };",
        "std::optional<std::vector<int>> SeamedTileAssembly::assemble(int rows,int cols,const std::vector<Tile>& tiles){if(rows<=0||cols<=0)return std::nullopt;std::vector<std::optional<int>> grid(static_cast<std::size_t>(rows)*static_cast<std::size_t>(cols));std::set<int> ids;for(auto t:tiles){if(!ids.insert(t.id).second||t.rows<=0||t.cols<=0||t.top<0||t.left<0||t.top>rows||t.left>cols||t.rows>rows-t.top||t.cols>cols-t.left||t.cells.size()!=static_cast<std::size_t>(t.rows)*static_cast<std::size_t>(t.cols))return std::nullopt;for(int r=0;r<t.rows;++r)for(int c=0;c<t.cols;++c){std::size_t at=(static_cast<std::size_t>(t.top)+static_cast<std::size_t>(r))*static_cast<std::size_t>(cols)+static_cast<std::size_t>(t.left)+static_cast<std::size_t>(c),src=static_cast<std::size_t>(r)*static_cast<std::size_t>(t.cols)+static_cast<std::size_t>(c);if(grid[at]&&*grid[at]!=t.cells[src])return std::nullopt;grid[at]=t.cells[src];}}std::vector<int> out;for(auto x:grid){if(!x)return std::nullopt;out.push_back(*x);}return out;}",
        "std::optional<std::vector<int>> SeamedTileAssembly::assemble(int,int,const std::vector<Tile>&){return std::nullopt;}",
        "using T=SeamedTileAssembly::Tile;auto g=SeamedTileAssembly::assemble(2,3,{{1,0,0,2,2,{1,2,4,5}},{2,0,1,2,2,{2,3,5,6}}});check(g&&*g==std::vector<int>({1,2,3,4,5,6}));",
        "using T=SeamedTileAssembly::Tile;check(!SeamedTileAssembly::assemble(1,2,{{1,0,0,1,1,{1}}}));check(!SeamedTileAssembly::assemble(1,1,{{1,0,0,1,1,{1}},{2,0,0,1,1,{2}}}));check(!SeamedTileAssembly::assemble(1,1,{{1,0,0,1,2,{1,2}}}));check(!SeamedTileAssembly::assemble(1,1,{{1,INT_MAX,0,1,1,{1}}}));",
        "if(grid[at]&&*grid[at]!=t.cells[src])return std::nullopt;", "if(grid[at])continue;",
        "exact-cover tile painting with seam agreement", "duplicate tile IDs, gaps, range errors, and conflicting overlaps reject", "the first tile silently wins conflicting seam cells",
    ),
    _case(
        "dpr-causal-version-reconcile", "CausalVersionReconcile", "Causal version reconcile", "merge",
        "class CausalVersionReconcile { public: struct Version{std::string key,value;std::vector<unsigned> clock;int replica;}; static std::optional<std::map<std::string,std::vector<Version>>> merge(const std::vector<std::vector<Version>>& shards,std::size_t replicas); };",
        "std::optional<std::map<std::string,std::vector<CausalVersionReconcile::Version>>> CausalVersionReconcile::merge(const std::vector<std::vector<Version>>& shards,std::size_t replicas){if(replicas==0)return std::nullopt;std::map<std::string,std::vector<Version>> groups;for(const auto&s:shards)for(auto v:s){if(v.key.empty()||v.clock.size()!=replicas||v.replica<0||static_cast<std::size_t>(v.replica)>=replicas)return std::nullopt;groups[v.key].push_back(v);}std::map<std::string,std::vector<Version>> out;auto dominates=[](const Version&a,const Version&b){bool greater=false;for(std::size_t i=0;i<a.clock.size();++i){if(a.clock[i]<b.clock[i])return false;if(a.clock[i]>b.clock[i])greater=true;}return greater;};for(auto&g:groups){for(std::size_t i=0;i<g.second.size();++i){bool dead=false;for(std::size_t j=0;j<g.second.size();++j)if(i!=j&&dominates(g.second[j],g.second[i]))dead=true;if(!dead)out[g.first].push_back(g.second[i]);}auto&v=out[g.first];std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.replica<b.replica;});for(std::size_t i=1;i<v.size();++i)if(v[i].clock==v[i-1].clock&&v[i].value!=v[i-1].value)return std::nullopt;}return out;}",
        "std::optional<std::map<std::string,std::vector<CausalVersionReconcile::Version>>> CausalVersionReconcile::merge(const std::vector<std::vector<Version>>&,std::size_t){return std::nullopt;}",
        "using V=CausalVersionReconcile::Version;auto r=CausalVersionReconcile::merge({{{\"k\",\"old\",{1,0},0}},{{\"k\",\"new\",{2,0},0},{\"k\",\"side\",{1,1},1}}},2);check(r&&(*r)[\"k\"].size()==2);",
        "using V=CausalVersionReconcile::Version;check(!CausalVersionReconcile::merge({{{\"\",\"x\",{1},0}}},1));check(!CausalVersionReconcile::merge({{{\"k\",\"x\",{1},1}}},1));check(!CausalVersionReconcile::merge({{{\"k\",\"x\",{1},0},{\"k\",\"y\",{1},0}}},1));",
        "if(a.clock[i]<b.clock[i])return false", "if(a.clock[i]<=b.clock[i])return false",
        "vector-clock dominance pruning with explicit concurrent survivors", "equal clocks with unequal payloads reject and survivors order by replica", "dominance incorrectly requires every component to be strictly greater",
    ),
    _case(
        "dpr-column-batch-row-merge", "ColumnBatchRowMerge", "Column batch row merge", "merge",
        "class ColumnBatchRowMerge { public: struct Batch{std::string column;std::vector<int> rows;std::vector<long long> values;}; struct Result{std::map<int,std::map<std::string,long long>> complete;std::vector<int> incomplete;}; static std::optional<Result> merge(const std::vector<Batch>& batches,const std::set<std::string>& required); };",
        "std::optional<ColumnBatchRowMerge::Result> ColumnBatchRowMerge::merge(const std::vector<Batch>& batches,const std::set<std::string>& required){if(required.empty())return std::nullopt;std::map<int,std::map<std::string,long long>> rows;for(const auto&b:batches){if(!required.count(b.column)||b.rows.size()!=b.values.size())return std::nullopt;for(std::size_t i=0;i<b.rows.size();++i)if(!rows[b.rows[i]].emplace(b.column,b.values[i]).second)return std::nullopt;}Result out;for(auto&r:rows){bool full=true;for(const auto&c:required)if(!r.second.count(c))full=false;if(full)out.complete.emplace(r.first,r.second);else out.incomplete.push_back(r.first);}return out;}",
        "std::optional<ColumnBatchRowMerge::Result> ColumnBatchRowMerge::merge(const std::vector<Batch>&,const std::set<std::string>&){return std::nullopt;}",
        "using B=ColumnBatchRowMerge::Batch;auto r=ColumnBatchRowMerge::merge({{\"a\",{2,1},{20,10}},{\"b\",{1},{11}}},{\"a\",\"b\"});check(r&&r->complete[1][\"a\"]==10&&r->complete[1][\"b\"]==11&&r->incomplete==std::vector<int>({2}));",
        "using B=ColumnBatchRowMerge::Batch;check(!ColumnBatchRowMerge::merge({},{}));check(!ColumnBatchRowMerge::merge({{\"a\",{1},{}}},{\"a\"}));check(!ColumnBatchRowMerge::merge({{\"a\",{1},{2}},{\"a\",{1},{3}}},{\"a\"}));",
        "if(full)out.complete.emplace", "if(full||!r.second.empty())out.complete.emplace",
        "outer row-ID merge requiring a complete named column set", "duplicate cells and misaligned batches reject; incomplete row IDs sort ascending", "any nonempty row is incorrectly admitted as complete",
    ),
    _case(
        "dpr-edge-shards-to-csr", "EdgeShardsToCsr", "Edge shards to CSR", "merge",
        "class EdgeShardsToCsr { public: struct Edge{std::size_t from,to;long long weight;}; struct Csr{std::vector<std::size_t> offsets,targets;std::vector<long long> weights;}; static std::optional<Csr> build(std::size_t vertices,const std::vector<std::vector<Edge>>& shards); };",
        "std::optional<EdgeShardsToCsr::Csr> EdgeShardsToCsr::build(std::size_t vertices,const std::vector<std::vector<Edge>>& shards){std::map<std::pair<std::size_t,std::size_t>,long long> edges;for(const auto&s:shards)for(auto e:s){if(e.from>=vertices||e.to>=vertices)return std::nullopt;auto key=std::make_pair(e.from,e.to);long long value=0;if(__builtin_add_overflow(edges[key],e.weight,&value))return std::nullopt;edges[key]=value;}Csr out;out.offsets.push_back(0);for(std::size_t v=0;v<vertices;++v){for(auto&e:edges)if(e.first.first==v&&e.second!=0){out.targets.push_back(e.first.second);out.weights.push_back(e.second);}out.offsets.push_back(out.targets.size());}return out;}",
        "std::optional<EdgeShardsToCsr::Csr> EdgeShardsToCsr::build(std::size_t,const std::vector<std::vector<Edge>>&){return std::nullopt;}",
        "using E=EdgeShardsToCsr::Edge;auto g=EdgeShardsToCsr::build(3,{{{0,2,4},{1,0,3}},{{0,2,-1}}});check(g&&g->offsets==std::vector<std::size_t>({0,1,2,2})&&g->targets==std::vector<std::size_t>({2,0})&&g->weights==std::vector<long long>({3,3}));",
        "using E=EdgeShardsToCsr::Edge;check(!EdgeShardsToCsr::build(2,{{{2,0,1}}}));auto g=EdgeShardsToCsr::build(2,{{{0,1,2}},{{0,1,-2}}});check(g&&g->targets.empty()&&g->offsets==std::vector<std::size_t>({0,0,0}));auto e=EdgeShardsToCsr::build(0,{});check(e&&e->offsets==std::vector<std::size_t>({0}));",
        "e.second!=0", "true",
        "checked duplicate-edge canonicalization into exact CSR offsets", "zero-weight cancellations vanish and every endpoint is bounded", "cancelled zero edges remain as adjacency entries",
    ),
    _case(
        "dpr-labeled-coverage-stitch", "LabeledCoverageStitch", "Labeled coverage stitch", "merge",
        "class LabeledCoverageStitch { public: struct Segment{std::size_t begin,end;int label;bool operator==(const Segment&o)const{return std::tie(begin,end,label)==std::tie(o.begin,o.end,o.label);}}; static std::optional<std::vector<Segment>> merge(std::size_t total,const std::vector<std::vector<Segment>>& shards); };",
        "std::optional<std::vector<LabeledCoverageStitch::Segment>> LabeledCoverageStitch::merge(std::size_t total,const std::vector<std::vector<Segment>>& shards){std::map<std::size_t,Segment> pieces;for(const auto&s:shards){std::size_t prior=0;bool first=true;for(auto x:s){if(x.begin>=x.end||x.end>total||(!first&&x.begin<prior)||!pieces.emplace(x.begin,x).second)return std::nullopt;first=false;prior=x.end;}}std::vector<Segment> out;std::size_t cursor=0;for(auto entry:pieces){auto x=entry.second;if(x.begin!=cursor)return std::nullopt;if(!out.empty()&&out.back().label==x.label)out.back().end=x.end;else out.push_back(x);cursor=x.end;}if(cursor!=total)return std::nullopt;return out;}",
        "std::optional<std::vector<LabeledCoverageStitch::Segment>> LabeledCoverageStitch::merge(std::size_t,const std::vector<std::vector<Segment>>&){return std::nullopt;}",
        "using S=LabeledCoverageStitch::Segment;auto r=LabeledCoverageStitch::merge(6,{{{0,2,1},{4,6,2}},{{2,4,1}}});check(r&&*r==std::vector<S>({{0,4,1},{4,6,2}}));",
        "using S=LabeledCoverageStitch::Segment;check(!LabeledCoverageStitch::merge(3,{{{0,1,1},{2,3,1}}}));check(!LabeledCoverageStitch::merge(2,{{{0,2,1}},{{1,2,2}}}));auto e=LabeledCoverageStitch::merge(0,{});check(e&&e->empty());",
        "if(!out.empty()&&out.back().label==x.label)", "if(false&&!out.empty()&&out.back().label==x.label)",
        "exact-cover labeled interval stitching with adjacent-run coalescing", "gaps, overlaps, duplicate starts, and out-of-range segments reject", "adjacent equal labels remain split rather than forming maximal runs",
    ),
    _case(
        "dpr-quorum-certificate-reduce", "QuorumCertificateReduce", "Quorum certificate reduce", "merge",
        "class QuorumCertificateReduce { public: struct Vote{int member,proposal,term;}; struct Decision{bool valid;std::optional<int> proposal;std::vector<int> equivocators;}; static Decision decide(const std::vector<std::vector<Vote>>& shards,const std::set<int>& members,std::size_t threshold); };",
        "QuorumCertificateReduce::Decision QuorumCertificateReduce::decide(const std::vector<std::vector<Vote>>& shards,const std::set<int>& members,std::size_t threshold){if(threshold==0||threshold>members.size())return {false,std::nullopt,{}};int term=INT_MIN;for(const auto&s:shards)for(auto v:s){if(!members.count(v.member))return {false,std::nullopt,{}};term=std::max(term,v.term);}std::map<int,std::set<int>> by_member;for(const auto&s:shards)for(auto v:s)if(v.term==term)by_member[v.member].insert(v.proposal);std::map<int,std::set<int>> support;std::vector<int> equiv;for(auto&m:by_member)if(m.second.size()>1)equiv.push_back(m.first);else support[*m.second.begin()].insert(m.first);if(!equiv.empty())return {true,std::nullopt,equiv};for(auto&p:support)if(p.second.size()>=threshold)return {true,p.first,{}};return {true,std::nullopt,{}};}",
        "QuorumCertificateReduce::Decision QuorumCertificateReduce::decide(const std::vector<std::vector<Vote>>&,const std::set<int>&,std::size_t){return {false,std::nullopt,{}};}",
        "using V=QuorumCertificateReduce::Vote;auto d=QuorumCertificateReduce::decide({{{1,7,3},{2,7,3}},{{3,8,2}}},{1,2,3},2);check(d.valid&&d.proposal==7&&d.equivocators.empty());",
        "using V=QuorumCertificateReduce::Vote;check(!QuorumCertificateReduce::decide({}, {1},0).valid);check(!QuorumCertificateReduce::decide({{{2,1,1}}},{1},1).valid);auto e=QuorumCertificateReduce::decide({{{1,7,2}},{{1,8,2}}},{1,2},2);check(e.valid&&!e.proposal&&e.equivocators==std::vector<int>({1}));",
        "support[*m.second.begin()].insert(m.first)", "support[*m.second.begin()].insert(0)",
        "maximum-term distinct-member quorum with equivocation evidence", "unknown members and invalid thresholds reject; duplicate votes count once", "all support is collapsed to one synthetic member identity",
    ),
    _case(
        "dpr-domain-separated-merkle-fold", "DomainSeparatedMerkleFold", "Domain-separated Merkle fold", "merge",
        "class DomainSeparatedMerkleFold { public: struct Leaf{std::size_t index;std::string bytes;}; static std::optional<unsigned long long> root(const std::vector<std::vector<Leaf>>& shards,std::size_t total); };",
        "std::optional<unsigned long long> DomainSeparatedMerkleFold::root(const std::vector<std::vector<Leaf>>& shards,std::size_t total){auto mix=[](unsigned long long h,unsigned char c){return (h^c)*1099511628211ULL;};std::vector<std::optional<std::string>> leaves(total);for(const auto&s:shards)for(auto l:s){if(l.index>=total||leaves[l.index])return std::nullopt;leaves[l.index]=l.bytes;}for(auto&x:leaves)if(!x)return std::nullopt;std::vector<unsigned long long> level;for(auto&x:leaves){unsigned long long h=mix(1469598103934665603ULL,0);for(unsigned char c:*x)h=mix(h,c);level.push_back(h);}if(level.empty())return mix(1469598103934665603ULL,2);while(level.size()>1){std::vector<unsigned long long> next;for(std::size_t i=0;i<level.size();i+=2){if(i+1==level.size()){next.push_back(level[i]);continue;}unsigned long long h=mix(1469598103934665603ULL,1);for(int b=0;b<8;++b)h=mix(h,static_cast<unsigned char>(level[i]>>(8*b)));for(int b=0;b<8;++b)h=mix(h,static_cast<unsigned char>(level[i+1]>>(8*b)));next.push_back(h);}level=next;}return level[0];}",
        "std::optional<unsigned long long> DomainSeparatedMerkleFold::root(const std::vector<std::vector<Leaf>>&,std::size_t){return std::nullopt;}",
        "using L=DomainSeparatedMerkleFold::Leaf;auto a=DomainSeparatedMerkleFold::root({{{0,\"a\"}},{{1,\"b\"},{2,\"c\"}}},3);auto b=DomainSeparatedMerkleFold::root({{{2,\"c\"},{0,\"a\"}},{{1,\"b\"}}},3);check(a&&b&&*a==*b);",
        "using L=DomainSeparatedMerkleFold::Leaf;check(!DomainSeparatedMerkleFold::root({{{0,\"a\"},{0,\"b\"}}},1));check(!DomainSeparatedMerkleFold::root({{{1,\"a\"}}},1));check(!DomainSeparatedMerkleFold::root({},1));auto e=DomainSeparatedMerkleFold::root({},0);check(e.has_value());",
        "next.push_back(level[i]);continue;", "next.push_back(level[i]^level[i]);continue;",
        "index-canonical domain-separated leaf/internal Merkle fold", "every index appears exactly once and odd nodes promote unchanged", "an odd node is self-combined instead of promoted",
    ),
)


assert len(CASES) == 12
