"""Finding-bound cycle-04 case repairs for bounded/circular storage."""
from __future__ import annotations

from dataclasses import replace


def apply_cycle04(cases):
    by = {case.task_id: case for case in cases}

    def revise(lookup_id, **changes):
        by[lookup_id] = replace(by[lookup_id], **changes)

    revise(
        "contiguous-sequence-window",
        reference=r'''ContiguousSequenceWindow::ContiguousSequenceWindow(std::size_t n,std::uint64_t first):slots_(n),first_(first),next_(first){if(!n)throw std::invalid_argument("capacity");}bool ContiguousSequenceWindow::append(std::uint64_t s,int v){if(s!=next_||next_-first_==slots_.size())return false;if(next_==std::numeric_limits<std::uint64_t>::max())throw std::overflow_error("sequence");slots_[s%slots_.size()]=Cell{s,v};++next_;return true;}std::optional<int> ContiguousSequenceWindow::get(std::uint64_t s)const{if(s<first_||s>=next_)return std::nullopt;const auto&c=slots_[s%slots_.size()];return c&&c->sequence==s?std::optional<int>(c->value):std::nullopt;}bool ContiguousSequenceWindow::trim_before(std::uint64_t s){if(s<first_||s>next_)return false;while(first_<s){slots_[first_%slots_.size()].reset();++first_;}return true;}std::pair<std::uint64_t,std::uint64_t> ContiguousSequenceWindow::range()const{return {first_,next_};}''',
        hidden=r'''int main(){ContiguousSequenceWindow w(1,std::numeric_limits<std::uint64_t>::max());try{w.append(std::numeric_limits<std::uint64_t>::max(),7);CHECK(false);}catch(const std::overflow_error&){}CHECK(w.range()==std::pair<std::uint64_t,std::uint64_t>{std::numeric_limits<std::uint64_t>::max(),std::numeric_limits<std::uint64_t>::max()});CHECK(!w.get(std::numeric_limits<std::uint64_t>::max()));return failures;}''',
        negative_old='if(next_==std::numeric_limits<std::uint64_t>::max())throw std::overflow_error("sequence");',
        negative_new='/* unchecked sequence wrap */',
        negative_reason="unchecked sequence overflow wraps the logical range after mutating a reusable slot",
    )

    revise(
        "ratio-cost-unit-cache",
        reference=r'''RatioCostUnitCache::RatioCostUnitCache(std::size_t n):cap_(n){if(!n)throw std::invalid_argument("capacity");}std::vector<int> RatioCostUnitCache::put(int k,int v,std::size_t s,std::size_t cost){if(!s||s>cap_)throw std::invalid_argument("size");for(auto it=entries_.begin();it!=entries_.end();++it)if(it->key==k){used_-=it->size;entries_.erase(it);break;}std::vector<int> out;while(used_>cap_-s){auto victim=entries_.begin();for(auto it=entries_.begin()+1;it!=entries_.end();++it){auto ratio_compare=[](std::size_t a,std::size_t b,std::size_t c,std::size_t d){int sign=1;for(;;){auto qa=a/b,qc=c/d;if(qa!=qc)return sign*(qa<qc?-1:1);auto ra=a%b,rc=c%d;if(!ra||!rc){if(!ra&&!rc)return 0;return sign*(!ra?-1:1);}a=b;b=ra;c=d;d=rc;sign=-sign;}};int order=ratio_compare(it->cost,it->size,victim->cost,victim->size);if(order<0||(order==0&&it->age<victim->age))victim=it;}out.push_back(victim->key);used_-=victim->size;entries_.erase(victim);}entries_.push_back({k,v,s,cost,++age_});used_+=s;return out;}std::optional<int> RatioCostUnitCache::get(int k){for(auto&e:entries_)if(e.key==k){e.age=++age_;return e.value;}return std::nullopt;}std::size_t RatioCostUnitCache::used()const{return used_;}''',
        hidden=r'''int main(){auto m=std::numeric_limits<std::size_t>::max();RatioCostUnitCache c(m);c.put(1,1,m/2,m-1);c.put(2,2,m/2+1,m);CHECK(c.put(3,3,1,1)==std::vector<int>({2}));CHECK(c.get(1)==1);return failures;}''',
        negative_old='int order=ratio_compare(it->cost,it->size,victim->cost,victim->size);',
        negative_new='int order=ratio_compare(it->cost,it->size,victim->cost,victim->size);order=1;',
        negative_reason="a fixed-width or cost-only victim comparison disagrees on near-limit ratios",
    )

    revise(
        "largest-remainder-quota-table",
        reference=r'''LargestRemainderQuotaTable::LargestRemainderQuotaTable(std::size_t s,std::vector<std::size_t>w):slots_(s),weights_(std::move(w)){if(!s||weights_.empty()||std::all_of(weights_.begin(),weights_.end(),[](auto x){return x==0;}))throw std::invalid_argument("weights");}std::vector<std::size_t> LargestRemainderQuotaTable::compute(std::size_t s)const{std::size_t total=0;for(auto w:weights_){if(w>std::numeric_limits<std::size_t>::max()-total)throw std::overflow_error("weights");total+=w;}struct Share{std::size_t remainder;std::size_t index;};std::vector<std::size_t> q(weights_.size());std::vector<Share> rem;std::size_t used=0;for(std::size_t i=0;i<weights_.size();++i){std::size_t quotient=0,remainder=0;for(std::size_t bit=std::numeric_limits<std::size_t>::digits;bit-->0;){quotient*=2;if(remainder>=total-remainder){remainder-=total-remainder;++quotient;}else remainder+=remainder;if((s>>bit)&std::size_t{1}){if(remainder>=total-weights_[i]){remainder-=total-weights_[i];++quotient;}else remainder+=weights_[i];}}q[i]=quotient;used+=quotient;rem.push_back({remainder,i});}std::sort(rem.begin(),rem.end(),[](const auto&a,const auto&b){return a.remainder!=b.remainder?a.remainder>b.remainder:a.index<b.index;});for(std::size_t i=0;i<s-used;++i)++q[rem[i].index];return q;}std::vector<std::size_t> LargestRemainderQuotaTable::quotas()const{return compute(slots_);}bool LargestRemainderQuotaTable::resize(std::size_t s){if(!s)return false;compute(s);slots_=s;return true;}''',
        hidden=r'''int main(){auto m=std::numeric_limits<std::size_t>::max();LargestRemainderQuotaTable q(3,{m/2,m/2});CHECK(q.quotas()==std::vector<std::size_t>({2,1}));CHECK(!q.resize(0));return failures;}''',
        negative_old='std::size_t quotient=0,remainder=0;',
        negative_new='std::size_t quotient=(s*weights_[i])/total,remainder=(s*weights_[i])%total;',
        negative_reason="fixed-width quota products overflow before division and reorder the largest remainders",
    )

    revise(
        "clustered-remainder-counter",
        header=r'''class ClusteredRemainderCounter{public:ClusteredRemainderCounter(std::size_t,std::uint8_t);bool add(std::uint64_t);bool remove(std::uint64_t);std::uint16_t count(std::uint64_t)const;std::vector<std::uint16_t> run_lengths()const;private:std::vector<std::vector<std::pair<std::uint64_t,std::uint16_t>>> runs_;std::uint8_t bits_;std::size_t used_=0;std::pair<std::size_t,std::uint64_t> split(std::uint64_t)const;};''',
        reference=r'''ClusteredRemainderCounter::ClusteredRemainderCounter(std::size_t n,std::uint8_t b):runs_(n),bits_(b){if(!n||b<1||b>16)throw std::invalid_argument("shape");}std::pair<std::size_t,std::uint64_t> ClusteredRemainderCounter::split(std::uint64_t h)const{auto mask=(std::uint64_t{1}<<bits_)-1;return {static_cast<std::size_t>((h>>bits_)%runs_.size()),h&mask};}bool ClusteredRemainderCounter::add(std::uint64_t h){auto[q,r]=split(h);auto&run=runs_[q];auto it=std::lower_bound(run.begin(),run.end(),r,[](auto&a,auto b){return a.first<b;});if(it!=run.end()&&it->first==r){if(it->second==std::numeric_limits<std::uint16_t>::max())return false;++it->second;return true;}if(used_==runs_.size())return false;run.insert(it,{r,1});++used_;return true;}bool ClusteredRemainderCounter::remove(std::uint64_t h){auto[q,r]=split(h);auto&run=runs_[q];auto it=std::lower_bound(run.begin(),run.end(),r,[](auto&a,auto b){return a.first<b;});if(it==run.end()||it->first!=r)return false;if(--it->second==0){run.erase(it);--used_;}return true;}std::uint16_t ClusteredRemainderCounter::count(std::uint64_t h)const{auto[q,r]=split(h);for(auto&x:runs_[q])if(x.first==r)return x.second;return 0;}std::vector<std::uint16_t> ClusteredRemainderCounter::run_lengths()const{std::vector<std::uint16_t> out;for(auto&r:runs_)out.push_back(static_cast<std::uint16_t>(r.size()));return out;}''',
        hidden=r'''int main(){ClusteredRemainderCounter f(1,2);CHECK(f.add(0));CHECK(f.add(0));CHECK(!f.add(1));CHECK(f.remove(0));CHECK(f.count(0)==1);CHECK(f.remove(0));CHECK(f.add(1));return failures;}''',
        negative_old='if(used_==runs_.size())return false;',
        negative_new='/* unbounded distinct remainders */',
        negative_reason="unbounded quotient runs admit more distinct counters than the fixed slot budget",
    )

    revise(
        "pending-result-idempotency-cache",
        reference=r'''PendingResultIdempotencyCache::PendingResultIdempotencyCache(std::size_t n):cap_(n){if(!n)throw std::invalid_argument("capacity");}std::optional<BeginDecision> PendingResultIdempotencyCache::begin(std::string_view k){for(auto&r:rows_)if(r.key==k)return BeginDecision{r.result?BeginDecision::Kind::Completed:BeginDecision::Kind::Pending,r.token};if(rows_.size()==cap_||used_==cap_||next_==std::numeric_limits<std::uint64_t>::max())return std::nullopt;rows_.push_back({std::string(k),next_,std::nullopt});return BeginDecision{BeginDecision::Kind::Started,next_++};}bool PendingResultIdempotencyCache::finish(std::uint64_t t,std::vector<std::uint8_t> v){for(auto&r:rows_)if(r.token==t&&!r.result){if(v.size()>cap_-used_)return false;used_+=v.size();r.result=std::move(v);return true;}return false;}std::optional<std::vector<std::uint8_t>> PendingResultIdempotencyCache::replay(std::string_view k)const{for(auto&r:rows_)if(r.key==k&&r.result)return r.result;return std::nullopt;}bool PendingResultIdempotencyCache::evict_done(std::size_t n){bool any=false;while(n--&&!rows_.empty()&&rows_.front().result){used_-=rows_.front().result->size();rows_.pop_front();any=true;}return any;}''',
        hidden=r'''int main(){PendingResultIdempotencyCache c(2);auto a=c.begin("a");CHECK(a);CHECK(!c.finish(a->token,{1,2,3}));auto again=c.begin("a");CHECK(again&&again->token==a->token&&again->kind==BeginDecision::Kind::Pending);CHECK(c.finish(a->token,{1,2}));CHECK(!c.begin("b"));CHECK(c.evict_done(1));CHECK(c.begin("b"));return failures;}''',
        negative_old='if(v.size()>cap_-used_)return false;',
        negative_new='/* result bytes may exceed the fixed byte budget */',
        negative_reason="row-count-only admission accepts a completed result larger than the byte capacity",
    )

    revise(
        "first-write-rollback-stack",
        header=r'''class FirstWriteRollbackStack{public:explicit FirstWriteRollbackStack(std::size_t);bool assign(std::size_t,int);std::optional<std::uint64_t> checkpoint();bool restore(std::uint64_t);bool release(std::uint64_t);std::vector<int> values()const;private:struct Frame{std::uint64_t id;std::map<std::size_t,int> old;};std::vector<int> values_;std::vector<Frame> frames_;std::size_t undo_cap_;std::size_t undo_used_=0;std::uint64_t next_=1;};''',
        reference=r'''FirstWriteRollbackStack::FirstWriteRollbackStack(std::size_t n):values_(n),undo_cap_(n){if(!n)throw std::invalid_argument("capacity");}std::optional<std::uint64_t> FirstWriteRollbackStack::checkpoint(){if(next_==std::numeric_limits<std::uint64_t>::max())return std::nullopt;frames_.push_back({next_,{}});return next_++;}bool FirstWriteRollbackStack::assign(std::size_t i,int v){if(i>=values_.size())throw std::invalid_argument("cell");if(!frames_.empty()&&!frames_.back().old.count(i)){if(undo_used_==undo_cap_)return false;frames_.back().old.emplace(i,values_[i]);++undo_used_;}values_[i]=v;return true;}bool FirstWriteRollbackStack::restore(std::uint64_t id){if(frames_.empty()||frames_.back().id!=id)return false;for(auto&x:frames_.back().old)values_[x.first]=x.second;undo_used_-=frames_.back().old.size();frames_.pop_back();return true;}bool FirstWriteRollbackStack::release(std::uint64_t id){if(frames_.empty()||frames_.back().id!=id)return false;undo_used_-=frames_.back().old.size();frames_.pop_back();return true;}std::vector<int> FirstWriteRollbackStack::values()const{return values_;}''',
        hidden=r'''int main(){FirstWriteRollbackStack s(1);auto a=s.checkpoint();CHECK(a&&s.assign(0,1)&&s.assign(0,2));auto b=s.checkpoint();CHECK(b);CHECK(!s.assign(0,3));CHECK(s.values()==std::vector<int>({2}));CHECK(s.release(*b));CHECK(s.restore(*a));CHECK(s.values()==std::vector<int>({0}));return failures;}''',
        negative_old='if(undo_used_==undo_cap_)return false;',
        negative_new='/* unbounded undo admission */',
        negative_reason="an unbounded nested first-write log accepts a record after the undo budget is exhausted",
    )

    revise(
        "rollback-spill-routing-banks",
        hidden=r'''int main(){RollbackSpillRoutingBanks s({1,2});CHECK(s.put(1,8));CHECK(s.put(1,9));CHECK(s.put(0,1));auto before=s.layout();CHECK(!s.put(0,2));CHECK(s.layout()==before);CHECK(s.take(1)==8);return failures;}''',
    )

    revise(
        "framed-byte-wrap-log",
        header=r'''class FramedByteWrapLog{public:explicit FramedByteWrapLog(std::size_t);std::optional<std::uint64_t> append(std::vector<std::uint8_t>);bool discard_through(std::uint64_t);std::optional<std::vector<std::uint8_t>> read(std::uint64_t)const;std::vector<std::uint64_t> ids()const;std::size_t wrap_markers()const;private:struct Rec{std::uint64_t id;std::size_t pos;std::size_t len;std::size_t charge;bool wrapped;};std::vector<std::uint8_t> ring_;std::deque<Rec> records_;std::size_t tail_=0;std::size_t used_=0;std::size_t markers_=0;std::uint64_t next_=1;};''',
        reference=r'''FramedByteWrapLog::FramedByteWrapLog(std::size_t n):ring_(n){if(!n)throw std::invalid_argument("capacity");}std::optional<std::uint64_t> FramedByteWrapLog::append(std::vector<std::uint8_t> p){if(p.size()>std::numeric_limits<std::uint32_t>::max())throw std::overflow_error("length");std::size_t need=p.size()+4;if(need>ring_.size())return std::nullopt;if(next_==std::numeric_limits<std::uint64_t>::max())throw std::overflow_error("id");std::size_t gap=tail_+need>ring_.size()?ring_.size()-tail_:0;if(need+gap>ring_.size()-used_)return std::nullopt;bool wrapped=gap!=0;if(wrapped){std::fill(ring_.begin()+static_cast<std::ptrdiff_t>(tail_),ring_.end(),0xff);tail_=0;++markers_;}std::uint32_t len=static_cast<std::uint32_t>(p.size());for(std::size_t i=0;i<4;++i)ring_[tail_+i]=static_cast<std::uint8_t>((len>>(8*i))&0xff);std::copy(p.begin(),p.end(),ring_.begin()+static_cast<std::ptrdiff_t>(tail_+4));records_.push_back({next_,tail_,p.size(),need+gap,wrapped});tail_=(tail_+need)%ring_.size();used_+=need+gap;return next_++;}bool FramedByteWrapLog::discard_through(std::uint64_t id){bool any=false;while(!records_.empty()&&records_.front().id<=id){used_-=records_.front().charge;if(records_.front().wrapped)--markers_;records_.pop_front();any=true;}if(records_.empty()){used_=0;tail_=0;markers_=0;}return any;}std::optional<std::vector<std::uint8_t>> FramedByteWrapLog::read(std::uint64_t id)const{for(const auto&r:records_)if(r.id==id)return std::vector<std::uint8_t>(ring_.begin()+static_cast<std::ptrdiff_t>(r.pos+4),ring_.begin()+static_cast<std::ptrdiff_t>(r.pos+4+r.len));return std::nullopt;}std::vector<std::uint64_t> FramedByteWrapLog::ids()const{std::vector<std::uint64_t> out;for(const auto&r:records_)out.push_back(r.id);return out;}std::size_t FramedByteWrapLog::wrap_markers()const{return markers_;}''',
        visible=r'''int main(){FramedByteWrapLog l(16);auto a=l.append({1,2,3});auto b=l.append({4,5});CHECK(a&&b);CHECK(l.discard_through(*a));auto c=l.append({6,7,8});CHECK(c&&l.wrap_markers()==1);CHECK(l.read(*c)==std::vector<std::uint8_t>({6,7,8}));CHECK(l.discard_through(*c));CHECK(l.wrap_markers()==0);return failures;}''',
        hidden=r'''int main(){FramedByteWrapLog l(400);std::vector<std::uint8_t> payload(300,7);auto id=l.append(payload);CHECK(id&&l.read(*id)==payload);CHECK(!l.append(std::vector<std::uint8_t>(397,1)));CHECK(l.discard_through(*id));auto empty=l.append({});CHECK(empty&&l.read(*empty)==std::vector<std::uint8_t>{});return failures;}''',
        negative_old='if(wrapped){std::fill(ring_.begin()+static_cast<std::ptrdiff_t>(tail_),ring_.end(),0xff);tail_=0;++markers_;}',
        negative_new='if(wrapped){tail_=0;}',
        negative_reason="wrapping without an explicit marker or marker accounting loses the physical tail gap",
    )

    revise(
        "crc-recovery-frame-store",
        header=r'''struct CrcFrame{std::uint16_t type;std::vector<std::uint8_t> payload;};class CrcRecoveryFrameStore{public:explicit CrcRecoveryFrameStore(std::size_t);bool write(std::uint16_t,std::vector<std::uint8_t>);std::optional<CrcFrame> read();bool corrupt_head(std::size_t);bool inject_incomplete(std::uint16_t,std::vector<std::uint8_t>,std::size_t);std::size_t corrupt_count()const;private:std::size_t cap_;std::deque<std::uint8_t> bytes_;std::size_t corrupt_=0;static std::uint16_t checksum(std::uint16_t,const std::vector<std::uint8_t>&);};''',
        reference=r'''std::uint16_t CrcRecoveryFrameStore::checksum(std::uint16_t type,const std::vector<std::uint8_t>&p){std::uint32_t c=type;for(auto b:p)c=(c*257u+b)&0xffffu;return static_cast<std::uint16_t>(c);}CrcRecoveryFrameStore::CrcRecoveryFrameStore(std::size_t n):cap_(n){if(!n)throw std::invalid_argument("capacity");}bool CrcRecoveryFrameStore::write(std::uint16_t type,std::vector<std::uint8_t> p){if(p.empty()||p.size()>std::numeric_limits<std::uint16_t>::max())return false;std::size_t n=p.size()+6;if(n>cap_-bytes_.size())return false;auto crc=checksum(type,p);bytes_.push_back(static_cast<std::uint8_t>(type&0xff));bytes_.push_back(static_cast<std::uint8_t>(type>>8));bytes_.push_back(static_cast<std::uint8_t>(p.size()&0xff));bytes_.push_back(static_cast<std::uint8_t>(p.size()>>8));bytes_.push_back(static_cast<std::uint8_t>(crc&0xff));bytes_.push_back(static_cast<std::uint8_t>(crc>>8));for(auto b:p)bytes_.push_back(b);return true;}std::optional<CrcFrame> CrcRecoveryFrameStore::read(){while(bytes_.size()>=6){std::uint16_t type=static_cast<std::uint16_t>(bytes_[0]|(std::uint16_t(bytes_[1])<<8));std::size_t len=static_cast<std::size_t>(bytes_[2]|(std::uint16_t(bytes_[3])<<8));if(len+6>bytes_.size())return std::nullopt;std::uint16_t stored=static_cast<std::uint16_t>(bytes_[4]|(std::uint16_t(bytes_[5])<<8));std::vector<std::uint8_t> payload;for(std::size_t i=0;i<len;++i)payload.push_back(bytes_[6+i]);for(std::size_t i=0;i<len+6;++i)bytes_.pop_front();if(checksum(type,payload)!=stored){++corrupt_;continue;}return CrcFrame{type,std::move(payload)};}return std::nullopt;}bool CrcRecoveryFrameStore::corrupt_head(std::size_t i){if(bytes_.size()<6)return false;std::size_t len=static_cast<std::size_t>(bytes_[2]|(std::uint16_t(bytes_[3])<<8));if(i>=len||6+i>=bytes_.size())return false;bytes_[6+i]^=0x5a;return true;}bool CrcRecoveryFrameStore::inject_incomplete(std::uint16_t type,std::vector<std::uint8_t> p,std::size_t prefix){if(p.empty()||p.size()>std::numeric_limits<std::uint16_t>::max())return false;std::vector<std::uint8_t> raw{static_cast<std::uint8_t>(type&0xff),static_cast<std::uint8_t>(type>>8),static_cast<std::uint8_t>(p.size()&0xff),static_cast<std::uint8_t>(p.size()>>8),0,0};raw.insert(raw.end(),p.begin(),p.end());prefix=std::min(prefix,raw.size());if(prefix>cap_-bytes_.size())return false;for(std::size_t i=0;i<prefix;++i)bytes_.push_back(raw[i]);return true;}std::size_t CrcRecoveryFrameStore::corrupt_count()const{return corrupt_;}''',
        visible=r'''int main(){CrcRecoveryFrameStore s(24);CHECK(s.write(1,{2,3}));CHECK(s.write(4,{5}));CHECK(s.corrupt_head(0));auto f=s.read();CHECK(f&&f->type==4&&f->payload==std::vector<std::uint8_t>({5}));CHECK(s.corrupt_count()==1);return failures;}''',
        hidden=r'''int main(){CrcRecoveryFrameStore s(12);CHECK(s.inject_incomplete(7,{1,2,3},7));CHECK(!s.read());CHECK(!s.corrupt_head(1));return failures;}''',
        negative_old='if(checksum(type,payload)!=stored)',
        negative_new='if(stored==0&&false)',
        negative_reason="payload corruption must skip a complete framed record while an incomplete tail remains retained",
    )

    revise(
        "segmented-delta-samples",
        header=r'''class SegmentedDeltaSamples{public:explicit SegmentedDeltaSamples(std::size_t);bool append(std::int64_t);std::optional<std::int64_t> at(std::size_t)const;std::vector<std::int64_t> decode()const;std::size_t base_segments()const;private:struct Cell{bool base;std::int64_t value;};std::size_t cap_;std::deque<Cell> cells_;void rebuild(const std::vector<std::int64_t>&);};''',
        reference=r'''SegmentedDeltaSamples::SegmentedDeltaSamples(std::size_t n):cap_(n){if(!n)throw std::invalid_argument("capacity");}void SegmentedDeltaSamples::rebuild(const std::vector<std::int64_t>&values){cells_.clear();for(std::size_t i=0;i<values.size();++i){bool base=true;std::int64_t encoded=values[i];if(i){auto prev=values[i-1];bool overflow=(values[i]>0&&prev<std::numeric_limits<std::int64_t>::min()+values[i])||(values[i]<0&&prev>std::numeric_limits<std::int64_t>::max()+values[i]);if(overflow)throw std::overflow_error("delta");auto delta=values[i]-prev;if(delta>=-32768&&delta<=32767){base=false;encoded=delta;}}cells_.push_back({base,encoded});}}bool SegmentedDeltaSamples::append(std::int64_t v){auto values=decode();if(!values.empty()){auto prev=values.back();if((v>0&&prev<std::numeric_limits<std::int64_t>::min()+v)||(v<0&&prev>std::numeric_limits<std::int64_t>::max()+v))throw std::overflow_error("delta");}values.push_back(v);if(values.size()>cap_)values.erase(values.begin());rebuild(values);return true;}std::vector<std::int64_t> SegmentedDeltaSamples::decode()const{std::vector<std::int64_t> out;for(const auto&c:cells_){if(c.base||out.empty())out.push_back(c.value);else out.push_back(out.back()+c.value);}return out;}std::optional<std::int64_t> SegmentedDeltaSamples::at(std::size_t age)const{auto v=decode();return age<v.size()?std::optional<std::int64_t>(v[v.size()-1-age]):std::nullopt;}std::size_t SegmentedDeltaSamples::base_segments()const{return static_cast<std::size_t>(std::count_if(cells_.begin(),cells_.end(),[](auto&c){return c.base;}));}''',
        visible=r'''int main(){SegmentedDeltaSamples s(2);s.append(100000);s.append(100001);s.append(100002);CHECK(s.decode()==std::vector<std::int64_t>({100001,100002}));CHECK(s.base_segments()==1);CHECK(s.at(0)==100002);return failures;}''',
        hidden=r'''int main(){SegmentedDeltaSamples s(3);s.append(-40000);s.append(40000);s.append(40001);CHECK(s.decode()==std::vector<std::int64_t>({-40000,40000,40001}));CHECK(s.base_segments()==2);CHECK(!s.at(3));return failures;}''',
        negative_old='if(values.size()>cap_)values.erase(values.begin());rebuild(values);',
        negative_new='if(values.size()>cap_)cells_.pop_front();else rebuild(values);',
        negative_reason="evicting a base cell without rebuilding its dependent delta segment corrupts retained absolute values",
    )

    revise(
        "neighborhood-hop-bitmap",
        header=r'''class NeighborhoodHopBitmap{public:NeighborhoodHopBitmap(std::size_t,std::size_t);bool insert(int,int);std::optional<int> find(int)const;bool erase(int);std::vector<std::uint64_t> hop_bits()const;private:struct Cell{int key;int value;};std::vector<std::optional<Cell>> cells_;std::vector<std::uint64_t> bits_;std::size_t hood_;std::size_t home(int)const;std::size_t distance(std::size_t,std::size_t)const;};''',
        reference=r'''NeighborhoodHopBitmap::NeighborhoodHopBitmap(std::size_t n,std::size_t h):cells_(n),bits_(n),hood_(h){if(!n||h<2||h>64||h>n)throw std::invalid_argument("neighborhood");}std::size_t NeighborhoodHopBitmap::home(int k)const{return static_cast<std::size_t>(k<0?-k:k)%cells_.size();}std::size_t NeighborhoodHopBitmap::distance(std::size_t a,std::size_t b)const{return (b+cells_.size()-a)%cells_.size();}std::optional<int> NeighborhoodHopBitmap::find(int k)const{auto h=home(k),mask=bits_[h];for(std::size_t d=0;d<hood_;++d)if(mask&(std::uint64_t{1}<<d)){auto i=(h+d)%cells_.size();if(cells_[i]&&cells_[i]->key==k)return cells_[i]->value;}return std::nullopt;}bool NeighborhoodHopBitmap::insert(int k,int v){if(find(k)){auto h=home(k);for(std::size_t d=0;d<hood_;++d){auto i=(h+d)%cells_.size();if(cells_[i]&&cells_[i]->key==k){cells_[i]->value=v;return true;}}}auto old_cells=cells_;auto old_bits=bits_;auto h=home(k);std::size_t free=cells_.size();for(std::size_t scan=0;scan<cells_.size();++scan){auto i=(h+scan)%cells_.size();if(!cells_[i]){free=i;break;}}if(free==cells_.size())return false;while(distance(h,free)>=hood_){bool moved=false;for(std::size_t back=hood_-1;back>0;--back){auto from=(free+cells_.size()-back)%cells_.size();if(!cells_[from])continue;auto source_home=home(cells_[from]->key);auto old_distance=distance(source_home,from),new_distance=distance(source_home,free);if(new_distance<hood_){cells_[free]=cells_[from];cells_[from].reset();bits_[source_home]&=~(std::uint64_t{1}<<old_distance);bits_[source_home]|=std::uint64_t{1}<<new_distance;free=from;moved=true;break;}}if(!moved){cells_=std::move(old_cells);bits_=std::move(old_bits);return false;}}auto d=distance(h,free);cells_[free]=Cell{k,v};bits_[h]|=std::uint64_t{1}<<d;return true;}bool NeighborhoodHopBitmap::erase(int k){auto h=home(k);for(std::size_t d=0;d<hood_;++d){auto i=(h+d)%cells_.size();if(cells_[i]&&cells_[i]->key==k){cells_[i].reset();bits_[h]&=~(std::uint64_t{1}<<d);return true;}}return false;}std::vector<std::uint64_t> NeighborhoodHopBitmap::hop_bits()const{return bits_;}''',
        visible=r'''int main(){NeighborhoodHopBitmap m(8,4);CHECK(m.insert(0,0));CHECK(m.insert(1,1));CHECK(m.insert(9,9));CHECK(m.insert(17,17));CHECK(m.insert(8,8));CHECK(m.find(8)==8&&m.find(1)==1);CHECK((m.hop_bits()[0]&2)!=0);return failures;}''',
        hidden=r'''int main(){NeighborhoodHopBitmap m(4,2);CHECK(m.insert(0,1));CHECK(m.insert(4,2));auto before=m.hop_bits();CHECK(!m.insert(8,3));CHECK(m.hop_bits()==before);CHECK(m.find(0)==1&&m.find(4)==2);return failures;}''',
        negative_old='for(std::size_t scan=0;scan<cells_.size();++scan)',
        negative_new='for(std::size_t scan=0;scan<hood_;++scan)',
        negative_reason="neighborhood-only vacancy search rejects an insertion that requires hopscotch relocation",
    )

    revise(
        "arena-generation-interner",
        header=r'''struct InternId{std::uint32_t slot;std::uint32_t generation;};class ArenaGenerationInterner{public:ArenaGenerationInterner(std::size_t,std::size_t);std::optional<InternId> intern(std::string_view);std::optional<std::string> resolve(InternId)const;bool release(InternId);std::size_t bytes_used()const;private:struct Entry{std::size_t offset=0;std::size_t size=0;std::uint32_t generation=1;std::size_t refs=0;bool live=false;};std::vector<char> arena_;std::size_t used_=0;std::vector<Entry> slots_;std::vector<std::pair<std::size_t,std::size_t>> free_;void coalesce();};''',
        reference=r'''ArenaGenerationInterner::ArenaGenerationInterner(std::size_t b,std::size_t s):arena_(b),slots_(s),free_{{0,b}}{if(!b||!s)throw std::invalid_argument("capacity");}void ArenaGenerationInterner::coalesce(){std::sort(free_.begin(),free_.end());std::vector<std::pair<std::size_t,std::size_t>> out;for(auto e:free_){if(!out.empty()&&out.back().first+out.back().second==e.first)out.back().second+=e.second;else out.push_back(e);}free_=std::move(out);}std::optional<InternId> ArenaGenerationInterner::intern(std::string_view v){for(std::size_t i=0;i<slots_.size();++i){auto&e=slots_[i];if(e.live&&e.size==v.size()&&std::equal(v.begin(),v.end(),arena_.begin()+static_cast<std::ptrdiff_t>(e.offset))){++e.refs;return InternId{static_cast<std::uint32_t>(i),e.generation};}}auto slot=std::find_if(slots_.begin(),slots_.end(),[](const auto&e){return !e.live;});if(slot==slots_.end())return std::nullopt;std::size_t offset=0;if(!v.empty()){auto extent=std::find_if(free_.begin(),free_.end(),[&](auto e){return e.second>=v.size();});if(extent==free_.end())return std::nullopt;offset=extent->first;extent->first+=v.size();extent->second-=v.size();if(!extent->second)free_.erase(extent);std::copy(v.begin(),v.end(),arena_.begin()+static_cast<std::ptrdiff_t>(offset));}slot->offset=offset;slot->size=v.size();slot->refs=1;slot->live=true;used_+=v.size();return InternId{static_cast<std::uint32_t>(slot-slots_.begin()),slot->generation};}std::optional<std::string> ArenaGenerationInterner::resolve(InternId id)const{if(id.slot>=slots_.size())return std::nullopt;const auto&e=slots_[id.slot];if(!e.live||e.generation!=id.generation)return std::nullopt;return std::string(arena_.begin()+static_cast<std::ptrdiff_t>(e.offset),arena_.begin()+static_cast<std::ptrdiff_t>(e.offset+e.size));}bool ArenaGenerationInterner::release(InternId id){if(id.slot>=slots_.size())return false;auto&e=slots_[id.slot];if(!e.live||e.generation!=id.generation)return false;if(--e.refs)return true;if(e.size)free_.push_back({e.offset,e.size});used_-=e.size;e.live=false;e.refs=0;++e.generation;coalesce();return true;}std::size_t ArenaGenerationInterner::bytes_used()const{return used_;}''',
        visible=r'''int main(){ArenaGenerationInterner i(5,2);auto a=i.intern("ab");auto b=i.intern("cde");CHECK(a&&b);CHECK(i.release(*a)&&i.release(*b));auto c=i.intern("abcde");CHECK(c&&i.resolve(*c)=="abcde"&&i.bytes_used()==5);CHECK(!i.resolve(*a));return failures;}''',
        hidden=r'''int main(){ArenaGenerationInterner i(3,2);auto a=i.intern("");auto b=i.intern("");CHECK(a&&b&&a->slot==b->slot);CHECK(i.release(*a));CHECK(i.resolve(*b)=="");CHECK(i.release(*b));auto c=i.intern("xyz");CHECK(c&&c->generation!=a->generation);return failures;}''',
        negative_old='if(!out.empty()&&out.back().first+out.back().second==e.first)',
        negative_new='if(false)',
        negative_reason="uncoalesced released arena extents reject a payload that fits only after adjacent merge",
    )

    revise(
        "atomic-dual-key-index",
        header=r'''class AtomicDualKeyIndex{public:explicit AtomicDualKeyIndex(std::size_t);bool link(int,int);bool unlink_left(int);bool unlink_right(int);std::optional<int> right_of(int)const;std::optional<int> left_of(int)const;private:struct Pair{int left=0;int right=0;bool live=false;};std::vector<Pair> pairs_;std::vector<int> left_;std::vector<int> right_;std::size_t live_=0;std::size_t hash(int)const;std::optional<std::size_t> find_left(int)const;std::optional<std::size_t> find_right(int)const;std::size_t insertion_slot(const std::vector<int>&,int)const;void unlink_slot(std::size_t);};''',
        reference=r'''AtomicDualKeyIndex::AtomicDualKeyIndex(std::size_t n):pairs_(n),left_(n,-1),right_(n,-1){if(!n)throw std::invalid_argument("capacity");}std::size_t AtomicDualKeyIndex::hash(int k)const{return static_cast<std::size_t>(k<0?-k:k)%pairs_.size();}std::optional<std::size_t> AtomicDualKeyIndex::find_left(int k)const{auto h=hash(k);for(std::size_t p=0;p<left_.size();++p){int slot=left_[(h+p)%left_.size()];if(slot==-1)return std::nullopt;if(slot>=0&&pairs_[static_cast<std::size_t>(slot)].live&&pairs_[static_cast<std::size_t>(slot)].left==k)return static_cast<std::size_t>(slot);}return std::nullopt;}std::optional<std::size_t> AtomicDualKeyIndex::find_right(int k)const{auto h=hash(k);for(std::size_t p=0;p<right_.size();++p){int slot=right_[(h+p)%right_.size()];if(slot==-1)return std::nullopt;if(slot>=0&&pairs_[static_cast<std::size_t>(slot)].live&&pairs_[static_cast<std::size_t>(slot)].right==k)return static_cast<std::size_t>(slot);}return std::nullopt;}std::size_t AtomicDualKeyIndex::insertion_slot(const std::vector<int>&table,int k)const{auto h=hash(k),first=table.size();for(std::size_t p=0;p<table.size();++p){auto i=(h+p)%table.size();if(table[i]==-2&&first==table.size())first=i;if(table[i]==-1)return first==table.size()?i:first;}return first;}bool AtomicDualKeyIndex::link(int l,int r){auto lp=find_left(l),rp=find_right(r);if(lp||rp)return lp&&rp&&*lp==*rp;if(live_==pairs_.size())return false;auto li=insertion_slot(left_,l),ri=insertion_slot(right_,r);if(li==left_.size()||ri==right_.size())return false;auto slot=static_cast<std::size_t>(std::find_if(pairs_.begin(),pairs_.end(),[](const auto&p){return !p.live;})-pairs_.begin());pairs_[slot]={l,r,true};left_[li]=static_cast<int>(slot);right_[ri]=static_cast<int>(slot);++live_;return true;}std::optional<int> AtomicDualKeyIndex::right_of(int l)const{auto i=find_left(l);return i?std::optional<int>(pairs_[*i].right):std::nullopt;}std::optional<int> AtomicDualKeyIndex::left_of(int r)const{auto i=find_right(r);return i?std::optional<int>(pairs_[*i].left):std::nullopt;}void AtomicDualKeyIndex::unlink_slot(std::size_t slot){for(auto&x:left_)if(x==static_cast<int>(slot))x=-2;for(auto&x:right_)if(x==static_cast<int>(slot))x=-2;pairs_[slot].live=false;--live_;}bool AtomicDualKeyIndex::unlink_left(int l){auto i=find_left(l);if(!i)return false;unlink_slot(*i);return true;}bool AtomicDualKeyIndex::unlink_right(int r){auto i=find_right(r);if(!i)return false;unlink_slot(*i);return true;}''',
        visible=r'''int main(){AtomicDualKeyIndex b(3);CHECK(b.link(1,10));CHECK(b.link(4,13));CHECK(!b.link(1,11));CHECK(!b.link(2,13));CHECK(b.right_of(4)==13&&b.left_of(10)==1);CHECK(b.unlink_left(1));CHECK(!b.left_of(10));CHECK(b.link(7,16));return failures;}''',
        hidden=r'''int main(){AtomicDualKeyIndex b(1);CHECK(b.link(-1,-2));CHECK(b.link(-1,-2));CHECK(!b.link(2,3));CHECK(b.unlink_right(-2));CHECK(!b.right_of(-1));CHECK(!b.unlink_left(-1));return failures;}''',
        negative_old='right_[ri]=static_cast<int>(slot);',
        negative_new='/* omit reverse-index publication */',
        negative_reason="publishing only one open-address index breaks atomic bidirectional visibility",
    )

    revise(
        "checkpointed-delta-history",
        header=r'''class CheckpointedDeltaHistory{public:CheckpointedDeltaHistory(std::size_t,std::size_t);bool mutate(int,int);std::optional<int> read(std::size_t,int)const;std::vector<std::size_t> checkpoints()const;private:struct Version{bool checkpoint;std::map<int,int> snapshot;int key=0;int value=0;std::size_t cost=0;};std::size_t units_;std::size_t cadence_;std::size_t used_=0;std::size_t since_checkpoint_=0;std::vector<Version> versions_;std::map<int,int> current_;};''',
        reference=r'''CheckpointedDeltaHistory::CheckpointedDeltaHistory(std::size_t u,std::size_t c):units_(u),cadence_(c){if(!u||!c)throw std::invalid_argument("capacity");}bool CheckpointedDeltaHistory::mutate(int k,int v){auto next=current_;next[k]=v;bool checkpoint=versions_.empty()||since_checkpoint_==cadence_;Version row;if(checkpoint){row={true,next,0,0,next.size()+1};}else row={false,{},k,v,1};if(row.cost>units_)return false;auto candidate=versions_;candidate.push_back(row);std::size_t candidate_used=used_+row.cost;while(candidate_used>units_){auto second=std::find_if(candidate.begin()+1,candidate.end(),[](const auto&x){return x.checkpoint;});if(second==candidate.end())return false;for(auto i=candidate.begin();i!=second;++i)candidate_used-=i->cost;candidate.erase(candidate.begin(),second);}versions_=std::move(candidate);used_=candidate_used;current_=std::move(next);since_checkpoint_=checkpoint?1:since_checkpoint_+1;return true;}std::optional<int> CheckpointedDeltaHistory::read(std::size_t version,int k)const{if(version>=versions_.size())return std::nullopt;std::size_t base=version;while(base&&!versions_[base].checkpoint)--base;if(!versions_[base].checkpoint)return std::nullopt;auto state=versions_[base].snapshot;for(std::size_t i=base+1;i<=version;++i)state[versions_[i].key]=versions_[i].value;auto found=state.find(k);return found==state.end()?std::nullopt:std::optional<int>(found->second);}std::vector<std::size_t> CheckpointedDeltaHistory::checkpoints()const{std::vector<std::size_t> out;for(std::size_t i=0;i<versions_.size();++i)if(versions_[i].checkpoint)out.push_back(i);return out;}''',
        visible=r'''int main(){CheckpointedDeltaHistory h(8,2);CHECK(h.mutate(1,1));CHECK(h.mutate(1,2));CHECK(h.mutate(2,3));CHECK(h.read(0,1)==1);CHECK(h.read(1,1)==2);CHECK(h.read(2,2)==3);CHECK(h.checkpoints()==std::vector<std::size_t>({0,2}));return failures;}''',
        hidden=r'''int main(){CheckpointedDeltaHistory h(5,1);CHECK(h.mutate(1,1));CHECK(h.mutate(1,2));CHECK(h.mutate(1,3));CHECK(h.read(0,1)==2);CHECK(h.read(1,1)==3);CHECK(h.checkpoints()==std::vector<std::size_t>({0,1}));CHECK(!h.read(2,1));return failures;}''',
        negative_old='auto state=versions_[base].snapshot;',
        negative_new='auto state=current_;',
        negative_reason="reading from current state instead of the nearest retained checkpoint cannot reconstruct old versions",
    )

    revise(
        "committed-prefix-ring-journal",
        header=r'''class CommittedPrefixRingJournal{public:explicit CommittedPrefixRingJournal(std::size_t);std::optional<std::uint64_t> append(int);bool commit_through(std::uint64_t);bool truncate_uncommitted();std::size_t trim_committed(std::size_t);std::vector<int> committed()const;private:struct Rec{std::uint64_t lsn;int value;bool committed;};std::vector<std::optional<Rec>> ring_;std::size_t head_=0;std::size_t count_=0;std::uint64_t next_=1;};''',
        reference=r'''CommittedPrefixRingJournal::CommittedPrefixRingJournal(std::size_t n):ring_(n){if(!n)throw std::invalid_argument("capacity");}std::optional<std::uint64_t> CommittedPrefixRingJournal::append(int v){if(count_==ring_.size())return std::nullopt;if(next_==std::numeric_limits<std::uint64_t>::max())throw std::overflow_error("lsn");auto at=(head_+count_)%ring_.size();ring_[at]=Rec{next_,v,false};++count_;return next_++;}bool CommittedPrefixRingJournal::commit_through(std::uint64_t l){std::size_t position=count_;for(std::size_t i=0;i<count_;++i)if(ring_[(head_+i)%ring_.size()]->lsn==l){position=i;break;}if(position==count_)return false;for(std::size_t i=0;i<=position;++i)ring_[(head_+i)%ring_.size()]->committed=true;return true;}bool CommittedPrefixRingJournal::truncate_uncommitted(){bool any=false;while(count_){auto at=(head_+count_-1)%ring_.size();if(ring_[at]->committed)break;ring_[at].reset();--count_;any=true;}return any;}std::size_t CommittedPrefixRingJournal::trim_committed(std::size_t n){std::size_t out=0;while(out<n&&count_&&ring_[head_]->committed){ring_[head_].reset();head_=(head_+1)%ring_.size();--count_;++out;}return out;}std::vector<int> CommittedPrefixRingJournal::committed()const{std::vector<int> out;for(std::size_t i=0;i<count_;++i){const auto&r=*ring_[(head_+i)%ring_.size()];if(r.committed)out.push_back(r.value);}return out;}''',
        visible=r'''int main(){CommittedPrefixRingJournal j(3);auto a=j.append(1);auto b=j.append(2);j.append(3);CHECK(a&&b&&j.commit_through(*b));CHECK(j.committed()==std::vector<int>({1,2}));CHECK(j.trim_committed(1)==1);CHECK(j.append(4));CHECK(j.committed()==std::vector<int>({2}));return failures;}''',
        hidden=r'''int main(){CommittedPrefixRingJournal j(2);auto a=j.append(4);auto b=j.append(5);CHECK(a&&b);CHECK(!j.append(6));CHECK(j.commit_through(*a));CHECK(j.trim_committed(3)==1);CHECK(j.append(6));CHECK(j.truncate_uncommitted());CHECK(j.committed().empty());return failures;}''',
        negative_old='for(std::size_t i=0;i<=position;++i)ring_[(head_+i)%ring_.size()]->committed=true;',
        negative_new='ring_[(head_+position)%ring_.size()]->committed=true;',
        negative_reason="committing only the named record breaks the committed-prefix invariant and prefix reclamation",
    )

    revise(
        "rectangle-generation-grid",
        header=r'''struct GridLease{std::size_t row;std::size_t col;std::size_t height;std::size_t width;std::uint64_t generation;};class RectangleGenerationGrid{public:RectangleGenerationGrid(std::size_t,std::size_t);std::optional<GridLease> reserve(std::size_t,std::size_t);bool release(GridLease);std::vector<std::size_t> row_free()const;private:std::size_t rows_;std::size_t cols_;std::vector<std::uint64_t> owner_;std::vector<std::size_t> row_runs_;std::uint64_t next_=1;void refresh(std::size_t);};''',
        reference=r'''RectangleGenerationGrid::RectangleGenerationGrid(std::size_t r,std::size_t c):rows_(r),cols_(c),owner_(r*c),row_runs_(r*c){if(!r||!c)throw std::invalid_argument("shape");for(std::size_t y=0;y<rows_;++y)refresh(y);}void RectangleGenerationGrid::refresh(std::size_t r){std::size_t run=0;for(std::size_t c=cols_;c-->0;){if(owner_[r*cols_+c]==0)++run;else run=0;row_runs_[r*cols_+c]=run;}}std::optional<GridLease> RectangleGenerationGrid::reserve(std::size_t h,std::size_t w){if(!h||!w||h>rows_||w>cols_)return std::nullopt;for(std::size_t r=0;r+h<=rows_;++r)for(std::size_t c=0;c+w<=cols_;++c){bool free=true;for(std::size_t y=0;y<h;++y)free&=row_runs_[(r+y)*cols_+c]>=w;if(free){if(next_==std::numeric_limits<std::uint64_t>::max())throw std::overflow_error("generation");auto g=next_++;for(std::size_t y=0;y<h;++y){for(std::size_t x=0;x<w;++x)owner_[(r+y)*cols_+c+x]=g;refresh(r+y);}return GridLease{r,c,h,w,g};}}return std::nullopt;}bool RectangleGenerationGrid::release(GridLease l){if(!l.height||!l.width||l.row>rows_||l.height>rows_-l.row||l.col>cols_||l.width>cols_-l.col)return false;for(std::size_t y=0;y<l.height;++y)for(std::size_t x=0;x<l.width;++x)if(owner_[(l.row+y)*cols_+l.col+x]!=l.generation)return false;for(std::size_t y=0;y<l.height;++y){for(std::size_t x=0;x<l.width;++x)owner_[(l.row+y)*cols_+l.col+x]=0;refresh(l.row+y);}return true;}std::vector<std::size_t> RectangleGenerationGrid::row_free()const{std::vector<std::size_t> out(rows_);for(std::size_t r=0;r<rows_;++r)for(std::size_t c=0;c<cols_;++c)out[r]+=owner_[r*cols_+c]==0;return out;}''',
        visible=r'''int main(){RectangleGenerationGrid g(3,4);auto a=g.reserve(2,2);CHECK(a&&a->row==0&&a->col==0);auto b=g.reserve(2,2);CHECK(b&&b->col==2);CHECK(g.row_free()==std::vector<std::size_t>({0,0,4}));CHECK(g.release(*a));auto c=g.reserve(3,1);CHECK(c&&c->col==0);return failures;}''',
        hidden=r'''int main(){RectangleGenerationGrid g(2,2);auto a=g.reserve(1,2);auto b=g.reserve(1,1);CHECK(a&&b);CHECK(g.release(*a));auto c=g.reserve(2,1);CHECK(c&&c->col==1);CHECK(!g.release({c->row,c->col,c->height,c->width,c->generation+1}));CHECK(g.release(*c));return failures;}''',
        negative_old='for(std::size_t y=0;y<h;++y)free&=row_runs_[(r+y)*cols_+c]>=w;',
        negative_new='free=row_runs_[r*cols_+c]>=w;',
        negative_reason="checking only one row summary admits a rectangle over occupied cells in another stripe",
    )

    revise(
        "capacity-generation-slab",
        task_id="capacity-indirect-compacting-slab",
        title="Indirect Compacting Slab",
        summary="Compact fixed object cells while preserving generational handles through indirection.",
        mechanism="fixed object cells, ordered handle slots, generation validation, and handle-to-physical indirection updated by compaction",
        contract="emplace uses the lowest free handle and lowest free physical cell; erase invalidates the handle; compact moves live cells left and reports physical moves while every live handle remains stable.",
        boundary="Zero capacity throws; full emplace is absent; invalid or stale get/erase is absent or false; generation and handle arithmetic are checked.",
        invariant="Every live handle names exactly one physical cell, every live physical cell names one handle, and compacted cells form a prefix.",
        forbidden="index-equals-physical-slot handles or a noncompacting free list",
        header=r'''struct CompactHandle{std::size_t slot;std::uint64_t generation;};struct CompactMove{std::size_t from;std::size_t to;};class IndirectCompactingSlab{public:explicit IndirectCompactingSlab(std::size_t);std::optional<CompactHandle> emplace(int);std::optional<int> get(CompactHandle)const;bool erase(CompactHandle);std::vector<CompactMove> compact();std::vector<int> physical_values()const;private:struct HandleEntry{std::size_t physical=0;std::uint64_t generation=1;bool live=false;};struct Cell{std::size_t handle;int value;};std::vector<HandleEntry> handles_;std::vector<std::optional<Cell>> cells_;std::set<std::size_t> free_handles_;};''',
        starter=r'''IndirectCompactingSlab::IndirectCompactingSlab(std::size_t){throw std::logic_error("not implemented");}std::optional<CompactHandle> IndirectCompactingSlab::emplace(int){throw std::logic_error("not implemented");}std::optional<int> IndirectCompactingSlab::get(CompactHandle)const{throw std::logic_error("not implemented");}bool IndirectCompactingSlab::erase(CompactHandle){throw std::logic_error("not implemented");}std::vector<CompactMove> IndirectCompactingSlab::compact(){throw std::logic_error("not implemented");}std::vector<int> IndirectCompactingSlab::physical_values()const{throw std::logic_error("not implemented");}''',
        reference=r'''IndirectCompactingSlab::IndirectCompactingSlab(std::size_t n):handles_(n),cells_(n){if(!n)throw std::invalid_argument("capacity");for(std::size_t i=0;i<n;++i)free_handles_.insert(i);}std::optional<CompactHandle> IndirectCompactingSlab::emplace(int v){if(free_handles_.empty())return std::nullopt;auto physical=static_cast<std::size_t>(std::find(cells_.begin(),cells_.end(),std::nullopt)-cells_.begin());if(physical==cells_.size())return std::nullopt;auto slot=*free_handles_.begin();free_handles_.erase(free_handles_.begin());handles_[slot].physical=physical;handles_[slot].live=true;cells_[physical]=Cell{slot,v};return CompactHandle{slot,handles_[slot].generation};}std::optional<int> IndirectCompactingSlab::get(CompactHandle h)const{if(h.slot>=handles_.size())return std::nullopt;const auto&e=handles_[h.slot];if(!e.live||e.generation!=h.generation||!cells_[e.physical])return std::nullopt;return cells_[e.physical]->value;}bool IndirectCompactingSlab::erase(CompactHandle h){if(!get(h))return false;auto&e=handles_[h.slot];cells_[e.physical].reset();e.live=false;++e.generation;free_handles_.insert(h.slot);return true;}std::vector<CompactMove> IndirectCompactingSlab::compact(){std::vector<CompactMove> out;std::size_t dst=0;for(std::size_t src=0;src<cells_.size();++src)if(cells_[src]){if(src!=dst){cells_[dst]=cells_[src];cells_[src].reset();handles_[cells_[dst]->handle].physical=dst;out.push_back({src,dst});}++dst;}return out;}std::vector<int> IndirectCompactingSlab::physical_values()const{std::vector<int> out;for(const auto&c:cells_)if(c)out.push_back(c->value);return out;}''',
        visible=r'''int main(){IndirectCompactingSlab s(3);auto a=s.emplace(1);auto b=s.emplace(2);auto c=s.emplace(3);CHECK(a&&b&&c&&s.erase(*b));auto moves=s.compact();CHECK(moves.size()==1&&moves[0].from==2&&moves[0].to==1);CHECK(s.get(*c)==3);CHECK(s.physical_values()==std::vector<int>({1,3}));return failures;}''',
        hidden=r'''int main(){IndirectCompactingSlab s(1);auto a=s.emplace(4);CHECK(a&&s.erase(*a));auto b=s.emplace(5);CHECK(b&&b->slot==a->slot&&b->generation!=a->generation);CHECK(!s.get(*a)&&s.get(*b)==5);return failures;}''',
        negative_old='handles_[cells_[dst]->handle].physical=dst;',
        negative_new='/* leave handle indirection at the old physical cell */',
        negative_reason="moving cells without updating handle indirection invalidates a stable live handle",
    )

    revise(
        "order-linked-open-map",
        task_id="rank-select-bit-directory",
        title="Rank/Select Bit Directory",
        summary="Maintain bounded bit membership with block counts for rank and select.",
        mechanism="fixed bit words plus per-word population summaries used to skip whole blocks during rank and select",
        contract="set and clear update exactly one bit and its block summary; rank counts set bits in [0,end); select returns the index of the zero-based nth set bit by skipping summarized blocks.",
        boundary="Zero capacity throws; indices and rank ends outside capacity throw; duplicate set/clear is false; absent select is empty.",
        invariant="Each block summary equals its word population and their sum equals ones().",
        forbidden="linear full-bit scans without maintained summaries or a dynamic ordered set",
        header=r'''class RankSelectBitDirectory{public:explicit RankSelectBitDirectory(std::size_t);bool set(std::size_t);bool clear(std::size_t);std::size_t rank(std::size_t)const;std::optional<std::size_t> select(std::size_t)const;std::size_t ones()const;private:std::size_t size_;std::vector<std::uint64_t> words_;std::vector<std::size_t> counts_;void refresh(std::size_t);};''',
        starter=r'''RankSelectBitDirectory::RankSelectBitDirectory(std::size_t):size_(0){throw std::logic_error("not implemented");}bool RankSelectBitDirectory::set(std::size_t){throw std::logic_error("not implemented");}bool RankSelectBitDirectory::clear(std::size_t){throw std::logic_error("not implemented");}std::size_t RankSelectBitDirectory::rank(std::size_t)const{throw std::logic_error("not implemented");}std::optional<std::size_t> RankSelectBitDirectory::select(std::size_t)const{throw std::logic_error("not implemented");}std::size_t RankSelectBitDirectory::ones()const{throw std::logic_error("not implemented");}void RankSelectBitDirectory::refresh(std::size_t){}''',
        reference=r'''RankSelectBitDirectory::RankSelectBitDirectory(std::size_t n):size_(n),words_((n+63)/64),counts_(words_.size()){if(!n)throw std::invalid_argument("capacity");}void RankSelectBitDirectory::refresh(std::size_t w){std::size_t count=0;auto bits=words_[w];while(bits){bits&=bits-1;++count;}counts_[w]=count;}bool RankSelectBitDirectory::set(std::size_t i){if(i>=size_)throw std::invalid_argument("index");auto w=i/64,mask=std::uint64_t{1}<<(i%64);if(words_[w]&mask)return false;words_[w]|=mask;refresh(w);return true;}bool RankSelectBitDirectory::clear(std::size_t i){if(i>=size_)throw std::invalid_argument("index");auto w=i/64,mask=std::uint64_t{1}<<(i%64);if(!(words_[w]&mask))return false;words_[w]&=~mask;refresh(w);return true;}std::size_t RankSelectBitDirectory::rank(std::size_t end)const{if(end>size_)throw std::invalid_argument("end");std::size_t total=0,full=end/64;for(std::size_t w=0;w<full;++w)total+=counts_[w];if(full<words_.size())for(std::size_t b=0;b<end%64;++b)total+=(words_[full]>>b)&1u;return total;}std::optional<std::size_t> RankSelectBitDirectory::select(std::size_t nth)const{for(std::size_t w=0;w<words_.size();++w){if(nth>=counts_[w]){nth-=counts_[w];continue;}for(std::size_t b=0;b<64&&w*64+b<size_;++b)if((words_[w]>>b)&1u){if(!nth)return w*64+b;--nth;}}return std::nullopt;}std::size_t RankSelectBitDirectory::ones()const{std::size_t total=0;for(auto n:counts_)total+=n;return total;}''',
        visible=r'''int main(){RankSelectBitDirectory d(130);CHECK(d.set(1)&&d.set(65)&&d.set(129));CHECK(d.rank(66)==2);CHECK(d.select(0)==1&&d.select(1)==65&&d.select(2)==129);CHECK(d.ones()==3);CHECK(d.clear(65));CHECK(d.select(1)==129);return failures;}''',
        hidden=r'''int main(){RankSelectBitDirectory d(2);CHECK(!d.clear(0));CHECK(d.set(0));CHECK(!d.set(0));CHECK(!d.select(1));try{d.rank(3);CHECK(false);}catch(const std::invalid_argument&){}return failures;}''',
        negative_old='counts_[w]=count;',
        negative_new='/* leave the block summary stale */',
        negative_reason="bit mutation without its population summary breaks rank/select block skipping",
    )

    return tuple(by[case.task_id] for case in cases)
