"""Clean-room case inventory for the duration/elapsed/countdown expansion.

The cases are intentionally data-only.  The owner in
``moonlight_duration_elapsed_countdown_expansion_aider_tasks`` renders and
verifies every root from this inventory.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DurationExpansionCase:
    task_id: str
    title: str
    subtopic: str
    mechanism: str
    api_shape: str
    invalid_rule: str
    ordering_rule: str
    boundary_rule: str
    strategy: int


_ROWS = (
    (
        "tempo-map-playback-integrator",
        "Tempo-map playback integrator",
        "rate-integration",
        "piecewise rational tempo integration across ordered beat spans",
        "ordered tempo segments plus a beat horizon -> checked microseconds",
        "reject nonpositive rates, reversed spans, and overlap",
        "segment start then input sequence",
        "clip the final segment exactly at the horizon",
    ),
    (
        "variable-frame-runtime-ledger",
        "Variable-frame runtime ledger",
        "rate-integration",
        "run-length frame-duration accumulation with dropped-frame accounting",
        "frame runs and time-base numerator/denominator -> runtime report",
        "reject zero counts, nonpositive time bases, and duplicate run IDs",
        "preserve run order",
        "zero admitted frames produce zero runtime",
    ),
    (
        "piecewise-speed-route-runtime",
        "Piecewise-speed route runtime",
        "rate-integration",
        "distance partition integration under piecewise constant speed limits",
        "contiguous route legs -> ceiling travel seconds and first gap",
        "reject nonpositive speed and overlapping or backward legs",
        "position order with stable leg ID ties",
        "touching legs are contiguous; uncovered distance is invalid",
    ),
    (
        "sensor-duty-cycle-exposure",
        "Sensor duty-cycle exposure",
        "rate-integration",
        "edge replay that integrates enabled exposure over a bounded horizon",
        "timestamped enable/disable edges and horizon -> enabled duration",
        "reject unknown edge kinds, decreasing timestamps, and duplicate state transitions",
        "caller event order",
        "an edge exactly at the horizon changes no exposure",
    ),
    (
        "production-rate-shift-duration",
        "Production rate shift duration",
        "rate-integration",
        "inverse-rate accumulation with carry between production shifts",
        "ordered shift capacities and requested units -> finish shift and elapsed",
        "reject nonpositive rates, negative units, and duplicate shift labels",
        "declared shift order",
        "completion exactly on a shift boundary selects that shift",
    ),
    (
        "fractional-sample-clock",
        "Fractional sample clock",
        "rate-integration",
        "Bresenham-style integer remainder carry for sample-to-time conversion",
        "sample batches and rational frequency -> ticks plus final remainder",
        "reject negative batch sizes and nonpositive frequency terms",
        "batch order is observable",
        "an empty batch preserves the current remainder",
    ),
    (
        "cooling-degree-minute-integral",
        "Cooling degree-minute integral",
        "rate-integration",
        "trapezoid integration of excess temperature over irregular samples",
        "strictly increasing samples and baseline -> doubled degree-minute area",
        "reject duplicate/backward timestamps and negative values",
        "timestamp order",
        "values equal to baseline contribute zero",
    ),
    (
        "hydraulic-pulse-on-time",
        "Hydraulic pulse on-time",
        "rate-integration",
        "union of clipped half-open valve pulses with per-channel dead time",
        "channel pulses, horizon, dead time -> effective on-time",
        "reject malformed pulses, duplicate IDs, and negative dead time",
        "channel then start then ID",
        "touching pulses merge only when their gap is at most dead time",
    ),
    (
        "battery-coulomb-runtime",
        "Battery coulomb runtime",
        "rate-integration",
        "signed current integration with capacity saturation and first-empty interpolation",
        "current plateaus and capacity -> remaining charge and empty position",
        "reject gaps, overlap, negative capacity, and arithmetic overflow",
        "plateau start",
        "landing exactly at zero records that plateau end",
    ),
    (
        "bandwidth-transfer-forecast",
        "Bandwidth transfer forecast",
        "rate-integration",
        "harmonic throughput forecast from byte/time observations",
        "positive transfer samples plus remaining bytes -> ceiling seconds",
        "reject empty observations, zero time, negative bytes, and overflow",
        "observations are aggregated, not reordered",
        "zero remaining bytes returns zero seconds",
    ),
    (
        "nested-trace-exclusive-time",
        "Nested trace exclusive time",
        "elapsed-replay",
        "stack replay of properly nested begin/end spans with child subtraction",
        "timestamped span edges -> per-label exclusive totals",
        "reject mismatched, duplicate, crossing, or unclosed spans",
        "edge order with nondecreasing timestamps",
        "zero-width spans are valid and contribute zero",
    ),
    (
        "async-watermark-lag",
        "Asynchronous watermark lag",
        "elapsed-replay",
        "per-source monotone watermark replay and global-minimum lag measurement",
        "source watermarks and observations -> maximum safe lag",
        "reject unknown sources, regressions, and observations before global watermark",
        "event sequence",
        "ties use the lexical source ID",
    ),
    (
        "distributed-critical-chain",
        "Distributed critical chain",
        "elapsed-replay",
        "DAG longest-path reconstruction over measured operation durations",
        "uniquely named operations and dependencies -> duration plus chain",
        "reject cycles, missing predecessors, duplicate IDs, and negative durations",
        "topological order with lexical ready ties",
        "an empty graph has duration zero and an empty chain",
    ),
    (
        "corrected-event-span",
        "Corrected event span",
        "elapsed-replay",
        "sequence-numbered correction replay over immutable raw timestamps",
        "events and corrections -> corrected min/max span",
        "reject stale corrections, unknown IDs, duplicate event IDs, and negative results",
        "correction sequence then event ID",
        "equal sequence numbers are stale",
    ),
    (
        "drift-calibrated-stopwatch",
        "Drift-calibrated stopwatch",
        "elapsed-replay",
        "piecewise affine tick calibration using exact integer interpolation",
        "raw tick intervals and calibration anchors -> calibrated elapsed",
        "reject nonmonotone anchors, zero tick spans, and uncovered intervals",
        "anchor tick order",
        "interval endpoints on anchors use the exact anchor value",
    ),
    (
        "dropout-gap-imputation",
        "Dropout gap imputation",
        "elapsed-replay",
        "bounded linear gap interpolation with explicit unresolved-hole accounting",
        "sample timestamps and maximum gap -> covered and imputed duration",
        "reject backward samples and negative limits; duplicate timestamps collapse",
        "timestamp then original position",
        "gaps equal to the limit are imputed",
    ),
    (
        "actor-occupancy-sweep",
        "Actor occupancy sweep",
        "elapsed-replay",
        "signed endpoint sweep producing exact time-at-concurrency buckets",
        "actor intervals -> duration histogram and first peak",
        "reject malformed intervals and duplicate actor/interval IDs",
        "endpoints before starts at equal positions",
        "touching intervals do not overlap",
    ),
    (
        "latency-bucket-quantile",
        "Latency bucket quantile",
        "elapsed-replay",
        "nearest-rank selection over weighted latency histogram buckets",
        "ordered bucket upper bounds, counts, and percentile -> selected bound",
        "reject unsorted bounds, negative counts, empty mass, and out-of-range percentile",
        "ascending bucket bound",
        "rank boundaries select the bucket containing the rank",
    ),
    (
        "rolling-utilization-window",
        "Rolling utilization window",
        "elapsed-replay",
        "two-pointer clipping of busy spans into each requested trailing window",
        "nonoverlapping busy spans and queries -> utilization numerators",
        "reject overlapping spans, decreasing queries, and nonpositive width",
        "query order",
        "left boundary is inclusive and right boundary exclusive",
    ),
    (
        "outage-episode-classifier",
        "Outage episode classifier",
        "elapsed-replay",
        "gap-aware coalescing followed by duration-band classification",
        "outage fragments, join gap, and bands -> ordered episodes",
        "reject overlap, negative gaps, and unsorted bands",
        "episode start then first fragment ID",
        "a gap equal to join gap coalesces",
    ),
    (
        "sealed-reveal-countdown",
        "Sealed reveal countdown",
        "countdown-state",
        "commit/reveal deadline machine with exactly-once reveal latch",
        "commit, advance, reveal, cancel operations -> state snapshots",
        "reject reveals before zero, repeated terminal actions, and negative advances",
        "operation order",
        "advancing exactly remaining units opens reveal",
    ),
    (
        "sterilization-stage-countdown",
        "Sterilization stage countdown",
        "countdown-state",
        "multi-stage consume loop with minimum-temperature holds",
        "stage plan plus temperature/elapsed updates -> completed stages",
        "reject low-temperature consumption and nonpositive stage durations",
        "stage declaration order",
        "one update may finish several stages",
    ),
    (
        "observation-window-arm",
        "Observation window arm",
        "countdown-state",
        "armed-window state machine that spends lead time then observation budget",
        "arm, tick, capture, disarm -> lead/active/closed state",
        "reject capture outside active state and re-arm after closure",
        "operation order",
        "zero lead activates immediately",
    ),
    (
        "relay-handoff-deadlines",
        "Relay handoff deadlines",
        "countdown-state",
        "per-leg countdown transfer with unused-time carry capped by next leg",
        "leg budgets and handoffs -> remaining team allowance",
        "reject out-of-order runners, negative elapsed, and post-finish handoffs",
        "runner index",
        "elapsed equal to allowance fails before carry",
    ),
    (
        "dependency-fuse-countdown",
        "Dependency fuse countdown",
        "countdown-state",
        "dependency-gated fuse bank with cascade cancellation",
        "fuse DAG, arm/tick/cancel operations -> fired IDs",
        "reject cycles, missing parents, duplicate IDs, and negative ticks",
        "lexical ID for simultaneous firing",
        "a cancelled parent cancels all descendants",
    ),
    (
        "recharge-charge-pool",
        "Recharge charge pool",
        "countdown-state",
        "independent charge timers with simultaneous recharge and bounded spend",
        "capacity, recharge duration, tick/spend operations -> charge state",
        "reject overspend, nonpositive recharge, and negative ticks",
        "oldest depleted slot recharges first on ties",
        "a tick may restore several charges",
    ),
    (
        "cohort-deadline-wheel",
        "Cohort deadline wheel",
        "countdown-state",
        "bucketed logical-time wheel with generation-stamped rescheduling",
        "cohort deadlines, reschedules, and advance -> expired cohorts",
        "reject past deadlines, stale generations, and duplicate cohorts",
        "deadline then cohort ID",
        "deadline equal to new time expires",
    ),
    (
        "reversible-calibration-timer",
        "Reversible calibration timer",
        "countdown-state",
        "forward/backward calibration cursor with irreversible completion boundary",
        "bounded signed adjustments and commit -> remaining calibration",
        "reject moves outside bounds and any move after commit",
        "operation order",
        "commit succeeds only at exactly zero",
    ),
    (
        "milestone-alarm-countdown",
        "Milestone alarm countdown",
        "countdown-state",
        "descending threshold cursor emitting crossed alarms exactly once",
        "unique thresholds and ticks -> emitted alarms",
        "reject nonpositive thresholds, duplicates, and negative ticks",
        "descending threshold",
        "zero tick emits nothing",
    ),
    (
        "semaphore-timeout-quorum",
        "Semaphore timeout quorum",
        "countdown-state",
        "quorum wait with member acknowledgements and timeout precedence",
        "member set, quorum, acknowledgements, and ticks -> acquired/timed-out",
        "reject unknown or duplicate acknowledgements and impossible quorum",
        "acknowledgement order",
        "quorum at the timeout instant wins only if acknowledged before tick",
    ),
    (
        "freeze-thaw-cycle-timer",
        "Freeze-thaw cycle timer",
        "countdown-state",
        "alternating phase countdown with completed-cycle counter",
        "freeze/thaw durations and temperature-qualified ticks -> cycle state",
        "reject wrong-sign temperature, negative ticks, and zero durations",
        "phase order",
        "excess elapsed crosses multiple phases",
    ),
    (
        "antidote-dose-countdown",
        "Antidote dose countdown",
        "countdown-state",
        "dose-spacing countdown with bounded early-dose deferral credits",
        "spacing, credits, tick/dose operations -> next eligibility",
        "reject late sequence IDs, negative ticks, and early dose without credit",
        "dose sequence",
        "a dose at remaining zero consumes no credit",
    ),
    (
        "airlock-equalization-timer",
        "Airlock equalization timer",
        "countdown-state",
        "pressure-delta dependent countdown that restarts on unsafe drift",
        "pressure samples and stable ticks -> unlock state",
        "reject out-of-range pressure and sampling regressions",
        "sample sequence",
        "unsafe drift resets accumulated stable time to zero",
    ),
    (
        "kiln-ramp-soak-countdown",
        "Kiln ramp/soak countdown",
        "countdown-state",
        "temperature ramp qualification followed by soak countdown and fault latch",
        "temperature/time updates -> ramping/soaking/complete/fault",
        "reject cooling during ramp beyond tolerance and any update after fault",
        "update order",
        "time before target temperature does not reduce soak",
    ),
    (
        "irrigation-zone-countdown",
        "Irrigation zone countdown",
        "countdown-state",
        "priority zone countdown with rain pause and unused-time donation",
        "zone plan, rain state, and ticks -> completed zones",
        "reject duplicate zones, negative ticks, and donation beyond next cap",
        "priority then declaration",
        "rain pauses every active zone",
    ),
    (
        "drone-return-reserve-timer",
        "Drone return-reserve timer",
        "countdown-state",
        "dual flight/reserve countdown with automatic return transition",
        "flight ticks and consumption rate changes -> outbound/return/landed",
        "reject nonpositive rates, negative ticks, and outbound commands after return",
        "command order",
        "reserve equality triggers return before further outbound time",
    ),
    (
        "packet-reassembly-expiry",
        "Packet reassembly expiry",
        "countdown-state",
        "per-message fragment countdown with completion-before-expiry ordering",
        "fragment arrivals and time advances -> completed/expired messages",
        "reject duplicate fragments, invalid totals, and late arrivals",
        "message ID for simultaneous terminal events",
        "arrival at deadline completes before the matching expiry sweep",
    ),
    (
        "consensus-election-timeout",
        "Consensus election timeout",
        "countdown-state",
        "term-stamped randomized-input timeout reset with stale-message rejection",
        "explicit timeout draws and heartbeat/tick events -> election terms",
        "reject nonpositive draws, stale terms, and negative ticks",
        "event order",
        "a heartbeat at zero cannot undo an already-started election",
    ),
    (
        "batch-embargo-countdown",
        "Batch embargo countdown",
        "countdown-state",
        "item embargo timers with batch release only when every item is ready",
        "item embargoes, extensions, and ticks -> released batches",
        "reject unknown items, negative extensions, and released mutations",
        "batch ID then item ID",
        "zero-duration items are ready at creation",
    ),
    (
        "telescope-exposure-sequence",
        "Telescope exposure sequence",
        "countdown-state",
        "exposure/readout phase machine with abort-safe partial accounting",
        "exposure plan, ticks, aborts -> captured and discarded durations",
        "reject nonpositive phases, negative ticks, and resume after abort",
        "plan order",
        "excess tick after readout starts the next exposure",
    ),
    (
        "linear-retry-budget",
        "Linear retry budget",
        "deadline-policy",
        "checked arithmetic-series retry delay accumulation",
        "attempt count, base, increment, and cap -> total wait",
        "reject negative values and overflow",
        "attempt number",
        "cap applies independently to each delay",
    ),
    (
        "fibonacci-retry-budget",
        "Fibonacci retry budget",
        "deadline-policy",
        "bounded Fibonacci delay recurrence with checked total",
        "attempt count and two seeds -> delay vector and sum",
        "reject negative seeds/count and recurrence overflow",
        "attempt number",
        "zero attempts return an empty vector",
    ),
    (
        "capped-exponential-retry",
        "Capped exponential retry",
        "deadline-policy",
        "doubling recurrence saturated per attempt before total accumulation",
        "base, cap, attempts -> delays and total",
        "reject nonpositive cap/base and overflow",
        "attempt number",
        "base above cap uses cap from the first attempt",
    ),
    (
        "decorrelated-backoff-ledger",
        "Decorrelated backoff ledger",
        "deadline-policy",
        "caller-draw validation against decorrelated lower/upper bounds",
        "base, cap, and proposed delays -> accepted schedule",
        "reject a draw outside [base,min(cap,3*previous)] atomically",
        "proposal order",
        "both bounds are inclusive",
    ),
    (
        "token-bucket-wait-time",
        "Token-bucket wait time",
        "deadline-policy",
        "fractional token accrual with remainder carry and earliest admission",
        "capacity, refill fraction, timestamped costs -> wait report",
        "reject decreasing timestamps, over-capacity costs, and nonpositive rates",
        "request order",
        "tokens arriving exactly at request time are spendable",
    ),
    (
        "leaky-bucket-drain-time",
        "Leaky-bucket drain time",
        "deadline-policy",
        "logical-time backlog drainage before each admitted arrival",
        "capacity, drain rate, and arrivals -> accepted/rejected backlog",
        "reject backward time and negative arrivals",
        "arrival order",
        "drain saturates backlog at zero",
    ),
    (
        "fixed-window-quota-reset",
        "Fixed-window quota reset",
        "deadline-policy",
        "epoch-aligned quota windows with checked boundary reset",
        "window width, quota, and requests -> decisions",
        "reject nonpositive policy and decreasing timestamps",
        "request order",
        "a request exactly at a boundary belongs to the new window",
    ),
    (
        "sliding-window-admission",
        "Sliding-window admission",
        "deadline-policy",
        "deque expiry of admitted request timestamps under a half-open horizon",
        "width, quota, and request times -> decisions",
        "reject nonpositive policy and decreasing timestamps",
        "request order",
        "timestamps at now-width are expired before admission",
    ),
    (
        "heartbeat-outage-detector",
        "Heartbeat outage detector",
        "deadline-policy",
        "per-node expected-heartbeat deadlines and coalesced outage episodes",
        "node heartbeats and logical advances -> outage intervals",
        "reject unknown nodes, backward time, and duplicate heartbeats",
        "deadline then node ID",
        "heartbeat exactly at deadline prevents outage",
    ),
    (
        "watchdog-miss-latch",
        "Watchdog miss latch",
        "deadline-policy",
        "consecutive missed-period counter with reset and permanent latch",
        "period, miss threshold, kick/tick events -> latched state",
        "reject negative ticks and any event after latch except snapshot",
        "event order",
        "one large tick can record multiple misses",
    ),
    (
        "idle-session-expiration",
        "Idle session expiration",
        "deadline-policy",
        "activity-rebased idle deadline with monotone logical time",
        "session opens, activity, and advance -> expired sessions",
        "reject stale activity, duplicate opens, and negative timeout",
        "deadline then session ID",
        "activity at exact deadline is stale because expiry runs first",
    ),
    (
        "absolute-lifetime-expiration",
        "Absolute lifetime expiration",
        "deadline-policy",
        "dual idle/absolute deadline selection without extending lifetime",
        "created sessions and activity -> terminal reason",
        "reject activity before creation, after expiry, or with stale sequence",
        "earliest deadline then ID",
        "equal idle/absolute deadlines report absolute",
    ),
    (
        "renewable-generation-lease",
        "Renewable generation lease",
        "deadline-policy",
        "generation-checked renewal with stale heap-entry suppression",
        "grant/renew/revoke/advance operations -> expired lease generations",
        "reject duplicate grants, stale generation, and nonpositive TTL",
        "deadline, ID, generation",
        "renewal at deadline loses to expiry",
    ),
    (
        "probation-grace-timeline",
        "Probation grace timeline",
        "deadline-policy",
        "violation-driven grace consumption with recovery checkpoints",
        "violations, recoveries, and advances -> probation outcome",
        "reject decreasing time, duplicate sequence, and post-terminal events",
        "event order",
        "recovery exactly at grace end succeeds before later advance",
    ),
    (
        "pause-resume-checkpoint-log",
        "Pause/resume checkpoint log",
        "timeline-analysis",
        "stateful stopwatch with pause exclusion and ordered checkpoint capture",
        "start/pause/resume/checkpoint/stop events -> active elapsed log",
        "reject illegal transitions and backward timestamps without mutation",
        "event order",
        "checkpoint while paused reports unchanged elapsed",
    ),
    (
        "correction-aware-lap-timeline",
        "Correction-aware lap timeline",
        "timeline-analysis",
        "lap prefix reconstruction after sequence-numbered delta corrections",
        "laps and corrections -> corrected splits and total",
        "reject unknown laps, stale corrections, negative results, and duplicates",
        "lap number; corrections by sequence",
        "zero-duration laps are retained",
    ),
    (
        "nested-scope-exclusive-profiler",
        "Nested-scope exclusive profiler",
        "timeline-analysis",
        "thread-local call stacks with cross-thread inclusive/exclusive aggregation",
        "threaded call edges -> sorted function totals",
        "reject mismatched stacks, backward thread time, and unclosed calls",
        "input order per thread",
        "simultaneous events on different threads are independent",
    ),
    (
        "concurrent-job-makespan",
        "Concurrent job makespan",
        "timeline-analysis",
        "capacity-constrained list scheduling using earliest-worker availability",
        "jobs, worker count, and release times -> assignments and makespan",
        "reject nonpositive workers, negative durations, duplicate IDs",
        "release then ID; earliest worker index tie",
        "zero-duration jobs still receive an assignment",
    ),
    (
        "two-machine-flow-shop",
        "Two-machine flow shop",
        "timeline-analysis",
        "Johnson partition ordering followed by two-machine completion recurrence",
        "two-stage jobs -> deterministic order and makespan",
        "reject negative stage durations and duplicate IDs",
        "Johnson keys then lexical ID",
        "zero-time stages are valid",
    ),
    (
        "precedence-earliest-finish",
        "Precedence earliest finish",
        "timeline-analysis",
        "Kahn topological replay with maximum predecessor finish",
        "DAG stages and durations -> per-stage finishes",
        "reject cycles, missing dependencies, duplicates, and negative duration",
        "lexical ready-stage ties",
        "sources start at zero",
    ),
    (
        "work-span-parallel-bound",
        "Work/span parallel bound",
        "timeline-analysis",
        "recursive series/parallel expression evaluation of total work and span",
        "validated expression nodes -> work, span, and parallelism ceiling",
        "reject cycles, wrong arity, missing nodes, and overflow",
        "postorder by node ID ties",
        "leaf duration may be zero",
    ),
    (
        "round-robin-service-clock",
        "Round-robin service clock",
        "timeline-analysis",
        "queue rotation under fixed quantum with arrival-time admission",
        "arriving jobs and quantum -> finish/response records",
        "reject nonpositive quantum, negative bursts, duplicate IDs, backward arrivals",
        "arrival then ID; FIFO ready queue",
        "burst zero finishes at arrival",
    ),
    (
        "shortest-job-response-ledger",
        "Shortest-job response ledger",
        "timeline-analysis",
        "nonpreemptive shortest-job selection among released work",
        "released jobs -> start, finish, and response",
        "reject negative times/bursts and duplicates",
        "burst then release then ID",
        "zero burst completes without advancing time",
    ),
    (
        "preemptive-priority-runtime",
        "Preemptive priority runtime",
        "timeline-analysis",
        "event-driven preemptive priority scheduling with remaining-time state",
        "arrivals with priorities -> completion order and run slices",
        "reject negative fields and duplicate IDs",
        "priority, arrival, ID",
        "equal-priority arrivals do not preempt the running job",
    ),
    (
        "deadline-lateness-profile",
        "Deadline lateness profile",
        "timeline-analysis",
        "earliest-deadline ordering and per-job signed lateness",
        "jobs with processing/deadline -> order and maximum lateness",
        "reject negative processing, duplicate IDs, and overflow",
        "deadline then ID",
        "negative lateness is retained",
    ),
    (
        "slack-consumption-ledger",
        "Slack consumption ledger",
        "timeline-analysis",
        "baseline-slack debit replay with first-negative witness",
        "milestones, actual durations, and amendments -> slack report",
        "reject stale amendments, missing milestones, and negative actuals",
        "milestone order then amendment sequence",
        "zero slack is not a breach",
    ),
    (
        "weighted-fair-time-slice",
        "Weighted-fair time slice",
        "timeline-analysis",
        "integer deficit round robin with carried credit",
        "weighted flows and service budget -> granted slices",
        "reject nonpositive weights, negative demand, duplicate IDs",
        "cyclic declaration order",
        "unused credit carries to the next round",
    ),
    (
        "largest-remainder-time-allocation",
        "Largest-remainder time allocation",
        "timeline-analysis",
        "Hamilton largest-remainder apportionment of integer time units",
        "weights and total units -> exact allocations",
        "reject negative weights, zero total weight, duplicate IDs",
        "fractional remainder descending then ID",
        "zero total units allocates zero to every member",
    ),
    (
        "proportional-runtime-split",
        "Proportional runtime split",
        "timeline-analysis",
        "checked quotient/remainder split with caller-specified minimums",
        "weights, minimums, and total runtime -> allocation or shortfall",
        "reject invalid weights/minimums, duplicates, and insufficient total",
        "input order for residual units",
        "sum of minimums equal total leaves no proportional pool",
    ),
    (
        "cumulative-checkpoint-crossings",
        "Cumulative checkpoint crossings",
        "timeline-analysis",
        "prefix accumulation with multi-threshold crossing emission",
        "increments and unique thresholds -> crossing step for each threshold",
        "reject negative increments, nonpositive thresholds, duplicates, and overflow",
        "threshold ascending",
        "threshold equal to a prefix crosses at that step",
    ),
    (
        "rolling-median-latency",
        "Rolling median latency",
        "timeline-analysis",
        "two-multiset rolling median with explicit outgoing erasure",
        "latencies and odd window width -> median series",
        "reject even/zero/oversized width and negative samples",
        "sample order",
        "duplicates occupy independent multiset counts",
    ),
    (
        "longest-busy-streak",
        "Longest busy streak",
        "timeline-analysis",
        "merge-touching busy intervals then stable longest-run selection",
        "busy intervals -> longest merged span and contributing IDs",
        "reject malformed intervals and duplicate IDs",
        "start/end/ID",
        "touching intervals merge; earliest equal longest wins",
    ),
    (
        "stable-lap-rank",
        "Stable lap rank",
        "timeline-analysis",
        "competition ranking with stable sequence ties and checked total",
        "numbered laps -> ranks, total, and spread",
        "reject duplicate numbers, negative elapsed, and overflow",
        "elapsed then original sequence",
        "equal elapsed shares rank with gaps after ties",
    ),
    (
        "pace-remaining-forecast",
        "Pace remaining forecast",
        "timeline-analysis",
        "median-of-recent positive split forecast with ceiling remaining time",
        "completed splits, recent count, and remaining distance -> forecast",
        "reject empty/negative splits, invalid recent count, and overflow",
        "split order",
        "even recent count uses the lower median",
    ),
    (
        "degree-hour-threshold-clock",
        "Degree-hour threshold clock",
        "timeline-analysis",
        "piecewise-linear threshold area accumulation with first-crossing interpolation",
        "temperature samples, baseline, target area -> crossing time",
        "reject backward timestamps, negative target, and ambiguous nonlinear crossing",
        "timestamp",
        "target zero crosses at first timestamp",
    ),
    (
        "thermal-dose-integrator",
        "Thermal dose integrator",
        "timeline-analysis",
        "piecewise exponential-equivalent dose accumulation using integer doubling bands",
        "temperature plateaus and reference -> equivalent minutes",
        "reject gaps/overlap, out-of-range temperatures, and overflow",
        "plateau start",
        "temperature exactly at reference has unit multiplier",
    ),
    (
        "satellite-contact-budget",
        "Satellite contact budget",
        "timeline-analysis",
        "visibility-window clipping and setup-cost subtraction across contacts",
        "contact windows, horizon, and per-contact setup -> usable duration",
        "reject overlap, negative setup, duplicate station IDs, and gaps outside horizon",
        "contact start then station ID",
        "a contact no longer than setup contributes zero",
    ),
    (
        "cryogenic-boiloff-window",
        "Cryogenic boil-off window",
        "timeline-analysis",
        "piecewise loss integration with reserve threshold crossing",
        "inventory, reserve, and loss-rate plateaus -> safe duration",
        "reject negative rates, overlap/gaps, invalid reserve, and overflow",
        "plateau start",
        "inventory equal reserve is unsafe at time zero",
    ),
    (
        "inspection-takt-ledger",
        "Inspection takt ledger",
        "timeline-analysis",
        "station-cycle replay with rework insertion and takt deviation accounting",
        "units, station durations, rework flags, and takt -> completion ledger",
        "reject negative durations, duplicate unit IDs, and nonpositive takt",
        "unit order then station order",
        "completion exactly on takt has zero deviation",
    ),
    (
        "floodgate-holdback-timer",
        "Floodgate holdback timer",
        "timeline-analysis",
        "inflow-volume integration against release capacity and first-spill detection",
        "flow plateaus, initial storage, capacity, and release rate -> spill report",
        "reject gaps/overlap, negative flows, and invalid storage",
        "plateau start",
        "storage equal capacity is allowed until positive net inflow",
    ),
)


_CYCLE_01_ROWS = _ROWS
REJECTED_CYCLE_01_IDS = tuple(row[0] for row in _CYCLE_01_ROWS)

_TRANSFORMS = (
    (
        "weighted-span",
        "Weighted span",
        "rate-integration",
        "convert each half-open span to ceiling(span * amount / weight)",
    ),
    (
        "clipped-window",
        "Clipped window",
        "elapsed-replay",
        "clip each half-open span to the inclusive/exclusive reserve/deadline horizon",
    ),
    (
        "countdown-budget",
        "Countdown budget",
        "countdown-state",
        "spend span * amount from a caller countdown when the record is enabled",
    ),
    (
        "deadline-slack",
        "Deadline slack",
        "countdown-state",
        "measure nonnegative remaining slack from each end point to its deadline in sequence order",
    ),
    (
        "retry-delay",
        "Retry delay",
        "deadline-policy",
        "derive a checked linear retry delay amount + sequence * weight",
    ),
    (
        "active-lifecycle",
        "Active lifecycle",
        "deadline-policy",
        "weight enabled lifetime by generation + 1 and ignore disabled lifetime",
    ),
    (
        "serial-schedule",
        "Serial schedule",
        "timeline-analysis",
        "advance one serial completion cursor by span plus setup amount in sequence order",
    ),
    (
        "remaining-forecast",
        "Remaining forecast",
        "timeline-analysis",
        "convert net span consumption above reserve to ceiling units by weight",
    ),
)

_REDUCERS = (
    ("total", "total", "sum every transformed value", "empty input returns zero"),
    (
        "ceiling-average",
        "ceiling average",
        "return the mathematical ceiling of the transformed mean",
        "empty input returns zero",
    ),
    (
        "carry-remainder",
        "carry and remainder",
        "divide the transformed sum by limit + 1, returning quotient as witness and remainder as value",
        "limit equal to LLONG_MAX is valid; mathematical divisor LLONG_MAX+1 is evaluated in the wide intermediate type",
    ),
    (
        "peak-witness",
        "peak witness",
        "select the greatest transformed value and its earliest processing index",
        "equal peaks keep the first index",
    ),
    (
        "threshold-count",
        "threshold count",
        "count transformed values greater than or equal to limit",
        "equality counts",
    ),
    (
        "positive-total",
        "positive total",
        "sum only strictly positive transformed values",
        "zero and negative values contribute nothing",
    ),
    (
        "first-crossing",
        "first crossing",
        "return the first processing index whose nonnegative prefix reaches limit",
        "limit zero crosses at the first accepted record; empty input has no crossing",
    ),
    (
        "capped-total",
        "capped total",
        "accumulate nonnegative transformed values without exceeding limit",
        "a contribution landing exactly on limit is retained",
    ),
    (
        "stable-change-count",
        "stable change count",
        "count runs of unequal consecutive transformed values",
        "empty input has zero runs",
    ),
    (
        "alternating-balance",
        "alternating balance",
        "return the absolute difference between even-index and odd-index transformed totals",
        "indexing follows deterministic processing order",
    ),
)

# Cycle-02 replacement inventory.  The rejected cycle-01 IDs remain preserved in
# immutable audit/remedy evidence; none is renamed or reused here.
_ROWS = tuple(
    (
        f"{transform_slug}-{reducer_slug}",
        f"{transform_title}: {reducer_title}",
        subtopic,
        f"{transform_mechanism}, then {reducer_mechanism}",
        "task-specific duration records -> checked report with value, witness, accepted, rejected, and stable event IDs",
        "reject malformed or duplicate records atomically; reject any unrepresentable result",
        "transform-specific stable order, then input position for remaining ties",
        f"{transform_boundary}; {reducer_boundary}",
    )
    for transform_slug, transform_title, subtopic, transform_mechanism in _TRANSFORMS
    for reducer_slug, reducer_title, reducer_mechanism, reducer_boundary in _REDUCERS
    for transform_boundary in (
        {
            "weighted-span": "zero weight is invalid and zero-width spans contribute zero",
            "clipped-window": "touching the clipping horizon contributes zero",
            "countdown-budget": "spending exactly the remaining countdown yields zero",
            "deadline-slack": "ending exactly at the deadline has zero slack",
            "retry-delay": "sequence zero adds no weighted delay",
            "active-lifecycle": "disabled records contribute zero",
            "serial-schedule": "a start equal to the current cursor has no idle gap",
            "remaining-forecast": "consumption equal to reserve contributes zero",
        }[transform_slug],
    )
)


CASES = tuple(DurationExpansionCase(*row, strategy=index) for index, row in enumerate(_ROWS))

assert len(CASES) == 80
assert len({case.task_id for case in CASES}) == 80
assert len({case.mechanism for case in CASES}) == 80
