"""Case inventory for the modular-clock-normalization expansion family."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ClockCase:
    task_id: str
    class_name: str
    title: str
    api: str
    definition: str
    starter: str
    visible: str
    hidden: str
    negative_old: str
    negative_new: str
    mechanism: str
    boundary: str
    negative_reason: str


def _case(
    task_id: str,
    class_name: str,
    title: str,
    api: str,
    definition: str,
    starter: str,
    visible: str,
    hidden: str,
    negative_old: str,
    negative_new: str,
    mechanism: str,
    boundary: str,
    negative_reason: str,
) -> ClockCase:
    return ClockCase(
        task_id,
        class_name,
        title,
        api,
        definition,
        starter,
        visible,
        hidden,
        negative_old,
        negative_new,
        mechanism,
        boundary,
        negative_reason,
    )


CASES: tuple[ClockCase, ...] = (
    _case(
        "mcn-euclidean-residue-ledger", "ResidueLedger", "Euclidean residue ledger",
        "class ResidueLedger { public: struct Ledger { long long residue; long long wraps; }; static std::optional<Ledger> fold(long long period,long long start,const std::vector<long long>& deltas); };",
        "std::optional<ResidueLedger::Ledger> ResidueLedger::fold(long long p,long long r,const std::vector<long long>& ds){if(p<=0||r<0||r>=p)return std::nullopt;long long w=0;for(long long d:ds){long long q=d/p,rem=d%p;if(rem<0){rem+=p;--q;}if(rem>0&&r>p-1-rem){r-=p-rem;++q;}else r+=rem;if((q>0&&w>LLONG_MAX-q)||(q<0&&w<LLONG_MIN-q))return std::nullopt;w+=q;}return Ledger{r,w};}",
        "std::optional<ResidueLedger::Ledger> ResidueLedger::fold(long long,long long,const std::vector<long long>&){return std::nullopt;}",
        "auto r=ResidueLedger::fold(10,8,{5,-23});check(r&&r->residue==0&&r->wraps==-1);",
        "check(!ResidueLedger::fold(0,0,{}));auto r=ResidueLedger::fold(7,0,{-1});check(r&&r->residue==6&&r->wraps==-1);auto z=ResidueLedger::fold(5,4,{1});check(z&&z->residue==0&&z->wraps==1);",
        "if(rem<0){rem+=p;--q;}", "if(rem<0){rem=-rem;}",
        "stepwise Euclidean reduction with signed quotient accounting",
        "the start is canonical and every step preserves a residue in [0,period)",
        "negative C++ remainder is reflected instead of Euclidean-normalized",
    ),
    _case(
        "mcn-balanced-phase-residue", "BalancedResidue", "Balanced phase residue",
        "class BalancedResidue { public: enum class Tie { negative, positive }; static std::optional<long long> normalize(long long value,long long period,Tie tie); };",
        "std::optional<long long> BalancedResidue::normalize(long long v,long long p,Tie tie){if(p<=0)return std::nullopt;long long r=v%p;if(r<0)r+=p;long long half=p/2;if(r>half||(p%2==0&&r==half&&tie==Tie::negative))r-=p;return r;}",
        "std::optional<long long> BalancedResidue::normalize(long long,long long,Tie){return std::nullopt;}",
        "check(BalancedResidue::normalize(15,10,BalancedResidue::Tie::negative)==-5);check(BalancedResidue::normalize(15,10,BalancedResidue::Tie::positive)==5);",
        "check(BalancedResidue::normalize(-6,9,BalancedResidue::Tie::positive)==3);check(!BalancedResidue::normalize(1,0,BalancedResidue::Tie::negative));",
        "tie==Tie::negative", "tie==Tie::positive",
        "centered representative selection with explicit even-period tie policy",
        "odd periods have one centered interval; even half-period ties obey Tie",
        "the half-period endpoint is always chosen positive",
    ),
    _case(
        "mcn-anchored-cycle-window", "AnchoredWindow", "Anchored cycle window",
        "class AnchoredWindow { public: struct Placement { long long value; long long cycle_index; }; static std::optional<Placement> place(long long value,long long origin,long long period); };",
        "std::optional<AnchoredWindow::Placement> AnchoredWindow::place(long long v,long long o,long long p){if(p<=0)return std::nullopt;long long d;if(__builtin_sub_overflow(v,o,&d))return std::nullopt;long long q=d/p,r=d%p;if(r<0){r+=p;--q;}long long x;if(__builtin_add_overflow(o,r,&x))return std::nullopt;return Placement{x,q};}",
        "std::optional<AnchoredWindow::Placement> AnchoredWindow::place(long long,long long,long long){return std::nullopt;}",
        "auto r=AnchoredWindow::place(-8,-3,10);check(r&&r->value==2&&r->cycle_index==-1);",
        "auto r=AnchoredWindow::place(27,5,7);check(r&&r->value==6&&r->cycle_index==3);check(!AnchoredWindow::place(0,0,-1));",
        "if(r<0){r+=p;--q;}", "if(r<0){r+=p;}",
        "floor-quotient placement in an arbitrary anchored half-open cycle",
        "the representative lies in [origin,origin+period) with mathematical floor quotient",
        "negative displacement uses truncating rather than floor division",
    ),
    _case(
        "mcn-directed-phase-distance", "DirectedDistance", "Directed phase distance",
        "class DirectedDistance { public: enum class Direction { clockwise, counterclockwise, same }; struct Distance { long long clockwise; long long counterclockwise; long long shortest; Direction direction; }; static std::optional<Distance> measure(long long from,long long to,long long period); };",
        "std::optional<DirectedDistance::Distance> DirectedDistance::measure(long long a,long long b,long long p){if(p<=0||a<0||a>=p||b<0||b>=p)return std::nullopt;long long cw=forward_distance(a,b,p),ccw=forward_distance(b,a,p);if(cw==0)return Distance{0,0,0,Direction::same};if(cw<ccw)return Distance{cw,ccw,cw,Direction::clockwise};return Distance{cw,ccw,ccw,Direction::counterclockwise};}",
        "std::optional<DirectedDistance::Distance> DirectedDistance::measure(long long,long long,long long){return std::nullopt;}",
        "auto r=DirectedDistance::measure(8,2,10);check(r&&r->clockwise==4&&r->counterclockwise==6&&r->direction==DirectedDistance::Direction::clockwise);",
        "auto t=DirectedDistance::measure(0,5,10);check(t&&t->direction==DirectedDistance::Direction::counterclockwise&&t->shortest==5);auto e=DirectedDistance::measure(0,LLONG_MAX-1,LLONG_MAX);check(e&&e->clockwise==LLONG_MAX-1&&e->counterclockwise==1);check(!DirectedDistance::measure(-1,0,10));",
        "if(cw<ccw)", "if(cw<=ccw)",
        "two directed modular distances with counterclockwise half-cycle ties",
        "inputs are canonical; equality is same and half-period ties are counterclockwise",
        "an exact directional tie is resolved clockwise",
    ),
    _case(
        "mcn-affine-phase-map", "AffinePhaseMap", "Affine phase map",
        "class AffinePhaseMap { public: static std::optional<long long> apply(long long phase,long long multiplier,long long shift,long long period); };",
        "std::optional<long long> AffinePhaseMap::apply(long long x,long long a,long long b,long long p){if(p<=0||x<0||x>=p)return std::nullopt;auto norm=[p](long long v){v%=p;if(v<0)v+=p;return v;};long long u=norm(a),v=x,acc=0;while(u){if(u&1)acc=(acc>=p-v)?acc-(p-v):acc+v;u>>=1;if(u)v=(v>=p-v)?v-(p-v):v+v;}long long s=norm(b);return (acc>=p-s)?acc-(p-s):acc+s;}",
        "std::optional<long long> AffinePhaseMap::apply(long long,long long,long long,long long){return std::nullopt;}",
        "check(AffinePhaseMap::apply(9,7,-4,11)==4);",
        "auto r=AffinePhaseMap::apply(LLONG_MAX-1,LLONG_MAX-2,LLONG_MIN+3,LLONG_MAX);check(r.has_value());check(!AffinePhaseMap::apply(0,1,0,0));",
        "while(u){if(u&1)", "while(false){if(u&1)",
        "overflow-safe binary modular multiplication followed by a signed shift",
        "phase must be canonical and period positive; intermediates never overflow",
        "raw affine multiplication is replaced by a no-op accumulator",
    ),
    _case(
        "mcn-linear-congruence-rendezvous", "CongruenceRendezvous", "Linear congruence rendezvous",
        "class CongruenceRendezvous { public: struct Solution { bool exists; long long step; long long repeats; }; static std::optional<Solution> first(long long rate,long long target,long long period); };",
        "std::optional<CongruenceRendezvous::Solution> CongruenceRendezvous::first(long long a,long long b,long long m){if(m<=0)return std::nullopt;a=euclidean_mod(a,m);b=euclidean_mod(b,m);long long g=std::gcd(a,m);if(b%g)return Solution{false,0,0};long long ar=a/g,br=b/g,mr=m/g;auto inv=inverse_mod_coprime(ar,mr);if(!inv)return std::nullopt;long long step=mul_mod_nonnegative(*inv,br,mr);return Solution{true,step,g};}",
        "std::optional<CongruenceRendezvous::Solution> CongruenceRendezvous::first(long long,long long,long long){return std::nullopt;}",
        "auto r=CongruenceRendezvous::first(6,8,14);check(r&&r->exists&&r->step==6&&r->repeats==2);",
        "auto n=CongruenceRendezvous::first(6,5,14);check(n&&!n->exists);check(!CongruenceRendezvous::first(1,0,0));",
        "if(b%g)return Solution{false,0,0};", "if(g!=1)return Solution{false,0,0};",
        "gcd reduction and modular inverse for a possibly non-coprime congruence",
        "incompatible targets return exists=false; the least solution is canonical",
        "all non-coprime rates are rejected even when the target is compatible",
    ),
    _case(
        "mcn-paired-clock-crt", "PairedClockCrt", "Paired clock CRT",
        "class PairedClockCrt { public: struct Solution { bool compatible; long long value; long long period; }; static std::optional<Solution> combine(long long a,long long pa,long long b,long long pb); };",
        "std::optional<PairedClockCrt::Solution> PairedClockCrt::combine(long long a,long long m,long long b,long long n){if(m<=0||n<=0||a<0||a>=m||b<0||b>=n)return std::nullopt;long long g=std::gcd(m,n);if(a%g!=b%g)return Solution{false,0,0};long long l;if(__builtin_mul_overflow(m/g,n,&l))return std::nullopt;long long mod=n/g;auto inv=inverse_mod_coprime((m/g)%mod,mod);if(!inv)return std::nullopt;long long rhs=euclidean_mod(b/g-a/g,mod);long long k=mul_mod_nonnegative(rhs,*inv,mod);long long v=add_mod_nonnegative(mul_mod_nonnegative(m%l,k,l),a,l);return Solution{true,v,l};}",
        "std::optional<PairedClockCrt::Solution> PairedClockCrt::combine(long long,long long,long long,long long){return std::nullopt;}",
        "auto r=PairedClockCrt::combine(2,6,5,9);check(r&&r->compatible&&r->value==14&&r->period==18);",
        "auto n=PairedClockCrt::combine(1,4,2,6);check(n&&!n->compatible);auto e=PairedClockCrt::combine(0,LLONG_MAX-2,1,LLONG_MAX);check(!e);check(!PairedClockCrt::combine(0,0,0,2));",
        "if(a%g!=b%g)return Solution{false,0,0};", "if(g!=1)return Solution{false,0,0};",
        "generalized two-modulus CRT with checked least-common period",
        "canonical residues are required and non-coprime systems use compatibility by gcd",
        "the solver assumes coprime periods",
    ),
    _case(
        "mcn-tick-rate-resampler", "TickRateResampler", "Tick-rate resampler",
        "class TickRateResampler { public: enum class Rounding { floor, nearest_even }; struct Mapped { long long tick; long long remainder; }; static std::optional<Mapped> map(long long tick,long long source_period,long long target_period,Rounding mode); };",
        "std::optional<TickRateResampler::Mapped> TickRateResampler::map(long long x,long long s,long long t,Rounding mode){if(s<=0||t<=0||x<0||x>=s)return std::nullopt;long long q=0,r=0;if(!mul_div_nonnegative(x,t,s,&q,&r))return std::nullopt;long long half=s/2;bool above=r>half;if(mode==Rounding::nearest_even&&(above||(s%2==0&&r==half&&(q&1))))++q;return Mapped{q%t,r};}",
        "std::optional<TickRateResampler::Mapped> TickRateResampler::map(long long,long long,long long,Rounding){return std::nullopt;}",
        "auto r=TickRateResampler::map(3,8,10,TickRateResampler::Rounding::nearest_even);check(r&&r->tick==4&&r->remainder==6);",
        "auto f=TickRateResampler::map(1,4,10,TickRateResampler::Rounding::nearest_even);check(f&&f->tick==2);auto e=TickRateResampler::map(1,4,2,TickRateResampler::Rounding::nearest_even);check(e&&e->tick==0);check(!TickRateResampler::map(4,4,2,TickRateResampler::Rounding::floor));",
        "mul_div_nonnegative(x,t,s,&q,&r)", "mul_div_nonnegative(x/s,t,s,&q,&r)",
        "exact rational phase scaling with floor or nearest-even rounding",
        "the source tick is canonical and the unreduced remainder is reported",
        "source division is performed before multiplication",
    ),
    _case(
        "mcn-fractional-phase-accumulator", "FractionalPhaseAccumulator", "Fractional phase accumulator",
        "class FractionalPhaseAccumulator { public: struct Report { bool valid; long long phase; long long fraction; }; FractionalPhaseAccumulator(long long period,long long numerator,long long denominator); Report advance(long long source_ticks); Report snapshot() const; private: long long period_; long long numerator_; long long denominator_; long long phase_=0; long long fraction_=0; bool valid_=true; };",
        "FractionalPhaseAccumulator::FractionalPhaseAccumulator(long long p,long long n,long long d):period_(p),numerator_(n),denominator_(d){if(p<=0||d<=0||n==LLONG_MIN)valid_=false;else{long long g=std::gcd(n<0?-n:n,d);numerator_/=g;denominator_/=g;}} FractionalPhaseAccumulator::Report FractionalPhaseAccumulator::snapshot()const{return {valid_,phase_,fraction_};} FractionalPhaseAccumulator::Report FractionalPhaseAccumulator::advance(long long ticks){if(!valid_)return snapshot();long long product,total;if(__builtin_mul_overflow(ticks,numerator_,&product)||__builtin_add_overflow(fraction_,product,&total))return {false,phase_,fraction_};long long q=total/denominator_,r=total%denominator_;if(r<0){r+=denominator_;--q;}long long step=euclidean_mod(q,period_);phase_=add_mod_nonnegative(phase_,step,period_);fraction_=r;return snapshot();}",
        "FractionalPhaseAccumulator::FractionalPhaseAccumulator(long long p,long long n,long long d):period_(p),numerator_(n),denominator_(d){} FractionalPhaseAccumulator::Report FractionalPhaseAccumulator::advance(long long){return {false,0,0};} FractionalPhaseAccumulator::Report FractionalPhaseAccumulator::snapshot()const{return {valid_,phase_,fraction_};}",
        "FractionalPhaseAccumulator x(10,3,2);auto a=x.advance(1);check(a.valid&&a.phase==1&&a.fraction==1);auto b=x.advance(1);check(b.phase==3&&b.fraction==0);",
        "FractionalPhaseAccumulator x(7,-1,3);auto a=x.advance(1);check(a.phase==6&&a.fraction==2);auto b=x.advance(2);check(b.phase==6&&b.fraction==0);FractionalPhaseAccumulator bad(0,1,2);check(!bad.snapshot().valid);",
        "fraction_=r;", "fraction_=0;",
        "stateful reduced rational carry retained across signed advances",
        "fraction is always in [0,denominator) and invalid construction never mutates",
        "fractional carry is discarded after each call",
    ),
    _case(
        "mcn-mixed-period-flattener", "MixedPeriodFlattener", "Mixed-period flattener",
        "class MixedPeriodFlattener { public: struct Flat { long long index; long long period; }; static std::optional<Flat> flatten(const std::vector<long long>& digits,const std::vector<long long>& radices); static std::optional<std::vector<long long>> expand(long long index,const std::vector<long long>& radices); };",
        "std::optional<MixedPeriodFlattener::Flat> MixedPeriodFlattener::flatten(const std::vector<long long>& d,const std::vector<long long>& r){if(d.size()!=r.size()||d.empty())return std::nullopt;long long x=0,p=1;for(size_t i=0;i<d.size();++i){if(r[i]<2||d[i]<0||d[i]>=r[i])return std::nullopt;}for(size_t i=0;i<d.size();++i){if(__builtin_mul_overflow(x,r[i],&x)||__builtin_add_overflow(x,d[i],&x)||__builtin_mul_overflow(p,r[i],&p))return std::nullopt;}return Flat{x,p};} std::optional<std::vector<long long>> MixedPeriodFlattener::expand(long long x,const std::vector<long long>& r){long long p=1;for(long long v:r){if(v<2||__builtin_mul_overflow(p,v,&p))return std::nullopt;}if(x<0||x>=p)return std::nullopt;std::vector<long long>d(r.size());for(size_t i=r.size();i-->0;){d[i]=x%r[i];x/=r[i];}return d;}",
        "std::optional<MixedPeriodFlattener::Flat> MixedPeriodFlattener::flatten(const std::vector<long long>&,const std::vector<long long>&){return std::nullopt;} std::optional<std::vector<long long>> MixedPeriodFlattener::expand(long long,const std::vector<long long>&){return std::nullopt;}",
        "auto f=MixedPeriodFlattener::flatten({1,2,3},{2,3,5});check(f&&f->index==28&&f->period==30);auto d=MixedPeriodFlattener::expand(28,{2,3,5});check(d&&*d==std::vector<long long>({1,2,3}));",
        "check(!MixedPeriodFlattener::flatten({0},{1}));check(!MixedPeriodFlattener::expand(30,{2,3,5}));auto z=MixedPeriodFlattener::flatten({0,0},{2,2});check(z&&z->index==0);",
        "x,r[i],&x", "x,r.back(),&x",
        "checked heterogeneous mixed-radix Horner flattening and inverse expansion",
        "all digits are canonical and every radix is at least two",
        "every position is flattened using the final radix",
    ),
    _case(
        "mcn-signed-hms-normalizer", "SignedHmsNormalizer", "Signed H:M:S normalizer",
        "class SignedHmsNormalizer { public: struct Hms { long long day; long long hour; long long minute; long long second; }; static std::optional<Hms> normalize(long long hours,long long minutes,long long seconds,long long day_hours); };",
        "std::optional<SignedHmsNormalizer::Hms> SignedHmsNormalizer::normalize(long long h,long long m,long long s,long long dh){if(dh<=0)return std::nullopt;long long total,day_units;if(__builtin_mul_overflow(h,60LL,&total)||__builtin_add_overflow(total,m,&total)||__builtin_mul_overflow(total,60LL,&total)||__builtin_add_overflow(total,s,&total)||__builtin_mul_overflow(dh,3600LL,&day_units))return std::nullopt;long long q=total/day_units,r=total%day_units;if(r<0){r+=day_units;--q;}return Hms{q,r/3600,(r/60)%60,r%60};}",
        "std::optional<SignedHmsNormalizer::Hms> SignedHmsNormalizer::normalize(long long,long long,long long,long long){return std::nullopt;}",
        "auto r=SignedHmsNormalizer::normalize(0,-1,-1,24);check(r&&r->day==-1&&r->hour==23&&r->minute==58&&r->second==59);",
        "auto r=SignedHmsNormalizer::normalize(49,120,120,24);check(r&&r->day==2&&r->hour==3&&r->minute==2&&r->second==0);check(!SignedHmsNormalizer::normalize(0,0,0,0));",
        "if(r<0){r+=day_units;--q;}", "if(r<0)r=-r;",
        "checked total-second combination with floor day division and base-60 expansion",
        "the day length is configurable and all fields may carry multiple units in either direction",
        "only one negative borrow is approximated by reflection",
    ),
    _case(
        "mcn-film-timecode-carry", "FilmTimecodeCarry", "Film timecode carry",
        "class FilmTimecodeCarry { public: struct Timecode { long long hour; long long minute; long long second; long long frame; }; struct Normalized { long long reel; Timecode code; }; static std::optional<Normalized> normalize(Timecode value,int fps,int hours_per_reel); };",
        "std::optional<FilmTimecodeCarry::Normalized> FilmTimecodeCarry::normalize(Timecode v,int fps,int hpr){if(fps<=0||hpr<=0)return std::nullopt;long long total,reel;if(__builtin_mul_overflow(v.hour,60LL,&total)||__builtin_add_overflow(total,v.minute,&total)||__builtin_mul_overflow(total,60LL,&total)||__builtin_add_overflow(total,v.second,&total)||__builtin_mul_overflow(total,static_cast<long long>(fps),&total)||__builtin_add_overflow(total,v.frame,&total)||__builtin_mul_overflow(static_cast<long long>(hpr),3600LL,&reel)||__builtin_mul_overflow(reel,static_cast<long long>(fps),&reel))return std::nullopt;long long q=total/reel,r=total%reel;if(r<0){r+=reel;--q;}Timecode c{r/(3600LL*fps),(r/(60LL*fps))%60,(r/fps)%60,r%fps};return Normalized{q,c};}",
        "std::optional<FilmTimecodeCarry::Normalized> FilmTimecodeCarry::normalize(Timecode,int,int){return std::nullopt;}",
        "auto r=FilmTimecodeCarry::normalize({0,0,59,30},24,2);check(r&&r->code.minute==1&&r->code.second==0&&r->code.frame==6);",
        "auto r=FilmTimecodeCarry::normalize({0,0,0,-1},25,1);check(r&&r->reel==-1&&r->code.hour==0&&r->code.minute==59&&r->code.second==59&&r->code.frame==24);check(!FilmTimecodeCarry::normalize({},0,1));",
        "(r/fps)%60", "r%60",
        "signed frame carry through seconds, minutes, hours, and reel quotient",
        "fps and reel hours are positive; every component may be noncanonical",
        "seconds are extracted without first removing the frame radix",
    ),
    _case(
        "mcn-music-grid-normalizer", "MusicGridNormalizer", "Music grid normalizer",
        "class MusicGridNormalizer { public: struct Position { long long bar; long long beat; long long tick; }; static std::optional<Position> normalize(Position value,int beats_per_bar,int ticks_per_beat); };",
        "std::optional<MusicGridNormalizer::Position> MusicGridNormalizer::normalize(Position v,int bpb,int tpb){if(bpb<=0||tpb<=0)return std::nullopt;long long q=v.tick/tpb,r=v.tick%tpb;if(r<0){r+=tpb;--q;}if(__builtin_add_overflow(v.beat,q,&v.beat))return std::nullopt;q=v.beat/bpb;long long b=v.beat%bpb;if(b<0){b+=bpb;--q;}if(__builtin_add_overflow(v.bar,q,&v.bar))return std::nullopt;return Position{v.bar,b,r};}",
        "std::optional<MusicGridNormalizer::Position> MusicGridNormalizer::normalize(Position,int,int){return std::nullopt;}",
        "auto r=MusicGridNormalizer::normalize({3,-1,-5},4,12);check(r&&r->bar==2&&r->beat==2&&r->tick==7);",
        "auto r=MusicGridNormalizer::normalize({0,9,25},4,12);check(r&&r->bar==2&&r->beat==3&&r->tick==1);check(!MusicGridNormalizer::normalize({},0,1));",
        "if(r<0){r+=tpb;--q;}", "if(r<0)r=0;",
        "two-stage floor carry from ticks through beats into an unbounded bar",
        "both grid radices are positive and negative ticks borrow across bars",
        "negative ticks are clamped instead of borrowed",
    ),
    _case(
        "mcn-shift-slot-subtick", "ShiftSlotSubtick", "Shift-slot-subtick normalizer",
        "class ShiftSlotSubtick { public: struct Coordinate { long long shift; long long slot; long long subtick; }; static std::optional<Coordinate> normalize(long long shift,long long slot,long long subtick,int slots,int subticks); };",
        "std::optional<ShiftSlotSubtick::Coordinate> ShiftSlotSubtick::normalize(long long sh,long long sl,long long sub,int ns,int nt){if(ns<=0||nt<=0)return std::nullopt;long long q=sub/nt,r=sub%nt;if(r<0){r+=nt;--q;}if(__builtin_add_overflow(sl,q,&sl))return std::nullopt;q=sl/ns;long long s=sl%ns;if(s<0){s+=ns;--q;}if(__builtin_add_overflow(sh,q,&sh))return std::nullopt;return Coordinate{sh,s,r};}",
        "std::optional<ShiftSlotSubtick::Coordinate> ShiftSlotSubtick::normalize(long long,long long,long long,int,int){return std::nullopt;}",
        "auto r=ShiftSlotSubtick::normalize(4,5,-1,6,10);check(r&&r->shift==4&&r->slot==4&&r->subtick==9);",
        "auto r=ShiftSlotSubtick::normalize(-2,-7,31,6,10);check(r&&r->shift==-3&&r->slot==2&&r->subtick==1);check(!ShiftSlotSubtick::normalize(0,0,0,1,0));",
        "if(s<0){s+=ns;--q;}", "if(s<0)s+=ns;",
        "heterogeneous Euclidean subtick and slot carries into a signed shift",
        "slot and subtick radices are independent and all supplied fields may be noncanonical",
        "the slot borrow does not decrement the outer shift",
    ),
    _case(
        "mcn-weighted-phase-histogram", "WeightedPhaseHistogram", "Weighted phase histogram",
        "class WeightedPhaseHistogram { public: struct Sample { long long phase; long long weight; }; struct Bucket { long long phase; long long weight; bool operator==(const Bucket& other) const { return phase==other.phase&&weight==other.weight; } }; static std::optional<std::vector<Bucket>> fold(long long period,const std::vector<Sample>& samples); };",
        "std::optional<std::vector<WeightedPhaseHistogram::Bucket>> WeightedPhaseHistogram::fold(long long p,const std::vector<Sample>& xs){if(p<=0)return std::nullopt;std::map<long long,long long> totals;for(auto x:xs){long long phase=euclidean_mod(x.phase,p);auto [it,inserted]=totals.emplace(phase,x.weight);if(!inserted){long long sum;if(__builtin_add_overflow(it->second,x.weight,&sum))return std::nullopt;it->second=sum;}}std::vector<Bucket> out;for(auto [phase,weight]:totals)if(weight!=0)out.push_back({phase,weight});return out;}",
        "std::optional<std::vector<WeightedPhaseHistogram::Bucket>> WeightedPhaseHistogram::fold(long long,const std::vector<Sample>&){return std::nullopt;}",
        "auto r=WeightedPhaseHistogram::fold(12,{{-1,3},{11,4},{2,-5},{14,2}});check(r&&*r==std::vector<WeightedPhaseHistogram::Bucket>({{2,-3},{11,7}}));",
        "auto e=WeightedPhaseHistogram::fold(7,{});check(e&&e->empty());auto z=WeightedPhaseHistogram::fold(5,{{-1,4},{4,-4}});check(z&&z->empty());check(!WeightedPhaseHistogram::fold(0,{}));check(!WeightedPhaseHistogram::fold(3,{{1,LLONG_MAX},{4,1}}));",
        "it->second=sum;", "it->second=x.weight;",
        "Euclidean phase bucketing with checked weight aggregation and zero-bucket elision",
        "period must be positive; empty input is valid, equal normalized phases merge, zero totals vanish, and overflow rejects the whole fold",
        "a later sample overwrites an equal normalized phase instead of accumulating its weight",
    ),
    _case(
        "mcn-heterogeneous-wheel-carry", "WheelCarry", "Heterogeneous wheel carry",
        "class WheelCarry { public: struct WheelState { long long outer; std::vector<long long> digits; }; static std::optional<WheelState> normalize(std::vector<long long> digits,const std::vector<long long>& radices); };",
        "std::optional<WheelCarry::WheelState> WheelCarry::normalize(std::vector<long long> d,const std::vector<long long>& r){if(d.size()!=r.size()||d.empty())return std::nullopt;long long carry=0;for(size_t i=d.size();i-->0;){if(r[i]<2||__builtin_add_overflow(d[i],carry,&d[i]))return std::nullopt;carry=d[i]/r[i];d[i]%=r[i];if(d[i]<0){d[i]+=r[i];--carry;}}return WheelState{carry,d};}",
        "std::optional<WheelCarry::WheelState> WheelCarry::normalize(std::vector<long long>,const std::vector<long long>&){return std::nullopt;}",
        "auto r=WheelCarry::normalize({1,-1,25},{3,4,10});check(r&&r->outer==0&&r->digits==std::vector<long long>({1,1,5}));",
        "auto r=WheelCarry::normalize({-7,0},{5,2});check(r&&r->outer==-2&&r->digits==std::vector<long long>({3,0}));check(!WheelCarry::normalize({1},{1}));",
        "for(size_t i=d.size();i-->0;)", "for(size_t i=0;i<d.size();++i)",
        "right-to-left floor carry through heterogeneous wheel radices",
        "all wheels are normalized and the final signed carry is returned as outer",
        "carries propagate from the most significant wheel toward the least",
    ),
    _case(
        "mcn-quotient-remainder-duration", "DurationQuotient", "Quotient-remainder duration",
        "class DurationQuotient { public: struct Parts { int sign; std::vector<long long> magnitude; }; static std::optional<Parts> split(long long signed_units,const std::vector<long long>& unit_sizes); };",
        "std::optional<DurationQuotient::Parts> DurationQuotient::split(long long x,const std::vector<long long>& sizes){if(sizes.empty()||x==LLONG_MIN)return std::nullopt;for(size_t i=0;i<sizes.size();++i)if(sizes[i]<=0||(i&&sizes[i-1]%sizes[i]!=0))return std::nullopt;int sign=x<0?-1:(x>0?1:0);long long n=x<0?-x:x;std::vector<long long> out;for(long long u:sizes){out.push_back(n/u);n%=u;}out.push_back(n);return Parts{sign,out};}",
        "std::optional<DurationQuotient::Parts> DurationQuotient::split(long long,const std::vector<long long>&){return std::nullopt;}",
        "auto r=DurationQuotient::split(-3661,{3600,60});check(r&&r->sign==-1&&r->magnitude==std::vector<long long>({1,1,1}));",
        "auto z=DurationQuotient::split(0,{10,2});check(z&&z->sign==0&&z->magnitude==std::vector<long long>({0,0,0}));check(!DurationQuotient::split(LLONG_MIN,{1}));check(!DurationQuotient::split(5,{6,4}));",
        "int sign=x<0?-1:(x>0?1:0);", "int sign=1;",
        "separate sign plus descending divisible-unit quotient expansion",
        "LLONG_MIN and non-divisible unit chains are invalid; zero has sign zero",
        "negative duration is treated as a positive cyclic time",
    ),
    _case(
        "mcn-carry-trace-normalizer", "CarryTraceNormalizer", "Carry-trace normalizer",
        "class CarryTraceNormalizer { public: struct Trace { std::vector<long long> digits; std::vector<long long> carries; }; static std::optional<Trace> normalize(std::vector<long long> digits,const std::vector<long long>& radices); };",
        "std::optional<CarryTraceNormalizer::Trace> CarryTraceNormalizer::normalize(std::vector<long long> d,const std::vector<long long>& r){if(d.size()!=r.size()||d.empty())return std::nullopt;std::vector<long long> c(d.size());for(size_t i=d.size();i-->0;){if(r[i]<2)return std::nullopt;long long q=d[i]/r[i],rem=d[i]%r[i];if(rem<0){rem+=r[i];--q;}d[i]=rem;c[i]=q;if(i){if(__builtin_add_overflow(d[i-1],q,&d[i-1]))return std::nullopt;}}return Trace{d,c};}",
        "std::optional<CarryTraceNormalizer::Trace> CarryTraceNormalizer::normalize(std::vector<long long>,const std::vector<long long>&){return std::nullopt;}",
        "auto r=CarryTraceNormalizer::normalize({1,2,13},{4,3,5});check(r&&r->digits==std::vector<long long>({2,1,3})&&r->carries==std::vector<long long>({0,1,2}));",
        "auto r=CarryTraceNormalizer::normalize({0,-1},{3,4});check(r&&r->digits==std::vector<long long>({2,3})&&r->carries==std::vector<long long>({-1,-1}));check(!CarryTraceNormalizer::normalize({},{ }));",
        "c[i]=q", "c[i]=0",
        "least-to-most significant floor carry with explicit per-position evidence",
        "the returned carries are the exact values applied to the next position",
        "correct canonical digits are returned with fabricated zero carry evidence",
    ),
    _case(
        "mcn-bounded-era-phase", "BoundedEraPhase", "Bounded era phase",
        "class BoundedEraPhase { public: struct EraPhase { long long era; long long phase; }; struct Report { bool valid; EraPhase value; }; static Report advance(EraPhase start,long long delta,long long period,long long min_era,long long max_era); };",
        "BoundedEraPhase::Report BoundedEraPhase::advance(EraPhase s,long long d,long long p,long long lo,long long hi){if(p<=0||lo>hi||s.era<lo||s.era>hi||s.phase<0||s.phase>=p)return {false,s};EraPhase original=s;long long q=d/p,r=d%p;if(r<0){r+=p;--q;}if(r&&s.phase>p-1-r){s.phase-=p-r;++q;}else s.phase+=r;long long era;if(__builtin_add_overflow(s.era,q,&era)||era<lo||era>hi)return {false,original};s.era=era;return {true,s};}",
        "BoundedEraPhase::Report BoundedEraPhase::advance(EraPhase s,long long,long long,long long,long long){return {false,s};}",
        "auto r=BoundedEraPhase::advance({2,9},5,10,0,3);check(r.valid&&r.value.era==3&&r.value.phase==4);",
        "auto r=BoundedEraPhase::advance({3,9},5,10,0,3);check(!r.valid&&r.value.era==3&&r.value.phase==9);auto n=BoundedEraPhase::advance({0,0},-1,10,0,3);check(!n.valid&&n.value.phase==0);",
        "return {false,original}", "original.era=std::clamp(era,lo,hi);return {false,original}",
        "atomic checked era quotient plus phase normalization inside fixed era bounds",
        "out-of-range advances return the original state without partial phase mutation",
        "era is clamped while the phase change is retained",
    ),
    _case(
        "mcn-sparse-unit-canonicalizer", "SparseUnitCanonicalizer", "Sparse unit canonicalizer",
        "class SparseUnitCanonicalizer { public: struct Term { std::string unit; long long amount; }; struct Unit { std::string name; long long base_size; }; static std::optional<std::vector<Term>> normalize(const std::vector<Term>& terms,const std::vector<Unit>& basis); };",
        "std::optional<std::vector<SparseUnitCanonicalizer::Term>> SparseUnitCanonicalizer::normalize(const std::vector<Term>& ts,const std::vector<Unit>& bs){if(bs.empty())return std::nullopt;std::map<std::string,long long> sizes;long long previous=LLONG_MAX;for(auto u:bs){if(u.name.empty()||u.base_size<=0||u.base_size>=previous||sizes.count(u.name))return std::nullopt;sizes[u.name]=u.base_size;previous=u.base_size;}long long total=0;for(auto t:ts){auto it=sizes.find(t.unit);long long term;if(it==sizes.end()||__builtin_mul_overflow(t.amount,it->second,&term)||__builtin_add_overflow(total,term,&total))return std::nullopt;}if(total<0)return std::nullopt;std::vector<Term> out;for(auto u:bs){long long q=total/u.base_size;total%=u.base_size;if(q)out.push_back({u.name,q});}return out;}",
        "std::optional<std::vector<SparseUnitCanonicalizer::Term>> SparseUnitCanonicalizer::normalize(const std::vector<Term>&,const std::vector<Unit>&){return std::nullopt;}",
        "auto r=SparseUnitCanonicalizer::normalize({{\"tick\",125}},{{\"turn\",60},{\"tick\",1}});check(r&&r->size()==2&&(*r)[0].amount==2&&(*r)[1].amount==5);",
        "auto z=SparseUnitCanonicalizer::normalize({},{{\"major\",10},{\"minor\",1}});check(z&&z->empty());check(!SparseUnitCanonicalizer::normalize({{\"x\",1}},{{\"y\",1}}));check(!SparseUnitCanonicalizer::normalize({},{{\"a\",2},{\"b\",3}}));",
        "total%=u.base_size", "total=0",
        "checked sparse term accumulation followed by descending basis decomposition",
        "basis sizes are unique and strictly descending; negative totals are invalid",
        "terms are merely sorted by label and residual magnitude is discarded",
    ),
)


if len(CASES) != 20:
    raise RuntimeError(f"expected first case tranche of 20, got {len(CASES)}")
