"""Numeric and ordered-algebra reduction roots for DPR expansion v2."""

from __future__ import annotations

from w8_biayn.integrations.moonlight_dpr_v2_cases import DprCase, _case


CASES: tuple[DprCase, ...] = (
    _case(
        "dpr-exact-mean-quotient", "ExactMeanQuotient", "Exact mean quotient", "numeric",
        "class ExactMeanQuotient { public: struct Mean{long long floor_quotient;unsigned long long remainder,count;}; static std::optional<Mean> reduce(const std::vector<std::vector<long long>>& shards); };",
        "std::optional<ExactMeanQuotient::Mean> ExactMeanQuotient::reduce(const std::vector<std::vector<long long>>& shards){long long total=0;unsigned long long count=0;for(const auto&shard:shards){long long partial=0;for(long long v:shard)if(__builtin_add_overflow(partial,v,&partial))return std::nullopt;if(__builtin_add_overflow(total,partial,&total)||count>ULLONG_MAX-shard.size())return std::nullopt;count+=shard.size();}if(count==0||count>static_cast<unsigned long long>(LLONG_MAX))return std::nullopt;long long n=static_cast<long long>(count),q=total/n,r=total%n;if(r<0){--q;r+=n;}return Mean{q,static_cast<unsigned long long>(r),count};}",
        "std::optional<ExactMeanQuotient::Mean> ExactMeanQuotient::reduce(const std::vector<std::vector<long long>>&){return std::nullopt;}",
        "auto m=ExactMeanQuotient::reduce({{-5,2},{2}});check(m&&m->floor_quotient==-1&&m->remainder==2&&m->count==3);",
        "check(!ExactMeanQuotient::reduce({}));check(!ExactMeanQuotient::reduce({{LLONG_MAX,1}}));auto m=ExactMeanQuotient::reduce({{4},{5,6}});check(m&&m->floor_quotient==5&&m->remainder==0);",
        "if(r<0){--q;r+=n;}", "if(r<0)r=-r;",
        "checked shard sum/count with Euclidean mean division", "empty totals reject and negative sums have nonnegative remainder", "negative remainder is absolutized without lowering the quotient",
    ),
    _case(
        "dpr-modular-product-fold", "ModularProductFold", "Modular product fold", "numeric",
        "class ModularProductFold { public: static std::optional<unsigned long long> reduce(const std::vector<std::vector<unsigned long long>>& shards,unsigned long long modulus); };",
        "std::optional<unsigned long long> ModularProductFold::reduce(const std::vector<std::vector<unsigned long long>>& shards,unsigned long long m){if(m==0)return std::nullopt;auto mul=[m](unsigned long long a,unsigned long long b){unsigned long long out=0;a%=m;while(b){if(b&1ULL)out=out>=m-a?out-(m-a):out+a;b>>=1;if(b)a=a>=m-a?a-(m-a):a+a;}return out;};std::vector<unsigned long long> partials;for(const auto&s:shards){unsigned long long p=1%m;for(auto v:s)p=mul(p,v);partials.push_back(p);}while(partials.size()>1){std::vector<unsigned long long> next;for(std::size_t i=0;i<partials.size();i+=2)next.push_back(i+1<partials.size()?mul(partials[i],partials[i+1]):partials[i]);partials=next;}return partials.empty()?1%m:partials[0];}",
        "std::optional<unsigned long long> ModularProductFold::reduce(const std::vector<std::vector<unsigned long long>>&,unsigned long long){return std::nullopt;}",
        "auto p=ModularProductFold::reduce({{ULLONG_MAX,2},{3}},97);check(p&&*p==((ULLONG_MAX%97)*2ULL%97)*3ULL%97);",
        "check(!ModularProductFold::reduce({},0));auto e=ModularProductFold::reduce({},1);check(e&&*e==0);auto p=ModularProductFold::reduce({{0},{9}},7);check(p&&*p==0);",
        "out=out>=m-a?out-(m-a):out+a", "out=(out+a)%m",
        "overflow-safe double-and-add modular partial product tree", "zero modulus rejects and empty product is the modular identity", "native unsigned addition wraps before modular reduction",
    ),
    _case(
        "dpr-polynomial-chunk-compose", "PolynomialChunkCompose", "Polynomial chunk compose", "numeric",
        "class PolynomialChunkCompose { public: struct Segment{unsigned long long value,power;std::size_t length;}; static std::optional<Segment> evaluate(const std::vector<unsigned long long>& coefficients,unsigned long long x,unsigned long long modulus,std::size_t chunk); };",
        "std::optional<PolynomialChunkCompose::Segment> PolynomialChunkCompose::evaluate(const std::vector<unsigned long long>& c,unsigned long long x,unsigned long long m,std::size_t chunk){if(m==0||chunk==0||m>1000000000ULL)return std::nullopt;auto mul=[m](unsigned long long a,unsigned long long b){return (a*b)%m;};std::vector<Segment> parts;for(std::size_t b=0;b<c.size();b+=chunk){Segment s{0,1,0};for(std::size_t i=b;i<std::min(c.size(),b+chunk);++i){s.value=(mul(s.value,x)+c[i])%m;s.power=mul(s.power,x);++s.length;}parts.push_back(s);}Segment out{0,1,0};for(const auto&s:parts){out.value=(mul(out.value,s.power)+s.value)%m;out.power=mul(out.power,s.power);out.length+=s.length;}return out;}",
        "std::optional<PolynomialChunkCompose::Segment> PolynomialChunkCompose::evaluate(const std::vector<unsigned long long>&,unsigned long long,unsigned long long,std::size_t){return std::nullopt;}",
        "auto p=PolynomialChunkCompose::evaluate({2,3,4},5,97,2);check(p&&p->value==69&&p->power==28&&p->length==3);",
        "check(!PolynomialChunkCompose::evaluate({},2,0,1));check(!PolynomialChunkCompose::evaluate({},2,7,0));auto p=PolynomialChunkCompose::evaluate({},3,7,2);check(p&&p->value==0&&p->power==1&&p->length==0);",
        "mul(out.value,s.power)+s.value", "out.value+s.value",
        "ordered Horner chunk summaries composed by segment power", "empty coefficients return the identity summary and chunk size is positive", "chunk values are added without positional power composition",
    ),
    _case(
        "dpr-ordered-matrix-chain", "OrderedMatrixChain", "Ordered matrix chain", "numeric",
        "class OrderedMatrixChain { public: struct Matrix{unsigned long long a,b,c,d;bool operator==(const Matrix&o)const{return std::tie(a,b,c,d)==std::tie(o.a,o.b,o.c,o.d);}}; static std::optional<Matrix> multiply(const std::vector<std::vector<Matrix>>& shards,unsigned long long modulus); };",
        "std::optional<OrderedMatrixChain::Matrix> OrderedMatrixChain::multiply(const std::vector<std::vector<Matrix>>& shards,unsigned long long m){if(m==0||m>1000000000ULL)return std::nullopt;auto product=[m](const Matrix&x,const Matrix&y){return Matrix{(x.a*y.a+x.b*y.c)%m,(x.a*y.b+x.b*y.d)%m,(x.c*y.a+x.d*y.c)%m,(x.c*y.b+x.d*y.d)%m};};Matrix out{1%m,0,0,1%m};for(const auto&shard:shards){Matrix partial{1%m,0,0,1%m};for(const auto&x:shard)partial=product(partial,x);out=product(out,partial);}return out;}",
        "std::optional<OrderedMatrixChain::Matrix> OrderedMatrixChain::multiply(const std::vector<std::vector<Matrix>>&,unsigned long long){return std::nullopt;}",
        "using M=OrderedMatrixChain::Matrix;auto p=OrderedMatrixChain::multiply({{{1,2,0,1}},{{2,0,1,3}}},101);check(p&&*p==M{4,6,1,3});",
        "check(!OrderedMatrixChain::multiply({},0));using M=OrderedMatrixChain::Matrix;auto p=OrderedMatrixChain::multiply({},7);check(p&&*p==M{1,0,0,1});auto q=OrderedMatrixChain::multiply({{{0,1,1,0},{1,1,0,1}}},97);check(q&&*q==M{0,1,1,1});",
        "out=product(out,partial);", "out=product(partial,out);",
        "source-ordered noncommutative matrix partial composition", "empty chain is identity and zero modulus rejects", "shard products compose in reverse operand order",
    ),
    _case(
        "dpr-checked-dot-product", "CheckedDotProduct", "Checked dot product", "numeric",
        "class CheckedDotProduct { public: struct Pair{long long left,right;}; static std::optional<long long> reduce(const std::vector<std::vector<Pair>>& shards); };",
        "std::optional<long long> CheckedDotProduct::reduce(const std::vector<std::vector<Pair>>& shards){long long total=0;for(const auto&s:shards){long long partial=0;for(auto p:s){long long product=0;if(__builtin_mul_overflow(p.left,p.right,&product)||__builtin_add_overflow(partial,product,&partial))return std::nullopt;}if(__builtin_add_overflow(total,partial,&total))return std::nullopt;}return total;}",
        "std::optional<long long> CheckedDotProduct::reduce(const std::vector<std::vector<Pair>>&){return std::nullopt;}",
        "auto p=CheckedDotProduct::reduce({{{2,3},{-4,5}},{{7,2}}});check(p&&*p==0);",
        "check(!CheckedDotProduct::reduce({{{LLONG_MAX,2}}}));auto p=CheckedDotProduct::reduce({{},{{3,4}}});check(p&&*p==12);auto z=CheckedDotProduct::reduce({});check(z&&*z==0);",
        "__builtin_mul_overflow(p.left,p.right,&product)", "product=p.left*p.right,false",
        "checked per-shard products and checked ordered total merge", "empty input is zero while product or accumulation overflow rejects", "multiplication occurs unchecked before accumulation",
    ),
    _case(
        "dpr-first-prefix-overflow", "FirstPrefixOverflow", "First prefix overflow", "numeric",
        "class FirstPrefixOverflow { public: struct Report{bool overflow;std::size_t index;long long value;}; static Report scan(const std::vector<std::vector<long long>>& shards,long long initial); };",
        "FirstPrefixOverflow::Report FirstPrefixOverflow::scan(const std::vector<std::vector<long long>>& shards,long long initial){long long current=initial;std::size_t index=0;for(const auto&s:shards)for(long long v:s){long long next=0;if(__builtin_add_overflow(current,v,&next))return {true,index,current};current=next;++index;}return {false,index,current};}",
        "FirstPrefixOverflow::Report FirstPrefixOverflow::scan(const std::vector<std::vector<long long>>&,long long x){return {false,0,x};}",
        "auto r=FirstPrefixOverflow::scan({{1,2},{3,-1}},5);check(!r.overflow&&r.index==4&&r.value==10);",
        "auto r=FirstPrefixOverflow::scan({{-1},{2}},LLONG_MAX);check(r.overflow&&r.index==1);auto q=FirstPrefixOverflow::scan({},7);check(!q.overflow&&q.index==0&&q.value==7);auto z=FirstPrefixOverflow::scan({{-1}},LLONG_MIN);check(z.overflow&&z.index==0);auto w=FirstPrefixOverflow::scan({{LLONG_MAX,1}},-1);check(!w.overflow&&w.value==LLONG_MAX);",
        "current=next;++index;", "current=v;++index;",
        "shard-ordered checked prefix state with exact first-failure index", "empty input preserves the initial value and failure index is source-global", "each element replaces rather than advances the incoming prefix state",
    ),
    _case(
        "dpr-chan-variance-state", "ChanVarianceState", "Chan variance state", "numeric",
        "class ChanVarianceState { public: struct State{long long count,sum,sum_squares;}; static std::optional<State> reduce(const std::vector<std::vector<long long>>& shards); };",
        "std::optional<ChanVarianceState::State> ChanVarianceState::reduce(const std::vector<std::vector<long long>>& shards){std::vector<State> partials;for(const auto&s:shards){State p{0,0,0};for(long long v:s){long long square=0;if(__builtin_mul_overflow(v,v,&square)||__builtin_add_overflow(p.sum,v,&p.sum)||__builtin_add_overflow(p.sum_squares,square,&p.sum_squares)||p.count==LLONG_MAX)return std::nullopt;++p.count;}partials.push_back(p);}while(partials.size()>1){std::vector<State> next;for(std::size_t i=0;i<partials.size();i+=2){if(i+1==partials.size()){next.push_back(partials[i]);continue;}State x=partials[i];if(__builtin_add_overflow(x.count,partials[i+1].count,&x.count)||__builtin_add_overflow(x.sum,partials[i+1].sum,&x.sum)||__builtin_add_overflow(x.sum_squares,partials[i+1].sum_squares,&x.sum_squares))return std::nullopt;next.push_back(x);}partials=next;}return partials.empty()?State{0,0,0}:partials[0];}",
        "std::optional<ChanVarianceState::State> ChanVarianceState::reduce(const std::vector<std::vector<long long>>&){return std::nullopt;}",
        "auto s=ChanVarianceState::reduce({{1,2},{3,4}});check(s&&s->count==4&&s->sum==10&&s->sum_squares==30);",
        "check(!ChanVarianceState::reduce({{LLONG_MAX}}));auto s=ChanVarianceState::reduce({{}, {5}});check(s&&s->count==1&&s->sum==5&&s->sum_squares==25);auto e=ChanVarianceState::reduce({});check(e&&e->count==0);",
        "__builtin_add_overflow(x.sum_squares,partials[i+1].sum_squares,&x.sum_squares)", "(x.sum_squares=std::max(x.sum_squares,partials[i+1].sum_squares),false)",
        "balanced merge of count, first moment, and exact second moment", "squaring and every field merge are checked", "second moments take a maximum rather than add across partials",
    ),
    _case(
        "dpr-paired-covariance-state", "PairedCovarianceState", "Paired covariance state", "numeric",
        "class PairedCovarianceState { public: struct Pair{long long x,y;}; struct State{long long count,sum_x,sum_y,sum_xy;}; static std::optional<State> reduce(const std::vector<std::vector<Pair>>& shards); };",
        "std::optional<PairedCovarianceState::State> PairedCovarianceState::reduce(const std::vector<std::vector<Pair>>& shards){State out{0,0,0,0};for(const auto&s:shards){State p{0,0,0,0};for(auto v:s){long long xy=0;if(__builtin_mul_overflow(v.x,v.y,&xy)||__builtin_add_overflow(p.sum_x,v.x,&p.sum_x)||__builtin_add_overflow(p.sum_y,v.y,&p.sum_y)||__builtin_add_overflow(p.sum_xy,xy,&p.sum_xy)||p.count==LLONG_MAX)return std::nullopt;++p.count;}if(__builtin_add_overflow(out.count,p.count,&out.count)||__builtin_add_overflow(out.sum_x,p.sum_x,&out.sum_x)||__builtin_add_overflow(out.sum_y,p.sum_y,&out.sum_y)||__builtin_add_overflow(out.sum_xy,p.sum_xy,&out.sum_xy))return std::nullopt;}return out;}",
        "std::optional<PairedCovarianceState::State> PairedCovarianceState::reduce(const std::vector<std::vector<Pair>>&){return std::nullopt;}",
        "auto s=PairedCovarianceState::reduce({{{1,2},{2,4}},{{3,1}}});check(s&&s->count==3&&s->sum_x==6&&s->sum_y==7&&s->sum_xy==13);",
        "check(!PairedCovarianceState::reduce({{{LLONG_MAX,2}}}));auto e=PairedCovarianceState::reduce({});check(e&&e->count==0);auto s=PairedCovarianceState::reduce({{},{{-2,3}}});check(s&&s->sum_xy==-6);",
        "__builtin_add_overflow(p.sum_xy,xy,&p.sum_xy)", "__builtin_add_overflow(p.sum_xy,v.x+v.y,&p.sum_xy)",
        "mergeable bivariate count, marginal sums, and co-moment", "paired multiplication overflow invalidates the whole state", "co-moment accumulates coordinate sums instead of products",
    ),
    _case(
        "dpr-rational-weighted-centroid", "RationalWeightedCentroid", "Rational weighted centroid", "numeric",
        "class RationalWeightedCentroid { public: struct Point{long long x,y,weight;}; struct State{long long weight,x_moment,y_moment;}; static std::optional<State> reduce(const std::vector<std::vector<Point>>& shards); };",
        "std::optional<RationalWeightedCentroid::State> RationalWeightedCentroid::reduce(const std::vector<std::vector<Point>>& shards){State out{0,0,0};for(const auto&s:shards){State p{0,0,0};for(auto v:s){if(v.weight<=0)return std::nullopt;long long xm=0,ym=0;if(__builtin_mul_overflow(v.x,v.weight,&xm)||__builtin_mul_overflow(v.y,v.weight,&ym)||__builtin_add_overflow(p.weight,v.weight,&p.weight)||__builtin_add_overflow(p.x_moment,xm,&p.x_moment)||__builtin_add_overflow(p.y_moment,ym,&p.y_moment))return std::nullopt;}if(__builtin_add_overflow(out.weight,p.weight,&out.weight)||__builtin_add_overflow(out.x_moment,p.x_moment,&out.x_moment)||__builtin_add_overflow(out.y_moment,p.y_moment,&out.y_moment))return std::nullopt;}if(out.weight==0)return std::nullopt;return out;}",
        "std::optional<RationalWeightedCentroid::State> RationalWeightedCentroid::reduce(const std::vector<std::vector<Point>>&){return std::nullopt;}",
        "auto c=RationalWeightedCentroid::reduce({{{0,2,1}},{{4,0,3}}});check(c&&c->weight==4&&c->x_moment==12&&c->y_moment==2);",
        "check(!RationalWeightedCentroid::reduce({}));check(!RationalWeightedCentroid::reduce({{{1,2,0}}}));check(!RationalWeightedCentroid::reduce({{{LLONG_MAX,1,2}}}));auto c=RationalWeightedCentroid::reduce({{{-2,-3,2}}});check(c&&c->x_moment==-4);",
        "__builtin_mul_overflow(v.x,v.weight,&xm)", "(xm=v.x,false)",
        "checked weighted mass and first-moment partial states", "weights are strictly positive and an empty total has no centroid", "x coordinates omit multiplication by mass",
    ),
    _case(
        "dpr-max-subarray-monoid", "MaxSubarrayMonoid", "Maximum subarray monoid", "numeric",
        "class MaxSubarrayMonoid { public: struct Best{long long sum;std::size_t begin,end;}; static std::optional<Best> reduce(const std::vector<std::vector<long long>>& shards); };",
        "std::optional<MaxSubarrayMonoid::Best> MaxSubarrayMonoid::reduce(const std::vector<std::vector<long long>>& shards){struct State{long long total,prefix,suffix,best;std::size_t length,prefix_end,suffix_begin,best_begin,best_end;};auto make=[](const std::vector<long long>&s)->std::optional<State>{if(s.empty())return State{0,LLONG_MIN,LLONG_MIN,LLONG_MIN,0,0,0,0,0};long long total=0,prefix=LLONG_MIN,current=0,best=LLONG_MIN;std::size_t prefix_end=0,best_begin=0,best_end=0,start=0;for(std::size_t i=0;i<s.size();++i){if(__builtin_add_overflow(total,s[i],&total))return std::nullopt;if(__builtin_add_overflow(current,s[i],&current))return std::nullopt;if(total>prefix){prefix=total;prefix_end=i+1;}if(current>best){best=current;best_begin=start;best_end=i+1;}if(current<0){current=0;start=i+1;}}long long suffix=0,run=0;std::size_t suffix_begin=s.size();for(std::size_t i=s.size();i-->0;){if(__builtin_add_overflow(run,s[i],&run))return std::nullopt;if(run>=suffix||suffix_begin==s.size()){suffix=run;suffix_begin=i;}}return State{total,prefix,suffix,best,s.size(),prefix_end,suffix_begin,best_begin,best_end};};std::optional<State> acc;for(const auto&s:shards){auto part=make(s);if(!part)return std::nullopt;if(part->length==0)continue;if(!acc){acc=*part;continue;}State a=*acc,b=*part;long long cross=0,total=0;if(__builtin_add_overflow(a.suffix,b.prefix,&cross)||__builtin_add_overflow(a.total,b.total,&total))return std::nullopt;State n{total,a.prefix,a.suffix,a.best,a.length+b.length,a.prefix_end,a.suffix_begin,a.best_begin,a.best_end};long long pref=0;if(__builtin_add_overflow(a.total,b.prefix,&pref))return std::nullopt;if(pref>n.prefix){n.prefix=pref;n.prefix_end=a.length+b.prefix_end;}long long suff=0;if(__builtin_add_overflow(a.suffix,b.total,&suff))return std::nullopt;if(suff>=b.suffix){n.suffix=suff;n.suffix_begin=a.suffix_begin;}else{n.suffix=b.suffix;n.suffix_begin=a.length+b.suffix_begin;}if(b.best>n.best){n.best=b.best;n.best_begin=a.length+b.best_begin;n.best_end=a.length+b.best_end;}if(cross>n.best){n.best=cross;n.best_begin=a.suffix_begin;n.best_end=a.length+b.prefix_end;}acc=n;}if(!acc)return std::nullopt;return Best{acc->best,acc->best_begin,acc->best_end};}",
        "std::optional<MaxSubarrayMonoid::Best> MaxSubarrayMonoid::reduce(const std::vector<std::vector<long long>>&){return std::nullopt;}",
        "auto b=MaxSubarrayMonoid::reduce({{-2,3},{4,-1,2}});check(b&&b->sum==8&&b->begin==1&&b->end==5);",
        "check(!MaxSubarrayMonoid::reduce({}));auto b=MaxSubarrayMonoid::reduce({{-5},{-2,-7}});check(b&&b->sum==-2&&b->begin==1&&b->end==2);auto q=MaxSubarrayMonoid::reduce({{1},{-5,10}});check(q&&q->sum==10&&q->begin==2&&q->end==3);check(!MaxSubarrayMonoid::reduce({{LLONG_MAX},{1}}));",
        "if(cross>n.best)", "if(false&&cross>n.best)",
        "cross-boundary total/prefix/suffix/best summary merge", "empty totals have no interval and checked arithmetic is atomic", "cross-shard candidates are never considered",
    ),
    _case(
        "dpr-longest-equal-run", "LongestEqualRun", "Longest equal run", "numeric",
        "class LongestEqualRun { public: struct Run{long long value;std::size_t begin,length;}; static std::optional<Run> reduce(const std::vector<std::vector<long long>>& shards); };",
        "std::optional<LongestEqualRun::Run> LongestEqualRun::reduce(const std::vector<std::vector<long long>>& shards){struct State{long long first,last,best_value;std::size_t length,prefix,suffix,best_begin,best_length;};std::optional<State> acc;std::size_t global=0;for(const auto&s:shards){if(s.empty())continue;State p{s.front(),s.back(),s.front(),s.size(),1,1,0,1};while(p.prefix<s.size()&&s[p.prefix]==s[0])++p.prefix;while(p.suffix<s.size()&&s[s.size()-1-p.suffix]==s.back())++p.suffix;for(std::size_t i=0;i<s.size();){std::size_t j=i+1;while(j<s.size()&&s[j]==s[i])++j;if(j-i>p.best_length){p.best_length=j-i;p.best_begin=i;p.best_value=s[i];}i=j;}if(!acc){p.best_begin+=global;acc=p;global+=s.size();continue;}State a=*acc;std::size_t cross=a.last==p.first?a.suffix+p.prefix:0;if(p.best_length>a.best_length){a.best_length=p.best_length;a.best_begin=global+p.best_begin;a.best_value=p.best_value;}if(cross>a.best_length){a.best_length=cross;a.best_begin=global-a.suffix;a.best_value=a.last;}a.prefix=(a.prefix==a.length&&a.first==p.first)?a.length+p.prefix:a.prefix;a.suffix=(p.suffix==p.length&&a.last==p.last)?p.length+a.suffix:p.suffix;a.last=p.last;a.length+=p.length;acc=a;global+=s.size();}if(!acc)return std::nullopt;return Run{acc->best_value,acc->best_begin,acc->best_length};}",
        "std::optional<LongestEqualRun::Run> LongestEqualRun::reduce(const std::vector<std::vector<long long>>&){return std::nullopt;}",
        "auto r=LongestEqualRun::reduce({{1,2,2},{2,2,3}});check(r&&r->value==2&&r->begin==1&&r->length==4);",
        "check(!LongestEqualRun::reduce({{}, {}}));auto r=LongestEqualRun::reduce({{4,4},{5,5}});check(r&&r->value==4&&r->begin==0&&r->length==2);auto q=LongestEqualRun::reduce({{7},{7},{7}});check(q&&q->length==3);",
        "std::size_t cross=a.last==p.first?a.suffix+p.prefix:0;", "std::size_t cross=0;",
        "endpoint-aware longest-run partial merge", "cross-boundary equal endpoints coalesce and ties retain the earliest run", "boundary runs are never joined",
    ),
    _case(
        "dpr-bracket-balance-summary", "BracketBalanceSummary", "Bracket balance summary", "numeric",
        "class BracketBalanceSummary { public: struct Result{bool balanced;std::optional<std::size_t> first_unmatched_close;long long unmatched_open;}; static std::optional<Result> reduce(const std::vector<std::string>& shards); };",
        "std::optional<BracketBalanceSummary::Result> BracketBalanceSummary::reduce(const std::vector<std::string>& shards){long long carry=0;std::size_t index=0;std::optional<std::size_t> close;for(const auto&s:shards)for(char c:s){if(c!='('&&c!=')')return std::nullopt;carry+=c=='('?1:-1;if(!close&&carry<0)close=index;++index;}return Result{!close&&carry==0,close,std::max(0LL,carry)};}",
        "std::optional<BracketBalanceSummary::Result> BracketBalanceSummary::reduce(const std::vector<std::string>&){return std::nullopt;}",
        "auto r=BracketBalanceSummary::reduce({\"(()\",\")()\"});check(r&&r->balanced&&!r->first_unmatched_close&&r->unmatched_open==0);auto q=BracketBalanceSummary::reduce({\"))\"});check(q&&q->first_unmatched_close==0);",
        "check(!BracketBalanceSummary::reduce({\"(x)\"}));auto r=BracketBalanceSummary::reduce({\")\",\"(\"});check(r&&!r->balanced&&r->first_unmatched_close==0);auto q=BracketBalanceSummary::reduce({\"((\",\")\"});check(q&&!q->balanced&&q->unmatched_open==1);auto z=BracketBalanceSummary::reduce({\"))\"});check(z&&z->first_unmatched_close==0);",
        "if(!close&&carry<0)close=index", "if(carry<0)close=index",
        "shard-ordered bracket balance state with earliest-close evidence", "invalid symbols reject and earliest unmatched close is a global index", "later unmatched closes overwrite the earliest failure index",
    ),
)


assert len(CASES) == 12
