"""Offset, selection, and canonicalization cases for modular clocks."""
from __future__ import annotations

from w8_biayn.integrations.moonlight_modular_clock_normalization_cases import (
    ClockCase,
    _case,
)


CASES: tuple[ClockCase, ...] = (
    _case(
        "mcn-offset-day-quotient-board", "OffsetDayBoard", "Offset day-quotient board",
        "class OffsetDayBoard { public: struct Location { std::string label; long long offset; }; struct Reading { std::string label; long long phase; long long day_delta; }; static std::optional<std::vector<Reading>> render(long long reference,long long period,const std::vector<Location>& locations); };",
        "std::optional<std::vector<OffsetDayBoard::Reading>> OffsetDayBoard::render(long long r,long long p,const std::vector<Location>& xs){if(p<=0||r<0||r>=p)return std::nullopt;std::vector<Reading> out;for(auto x:xs){if(x.label.empty())return std::nullopt;long long q=x.offset/p,rem=x.offset%p;if(rem<0){rem+=p;--q;}long long phase=add_mod_nonnegative(r,rem,p);if(rem&&r>p-1-rem&&__builtin_add_overflow(q,1LL,&q))return std::nullopt;out.push_back({x.label,phase,q});}return out;}",
        "std::optional<std::vector<OffsetDayBoard::Reading>> OffsetDayBoard::render(long long,long long,const std::vector<Location>&){return std::nullopt;}",
        "auto r=OffsetDayBoard::render(2,10,{{\"far\",27},{\"west\",-15}});check(r&&(*r)[0].phase==9&&(*r)[0].day_delta==2&&(*r)[1].phase==7&&(*r)[1].day_delta==-2);",
        "auto e=OffsetDayBoard::render(0,5,{});check(e&&e->empty());check(!OffsetDayBoard::render(0,5,{{\"\",1}}));auto r=OffsetDayBoard::render(9,10,{{\"x\",1}});check(r&&(*r)[0].day_delta==1);",
        "out.push_back({x.label,phase,q})", "out.push_back({x.label,phase,std::clamp(q,-1LL,1LL)})",
        "signed offset Euclidean quotient retained without day-range clamping",
        "labels are nonempty and output order is identical to input order",
        "day delta is clamped to previous/same/next",
    ),
    _case(
        "mcn-offset-graph-consistency", "OffsetGraphConsistency", "Offset graph consistency",
        "class OffsetGraphConsistency { public: struct Edge { int from; int to; long long offset; }; struct Report { bool consistent; int bad_edge; std::vector<long long> potentials; }; static Report solve(int node_count,const std::vector<Edge>& edges,long long period); };",
        "OffsetGraphConsistency::Report OffsetGraphConsistency::solve(int n,const std::vector<Edge>& es,long long p){Report out{n>=0&&p>0,-1,std::vector<long long>(n,-1)};if(!out.consistent)return out;std::vector<std::vector<std::pair<int,long long>>> g(n);for(size_t i=0;i<es.size();++i){auto e=es[i];if(e.from<0||e.from>=n||e.to<0||e.to>=n){out.consistent=false;out.bad_edge=static_cast<int>(i);return out;}long long w=euclidean_mod(e.offset,p);g[e.from].push_back({e.to,w});g[e.to].push_back({e.from,w==0?0:p-w});}for(int root=0;root<n;++root)if(out.potentials[root]<0){out.potentials[root]=0;std::queue<int> q;q.push(root);while(!q.empty()){int u=q.front();q.pop();for(auto [v,w]:g[u]){long long want=add_mod_nonnegative(out.potentials[u],w,p);if(out.potentials[v]<0){out.potentials[v]=want;q.push(v);}else if(out.potentials[v]!=want){out.consistent=false;for(size_t i=0;i<es.size();++i)if((es[i].from==u&&es[i].to==v)||(es[i].from==v&&es[i].to==u)){out.bad_edge=static_cast<int>(i);break;}return out;}}}}return out;}",
        "OffsetGraphConsistency::Report OffsetGraphConsistency::solve(int,const std::vector<Edge>&,long long){return {false,-1,{}};}",
        "auto r=OffsetGraphConsistency::solve(3,{{0,1,3},{1,2,4},{0,2,7}},10);check(r.consistent&&r.potentials==std::vector<long long>({0,3,7}));",
        "auto b=OffsetGraphConsistency::solve(3,{{0,1,3},{1,2,4},{0,2,8}},10);check(!b.consistent&&b.bad_edge>=0);auto d=OffsetGraphConsistency::solve(3,{},10);check(d.consistent&&d.potentials==std::vector<long long>({0,0,0}));",
        "for(int root=0;root<n;++root)", "for(int root=0;root<std::min(n,1);++root)",
        "component-wise BFS assignment of modular offset potentials and constraint checks",
        "every disconnected component receives root potential zero; invalid endpoints fail",
        "only the first connected component is checked",
    ),
    _case(
        "mcn-canonical-offset-table", "CanonicalOffsetTable", "Canonical offset table",
        "class CanonicalOffsetTable { public: struct Entry { std::string label; long long offset; }; struct Group { long long residue; std::vector<std::string> labels; }; static std::optional<std::vector<Group>> build(long long period,const std::vector<Entry>& entries); };",
        "std::optional<std::vector<CanonicalOffsetTable::Group>> CanonicalOffsetTable::build(long long p,const std::vector<Entry>& xs){if(p<=0)return std::nullopt;std::set<std::string> labels;std::map<long long,std::vector<std::string>> groups;for(auto x:xs){if(x.label.empty()||!labels.insert(x.label).second)return std::nullopt;long long r=x.offset%p;if(r<0)r+=p;groups[r].push_back(x.label);}std::vector<Group> out;for(auto& [r,names]:groups)out.push_back({r,names});return out;}",
        "std::optional<std::vector<CanonicalOffsetTable::Group>> CanonicalOffsetTable::build(long long,const std::vector<Entry>&){return std::nullopt;}",
        "auto r=CanonicalOffsetTable::build(10,{{\"a\",-1},{\"b\",9},{\"c\",2}});check(r&&r->size()==2&&(*r)[0].residue==2&&(*r)[1].labels==std::vector<std::string>({\"a\",\"b\"}));",
        "check(!CanonicalOffsetTable::build(5,{{\"a\",1},{\"a\",2}}));auto e=CanonicalOffsetTable::build(5,{});check(e&&e->empty());check(!CanonicalOffsetTable::build(0,{}));",
        "groups[r].push_back(x.label)", "groups[x.offset].push_back(x.label)",
        "label-unique grouping by Euclidean-equivalent signed offsets",
        "groups order by residue while equal-residue labels retain input order",
        "grouping uses raw rather than normalized offsets",
    ),
    _case(
        "mcn-inverse-offset-resolver", "InverseOffsetResolver", "Inverse offset resolver",
        "class InverseOffsetResolver { public: struct Candidate { int id; long long offset; }; struct Instant { int id; long long absolute; long long phase; }; static std::optional<std::vector<Instant>> resolve(long long local,long long period,const std::vector<Candidate>& candidates,std::optional<long long> day); };",
        "std::optional<std::vector<InverseOffsetResolver::Instant>> InverseOffsetResolver::resolve(long long local,long long p,const std::vector<Candidate>& xs,std::optional<long long> day){if(p<=0||local<0||local>=p)return std::nullopt;std::set<int> ids;std::vector<Instant> out;for(auto c:xs){if(c.id<=0||!ids.insert(c.id).second)return std::nullopt;long long r=sub_mod_nonnegative(local,euclidean_mod(c.offset,p),p);long long absolute=r;if(day){long long base;if(__builtin_mul_overflow(*day,p,&base)||__builtin_add_overflow(base,r,&absolute))return std::nullopt;}out.push_back({c.id,absolute,r});}std::sort(out.begin(),out.end(),[](Instant a,Instant b){return a.absolute!=b.absolute?a.absolute<b.absolute:a.id<b.id;});return out;}",
        "std::optional<std::vector<InverseOffsetResolver::Instant>> InverseOffsetResolver::resolve(long long,long long,const std::vector<Candidate>&,std::optional<long long>){return std::nullopt;}",
        "auto r=InverseOffsetResolver::resolve(2,10,{{2,5},{1,-3}},1);check(r&&(*r)[0].id==1&&(*r)[0].absolute==15&&(*r)[1].id==2&&(*r)[1].absolute==17);",
        "auto r=InverseOffsetResolver::resolve(0,10,{{1,1}},std::nullopt);check(r&&(*r)[0].phase==9);check(!InverseOffsetResolver::resolve(0,5,{{1,0},{1,1}},0));",
        "sub_mod_nonnegative(local,euclidean_mod(c.offset,p),p)", "add_mod_nonnegative(local,euclidean_mod(c.offset,p),p)",
        "inverse signed-offset mapping with optional absolute-day lift and stable ordering",
        "candidate IDs are positive/unique and local phase is canonical",
        "offsets are added instead of subtracted",
    ),
    _case(
        "mcn-offset-roundtrip-auditor", "OffsetRoundtripAuditor", "Offset round-trip auditor",
        "class OffsetRoundtripAuditor { public: struct Record { long long reference; long long offset; long long local; long long day; }; struct Report { bool valid; int bad_index; }; static Report audit(const std::vector<Record>& records,long long period); };",
        "OffsetRoundtripAuditor::Report OffsetRoundtripAuditor::audit(const std::vector<Record>& xs,long long p){if(p<=0)return {false,-1};for(size_t i=0;i<xs.size();++i){auto x=xs[i];if(x.reference<0||x.reference>=p||x.local<0||x.local>=p)return {false,static_cast<int>(i)};long long q=x.offset/p,r=x.offset%p;if(r<0){r+=p;--q;}long long local=add_mod_nonnegative(x.reference,r,p);if(r&&x.reference>p-1-r&&__builtin_add_overflow(q,1LL,&q))return {false,static_cast<int>(i)};if(local!=x.local||q!=x.day)return {false,static_cast<int>(i)};}return {true,-1};}",
        "OffsetRoundtripAuditor::Report OffsetRoundtripAuditor::audit(const std::vector<Record>&,long long){return {false,-1};}",
        "auto r=OffsetRoundtripAuditor::audit({{8,5,3,1},{2,-5,7,-1}},10);check(r.valid);",
        "auto b=OffsetRoundtripAuditor::audit({{8,5,3,0}},10);check(!b.valid&&b.bad_index==0);auto e=OffsetRoundtripAuditor::audit({},10);check(e.valid);check(!OffsetRoundtripAuditor::audit({},0).valid);",
        "local!=x.local||q!=x.day", "local!=x.local",
        "exact residue and signed quotient recomputation for offset round trips",
        "the first malformed or mismatched record is reported and empty input passes",
        "day quotient mismatches are ignored",
    ),
    _case(
        "mcn-staged-offset-transition", "StagedOffsetTransition", "Staged offset transition",
        "class StagedOffsetTransition { public: struct Change { long long at; long long new_offset; }; struct Report { bool valid; long long local_phase; long long local_day; int active_change; bool gap_before; bool overlap_before; }; static Report map(long long reference,long long period,long long initial_offset,const std::vector<Change>& changes); };",
        "StagedOffsetTransition::Report StagedOffsetTransition::map(long long ref,long long p,long long off,const std::vector<Change>& xs){if(p<=0)return {false,0,0,-1,false,false};long long last=LLONG_MIN;int active=-1;bool gap=false,overlap=false;for(size_t i=0;i<xs.size();++i){if(xs[i].at<last)return {false,0,0,-1,false,false};if(xs[i].at<=ref){gap=xs[i].new_offset>off;overlap=xs[i].new_offset<off;off=xs[i].new_offset;active=static_cast<int>(i);}last=xs[i].at;}long long oq=off/p,r=off%p;if(r<0){r+=p;--oq;}long long rq=ref/p,base=ref%p;if(base<0){base+=p;--rq;}long long phase=add_mod_nonnegative(base,r,p),q;if(__builtin_add_overflow(oq,rq,&q))return {false,0,0,-1,false,false};if(r&&base>p-1-r&&__builtin_add_overflow(q,1LL,&q))return {false,0,0,-1,false,false};return {true,phase,q,active,gap,overlap};}",
        "StagedOffsetTransition::Report StagedOffsetTransition::map(long long,long long,long long,const std::vector<Change>&){return {false,0,0,-1,false,false};}",
        "auto r=StagedOffsetTransition::map(12,10,1,{{5,3},{15,-2}});check(r.valid&&r.active_change==0&&r.local_phase==5&&r.gap_before&&!r.overlap_before);",
        "auto r=StagedOffsetTransition::map(20,10,1,{{5,3},{15,-2}});check(r.valid&&r.active_change==1&&r.overlap_before);check(!StagedOffsetTransition::map(0,10,0,{{2,1},{1,2}}).valid);",
        "xs[i].at<=ref", "xs[i].at%p<=ref%p",
        "absolute ordered offset-transition selection plus local gap/overlap diagnostics",
        "changes are nondecreasing absolute instants; the last not-after change is active",
        "transitions are selected by normalized phase",
    ),
    _case(
        "mcn-variable-period-segment-map", "VariablePeriodMap", "Variable-period segment map",
        "class VariablePeriodMap { public: struct Segment { long long length; long long period; }; struct Position { int segment; long long cycle; long long phase; }; static std::optional<Position> locate(long long absolute_tick,const std::vector<Segment>& segments); };",
        "std::optional<VariablePeriodMap::Position> VariablePeriodMap::locate(long long x,const std::vector<Segment>& xs){if(x<0)return std::nullopt;long long at=0;for(size_t i=0;i<xs.size();++i){auto s=xs[i];if(s.length<=0||s.period<=0)return std::nullopt;long long end;if(__builtin_add_overflow(at,s.length,&end))return std::nullopt;if(x<end){long long d=x-at;return Position{static_cast<int>(i),d/s.period,d%s.period};}at=end;}return std::nullopt;}",
        "std::optional<VariablePeriodMap::Position> VariablePeriodMap::locate(long long,const std::vector<Segment>&){return std::nullopt;}",
        "auto r=VariablePeriodMap::locate(13,{{10,4},{8,3}});check(r&&r->segment==1&&r->cycle==1&&r->phase==0);",
        "auto r=VariablePeriodMap::locate(17,{{10,4},{8,3}});check(r&&r->cycle==2&&r->phase==1);check(!VariablePeriodMap::locate(18,{{10,4},{8,3}}));check(!VariablePeriodMap::locate(0,{{1,0}}));",
        "d/s.period,d%s.period", "d/xs.front().period,d%xs.front().period",
        "checked prefix location across finite segments with segment-specific periods",
        "partial final cycles are valid but ticks at total length are absent",
        "the first segment period is reused for every segment",
    ),
    _case(
        "mcn-dual-cycle-rendezvous", "DualCycleRendezvous", "Dual-cycle rendezvous",
        "class DualCycleRendezvous { public: struct Solution { bool exists; long long tick; long long repeat; }; static std::optional<Solution> next(long long after,long long phase_a,long long period_a,long long phase_b,long long period_b); };",
        "std::optional<DualCycleRendezvous::Solution> DualCycleRendezvous::next(long long after,long long a,long long m,long long b,long long n){if(m<=0||n<=0||a<0||a>=m||b<0||b>=n)return std::nullopt;long long g=std::gcd(m,n);if(a%g!=b%g)return Solution{false,0,0};long long l;if(__builtin_mul_overflow(m/g,n,&l))return std::nullopt;long long mod=n/g;auto inv=inverse_mod_coprime((m/g)%mod,mod);if(!inv)return std::nullopt;long long rhs=euclidean_mod(b/g-a/g,mod),k=mul_mod_nonnegative(rhs,*inv,mod);long long base=add_mod_nonnegative(mul_mod_nonnegative(m%l,k,l),a,l);if(base<=after){long long gap=after-base,jumps=gap/l;if(jumps==LLONG_MAX)return std::nullopt;++jumps;long long advance;if(__builtin_mul_overflow(jumps,l,&advance)||__builtin_add_overflow(base,advance,&base))return std::nullopt;}return Solution{true,base,l};}",
        "std::optional<DualCycleRendezvous::Solution> DualCycleRendezvous::next(long long,long long,long long,long long,long long){return std::nullopt;}",
        "auto r=DualCycleRendezvous::next(14,2,6,5,9);check(r&&r->exists&&r->tick==32&&r->repeat==18);",
        "auto r=DualCycleRendezvous::next(-1,2,6,5,9);check(r&&r->tick==14);auto n=DualCycleRendezvous::next(0,1,4,2,6);check(n&&!n->exists);auto large=DualCycleRendezvous::next(0,1,1000000007,2,1000000009);check(large&&large->exists);check(!DualCycleRendezvous::next(LLONG_MAX,0,1,0,1));",
        "if(base<=after)", "if(base<after)",
        "compatible dual-cycle congruence followed by strict-after ceiling lift",
        "the result is the first rendezvous strictly greater than after",
        "a rendezvous equal to the lower bound is returned",
    ),
    _case(
        "mcn-reference-window-projector", "ReferenceWindowProjector", "Reference-window projector",
        "class ReferenceWindowProjector { public: struct Arc { long long begin; long long end; }; struct Span { long long begin; long long end; }; static std::optional<std::vector<Span>> project(Arc local_arc,long long offset,long long reference_begin,long long reference_end,long long period); };",
        "std::optional<std::vector<ReferenceWindowProjector::Span>> ReferenceWindowProjector::project(Arc a,long long off,long long lo,long long hi,long long p){if(p<=0||lo>hi||a.begin<0||a.begin>=p||a.end<0||a.end>=p||a.begin==a.end)return std::nullopt;long long start=sub_mod_nonnegative(a.begin,euclidean_mod(off,p),p),len=forward_distance(a.begin,a.end,p),diff;if(__builtin_sub_overflow(lo,start,&diff))return std::nullopt;long long k=diff/p;if(diff%p<0)--k;std::vector<Span> out;for(;;){long long product,b,e;if(__builtin_mul_overflow(k,p,&product)||__builtin_add_overflow(product,start,&b)||__builtin_add_overflow(b,len,&e))return std::nullopt;if(b>=hi)break;long long l=std::max(lo,b),r=std::min(hi,e);if(l<r)out.push_back({l,r});if(__builtin_add_overflow(k,1LL,&k))return std::nullopt;}return out;}",
        "std::optional<std::vector<ReferenceWindowProjector::Span>> ReferenceWindowProjector::project(Arc,long long,long long,long long,long long){return std::nullopt;}",
        "auto r=ReferenceWindowProjector::project({8,2},3,0,25,10);check(r&&r->size()==2&&(*r)[0].begin==5&&(*r)[0].end==9&&(*r)[1].begin==15&&(*r)[1].end==19);",
        "auto z=ReferenceWindowProjector::project({1,3},0,4,4,5);check(z&&z->empty());check(!ReferenceWindowProjector::project({1,1},0,0,5,5));",
        "for(;;)", "for(long long once=0;once<1;++once)",
        "inverse offset projection with repeated periodic occurrence enumeration and clipping",
        "reference window is half-open and a local equal-endpoint arc is invalid ambiguity",
        "only one normalized occurrence is projected",
    ),
    _case(
        "mcn-offset-equivalence-grouper", "OffsetEquivalenceGrouper", "Offset equivalence grouper",
        "class OffsetEquivalenceGrouper { public: struct Source { int id; long long offset; long long period; }; struct Group { long long residue; std::vector<int> ids; }; static std::optional<std::vector<Group>> group(const std::vector<Source>& sources,long long common_period); };",
        "std::optional<std::vector<OffsetEquivalenceGrouper::Group>> OffsetEquivalenceGrouper::group(const std::vector<Source>& xs,long long cp){if(cp<=0)return std::nullopt;std::set<int> ids;std::map<long long,std::vector<int>> groups;for(auto s:xs){if(s.id<=0||!ids.insert(s.id).second||s.period<=0||cp%s.period!=0)return std::nullopt;long long scale=cp/s.period,r=s.offset%s.period;if(r<0)r+=s.period;long long converted;if(__builtin_mul_overflow(r,scale,&converted))return std::nullopt;groups[converted].push_back(s.id);}std::vector<Group> out;for(auto& [r,v]:groups)out.push_back({r,v});return out;}",
        "std::optional<std::vector<OffsetEquivalenceGrouper::Group>> OffsetEquivalenceGrouper::group(const std::vector<Source>&,long long){return std::nullopt;}",
        "auto r=OffsetEquivalenceGrouper::group({{1,1,4},{2,2,8},{3,-1,4}},8);check(r&&r->size()==2&&(*r)[0].residue==2&&(*r)[0].ids==std::vector<int>({1,2}));",
        "check(!OffsetEquivalenceGrouper::group({{1,1,6}},8));check(!OffsetEquivalenceGrouper::group({{1,1,4},{1,2,4}},8));auto e=OffsetEquivalenceGrouper::group({},8);check(e&&e->empty());",
        "groups[converted].push_back", "groups[s.offset].push_back",
        "exact commensurate-period conversion and residue equivalence grouping",
        "source periods must divide the common period and IDs are positive/unique",
        "raw offsets are compared without period conversion",
    ),
    _case(
        "mcn-circular-l1-median", "CircularL1Median", "Circular L1 median",
        "class CircularL1Median { public: struct Result { long long phase; long long cost; }; static std::optional<Result> select(const std::vector<long long>& phases,long long period); };",
        "std::optional<CircularL1Median::Result> CircularL1Median::select(const std::vector<long long>& xs,long long p){if(p<=0||xs.empty())return std::nullopt;std::set<long long> candidates;for(long long x:xs){if(x<0||x>=p)return std::nullopt;candidates.insert(x);}Result best{0,LLONG_MAX};for(long long c:candidates){long long cost=0;for(long long x:xs){long long d=forward_distance(c,x,p);d=std::min(d,p-d);if(__builtin_add_overflow(cost,d,&cost))return std::nullopt;}if(cost<best.cost||(cost==best.cost&&c<best.phase))best={c,cost};}return best;}",
        "std::optional<CircularL1Median::Result> CircularL1Median::select(const std::vector<long long>&,long long){return std::nullopt;}",
        "auto r=CircularL1Median::select({9,0,1},10);check(r&&r->phase==0&&r->cost==2);",
        "auto r=CircularL1Median::select({2,8},10);check(r&&r->phase==2&&r->cost==4);check(!CircularL1Median::select({},10));check(!CircularL1Median::select({10},10));",
        "d=std::min(d,p-d)", "d=x>c?x-c:c-x",
        "candidate circular L1 cost minimization over normalized shortest arcs",
        "the selected phase is an input residue and equal costs choose smallest phase",
        "ordinary linear distance is used",
    ),
    _case(
        "mcn-squared-phase-medoid", "SquaredPhaseMedoid", "Squared phase medoid",
        "class SquaredPhaseMedoid { public: enum class Tie { first, last }; struct Result { int index; long long cost; }; static std::optional<Result> select(const std::vector<long long>& phases,long long period,Tie tie); };",
        "std::optional<SquaredPhaseMedoid::Result> SquaredPhaseMedoid::select(const std::vector<long long>& xs,long long p,Tie tie){if(p<=0||xs.empty())return std::nullopt;Result best{-1,LLONG_MAX};for(size_t i=0;i<xs.size();++i){if(xs[i]<0||xs[i]>=p)return std::nullopt;long long cost=0;for(long long x:xs){long long d=forward_distance(xs[i],x,p);d=std::min(d,p-d);long long sq;if(__builtin_mul_overflow(d,d,&sq)||__builtin_add_overflow(cost,sq,&cost))return std::nullopt;}if(cost<best.cost||(cost==best.cost&&tie==Tie::last))best={static_cast<int>(i),cost};}return best;}",
        "std::optional<SquaredPhaseMedoid::Result> SquaredPhaseMedoid::select(const std::vector<long long>&,long long,Tie){return std::nullopt;}",
        "auto r=SquaredPhaseMedoid::select({9,0,4},10,SquaredPhaseMedoid::Tie::first);check(r&&r->index==1&&r->cost==17);",
        "auto f=SquaredPhaseMedoid::select({0,5},10,SquaredPhaseMedoid::Tie::first);auto l=SquaredPhaseMedoid::select({0,5},10,SquaredPhaseMedoid::Tie::last);check(f&&l&&f->index==0&&l->index==1);check(!SquaredPhaseMedoid::select({},10,SquaredPhaseMedoid::Tie::first));",
        "d=std::min(d,p-d)", "d=x>xs[i]?x-xs[i]:xs[i]-x",
        "input medoid minimization using checked squared shortest-arc distances",
        "ties choose first or last input occurrence explicitly",
        "squared linear rather than circular distances determine the medoid",
    ),
    _case(
        "mcn-modular-mode-selector", "ModularModeSelector", "Modular mode selector",
        "class ModularModeSelector { public: struct Result { long long phase; int count; long long distance; }; static std::optional<Result> select(const std::vector<long long>& phases,long long period,long long anchor); };",
        "std::optional<ModularModeSelector::Result> ModularModeSelector::select(const std::vector<long long>& xs,long long p,long long a){if(p<=0||a<0||a>=p||xs.empty())return std::nullopt;std::map<long long,int> counts;for(long long x:xs)++counts[euclidean_mod(x,p)];Result best{0,-1,0};for(auto [x,c]:counts){long long d=forward_distance(a,x,p);if(c>best.count||(c==best.count&&(d<best.distance||(d==best.distance&&x<best.phase))))best={x,c,d};}return best;}",
        "std::optional<ModularModeSelector::Result> ModularModeSelector::select(const std::vector<long long>&,long long,long long){return std::nullopt;}",
        "auto r=ModularModeSelector::select({8,8,2,2},10,9);check(r&&r->phase==2&&r->count==2&&r->distance==3);",
        "auto r=ModularModeSelector::select({1,4},5,3);check(r&&r->phase==4);auto n=ModularModeSelector::select({-1,4,9},5,0);check(n&&n->phase==4&&n->count==3);check(!ModularModeSelector::select({},5,0));check(!ModularModeSelector::select({1},5,5));",
        "d<best.distance", "x<best.phase",
        "frequency maximization with anchor-clockwise and numeric tertiary ties",
        "sample phases are Euclidean-normalized, the anchor is canonical, and empty samples are invalid",
        "frequency ties ignore the anchor and choose the smallest residue",
    ),
    _case(
        "mcn-shortest-enclosing-arc", "ShortestEnclosingArc", "Shortest enclosing arc",
        "class ShortestEnclosingArc { public: struct Weighted { long long phase; long long weight; }; struct Arc { long long start; long long end; long long length; }; static std::optional<Arc> enclose(std::vector<Weighted> phases,long long period,long long required_weight); };",
        "std::optional<ShortestEnclosingArc::Arc> ShortestEnclosingArc::enclose(std::vector<Weighted> xs,long long p,long long need){if(p<=0||need<=0||xs.empty())return std::nullopt;for(auto x:xs)if(x.phase<0||x.phase>=p||x.weight<=0)return std::nullopt;std::sort(xs.begin(),xs.end(),[](Weighted a,Weighted b){return a.phase<b.phase;});size_t n=xs.size(),j=0;long long sum=0;Arc best{0,0,LLONG_MAX};for(size_t i=0;i<n;++i){while(j<i+n&&sum<need){if(__builtin_add_overflow(sum,xs[j%n].weight,&sum))return std::nullopt;++j;}if(sum>=need){long long start=xs[i].phase,end=xs[(j-1)%n].phase,len=forward_distance(start,end,p);if(len<best.length||(len==best.length&&start<best.start))best={start,end,len};}sum-=xs[i].weight;}if(best.length==LLONG_MAX)return std::nullopt;return best;}",
        "std::optional<ShortestEnclosingArc::Arc> ShortestEnclosingArc::enclose(std::vector<Weighted>,long long,long long){return std::nullopt;}",
        "auto r=ShortestEnclosingArc::enclose({{9,2},{1,2},{5,1}},10,4);check(r&&r->start==9&&r->end==1&&r->length==2);",
        "auto r=ShortestEnclosingArc::enclose({{1,2},{3,2}},10,5);check(!r);check(!ShortestEnclosingArc::enclose({{1,0}},10,1));auto one=ShortestEnclosingArc::enclose({{4,3}},10,2);check(one&&one->length==0);",
        "__builtin_add_overflow(sum,xs[j%n].weight,&sum)", "__builtin_add_overflow(sum,1LL,&sum)",
        "duplicated circular two-pointer sweep for a minimum required-weight arc",
        "weights are positive and infeasible required weight returns nullopt",
        "weights are ignored and every phase counts once",
    ),
    _case(
        "mcn-largest-gap-clusterer", "LargestGapClusterer", "Largest-gap clusterer",
        "class LargestGapClusterer { public: struct Cluster { std::vector<long long> phases; }; static std::optional<std::vector<Cluster>> cluster(std::vector<long long> phases,long long period,int cluster_count); };",
        "std::optional<std::vector<LargestGapClusterer::Cluster>> LargestGapClusterer::cluster(std::vector<long long> xs,long long p,int k){if(p<=0||k<=0||k>static_cast<int>(xs.size()))return std::nullopt;for(long long x:xs)if(x<0||x>=p)return std::nullopt;std::sort(xs.begin(),xs.end());std::vector<std::pair<long long,int>> gaps;for(size_t i=0;i<xs.size();++i){long long gap=i+1<xs.size()?xs[i+1]-xs[i]:p-(xs[i]-xs[0]);gaps.push_back({gap,static_cast<int>(i)});}std::sort(gaps.begin(),gaps.end(),[](auto a,auto b){return a.first!=b.first?a.first>b.first:a.second<b.second;});std::set<int> cuts;for(int i=0;i<k;++i)cuts.insert(gaps[i].second);int start=(*cuts.begin()+1)%static_cast<int>(xs.size());std::vector<Cluster> out(1);for(size_t step=0;step<xs.size();++step){int i=(start+static_cast<int>(step))%static_cast<int>(xs.size());out.back().phases.push_back(xs[i]);if(cuts.count(i)&&step+1<xs.size())out.push_back({});}return out;}",
        "std::optional<std::vector<LargestGapClusterer::Cluster>> LargestGapClusterer::cluster(std::vector<long long>,long long,int){return std::nullopt;}",
        "auto r=LargestGapClusterer::cluster({9,0,1,5,6},10,2);check(r&&r->size()==2&&(*r)[0].phases==std::vector<long long>({5,6})&&(*r)[1].phases==std::vector<long long>({9,0,1}));",
        "auto r=LargestGapClusterer::cluster({1,3,5},6,3);check(r&&r->size()==3);check(!LargestGapClusterer::cluster({},5,1));check(!LargestGapClusterer::cluster({1},5,2));",
        "a.first>b.first", "a.first<b.first",
        "deterministic cuts at the largest circular gaps followed by clockwise cluster emission",
        "cluster count is in [1,n] and equal gaps choose smaller predecessor index",
        "the smallest gaps are cut",
    ),
    _case(
        "mcn-nearest-free-phase", "NearestFreePhase", "Nearest free phase",
        "class NearestFreePhase { public: enum class Tie { counterclockwise, clockwise }; struct Result { bool found; long long phase; long long distance; }; static std::optional<Result> choose(long long request,long long period,const std::vector<long long>& blocked,Tie tie); };",
        "std::optional<NearestFreePhase::Result> NearestFreePhase::choose(long long x,long long p,const std::vector<long long>& bs,Tie tie){if(p<=0||p>1000000||x<0||x>=p)return std::nullopt;std::vector<bool> blocked(static_cast<size_t>(p));long long count=0;for(long long b:bs){long long normalized=euclidean_mod(b,p);if(!blocked[static_cast<size_t>(normalized)]){blocked[static_cast<size_t>(normalized)]=true;++count;}}if(count==p)return Result{false,0,0};for(long long d=0;d<p;++d){long long ccw=sub_mod_nonnegative(x,d,p),cw=add_mod_nonnegative(x,d,p);if(d==0&&!blocked[static_cast<size_t>(x)])return Result{true,x,0};long long first=tie==Tie::counterclockwise?ccw:cw,second=tie==Tie::counterclockwise?cw:ccw;if(!blocked[static_cast<size_t>(first)])return Result{true,first,d};if(!blocked[static_cast<size_t>(second)])return Result{true,second,d};}return Result{false,0,0};}",
        "std::optional<NearestFreePhase::Result> NearestFreePhase::choose(long long,long long,const std::vector<long long>&,Tie){return std::nullopt;}",
        "auto r=NearestFreePhase::choose(0,10,{0,1,9},NearestFreePhase::Tie::counterclockwise);check(r&&r->found&&r->phase==8&&r->distance==2);",
        "auto c=NearestFreePhase::choose(0,5,{0},NearestFreePhase::Tie::clockwise);check(c&&c->phase==1);auto normalized=NearestFreePhase::choose(0,5,{-5,5,1},NearestFreePhase::Tie::counterclockwise);check(normalized&&normalized->phase==4);auto n=NearestFreePhase::choose(0,2,{0,1},NearestFreePhase::Tie::clockwise);check(n&&!n->found);",
        "tie==Tie::counterclockwise?ccw:cw", "cw",
        "symmetric distance expansion with explicit directional tie order",
        "blocked phases are Euclidean-normalized and uniqued, period is at most one million, and a fully blocked cycle returns found=false",
        "search is always clockwise",
    ),
    _case(
        "mcn-minimal-cycle-rotation", "MinimalCycleRotation", "Minimal cycle rotation",
        "class MinimalCycleRotation { public: struct Rotation { int start; std::vector<long long> values; }; static std::optional<Rotation> canonical(const std::vector<long long>& values,long long period); };",
        "std::optional<MinimalCycleRotation::Rotation> MinimalCycleRotation::canonical(const std::vector<long long>& input,long long p){if(p<=0)return std::nullopt;std::vector<long long> s=input;for(long long& x:s){x%=p;if(x<0)x+=p;}int n=static_cast<int>(s.size());if(n==0)return Rotation{0,{}};std::vector<long long> d=s;d.insert(d.end(),s.begin(),s.end());int i=0,j=1,k=0;while(i<n&&j<n&&k<n){if(d[i+k]==d[j+k]){++k;continue;}if(d[i+k]>d[j+k]){i=i+k+1;if(i<=j)i=j+1;}else{j=j+k+1;if(j<=i)j=i+1;}k=0;}int start=std::min(i,j);std::vector<long long> out;for(int q=0;q<n;++q)out.push_back(s[(start+q)%n]);return Rotation{start,out};}",
        "std::optional<MinimalCycleRotation::Rotation> MinimalCycleRotation::canonical(const std::vector<long long>&,long long){return std::nullopt;}",
        "auto r=MinimalCycleRotation::canonical({3,1,2},10);check(r&&r->start==1&&r->values==std::vector<long long>({1,2,3}));",
        "auto r=MinimalCycleRotation::canonical({2,1,2,1},5);check(r&&r->start==1&&r->values==std::vector<long long>({1,2,1,2}));auto e=MinimalCycleRotation::canonical({},5);check(e&&e->start==0);",
        "int start=std::min(i,j)", "std::sort(s.begin(),s.end());int start=0",
        "Booth linear-time lexicographically minimal cyclic rotation after normalization",
        "periodic ties choose the smallest start and empty input has start zero",
        "values are sorted, destroying cyclic adjacency",
    ),
    _case(
        "mcn-rotation-invariant-deltas", "RotationInvariantDeltas", "Rotation-invariant deltas",
        "class RotationInvariantDeltas { public: static std::optional<std::vector<long long>> canonical(const std::vector<long long>& phases,long long period); };",
        "std::optional<std::vector<long long>> RotationInvariantDeltas::canonical(const std::vector<long long>& xs,long long p){if(p<=0)return std::nullopt;for(long long x:xs)if(x<0||x>=p)return std::nullopt;if(xs.empty())return std::vector<long long>{};std::vector<long long> d;for(size_t i=0;i<xs.size();++i)d.push_back(forward_distance(xs[i],xs[(i+1)%xs.size()],p));std::vector<long long> best=d;for(size_t s=1;s<d.size();++s){std::vector<long long> r;for(size_t i=0;i<d.size();++i)r.push_back(d[(s+i)%d.size()]);if(r<best)best=r;}return best;}",
        "std::optional<std::vector<long long>> RotationInvariantDeltas::canonical(const std::vector<long long>&,long long){return std::nullopt;}",
        "auto a=RotationInvariantDeltas::canonical({1,4,8},10);auto b=RotationInvariantDeltas::canonical({8,1,4},10);check(a&&b&&*a==*b&&*a==std::vector<long long>({3,3,4}));",
        "auto one=RotationInvariantDeltas::canonical({5},10);check(one&&*one==std::vector<long long>({0}));auto e=RotationInvariantDeltas::canonical({},10);check(e&&e->empty());check(!RotationInvariantDeltas::canonical({10},10));",
        "d.push_back(forward_distance(xs[i],xs[(i+1)%xs.size()],p))", "d=xs",
        "clockwise difference word followed by lexicographically minimal word rotation",
        "the representation is invariant under rotating the input phase cycle",
        "raw phase values rather than deltas are canonicalized",
    ),
    _case(
        "mcn-dihedral-phase-canonicalizer", "DihedralCanonicalizer", "Dihedral phase canonicalizer",
        "class DihedralCanonicalizer { public: struct Result { bool reflected; int rotation; std::vector<long long> values; }; static std::optional<Result> canonical(const std::vector<long long>& phases,long long period); };",
        "std::optional<DihedralCanonicalizer::Result> DihedralCanonicalizer::canonical(const std::vector<long long>& input,long long p){if(p<=0)return std::nullopt;std::vector<long long> a=input;for(long long& x:a){x%=p;if(x<0)x+=p;}int n=static_cast<int>(a.size());Result best{false,0,a};bool set=false;for(int reflect=0;reflect<2;++reflect){std::vector<long long> base=a;if(reflect)std::reverse(base.begin(),base.end());for(int s=0;s<std::max(1,n);++s){std::vector<long long> v;for(int i=0;i<n;++i)v.push_back(base[(s+i)%n]);if(!set||v<best.values||(v==best.values&&(reflect<static_cast<int>(best.reflected)||(reflect==static_cast<int>(best.reflected)&&s<best.rotation)))){best={reflect!=0,s,v};set=true;}}}return best;}",
        "std::optional<DihedralCanonicalizer::Result> DihedralCanonicalizer::canonical(const std::vector<long long>&,long long){return std::nullopt;}",
        "auto r=DihedralCanonicalizer::canonical({3,2,1},10);check(r&&r->reflected&&r->values==std::vector<long long>({1,2,3}));",
        "auto r=DihedralCanonicalizer::canonical({1,2,1,2},5);check(r&&!r->reflected&&r->rotation==0);auto e=DihedralCanonicalizer::canonical({},5);check(e&&e->values.empty());",
        "for(int reflect=0;reflect<2;++reflect)", "for(int reflect=0;reflect<1;++reflect)",
        "lexicographic comparison across every rotation and reflected reverse rotation",
        "ties prefer nonreflected orientation then smallest rotation",
        "reflected orientations are never considered",
    ),
    _case(
        "mcn-modular-permutation-auditor", "ModularPermutationAuditor", "Modular permutation auditor",
        "class ModularPermutationAuditor { public: struct Report { bool bijective; int cycles; int fixed_points; }; static std::optional<Report> audit(long long multiplier,long long shift,int period); };",
        "std::optional<ModularPermutationAuditor::Report> ModularPermutationAuditor::audit(long long a,long long b,int p){if(p<=0||p>1000000)return std::nullopt;a=euclidean_mod(a,p);b=euclidean_mod(b,p);if(std::gcd(a,static_cast<long long>(p))!=1)return Report{false,0,0};std::vector<bool> seen(static_cast<size_t>(p));int cycles=0,fixed=0;for(int x=0;x<p;++x)if(!seen[static_cast<size_t>(x)]){++cycles;int y=x,length=0;do{seen[static_cast<size_t>(y)]=true;++length;y=static_cast<int>(add_mod_nonnegative(mul_mod_nonnegative(a,y,p),b,p));}while(!seen[static_cast<size_t>(y)]);if(length==1)++fixed;}return Report{true,cycles,fixed};}",
        "std::optional<ModularPermutationAuditor::Report> ModularPermutationAuditor::audit(long long,long long,int){return std::nullopt;}",
        "auto r=ModularPermutationAuditor::audit(3,1,8);check(r&&r->bijective&&r->cycles==2&&r->fixed_points==0);",
        "auto n=ModularPermutationAuditor::audit(2,1,8);check(n&&!n->bijective);auto i=ModularPermutationAuditor::audit(1,0,5);check(i&&i->cycles==5&&i->fixed_points==5);check(!ModularPermutationAuditor::audit(1,0,0));",
        "std::gcd(a,static_cast<long long>(p))!=1", "a==0",
        "gcd bijectivity proof followed by explicit affine-permutation cycle decomposition",
        "period is bounded for deterministic memory and fixed points are one-element cycles",
        "every nonzero multiplier is called bijective",
    ),
)


if len(CASES) != 20:
    raise RuntimeError(f"expected offset/selection tranche of 20, got {len(CASES)}")
