"""Sequence and cyclic-range cases for modular clock normalization."""
from __future__ import annotations

from w8_biayn.integrations.moonlight_modular_clock_normalization_cases import (
    ClockCase,
    _case,
)


CASES: tuple[ClockCase, ...] = (
    _case(
        "mcn-claimed-wrap-validator", "ClaimedWrapValidator", "Claimed wrap validator",
        "class ClaimedWrapValidator { public: struct Reading { long long phase; long long wrap; }; struct Report { bool valid; int bad_index; std::vector<long long> absolute; }; static Report validate(const std::vector<Reading>& readings,long long period); };",
        "ClaimedWrapValidator::Report ClaimedWrapValidator::validate(const std::vector<Reading>& xs,long long p){Report out{p>0,-1,{}};if(p<=0)return out;long long last=LLONG_MIN;for(size_t i=0;i<xs.size();++i){auto x=xs[i];if(x.phase<0||x.phase>=p){out.valid=false;out.bad_index=static_cast<int>(i);return out;}long long base;if(__builtin_mul_overflow(x.wrap,p,&base)||__builtin_add_overflow(base,x.phase,&base)||base<last){out.valid=false;out.bad_index=static_cast<int>(i);return out;}if(i&&x.phase<xs[i-1].phase&&x.wrap<=xs[i-1].wrap){out.valid=false;out.bad_index=static_cast<int>(i);return out;}out.absolute.push_back(base);last=base;}return out;}",
        "ClaimedWrapValidator::Report ClaimedWrapValidator::validate(const std::vector<Reading>&,long long){return {false,-1,{}};}",
        "auto r=ClaimedWrapValidator::validate({{8,0},{1,1},{5,1}},10);check(r.valid&&r.absolute==std::vector<long long>({8,11,15}));",
        "auto b=ClaimedWrapValidator::validate({{8,0},{1,0}},10);check(!b.valid&&b.bad_index==1&&b.absolute.size()==1);auto d=ClaimedWrapValidator::validate({{1,1},{9,0}},10);check(!d.valid&&d.bad_index==1);check(!ClaimedWrapValidator::validate({},0).valid);",
        "base<last", "(i&&base<last-p)",
        "claimed epoch multiplication plus monotone absolute and wrap-drop validation",
        "canonical phases and exact nondecreasing absolute readings are required",
        "a phase drop with an unchanged wrap counter is accepted",
    ),
    _case(
        "mcn-monotone-phase-unwrapper", "MonotonePhaseUnwrapper", "Monotone phase unwrapper",
        "class MonotonePhaseUnwrapper { public: static std::optional<std::vector<long long>> unwrap(const std::vector<long long>& phases,long long period); };",
        "std::optional<std::vector<long long>> MonotonePhaseUnwrapper::unwrap(const std::vector<long long>& xs,long long p){if(p<=0)return std::nullopt;std::vector<long long> out;for(long long x:xs){if(x<0||x>=p)return std::nullopt;if(out.empty()){out.push_back(x);continue;}long long gap=out.back()>x?out.back()-x:0,k=gap/p+(gap%p!=0);long long v;if(__builtin_mul_overflow(k,p,&v)||__builtin_add_overflow(v,x,&v))return std::nullopt;out.push_back(v);}return out;}",
        "std::optional<std::vector<long long>> MonotonePhaseUnwrapper::unwrap(const std::vector<long long>&,long long){return std::nullopt;}",
        "auto r=MonotonePhaseUnwrapper::unwrap({8,1,1,3},10);check(r&&*r==std::vector<long long>({8,11,11,13}));",
        "auto e=MonotonePhaseUnwrapper::unwrap({},7);check(e&&e->empty());check(!MonotonePhaseUnwrapper::unwrap({7},7));auto r=MonotonePhaseUnwrapper::unwrap({0,0},5);check(r&&(*r)[1]==0);",
        "k=gap/p+(gap%p!=0)", "k=gap/p+1",
        "least nondecreasing lift of each canonical phase",
        "equal phases stay equal and only required wraps are added",
        "every non-increasing sample is forced into the next epoch",
    ),
    _case(
        "mcn-bounded-jump-unwrapper", "BoundedJumpUnwrapper", "Bounded-jump unwrapper",
        "class BoundedJumpUnwrapper { public: struct Report { bool valid; int bad_index; std::vector<long long> values; }; static Report unwrap(const std::vector<long long>& phases,long long period,long long max_step); };",
        "BoundedJumpUnwrapper::Report BoundedJumpUnwrapper::unwrap(const std::vector<long long>& xs,long long p,long long bound){Report out{p>0&&bound>=0,-1,{}};if(!out.valid)return out;for(size_t i=0;i<xs.size();++i){if(xs[i]<0||xs[i]>=p){out.valid=false;out.bad_index=static_cast<int>(i);return out;}if(i==0){out.values.push_back(xs[i]);continue;}long long delta=forward_distance(xs[i-1],xs[i],p);if(delta>bound||(bound>=p&&bound-p>=delta)){out.valid=false;out.bad_index=static_cast<int>(i);return out;}long long v;if(__builtin_add_overflow(out.values.back(),delta,&v)){out.valid=false;out.bad_index=static_cast<int>(i);return out;}out.values.push_back(v);}return out;}",
        "BoundedJumpUnwrapper::Report BoundedJumpUnwrapper::unwrap(const std::vector<long long>&,long long,long long){return {false,-1,{}};}",
        "auto r=BoundedJumpUnwrapper::unwrap({8,1,4},10,4);check(r.valid&&r.values==std::vector<long long>({8,11,14}));",
        "auto b=BoundedJumpUnwrapper::unwrap({1,7},10,5);check(!b.valid&&b.bad_index==1);auto a=BoundedJumpUnwrapper::unwrap({1,3},5,7);check(!a.valid&&a.bad_index==1);",
        "delta>bound||(bound>=p&&bound-p>=delta)", "delta>bound",
        "unique forward lift constrained by a maximum step",
        "a step is invalid when absent or when more than one epoch lift fits the bound",
        "ambiguous multi-wrap lifts are silently accepted",
    ),
    _case(
        "mcn-directed-phase-unwrapper", "DirectedPhaseUnwrapper", "Directed phase unwrapper",
        "class DirectedPhaseUnwrapper { public: enum class Direction { forward, backward, stationary }; struct Sample { long long phase; Direction direction; }; static std::optional<std::vector<long long>> unwrap(const std::vector<Sample>& samples,long long period); };",
        "std::optional<std::vector<long long>> DirectedPhaseUnwrapper::unwrap(const std::vector<Sample>& xs,long long p){if(p<=0)return std::nullopt;std::vector<long long> out;for(size_t i=0;i<xs.size();++i){if(xs[i].phase<0||xs[i].phase>=p)return std::nullopt;if(i==0){out.push_back(xs[i].phase);continue;}long long raw=xs[i].phase-xs[i-1].phase,step=0;if(xs[i].direction==Direction::stationary){if(raw!=0)return std::nullopt;}else if(xs[i].direction==Direction::forward){step=raw>0?raw:raw+p;}else step=raw<0?raw:raw-p;long long v;if(__builtin_add_overflow(out.back(),step,&v))return std::nullopt;out.push_back(v);}return out;}",
        "std::optional<std::vector<long long>> DirectedPhaseUnwrapper::unwrap(const std::vector<Sample>&,long long){return std::nullopt;}",
        "using D=DirectedPhaseUnwrapper::Direction;auto r=DirectedPhaseUnwrapper::unwrap({{8,D::forward},{1,D::forward},{7,D::backward}},10);check(r&&*r==std::vector<long long>({8,11,7}));",
        "using D=DirectedPhaseUnwrapper::Direction;check(!DirectedPhaseUnwrapper::unwrap({{1,D::forward},{2,D::stationary}},5));auto r=DirectedPhaseUnwrapper::unwrap({{3,D::forward},{3,D::forward}},5);check(r&&(*r)[1]==8);",
        "else step=raw<0?raw:raw-p", "else step=raw>0?raw:raw+p",
        "direction-qualified least nonzero lifts with explicit stationary edges",
        "forward/backward equal phases move a full period; stationary requires equality",
        "backward hints are executed as forward motion",
    ),
    _case(
        "mcn-nearest-anchor-unwrapper", "NearestAnchorUnwrapper", "Nearest-anchor unwrapper",
        "class NearestAnchorUnwrapper { public: enum class Tie { lower, upper }; static std::optional<std::vector<long long>> place(const std::vector<long long>& phases,const std::vector<long long>& anchors,long long period,Tie tie); };",
        "std::optional<std::vector<long long>> NearestAnchorUnwrapper::place(const std::vector<long long>& xs,const std::vector<long long>& as,long long p,Tie tie){if(p<=0||xs.size()!=as.size())return std::nullopt;std::vector<long long> out;for(size_t i=0;i<xs.size();++i){if(xs[i]<0||xs[i]>=p)return std::nullopt;long long diff;if(__builtin_sub_overflow(as[i],xs[i],&diff))return std::nullopt;long long q=diff/p;if(diff%p<0)--q;long long lo,product;if(__builtin_mul_overflow(q,p,&product)||__builtin_add_overflow(xs[i],product,&lo))return std::nullopt;long long hi;if(__builtin_add_overflow(lo,p,&hi))return std::nullopt;long long dl,dh;if(__builtin_sub_overflow(as[i],lo,&dl)||__builtin_sub_overflow(hi,as[i],&dh))return std::nullopt;out.push_back(dl<dh||(dl==dh&&tie==Tie::lower)?lo:hi);}return out;}",
        "std::optional<std::vector<long long>> NearestAnchorUnwrapper::place(const std::vector<long long>&,const std::vector<long long>&,long long,Tie){return std::nullopt;}",
        "auto r=NearestAnchorUnwrapper::place({2,8},{17,-3},10,NearestAnchorUnwrapper::Tie::lower);check(r&&*r==std::vector<long long>({12,-2}));",
        "auto l=NearestAnchorUnwrapper::place({0},{5},10,NearestAnchorUnwrapper::Tie::lower);auto u=NearestAnchorUnwrapper::place({0},{5},10,NearestAnchorUnwrapper::Tie::upper);check(l&&u&&(*l)[0]==0&&(*u)[0]==10);check(!NearestAnchorUnwrapper::place({1},{},5,NearestAnchorUnwrapper::Tie::lower));",
        "tie==Tie::lower", "tie==Tie::upper",
        "independent nearest absolute representative around each supplied anchor",
        "exact half-period ties obey one global lower/upper policy",
        "all ties are resolved upward",
    ),
    _case(
        "mcn-sensor-phase-aligner", "SensorPhaseAligner", "Sensor phase aligner",
        "class SensorPhaseAligner { public: struct Sensor { long long phase; long long offset; }; struct Aligned { int index; long long phase; }; static std::optional<std::vector<Aligned>> align(const std::vector<Sensor>& sensors,long long period); };",
        "std::optional<std::vector<SensorPhaseAligner::Aligned>> SensorPhaseAligner::align(const std::vector<Sensor>& xs,long long p){if(p<=0)return std::nullopt;std::vector<Aligned> out;for(size_t i=0;i<xs.size();++i){if(xs[i].phase<0||xs[i].phase>=p)return std::nullopt;long long off=euclidean_mod(xs[i].offset,p),x=sub_mod_nonnegative(xs[i].phase,off,p);out.push_back({static_cast<int>(i),x});}std::stable_sort(out.begin(),out.end(),[](Aligned a,Aligned b){return a.phase<b.phase;});return out;}",
        "std::optional<std::vector<SensorPhaseAligner::Aligned>> SensorPhaseAligner::align(const std::vector<Sensor>&,long long){return std::nullopt;}",
        "auto r=SensorPhaseAligner::align({{2,5},{7,-3},{1,1}},10);check(r&&(*r)[0].index==1&&(*r)[1].index==2&&(*r)[2].index==0);",
        "auto r=SensorPhaseAligner::align({{0,10},{0,0}},10);check(r&&(*r)[0].index==0&&(*r)[1].index==1);check(!SensorPhaseAligner::align({{10,0}},10));",
        "sub_mod_nonnegative(xs[i].phase,off,p)", "add_mod_nonnegative(xs[i].phase,off,p)",
        "signed calibration removal and stable ordering in a shared reference phase",
        "sensor phases are canonical; equal aligned phases preserve sensor order",
        "calibration offsets are added rather than removed",
    ),
    _case(
        "mcn-gap-aware-phase-unwrapper", "GapAwareUnwrapper", "Gap-aware phase unwrapper",
        "class GapAwareUnwrapper { public: struct Sample { long long phase; long long missing_before; }; struct Report { bool valid; int bad_index; std::vector<long long> values; }; static Report unwrap(const std::vector<Sample>& samples,long long period,long long max_per_step); };",
        "GapAwareUnwrapper::Report GapAwareUnwrapper::unwrap(const std::vector<Sample>& xs,long long p,long long maxs){Report out{p>0&&maxs>=0,-1,{}};if(!out.valid)return out;for(size_t i=0;i<xs.size();++i){if(xs[i].phase<0||xs[i].phase>=p||xs[i].missing_before<0){out.valid=false;out.bad_index=static_cast<int>(i);return out;}if(i==0){out.values.push_back(xs[i].phase);continue;}long long delta=forward_distance(xs[i-1].phase,xs[i].phase,p),steps,bound;if(__builtin_add_overflow(xs[i].missing_before,1LL,&steps)||__builtin_mul_overflow(steps,maxs,&bound)){out.valid=false;out.bad_index=static_cast<int>(i);return out;}if(delta>bound||(bound>=p&&bound-p>=delta)){out.valid=false;out.bad_index=static_cast<int>(i);return out;}long long value;if(__builtin_add_overflow(out.values.back(),delta,&value)){out.valid=false;out.bad_index=static_cast<int>(i);return out;}out.values.push_back(value);}return out;}",
        "GapAwareUnwrapper::Report GapAwareUnwrapper::unwrap(const std::vector<Sample>&,long long,long long){return {false,-1,{}};}",
        "auto r=GapAwareUnwrapper::unwrap({{8,0},{3,2}},10,2);check(r.valid&&r.values==std::vector<long long>({8,13}));",
        "auto b=GapAwareUnwrapper::unwrap({{8,0},{3,0}},10,2);check(!b.valid&&b.bad_index==1);auto a=GapAwareUnwrapper::unwrap({{1,0},{2,10}},5,1);check(!a.valid);",
        "__builtin_add_overflow(xs[i].missing_before,1LL,&steps)", "__builtin_add_overflow(0LL,1LL,&steps)",
        "unique forward lift bounded by missing-sample-expanded step capacity",
        "missing_before is nonnegative and both absent and ambiguous lifts reject",
        "missing sample multiplicity is ignored",
    ),
    _case(
        "mcn-reset-aware-phase-trace", "ResetAwareTrace", "Reset-aware phase trace",
        "class ResetAwareTrace { public: struct Event { long long phase; bool reset; }; struct Point { long long epoch; long long absolute; }; static std::optional<std::vector<Point>> unwrap(const std::vector<Event>& events,long long period); };",
        "std::optional<std::vector<ResetAwareTrace::Point>> ResetAwareTrace::unwrap(const std::vector<Event>& xs,long long p){if(p<=0)return std::nullopt;std::vector<Point> out;long long epoch=0,base=0,prev=0;for(size_t i=0;i<xs.size();++i){if(xs[i].phase<0||xs[i].phase>=p)return std::nullopt;if(i==0||xs[i].reset){if(i&&__builtin_add_overflow(epoch,1LL,&epoch))return std::nullopt;base=xs[i].phase;}else{long long d=forward_distance(prev,xs[i].phase,p);if(__builtin_add_overflow(base,d,&base))return std::nullopt;}out.push_back({epoch,base});prev=xs[i].phase;}return out;}",
        "std::optional<std::vector<ResetAwareTrace::Point>> ResetAwareTrace::unwrap(const std::vector<Event>&,long long){return std::nullopt;}",
        "auto r=ResetAwareTrace::unwrap({{8,false},{1,false},{7,true},{2,false}},10);check(r&&(*r)[1].absolute==11&&(*r)[2].epoch==1&&(*r)[2].absolute==7&&(*r)[3].absolute==12);",
        "auto r=ResetAwareTrace::unwrap({{8,false},{1,false}},10);check(r&&(*r)[1].epoch==0);auto z=ResetAwareTrace::unwrap({{8,false},{1,true}},10);check(z&&(*z)[1].epoch==1&&(*z)[1].absolute==1);",
        "if(i==0||xs[i].reset)", "if(i==0||xs[i].reset||xs[i].phase<prev)",
        "explicit reset epochs separated from monotone modular unwrapping",
        "only a reset flag starts a new epoch; ordinary phase drops wrap within the epoch",
        "every phase decrease is treated as an implicit reset",
    ),
    _case(
        "mcn-jitter-filtered-unwrapper", "JitterFilteredUnwrapper", "Jitter-filtered unwrapper",
        "class JitterFilteredUnwrapper { public: struct Report { bool valid; int wraps; std::vector<long long> values; }; static Report unwrap(const std::vector<long long>& phases,long long period,long long backward_tolerance); };",
        "JitterFilteredUnwrapper::Report JitterFilteredUnwrapper::unwrap(const std::vector<long long>& xs,long long p,long long tol){Report out{p>0&&tol>=0&&tol<p,0,{}};if(!out.valid)return out;long long epoch=0;for(size_t i=0;i<xs.size();++i){if(xs[i]<0||xs[i]>=p){out.valid=false;return out;}if(i&&xs[i]<xs[i-1]&&xs[i-1]-xs[i]>tol){++out.wraps;if(__builtin_add_overflow(epoch,p,&epoch)){out.valid=false;return out;}}long long v;if(__builtin_add_overflow(epoch,xs[i],&v)){out.valid=false;return out;}out.values.push_back(v);}return out;}",
        "JitterFilteredUnwrapper::Report JitterFilteredUnwrapper::unwrap(const std::vector<long long>&,long long,long long){return {false,0,{}};}",
        "auto r=JitterFilteredUnwrapper::unwrap({8,7,9,1},10,2);check(r.valid&&r.wraps==1&&r.values==std::vector<long long>({8,7,9,11}));",
        "auto r=JitterFilteredUnwrapper::unwrap({5,4,3},10,2);check(r.valid&&r.wraps==0&&r.values.back()==3);check(!JitterFilteredUnwrapper::unwrap({},5,5).valid);",
        "xs[i-1]-xs[i]>tol", "xs[i-1]-xs[i]>0",
        "phase-drop classification into tolerated backward jitter or an epoch wrap",
        "tolerance is in [0,period); small decreases remain in the same epoch",
        "every negative delta creates a wrap",
    ),
    _case(
        "mcn-modular-delta-codec", "ModularDeltaCodec", "Modular delta codec",
        "class ModularDeltaCodec { public: enum class Tie { negative, positive }; static std::optional<std::vector<long long>> encode(const std::vector<long long>& phases,long long period,Tie tie); static std::optional<std::vector<long long>> decode(long long first,const std::vector<long long>& deltas,long long period); };",
        "std::optional<std::vector<long long>> ModularDeltaCodec::encode(const std::vector<long long>& xs,long long p,Tie tie){if(p<=0)return std::nullopt;std::vector<long long> d;for(size_t i=0;i<xs.size();++i){if(xs[i]<0||xs[i]>=p)return std::nullopt;if(i){long long r=forward_distance(xs[i-1],xs[i],p);if(r>p/2||(p%2==0&&r==p/2&&tie==Tie::negative))r-=p;d.push_back(r);}}return d;} std::optional<std::vector<long long>> ModularDeltaCodec::decode(long long first,const std::vector<long long>& ds,long long p){if(p<=0||first<0||first>=p)return std::nullopt;std::vector<long long> out{first};for(long long d:ds){out.push_back(add_mod_nonnegative(out.back(),euclidean_mod(d,p),p));}return out;}",
        "std::optional<std::vector<long long>> ModularDeltaCodec::encode(const std::vector<long long>&,long long,Tie){return std::nullopt;} std::optional<std::vector<long long>> ModularDeltaCodec::decode(long long,const std::vector<long long>&,long long){return std::nullopt;}",
        "auto d=ModularDeltaCodec::encode({8,1,7},10,ModularDeltaCodec::Tie::negative);check(d&&*d==std::vector<long long>({3,-4}));auto r=ModularDeltaCodec::decode(8,*d,10);check(r&&*r==std::vector<long long>({8,1,7}));",
        "auto d=ModularDeltaCodec::encode({0,5},10,ModularDeltaCodec::Tie::negative);check(d&&(*d)[0]==-5);auto p=ModularDeltaCodec::encode({0,5},10,ModularDeltaCodec::Tie::positive);check(p&&(*p)[0]==5);check(!ModularDeltaCodec::decode(10,{},10));",
        "if(r>p/2", "if(r>=p",
        "shortest signed delta encoding with exact modular decode",
        "half-period ties are explicit and decoded phases are always canonical",
        "raw linear differences are retained instead of shortest deltas",
    ),
    _case(
        "mcn-anchored-arc-splitter", "AnchoredArcSplitter", "Anchored arc splitter",
        "class AnchoredArcSplitter { public: struct Arc { long long begin; long long end; }; struct Segment { long long begin; long long end; }; static std::optional<std::vector<Segment>> split(Arc arc,long long anchor,long long period); };",
        "std::optional<std::vector<AnchoredArcSplitter::Segment>> AnchoredArcSplitter::split(Arc a,long long anchor,long long p){if(p<=0||a.begin<0||a.begin>=p||a.end<0||a.end>=p||anchor<0||anchor>=p)return std::nullopt;if(a.begin==a.end)return std::vector<Segment>{};auto rot=[=](long long x){return sub_mod_nonnegative(x,anchor,p);};long long b=rot(a.begin),e=rot(a.end);if(b<e)return std::vector<Segment>{{b,e}};return std::vector<Segment>{{b,p},{0,e}};}",
        "std::optional<std::vector<AnchoredArcSplitter::Segment>> AnchoredArcSplitter::split(Arc,long long,long long){return std::nullopt;}",
        "auto r=AnchoredArcSplitter::split({8,3},5,10);check(r&&r->size()==1&&(*r)[0].begin==3&&(*r)[0].end==8);",
        "auto r=AnchoredArcSplitter::split({3,8},5,10);check(r&&r->size()==2&&(*r)[0].begin==8&&(*r)[1].end==3);auto e=AnchoredArcSplitter::split({2,2},0,5);check(e&&e->empty());",
        "sub_mod_nonnegative(x,anchor,p)", "x",
        "rotation to an arbitrary anchor cut followed by at-most-two half-open pieces",
        "equal endpoints are empty and all values are canonical",
        "arcs are split at numeric zero rather than the supplied anchor",
    ),
    _case(
        "mcn-cyclic-overlap-measurer", "CyclicOverlapMeasurer", "Cyclic overlap measurer",
        "class CyclicOverlapMeasurer { public: struct Arc { long long begin; long long end; }; struct Overlap { long long length; std::vector<Arc> pieces; }; static std::optional<Overlap> measure(Arc left,Arc right,long long period); };",
        "std::optional<CyclicOverlapMeasurer::Overlap> CyclicOverlapMeasurer::measure(Arc a,Arc b,long long p){auto pieces=[p](Arc x){std::vector<Arc> v;if(x.begin==x.end)return v;if(x.begin<x.end)v.push_back(x);else{v.push_back({x.begin,p});v.push_back({0,x.end});}return v;};if(p<=0||a.begin<0||a.begin>=p||a.end<0||a.end>=p||b.begin<0||b.begin>=p||b.end<0||b.end>=p)return std::nullopt;std::vector<Arc> out;long long total=0;for(auto x:pieces(a))for(auto y:pieces(b)){long long l=std::max(x.begin,y.begin),r=std::min(x.end,y.end);if(l<r){out.push_back({l,r});if(__builtin_add_overflow(total,r-l,&total))return std::nullopt;}}std::sort(out.begin(),out.end(),[](Arc x,Arc y){return x.begin<y.begin;});if(out.size()>1&&out.front().begin==0&&out.back().end==p){Arc wrap{out.back().begin,out.front().end};out.erase(out.begin());out.back()=wrap;}return Overlap{total,out};}",
        "std::optional<CyclicOverlapMeasurer::Overlap> CyclicOverlapMeasurer::measure(Arc,Arc,long long){return std::nullopt;}",
        "auto r=CyclicOverlapMeasurer::measure({8,3},{1,9},10);check(r&&r->length==3&&r->pieces.size()==2);",
        "auto z=CyclicOverlapMeasurer::measure({2,2},{0,4},5);check(z&&z->length==0);auto r=CyclicOverlapMeasurer::measure({4,1},{4,1},5);check(r&&r->length==2&&r->pieces.size()==1&&r->pieces[0].begin==4&&r->pieces[0].end==1);",
        "for(auto x:pieces(a))", "for(auto x:std::vector<Arc>{a})",
        "pairwise intersection of linearized cyclic half-open arc pieces followed by boundary coalescing",
        "empty arcs measure zero and pieces connected through period/zero coalesce into one wrapped arc",
        "left wrapped arc is compared as one invalid linear interval",
    ),
    _case(
        "mcn-periodic-cover-coalescer", "PeriodicCoverCoalescer", "Periodic cover coalescer",
        "class PeriodicCoverCoalescer { public: struct Arc { long long begin; long long end; }; struct Cover { bool full; std::vector<Arc> pieces; }; static std::optional<Cover> coalesce(const std::vector<Arc>& arcs,long long period); };",
        "std::optional<PeriodicCoverCoalescer::Cover> PeriodicCoverCoalescer::coalesce(const std::vector<Arc>& xs,long long p){if(p<=0)return std::nullopt;std::vector<std::pair<long long,int>> ev;for(auto a:xs){if(a.begin<0||a.begin>=p||a.end<0||a.end>=p)return std::nullopt;if(a.begin==a.end)continue;if(a.begin<a.end){ev.push_back({a.begin,1});ev.push_back({a.end,-1});}else{ev.push_back({0,1});ev.push_back({a.end,-1});ev.push_back({a.begin,1});ev.push_back({p,-1});}}std::sort(ev.begin(),ev.end());std::vector<Arc> out;int depth=0;long long start=0;for(size_t i=0;i<ev.size();){long long x=ev[i].first,before=depth;while(i<ev.size()&&ev[i].first==x){depth+=ev[i].second;++i;}if(before==0&&depth>0)start=x;if(before>0&&depth==0)out.push_back({start,x});}if(out.size()==1&&out[0].begin==0&&out[0].end==p)return Cover{true,{}};if(out.size()>1&&out.front().begin==0&&out.back().end==p){Arc wrap{out.back().begin,out.front().end};out.erase(out.begin());out.back()=wrap;}return Cover{false,out};}",
        "std::optional<PeriodicCoverCoalescer::Cover> PeriodicCoverCoalescer::coalesce(const std::vector<Arc>&,long long){return std::nullopt;}",
        "auto r=PeriodicCoverCoalescer::coalesce({{8,2},{1,5}},10);check(r&&!r->full&&r->pieces.size()==1&&r->pieces[0].begin==8&&r->pieces[0].end==5);",
        "auto f=PeriodicCoverCoalescer::coalesce({{0,5},{5,0}},10);check(f&&f->full&&f->pieces.empty());auto e=PeriodicCoverCoalescer::coalesce({},10);check(e&&!e->full&&e->pieces.empty());",
        "depth+=ev[i].second", "depth=ev[i].second",
        "coverage-depth event sweep with coalesced half-open pieces",
        "adjacent and overlapping coverage coalesce; an exact full cycle has a dedicated flag",
        "event depth is overwritten rather than accumulated",
    ),
    _case(
        "mcn-circular-gap-complement", "CircularGapComplement", "Circular gap complement",
        "class CircularGapComplement { public: struct Arc { long long begin; long long end; }; static std::optional<std::vector<Arc>> gaps(const std::vector<Arc>& covered,long long period); };",
        "std::optional<std::vector<CircularGapComplement::Arc>> CircularGapComplement::gaps(const std::vector<Arc>& xs,long long p){if(p<=0)return std::nullopt;std::vector<std::pair<long long,long long>> seg;for(auto a:xs){if(a.begin<0||a.begin>=p||a.end<0||a.end>=p)return std::nullopt;if(a.begin==a.end)continue;if(a.begin<a.end)seg.push_back({a.begin,a.end});else{seg.push_back({a.begin,p});seg.push_back({0,a.end});}}std::sort(seg.begin(),seg.end());std::vector<std::pair<long long,long long>> merged;for(auto s:seg){if(merged.empty()||s.first>merged.back().second)merged.push_back(s);else merged.back().second=std::max(merged.back().second,s.second);}std::vector<Arc> out;long long at=0;for(auto s:merged){if(at<s.first)out.push_back({at,s.first});at=std::max(at,s.second);}if(at<p)out.push_back({at,p});if(out.size()>1&&out.front().begin==0&&out.back().end==p){Arc wrap{out.back().begin,out.front().end};out.erase(out.begin());out.back()=wrap;}return out;}",
        "std::optional<std::vector<CircularGapComplement::Arc>> CircularGapComplement::gaps(const std::vector<Arc>&,long long){return std::nullopt;}",
        "auto r=CircularGapComplement::gaps({{8,2},{4,6}},10);check(r&&r->size()==2);",
        "auto all=CircularGapComplement::gaps({{0,5},{5,0}},10);check(all&&all->empty());auto empty=CircularGapComplement::gaps({},7);check(empty&&empty->size()==1&&(*empty)[0].begin==0&&(*empty)[0].end==7);",
        "if(at<s.first)out.push_back({at,s.first});", "if(at<s.first)at=s.first;",
        "coalesced coverage complement with boundary gap rejoining",
        "empty coverage yields [0,period), full coverage yields no gaps",
        "uncovered spans advance the cursor but are never emitted",
    ),
    _case(
        "mcn-minimum-covering-arc", "MinimumCoveringArc", "Minimum covering arc",
        "class MinimumCoveringArc { public: struct Arc { long long start; long long end; long long length; }; static std::optional<Arc> cover(std::vector<long long> phases,long long period); };",
        "std::optional<MinimumCoveringArc::Arc> MinimumCoveringArc::cover(std::vector<long long> xs,long long p){if(p<=0)return std::nullopt;for(long long x:xs)if(x<0||x>=p)return std::nullopt;if(xs.empty())return Arc{0,0,0};std::sort(xs.begin(),xs.end());xs.erase(std::unique(xs.begin(),xs.end()),xs.end());long long best=-1,start=0,end=0;for(size_t i=0;i<xs.size();++i){long long candidate=i+1<xs.size()?xs[i+1]:xs[0];long long gap=i+1<xs.size()?xs[i+1]-xs[i]:p-(xs[i]-xs[0]);if(gap>best||(gap==best&&candidate<start)){best=gap;start=candidate;end=xs[i];}}return Arc{start,end,p-best};}",
        "std::optional<MinimumCoveringArc::Arc> MinimumCoveringArc::cover(std::vector<long long>,long long){return std::nullopt;}",
        "auto r=MinimumCoveringArc::cover({9,1,2},10);check(r&&r->start==9&&r->end==2&&r->length==3);",
        "auto z=MinimumCoveringArc::cover({},8);check(z&&z->length==0);auto one=MinimumCoveringArc::cover({4,4},8);check(one&&one->length==0&&one->start==4);check(!MinimumCoveringArc::cover({8},8));",
        "gap>best", "gap<best",
        "largest circular-gap removal for a minimum clockwise covering arc",
        "duplicates collapse and equal largest gaps choose the smallest resulting start",
        "the smallest rather than largest gap is removed",
    ),
    _case(
        "mcn-boundary-aware-window", "BoundaryAwareWindow", "Boundary-aware window",
        "class BoundaryAwareWindow { public: enum class Location { outside, start, inside, end }; struct Window { long long begin; long long end; bool include_begin; bool include_end; }; static std::optional<Location> classify(long long phase,Window window,long long period); };",
        "std::optional<BoundaryAwareWindow::Location> BoundaryAwareWindow::classify(long long x,Window w,long long p){if(p<=0||x<0||x>=p||w.begin<0||w.begin>=p||w.end<0||w.end>=p)return std::nullopt;if(x==w.begin)return w.include_begin?Location::start:Location::outside;if(x==w.end)return w.include_end?Location::end:Location::outside;if(w.begin==w.end)return Location::outside;bool in=w.begin<w.end?(x>w.begin&&x<w.end):(x>w.begin||x<w.end);return in?Location::inside:Location::outside;}",
        "std::optional<BoundaryAwareWindow::Location> BoundaryAwareWindow::classify(long long,Window,long long){return std::nullopt;}",
        "using L=BoundaryAwareWindow::Location;check(BoundaryAwareWindow::classify(9,{8,2,true,false},10)==L::inside);check(BoundaryAwareWindow::classify(2,{8,2,true,false},10)==L::outside);",
        "using L=BoundaryAwareWindow::Location;check(BoundaryAwareWindow::classify(8,{8,2,false,true},10)==L::outside);check(BoundaryAwareWindow::classify(2,{8,2,false,true},10)==L::end);check(BoundaryAwareWindow::classify(3,{3,3,true,true},5)==L::start);",
        "return w.include_end?Location::end:Location::outside", "return Location::end",
        "independent endpoint inclusion and wrapped interior classification",
        "equal endpoints contain only an explicitly included shared endpoint",
        "the ending endpoint is always included",
    ),
    _case(
        "mcn-anchor-relative-clipper", "AnchorRelativeClipper", "Anchor-relative clipper",
        "class AnchorRelativeClipper { public: struct Arc { long long begin; long long end; }; struct LinearSpan { long long begin; long long end; }; static std::optional<std::vector<LinearSpan>> clip(const std::vector<Arc>& arcs,long long anchor,long long horizon,long long period); };",
        "std::optional<std::vector<AnchorRelativeClipper::LinearSpan>> AnchorRelativeClipper::clip(const std::vector<Arc>& xs,long long anchor,long long horizon,long long p){if(p<=0||horizon<0)return std::nullopt;long long finish;if(__builtin_add_overflow(anchor,horizon,&finish))return std::nullopt;std::vector<LinearSpan> out;for(auto a:xs){if(a.begin<0||a.begin>=p||a.end<0||a.end>=p)return std::nullopt;long long len=forward_distance(a.begin,a.end,p);if(len==0)continue;long long diff;if(__builtin_sub_overflow(anchor,a.begin,&diff))return std::nullopt;long long k=diff/p;if(diff%p<0)--k;for(;;){long long product,b,e;if(__builtin_mul_overflow(k,p,&product)||__builtin_add_overflow(a.begin,product,&b)||__builtin_add_overflow(b,len,&e))return std::nullopt;if(b>=finish)break;long long l=std::max(b,anchor),r=std::min(e,finish);if(l<r)out.push_back({l,r});if(__builtin_add_overflow(k,1LL,&k))return std::nullopt;}}std::sort(out.begin(),out.end(),[](LinearSpan a,LinearSpan b){return a.begin<b.begin;});return out;}",
        "std::optional<std::vector<AnchorRelativeClipper::LinearSpan>> AnchorRelativeClipper::clip(const std::vector<Arc>&,long long,long long,long long){return std::nullopt;}",
        "auto r=AnchorRelativeClipper::clip({{8,2}},9,15,10);check(r&&r->size()==2&&(*r)[0].begin==9&&(*r)[0].end==12&&(*r)[1].begin==18);",
        "auto z=AnchorRelativeClipper::clip({{1,1}},0,20,5);check(z&&z->empty());auto r=AnchorRelativeClipper::clip({{1,3}},10,0,5);check(r&&r->empty());",
        "for(;;)", "for(long long once=0;once<1;++once)",
        "enumeration and clipping of every periodic arc occurrence in a finite absolute window",
        "horizon is nonnegative and equal arc endpoints are empty",
        "only one occurrence near the anchor is examined",
    ),
    _case(
        "mcn-shifted-reservation-normalizer", "ReservationNormalizer", "Shifted reservation normalizer",
        "class ReservationNormalizer { public: struct Arc { long long begin; long long end; }; struct Reservation { int id; Arc arc; }; static std::optional<std::vector<Reservation>> shift(const std::vector<Reservation>& reservations,long long offset,long long period); };",
        "std::optional<std::vector<ReservationNormalizer::Reservation>> ReservationNormalizer::shift(const std::vector<Reservation>& xs,long long off,long long p){if(p<=0)return std::nullopt;std::set<int> ids;std::vector<Reservation> out;off=euclidean_mod(off,p);for(auto r:xs){if(r.id<=0||!ids.insert(r.id).second||r.arc.begin<0||r.arc.begin>=p||r.arc.end<0||r.arc.end>=p||r.arc.begin==r.arc.end)return std::nullopt;long long b=add_mod_nonnegative(r.arc.begin,off,p),e=add_mod_nonnegative(r.arc.end,off,p);out.push_back({r.id,{b,e}});}return out;}",
        "std::optional<std::vector<ReservationNormalizer::Reservation>> ReservationNormalizer::shift(const std::vector<Reservation>&,long long,long long){return std::nullopt;}",
        "auto r=ReservationNormalizer::shift({{2,{8,1}},{1,{2,4}}},3,10);check(r&&(*r)[0].id==2&&(*r)[0].arc.begin==1&&(*r)[0].arc.end==4&&(*r)[1].id==1);",
        "check(!ReservationNormalizer::shift({{1,{0,0}}},1,5));check(!ReservationNormalizer::shift({{1,{0,1}},{1,{2,3}}},1,5));auto r=ReservationNormalizer::shift({{1,{1,2}}},-3,5);check(r&&(*r)[0].arc.begin==3);",
        "e=add_mod_nonnegative(r.arc.end,off,p)", "e=r.arc.end",
        "stable-ID cyclic translation of both reservation endpoints",
        "IDs are positive/unique and equal endpoints are rejected as full-cycle ambiguity",
        "only reservation starts are shifted",
    ),
    _case(
        "mcn-circular-bin-rebalancer", "CircularBinRebalancer", "Circular bin rebalancer",
        "class CircularBinRebalancer { public: struct Fraction { long long numerator; long long denominator; }; static std::optional<std::vector<Fraction>> rebin(const std::vector<long long>& values,int source_bins,int target_bins); };",
        "std::optional<std::vector<CircularBinRebalancer::Fraction>> CircularBinRebalancer::rebin(const std::vector<long long>& v,int s,int t){if(s<=0||t<=0||static_cast<int>(v.size())!=s)return std::nullopt;std::vector<long long> num(static_cast<size_t>(t));long long den=t;for(int i=0;i<s;++i){if(v[i]<0)return std::nullopt;for(int j=0;j<t;++j){long long l=std::max<long long>(static_cast<long long>(i)*t,static_cast<long long>(j)*s),r=std::min<long long>(static_cast<long long>(i+1)*t,static_cast<long long>(j+1)*s);if(l<r){long long add;if(__builtin_mul_overflow(v[i],r-l,&add)||__builtin_add_overflow(num[j],add,&num[j]))return std::nullopt;}}}std::vector<Fraction> out;for(long long n:num){long long g=std::gcd(n,den);out.push_back({n/g,den/g});}return out;}",
        "std::optional<std::vector<CircularBinRebalancer::Fraction>> CircularBinRebalancer::rebin(const std::vector<long long>&,int,int){return std::nullopt;}",
        "auto r=CircularBinRebalancer::rebin({6,0},2,3);check(r&&r->size()==3&&(*r)[0].numerator==4&&(*r)[1].numerator==2&&(*r)[2].numerator==0);",
        "auto r=CircularBinRebalancer::rebin({3,3,3},3,1);check(r&&(*r)[0].numerator==9);check(!CircularBinRebalancer::rebin({1},2,2));check(!CircularBinRebalancer::rebin({-1},1,1));",
        "__builtin_add_overflow(num[j],add,&num[j])", "__builtin_add_overflow(num[(i*t)/s],v[i],&num[(i*t)/s])",
        "exact rational overlap redistribution between two cyclic uniform partitions",
        "source values are nonnegative and every output fraction is reduced",
        "each source bin is assigned wholly to one target bin",
    ),
    _case(
        "mcn-cyclic-range-subtractor", "CyclicRangeSubtractor", "Cyclic range subtractor",
        "class CyclicRangeSubtractor { public: struct Arc { long long begin; long long end; }; static std::optional<std::vector<Arc>> subtract(Arc source,const std::vector<Arc>& cuts,long long period); };",
        "std::optional<std::vector<CyclicRangeSubtractor::Arc>> CyclicRangeSubtractor::subtract(Arc src,const std::vector<Arc>& cuts,long long p){if(p<=0||src.begin<0||src.begin>=p||src.end<0||src.end>=p||src.begin==src.end)return std::nullopt;auto linear=[p](Arc a){std::vector<std::pair<long long,long long>> v;if(a.begin<a.end)v.push_back({a.begin,a.end});else{v.push_back({a.begin,p});v.push_back({0,a.end});}return v;};std::vector<std::pair<long long,long long>> remain=linear(src);for(auto c:cuts){if(c.begin<0||c.begin>=p||c.end<0||c.end>=p)return std::nullopt;for(auto cut:linear(c)){std::vector<std::pair<long long,long long>> next;for(auto s:remain){if(cut.second<=s.first||cut.first>=s.second)next.push_back(s);else{if(s.first<cut.first)next.push_back({s.first,cut.first});if(cut.second<s.second)next.push_back({cut.second,s.second});}}remain=next;}}std::vector<Arc> out;for(auto s:remain)out.push_back({s.first,s.second==p?0:s.second});std::stable_sort(out.begin(),out.end(),[=](Arc a,Arc b){return forward_distance(src.begin,a.begin,p)<forward_distance(src.begin,b.begin,p);});return out;}",
        "std::optional<std::vector<CyclicRangeSubtractor::Arc>> CyclicRangeSubtractor::subtract(Arc,const std::vector<Arc>&,long long){return std::nullopt;}",
        "auto r=CyclicRangeSubtractor::subtract({8,4},{{9,1}},10);check(r&&r->size()==2&&(*r)[0].begin==8&&(*r)[0].end==9&&(*r)[1].begin==1&&(*r)[1].end==4);",
        "auto r=CyclicRangeSubtractor::subtract({1,6},{{2,3},{4,5}},10);check(r&&r->size()==3);auto z=CyclicRangeSubtractor::subtract({1,2},{{0,3}},5);check(z&&z->empty());check(!CyclicRangeSubtractor::subtract({1,1},{},5));",
        "if(s.first<cut.first)next.push_back({s.first,cut.first});", "if(s.first<cut.first||cut.second<s.second)continue;",
        "iterated linear-piece subtraction with clockwise source-relative output order",
        "source is nonempty; cuts may wrap and overlapping cuts are idempotent",
        "any partial overlap discards the whole remaining fragment",
    ),
)


if len(CASES) != 20:
    raise RuntimeError(f"expected sequence/range tranche of 20, got {len(CASES)}")
