"""Structural-summary and scan roots for DPR expansion v2."""

from __future__ import annotations

from w8_biayn.integrations.moonlight_dpr_v2_cases import DprCase, _case


CASES: tuple[DprCase, ...] = (
    _case(
        "dpr-dfa-transform-compose", "DfaTransformCompose", "DFA transform compose", "structural",
        "class DfaTransformCompose { public: static std::optional<int> run(const std::vector<std::vector<int>>& transition,int start,const std::vector<std::vector<int>>& symbol_shards); };",
        "std::optional<int> DfaTransformCompose::run(const std::vector<std::vector<int>>& t,int start,const std::vector<std::vector<int>>& shards){if(t.empty()||start<0||static_cast<std::size_t>(start)>=t.size())return std::nullopt;std::size_t alphabet=t[0].size();if(alphabet==0)return std::nullopt;for(const auto&row:t){if(row.size()!=alphabet)return std::nullopt;for(int x:row)if(x<0||static_cast<std::size_t>(x)>=t.size())return std::nullopt;}std::vector<std::vector<int>> transforms;for(const auto&s:shards){std::vector<int> f(t.size());std::iota(f.begin(),f.end(),0);for(int symbol:s){if(symbol<0||static_cast<std::size_t>(symbol)>=alphabet)return std::nullopt;for(int&state:f)state=t[static_cast<std::size_t>(state)][static_cast<std::size_t>(symbol)];}transforms.push_back(f);}int state=start;for(const auto&f:transforms)state=f[static_cast<std::size_t>(state)];return state;}",
        "std::optional<int> DfaTransformCompose::run(const std::vector<std::vector<int>>&,int,const std::vector<std::vector<int>>&){return std::nullopt;}",
        "std::vector<std::vector<int>> t{{0,1},{2,1},{2,0}};auto s=DfaTransformCompose::run(t,0,{{1,1},{0}});check(s&&*s==2);",
        "check(!DfaTransformCompose::run({},0,{}));check(!DfaTransformCompose::run({{0,2}},0,{}));check(!DfaTransformCompose::run({{0}},0,{{1}}));auto s=DfaTransformCompose::run({{0}},0,{});check(s&&*s==0);",
        "state=f[static_cast<std::size_t>(state)]", "state=f[static_cast<std::size_t>(start)]",
        "per-shard full DFA state transformation composition", "table dimensions and every transition/symbol are validated", "every shard transformation is applied to the original start state",
    ),
    _case(
        "dpr-exclusive-block-scan", "ExclusiveBlockScan", "Exclusive block scan", "structural",
        "class ExclusiveBlockScan { public: static std::optional<std::vector<long long>> scan(const std::vector<std::vector<long long>>& blocks,long long initial); };",
        "std::optional<std::vector<long long>> ExclusiveBlockScan::scan(const std::vector<std::vector<long long>>& blocks,long long initial){std::vector<long long> out;long long carry=initial;for(const auto&b:blocks)for(long long v:b){out.push_back(carry);long long next=0;if(__builtin_add_overflow(carry,v,&next))return std::nullopt;carry=next;}return out;}",
        "std::optional<std::vector<long long>> ExclusiveBlockScan::scan(const std::vector<std::vector<long long>>&,long long){return std::nullopt;}",
        "auto s=ExclusiveBlockScan::scan({{2,3},{4,-1}},10);check(s&&*s==std::vector<long long>({10,12,15,19}));",
        "check(!ExclusiveBlockScan::scan({{1}},LLONG_MAX));auto s=ExclusiveBlockScan::scan({{}, {2}},5);check(s&&*s==std::vector<long long>({5}));auto e=ExclusiveBlockScan::scan({},7);check(e&&e->empty());auto q=ExclusiveBlockScan::scan({{LLONG_MAX,1}},-1);check(q&&*q==std::vector<long long>({-1,LLONG_MAX-1}));",
        "carry=next;", "carry=v;",
        "source-ordered checked exclusive state across declared blocks", "empty blocks preserve position and overflow returns no partial output", "each value replaces rather than advances the incoming carry",
    ),
    _case(
        "dpr-segmented-inclusive-scan", "SegmentedInclusiveScan", "Segmented inclusive scan", "structural",
        "class SegmentedInclusiveScan { public: struct Entry{long long value;bool starts;}; static std::optional<std::vector<long long>> scan(const std::vector<std::vector<Entry>>& blocks); };",
        "std::optional<std::vector<long long>> SegmentedInclusiveScan::scan(const std::vector<std::vector<Entry>>& blocks){std::vector<long long> out;long long carry=0;bool first=true;for(const auto&b:blocks)for(auto e:b){if(first&&!e.starts)return std::nullopt;if(e.starts)carry=0;long long next=0;if(__builtin_add_overflow(carry,e.value,&next))return std::nullopt;carry=next;out.push_back(carry);first=false;}return out;}",
        "std::optional<std::vector<long long>> SegmentedInclusiveScan::scan(const std::vector<std::vector<Entry>>&){return std::nullopt;}",
        "using E=SegmentedInclusiveScan::Entry;auto s=SegmentedInclusiveScan::scan({{{2,true},{3,false}},{{4,false},{1,true},{5,false}}});check(s&&*s==std::vector<long long>({2,5,9,1,6}));",
        "using E=SegmentedInclusiveScan::Entry;check(!SegmentedInclusiveScan::scan({{{1,false}}}));auto s=SegmentedInclusiveScan::scan({{},{{1,true}},{{2,false}}});check(s&&*s==std::vector<long long>({1,3}));check(!SegmentedInclusiveScan::scan({{{LLONG_MAX,true},{1,false}}}));auto q=SegmentedInclusiveScan::scan({{{-1,true}},{{LLONG_MAX,false},{1,false}}});check(q&&*q==std::vector<long long>({-1,LLONG_MAX-1,LLONG_MAX}));",
        "if(e.starts)carry=0", "if(false&&e.starts)carry=0",
        "source-ordered segmented state with reset-aware checked carry", "the first global entry starts a segment and resets stop incoming carry", "segment starts fail to reset the incoming carry",
    ),
    _case(
        "dpr-earliest-constraint-failure", "EarliestConstraintFailure", "Earliest constraint failure", "structural",
        "class EarliestConstraintFailure { public: struct Check{std::size_t index;int code;bool passed;}; struct Report{bool valid,passed;std::size_t index;int code;}; static Report reduce(const std::vector<std::vector<Check>>& shards); };",
        "EarliestConstraintFailure::Report EarliestConstraintFailure::reduce(const std::vector<std::vector<Check>>& shards){std::map<std::size_t,Check> ordered;for(const auto&s:shards)for(auto c:s)if(!ordered.emplace(c.index,c).second)return {false,false,0,0};for(std::size_t i=0;i<ordered.size();++i)if(!ordered.count(i))return {false,false,0,0};for(const auto&x:ordered)if(!x.second.passed)return {true,false,x.first,x.second.code};return {true,true,ordered.size(),0};}",
        "EarliestConstraintFailure::Report EarliestConstraintFailure::reduce(const std::vector<std::vector<Check>>&){return {false,false,0,0};}",
        "using C=EarliestConstraintFailure::Check;auto r=EarliestConstraintFailure::reduce({{{2,9,false}},{{0,0,true},{1,4,false}}});check(r.valid&&!r.passed&&r.index==1&&r.code==4);",
        "using C=EarliestConstraintFailure::Check;auto d=EarliestConstraintFailure::reduce({{{0,1,true}},{{0,2,false}}});check(!d.valid);auto g=EarliestConstraintFailure::reduce({{{1,1,true}}});check(!g.valid);auto e=EarliestConstraintFailure::reduce({});check(e.valid&&e.passed&&e.index==0);",
        "if(!x.second.passed)return", "if(!x.second.passed&&x.second.code<0)return",
        "index-canonical validation and earliest failing constraint", "indices must be unique and contiguous independent of shard order", "positive-code failures are silently treated as passes",
    ),
    _case(
        "dpr-stable-topk-summary", "StableTopKSummary", "Stable top-K summary", "structural",
        "class StableTopKSummary { public: struct Item{int id;long long score;std::size_t index;bool operator==(const Item&o)const{return std::tie(id,score,index)==std::tie(o.id,o.score,o.index);}}; static std::optional<std::vector<Item>> reduce(const std::vector<std::vector<Item>>& shards,std::size_t k); };",
        "std::optional<std::vector<StableTopKSummary::Item>> StableTopKSummary::reduce(const std::vector<std::vector<Item>>& shards,std::size_t k){auto less=[](const Item&a,const Item&b){return std::tie(a.score,b.index,b.id)>std::tie(b.score,a.index,a.id);};std::set<int> ids;std::vector<std::vector<Item>> partials;for(auto s:shards){for(const auto&x:s)if(!ids.insert(x.id).second)return std::nullopt;std::sort(s.begin(),s.end(),less);if(s.size()>k)s.resize(k);partials.push_back(s);}std::vector<Item> out;for(const auto&p:partials){std::vector<Item> merged;std::merge(out.begin(),out.end(),p.begin(),p.end(),std::back_inserter(merged),less);if(merged.size()>k)merged.resize(k);out=merged;}return out;}",
        "std::optional<std::vector<StableTopKSummary::Item>> StableTopKSummary::reduce(const std::vector<std::vector<Item>>&,std::size_t){return std::nullopt;}",
        "using I=StableTopKSummary::Item;auto r=StableTopKSummary::reduce({{{1,5,2},{2,9,1}},{{3,9,0},{4,7,3}}},3);check(r&&*r==std::vector<I>({{3,9,0},{2,9,1},{4,7,3}}));",
        "using I=StableTopKSummary::Item;check(!StableTopKSummary::reduce({{{1,2,0}},{{1,3,1}}},2));auto z=StableTopKSummary::reduce({{{1,2,0}}},0);check(z&&z->empty());auto r=StableTopKSummary::reduce({{},{{2,1,4}}},2);check(r&&r->size()==1);",
        "if(merged.size()>k)merged.resize(k);", "if(out.empty()&&merged.size()>k)merged.resize(k);",
        "bounded per-shard top-K states with stable ordered merge", "duplicate identities reject and zero K returns empty", "later merges are allowed to exceed the global K bound",
    ),
    _case(
        "dpr-majority-summary-verify", "MajoritySummaryVerify", "Majority summary verify", "structural",
        "class MajoritySummaryVerify { public: static std::optional<long long> majority(const std::vector<std::vector<long long>>& shards); };",
        "std::optional<long long> MajoritySummaryVerify::majority(const std::vector<std::vector<long long>>& shards){struct State{long long candidate;std::size_t residual;};std::vector<State> partials;std::size_t total=0;for(const auto&s:shards){State p{0,0};for(long long v:s){if(p.residual==0){p={v,1};}else if(v==p.candidate)++p.residual;else --p.residual;}partials.push_back(p);total+=s.size();}State merged{0,0};for(auto p:partials){if(merged.residual==0)merged=p;else if(p.residual==0)continue;else if(merged.candidate==p.candidate)merged.residual+=p.residual;else if(merged.residual>=p.residual)merged.residual-=p.residual;else{merged.candidate=p.candidate;merged.residual=p.residual-merged.residual;}}if(total==0||merged.residual==0)return std::nullopt;std::size_t count=0;for(const auto&s:shards)count+=static_cast<std::size_t>(std::count(s.begin(),s.end(),merged.candidate));return count>total/2?std::optional<long long>(merged.candidate):std::nullopt;}",
        "std::optional<long long> MajoritySummaryVerify::majority(const std::vector<std::vector<long long>>&){return std::nullopt;}",
        "auto m=MajoritySummaryVerify::majority({{2,1,2},{3,2,2}});check(m&&*m==2);",
        "check(!MajoritySummaryVerify::majority({}));check(!MajoritySummaryVerify::majority({{1,2},{1,2}}));auto m=MajoritySummaryVerify::majority({{}, {7,7,8}});check(m&&*m==7);",
        "return count>total/2?", "return merged.residual>0?",
        "Boyer-Moore partial cancellation followed by exact verification", "candidate state alone never proves strict majority", "combined residual candidate is accepted without verification",
    ),
    _case(
        "dpr-cross-shard-inversion-count", "CrossShardInversions", "Cross-shard inversion count", "structural",
        "class CrossShardInversions { public: struct Result{unsigned long long inversions;std::vector<long long> sorted;}; static std::optional<Result> count(const std::vector<std::vector<long long>>& shards); };",
        "std::optional<CrossShardInversions::Result> CrossShardInversions::count(const std::vector<std::vector<long long>>& shards){auto merge=[](Result a,Result b)->std::optional<Result>{Result out{a.inversions+b.inversions,{}};if(out.inversions<a.inversions)return std::nullopt;std::size_t i=0,j=0;while(i<a.sorted.size()||j<b.sorted.size()){if(j==b.sorted.size()||(i<a.sorted.size()&&a.sorted[i]<=b.sorted[j]))out.sorted.push_back(a.sorted[i++]);else{unsigned long long add=a.sorted.size()-i;if(out.inversions>ULLONG_MAX-add)return std::nullopt;out.inversions+=add;out.sorted.push_back(b.sorted[j++]);}}return out;};std::vector<Result> parts;for(const auto&s:shards){Result p{0,s};for(std::size_t i=0;i<s.size();++i)for(std::size_t j=i+1;j<s.size();++j)if(s[i]>s[j])++p.inversions;std::sort(p.sorted.begin(),p.sorted.end());parts.push_back(p);}while(parts.size()>1){std::vector<Result> next;for(std::size_t i=0;i<parts.size();i+=2){if(i+1==parts.size())next.push_back(parts[i]);else{auto m=merge(parts[i],parts[i+1]);if(!m)return std::nullopt;next.push_back(*m);}}parts=next;}return parts.empty()?Result{0,{}}:parts[0];}",
        "std::optional<CrossShardInversions::Result> CrossShardInversions::count(const std::vector<std::vector<long long>>&){return std::nullopt;}",
        "auto r=CrossShardInversions::count({{3,1},{2,0}});check(r&&r->inversions==5&&r->sorted==std::vector<long long>({0,1,2,3}));",
        "auto e=CrossShardInversions::count({});check(e&&e->inversions==0&&e->sorted.empty());auto r=CrossShardInversions::count({{1,1},{1}});check(r&&r->inversions==0);auto q=CrossShardInversions::count({{}, {2,1}});check(q&&q->inversions==1);",
        "out.inversions+=add;", "/* omit cross inversions */",
        "sorted partial merge with cross-inversion accounting", "equal values are not inversions and count overflow rejects", "only within-shard inversions are counted",
    ),
    _case(
        "dpr-pareto-frontier-merge", "ParetoFrontierMerge", "Pareto frontier merge", "structural",
        "class ParetoFrontierMerge { public: struct Point{int id;long long x,y;bool operator==(const Point&o)const{return std::tie(id,x,y)==std::tie(o.id,o.x,o.y);}}; static std::optional<std::vector<Point>> reduce(const std::vector<std::vector<Point>>& shards); };",
        "std::optional<std::vector<ParetoFrontierMerge::Point>> ParetoFrontierMerge::reduce(const std::vector<std::vector<Point>>& shards){std::set<int> ids;std::vector<std::vector<Point>> partials;auto frontier=[](std::vector<Point> all){std::vector<Point> out;for(const auto&p:all){bool dominated=false;for(const auto&q:all)if((q.x>=p.x&&q.y>=p.y)&&(q.x>p.x||q.y>p.y)){dominated=true;break;}if(!dominated)out.push_back(p);}std::sort(out.begin(),out.end(),[](const Point&a,const Point&b){return std::tie(a.x,a.y,a.id)<std::tie(b.x,b.y,b.id);});return out;};for(auto s:shards){for(auto p:s)if(!ids.insert(p.id).second)return std::nullopt;partials.push_back(frontier(s));}std::vector<Point> all;for(auto&p:partials)all.insert(all.end(),p.begin(),p.end());return frontier(all);}",
        "std::optional<std::vector<ParetoFrontierMerge::Point>> ParetoFrontierMerge::reduce(const std::vector<std::vector<Point>>&){return std::nullopt;}",
        "using P=ParetoFrontierMerge::Point;auto f=ParetoFrontierMerge::reduce({{{1,1,3},{2,3,2}},{{3,2,4},{4,0,9}}});check(f&&*f==std::vector<P>({{4,0,9},{3,2,4},{2,3,2}}));",
        "using P=ParetoFrontierMerge::Point;check(!ParetoFrontierMerge::reduce({{{1,0,0}},{{1,1,1}}}));auto f=ParetoFrontierMerge::reduce({{{1,1,1},{2,1,1}}});check(f&&f->size()==2);auto e=ParetoFrontierMerge::reduce({});check(e&&e->empty());",
        "return frontier(all);", "return all;",
        "per-shard Pareto pruning followed by global re-pruning", "duplicate identities reject and equal coordinates retain both identities", "partial frontiers are concatenated without cross-shard dominance",
    ),
    _case(
        "dpr-sparse-coo-canonical-merge", "SparseCooCanonicalMerge", "Sparse COO canonical merge", "structural",
        "class SparseCooCanonicalMerge { public: struct Cell{std::size_t row,col;long long value;bool operator==(const Cell&o)const{return std::tie(row,col,value)==std::tie(o.row,o.col,o.value);}}; static std::optional<std::vector<Cell>> merge(std::size_t rows,std::size_t cols,const std::vector<std::vector<Cell>>& shards); };",
        "std::optional<std::vector<SparseCooCanonicalMerge::Cell>> SparseCooCanonicalMerge::merge(std::size_t rows,std::size_t cols,const std::vector<std::vector<Cell>>& shards){std::map<std::pair<std::size_t,std::size_t>,long long> totals;for(const auto&s:shards){std::pair<std::size_t,std::size_t> previous{0,0};bool first=true;for(auto c:s){if(c.row>=rows||c.col>=cols)return std::nullopt;auto key=std::make_pair(c.row,c.col);if(!first&&key<=previous)return std::nullopt;first=false;previous=key;long long next=0;if(__builtin_add_overflow(totals[key],c.value,&next))return std::nullopt;totals[key]=next;}}std::vector<Cell> out;for(auto x:totals)if(x.second!=0)out.push_back({x.first.first,x.first.second,x.second});return out;}",
        "std::optional<std::vector<SparseCooCanonicalMerge::Cell>> SparseCooCanonicalMerge::merge(std::size_t,std::size_t,const std::vector<std::vector<Cell>>&){return std::nullopt;}",
        "using C=SparseCooCanonicalMerge::Cell;auto m=SparseCooCanonicalMerge::merge(3,3,{{{0,1,2},{2,0,4}},{{0,1,-2},{1,2,5}}});check(m&&*m==std::vector<C>({{1,2,5},{2,0,4}}));",
        "using C=SparseCooCanonicalMerge::Cell;check(!SparseCooCanonicalMerge::merge(1,1,{{{1,0,2}}}));check(!SparseCooCanonicalMerge::merge(2,2,{{{1,0,1},{0,1,2}}}));auto e=SparseCooCanonicalMerge::merge(2,2,{});check(e&&e->empty());",
        "if(x.second!=0)out.push_back", "out.push_back",
        "validated sorted COO shards with checked coordinate accumulation", "zero cancellations disappear and output is canonical row-major", "zero-valued cancellation cells remain in canonical output",
    ),
    _case(
        "dpr-convex-hull-fragment-merge", "ConvexHullFragments", "Convex hull fragment merge", "structural",
        "class ConvexHullFragments { public: struct Point{long long x,y;bool operator==(const Point&o)const{return x==o.x&&y==o.y;}bool operator<(const Point&o)const{return std::tie(x,y)<std::tie(o.x,o.y);}}; static std::vector<Point> reduce(const std::vector<std::vector<Point>>& shards); };",
        "std::vector<ConvexHullFragments::Point> ConvexHullFragments::reduce(const std::vector<std::vector<Point>>& shards){for(const auto&s:shards)for(auto p:s)if(p.x<-1000000000LL||p.x>1000000000LL||p.y<-1000000000LL||p.y>1000000000LL)return {};auto hull=[](std::vector<Point> p){std::sort(p.begin(),p.end());p.erase(std::unique(p.begin(),p.end(),[](auto a,auto b){return a==b;}),p.end());if(p.size()<3)return p;auto cross=[](Point a,Point b,Point c)->long long{long long dx1,dy1,dx2,dy2,p1,p2,cr; if(__builtin_sub_overflow(b.x,a.x,&dx1)||__builtin_sub_overflow(c.y,a.y,&dy1)||__builtin_sub_overflow(b.y,a.y,&dy2)||__builtin_sub_overflow(c.x,a.x,&dx2)||__builtin_mul_overflow(dx1,dy1,&p1)||__builtin_mul_overflow(dx2,dy2,&p2)||__builtin_sub_overflow(p1,p2,&cr))return 1;return cr;};std::vector<Point> h;for(auto x:p){while(h.size()>=2&&cross(h[h.size()-2],h.back(),x)<=0)h.pop_back();h.push_back(x);}std::size_t lower=h.size();for(std::size_t i=p.size()-1;i-->0;){auto x=p[i];while(h.size()>lower&&cross(h[h.size()-2],h.back(),x)<=0)h.pop_back();h.push_back(x);}h.pop_back();return h;};std::vector<Point> candidates;for(auto s:shards){auto h=hull(s);candidates.insert(candidates.end(),h.begin(),h.end());}return hull(candidates);}",
        "std::vector<ConvexHullFragments::Point> ConvexHullFragments::reduce(const std::vector<std::vector<Point>>&){return {};}",
        "using P=ConvexHullFragments::Point;auto h=ConvexHullFragments::reduce({{{0,0},{1,1},{2,0}},{{0,2},{2,2},{1,1}}});check(h==std::vector<P>({{0,0},{2,0},{2,2},{0,2}}));",
        "using P=ConvexHullFragments::Point;auto h=ConvexHullFragments::reduce({{{0,0},{1,0},{2,0}}});check(h==std::vector<P>({{0,0},{2,0}}));check(ConvexHullFragments::reduce({}).empty());check(ConvexHullFragments::reduce({{{LLONG_MIN,0},{0,LLONG_MAX},{1,1}}}).empty());auto q=ConvexHullFragments::reduce({{{1,1},{1,1}}});check(q==std::vector<P>({{1,1}}));",
        "return hull(candidates);", "return candidates;",
        "per-fragment monotone hull followed by global rehull", "coordinates outside the exact bounded orientation domain reject as an empty result", "fragment hulls are concatenated without global rehulling",
    ),
    _case(
        "dpr-sorted-shard-median", "SortedShardMedian", "Sorted shard median", "structural",
        "class SortedShardMedian { public: struct Median{long long low,high;bool even;}; static std::optional<Median> select(const std::vector<std::vector<long long>>& sorted_shards); };",
        "std::optional<SortedShardMedian::Median> SortedShardMedian::select(const std::vector<std::vector<long long>>& shards){std::size_t total=0;for(const auto&s:shards){if(!std::is_sorted(s.begin(),s.end()))return std::nullopt;total+=s.size();}if(total==0)return std::nullopt;std::vector<std::size_t> at(shards.size());auto next=[&](){std::size_t best=shards.size();for(std::size_t i=0;i<shards.size();++i)if(at[i]<shards[i].size()&&(best==shards.size()||shards[i][at[i]]<shards[best][at[best]]||(shards[i][at[i]]==shards[best][at[best]]&&i<best)))best=i;long long v=shards[best][at[best]++];return v;};long long low=0,high=0;for(std::size_t rank=0;rank<=total/2;++rank){long long v=next();if(rank==(total-1)/2)low=v;if(rank==total/2)high=v;}return Median{low,high,total%2==0};}",
        "std::optional<SortedShardMedian::Median> SortedShardMedian::select(const std::vector<std::vector<long long>>&){return std::nullopt;}",
        "auto m=SortedShardMedian::select({{1,4,9},{2,3,10}});check(m&&m->even&&m->low==3&&m->high==4);",
        "check(!SortedShardMedian::select({{2,1}}));check(!SortedShardMedian::select({}));auto m=SortedShardMedian::select({{}, {5,5,7}});check(m&&!m->even&&m->low==5&&m->high==5);",
        "shards[i][at[i]]<shards[best][at[best]]", "shards[i][at[i]]>shards[best][at[best]]",
        "rank-selecting K-way traversal of validated sorted shards", "empty totals reject and even totals retain both middle values", "the merge selects greatest rather than least available heads",
    ),
    _case(
        "dpr-priority-reservoir-merge", "PriorityReservoirMerge", "Priority reservoir merge", "structural",
        "class PriorityReservoirMerge { public: struct Item{unsigned long long id;long long payload;}; struct Sample{unsigned long long priority,id;long long payload;}; static std::optional<std::vector<Sample>> reduce(const std::vector<std::vector<Item>>& shards,unsigned long long seed,std::size_t k); };",
        "std::optional<std::vector<PriorityReservoirMerge::Sample>> PriorityReservoirMerge::reduce(const std::vector<std::vector<Item>>& shards,unsigned long long seed,std::size_t k){auto mix=[](unsigned long long x){x^=x>>30;x*=0xbf58476d1ce4e5b9ULL;x^=x>>27;x*=0x94d049bb133111ebULL;return x^(x>>31);};auto less=[](const Sample&a,const Sample&b){return std::tie(a.priority,a.id)<std::tie(b.priority,b.id);};std::set<unsigned long long> ids;std::vector<std::vector<Sample>> partials;for(const auto&s:shards){std::vector<Sample> p;for(auto x:s){if(!ids.insert(x.id).second)return std::nullopt;p.push_back({mix(seed^x.id),x.id,x.payload});}std::sort(p.begin(),p.end(),less);if(p.size()>k)p.resize(k);partials.push_back(p);}std::vector<Sample> out;for(auto&p:partials){out.insert(out.end(),p.begin(),p.end());std::sort(out.begin(),out.end(),less);if(out.size()>k)out.resize(k);}return out;}",
        "std::optional<std::vector<PriorityReservoirMerge::Sample>> PriorityReservoirMerge::reduce(const std::vector<std::vector<Item>>&,unsigned long long,std::size_t){return std::nullopt;}",
        "using I=PriorityReservoirMerge::Item;auto a=PriorityReservoirMerge::reduce({{{1,10},{2,20}},{{3,30}}},7,2);auto b=PriorityReservoirMerge::reduce({{{3,30}},{{1,10},{2,20}}},7,2);check(a&&b&&a->size()==2&&b->size()==2);check((*a)[0].id==(*b)[0].id&&(*a)[1].id==(*b)[1].id);",
        "using I=PriorityReservoirMerge::Item;check(!PriorityReservoirMerge::reduce({{{1,1}},{{1,2}}},0,1));auto z=PriorityReservoirMerge::reduce({{{1,1}}},0,0);check(z&&z->empty());auto e=PriorityReservoirMerge::reduce({},3,2);check(e&&e->empty());",
        "mix(seed^x.id)", "mix(seed^static_cast<unsigned long long>(x.payload))",
        "mergeable bottom-K deterministic priority reservoir", "duplicate identities reject and priorities depend only on seed and identity", "priority depends on mutable payload rather than stable identity",
    ),
)


assert len(CASES) == 12
