"""One-to-one clean-room cases for the transpose remediation family."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TransposeCase:
    legacy_id: str
    task_id: str
    title: str
    objective: str
    profile: str
    function: str
    types: str
    params: str
    return_type: str
    body: str
    visible: str
    hidden: str
    marker: str
    prompt_terms: tuple[str, ...]
    negative_old: str
    negative_new: str
    negative_description: str


def _case(**values: object) -> TransposeCase:
    return TransposeCase(**values)  # type: ignore[arg-type]


CASES = (
    _case(
        legacy_id="transpose-call-center", task_id="transpose-call-center",
        title="Call Volume Dense Transpose",
        objective="transpose a validated rectangular call-volume ledger and compute a weighted output checksum",
        profile="out-of-place dense rectangular coordinate bijection",
        function="transpose_call_volume",
        types="struct CallTranspose { bool valid{}; std::vector<std::vector<int>> cells; long long checksum{}; };",
        params="const std::vector<std::vector<int>>& rows", return_type="CallTranspose",
        body="""CallTranspose out{}; if(rows.empty()){out.valid=true;return out;} const std::size_t width=rows.front().size(); if(width==0U)return out; for(const auto& row:rows)if(row.size()!=width)return out; out.cells.assign(width,std::vector<int>(rows.size())); for(std::size_t r=0;r<rows.size();++r)for(std::size_t c=0;c<width;++c)out.cells[c][r]=rows[r][c]; long long weight=1;for(const auto& row:out.cells)for(int value:row)out.checksum+=weight++*value;out.valid=true;return out;""",
        visible="""auto r=transpose_call_volume({{1,2,3},{4,5,6}});if(!r.valid||r.cells!=std::vector<std::vector<int>>{{1,4},{2,5},{3,6}}||r.checksum!=86)return 1;return 0;""",
        hidden="""if(transpose_call_volume({{1,2},{3}}).valid)return 1;auto e=transpose_call_volume({});if(!e.valid||!e.cells.empty())return 1;if(transpose_call_volume({{}}).valid)return 1;return 0;""",
        marker="out.cells[c][r]", prompt_terms=("rectangular", "swapped dimensions", "coordinate bijection", "weighted checksum"),
        negative_old="out.cells[c][r]=rows[r][c];", negative_new="out.cells[c][r]=rows[r][width-1U-c];",
        negative_description="reverse source columns instead of applying the row-to-column bijection",
    ),
    _case(
        legacy_id="transpose-choir-rehearsal", task_id="transpose-square-in-place",
        title="In-Place Square Score Transpose",
        objective="transpose a square rehearsal score in place using only upper-triangle swaps",
        profile="in-place upper-triangle pair swaps with atomic validation",
        function="transpose_square_score",
        types="struct SquareTranspose { bool valid{}; long long diagonal{}; std::size_t swaps{}; };",
        params="std::vector<std::vector<int>>& score", return_type="SquareTranspose",
        body="""SquareTranspose out{};const std::size_t n=score.size();for(const auto& row:score)if(row.size()!=n)return out;for(std::size_t r=0;r<n;++r){out.diagonal+=score[r][r];for(std::size_t c=r+1U;c<n;++c){std::swap(score[r][c],score[c][r]);++out.swaps;}}out.valid=true;return out;""",
        visible="""std::vector<std::vector<int>> g{{1,2,3},{4,5,6},{7,8,9}};auto r=transpose_square_score(g);if(!r.valid||g!=std::vector<std::vector<int>>{{1,4,7},{2,5,8},{3,6,9}}||r.diagonal!=15||r.swaps!=3)return 1;return 0;""",
        hidden="""std::vector<std::vector<int>> bad{{1,2},{3}};auto copy=bad;if(transpose_square_score(bad).valid||bad!=copy)return 1;std::vector<std::vector<int>> e;auto r=transpose_square_score(e);if(!r.valid||r.swaps!=0)return 1;return 0;""",
        marker="c=r+1U", prompt_terms=("in place", "upper triangle", "atomic validation", "swap count"),
        negative_old="std::swap(score[r][c],score[c][r]);", negative_new="std::swap(score[r][c],score[r][c]);",
        negative_description="self-swap the upper triangle and leave the matrix unchanged",
    ),
    _case(
        legacy_id="transpose-class-register", task_id="transpose-ragged-pad-mask",
        title="Ragged Register Pad Mask",
        objective="transpose ragged register rows with a fill value and a separate occupancy mask",
        profile="zip-longest ragged transpose with explicit provenance mask",
        function="transpose_padded_register",
        types="struct PaddedRegister { std::vector<std::vector<int>> cells; std::vector<std::vector<bool>> present; std::size_t padded{}; };",
        params="const std::vector<std::vector<int>>& rows, int fill", return_type="PaddedRegister",
        body="""PaddedRegister out{};std::size_t width=0;for(const auto& row:rows)width=std::max(width,row.size());out.cells.assign(width,std::vector<int>(rows.size(),fill));out.present.assign(width,std::vector<bool>(rows.size(),false));for(std::size_t r=0;r<rows.size();++r)for(std::size_t c=0;c<width;++c)if(c<rows[r].size()){out.cells[c][r]=rows[r][c];out.present[c][r]=true;}else ++out.padded;return out;""",
        visible="""auto r=transpose_padded_register({{1,2,3},{4}},-9);if(r.cells!=std::vector<std::vector<int>>{{1,4},{2,-9},{3,-9}}||!r.present[0][0]||r.present[1][1]||r.padded!=2)return 1;return 0;""",
        hidden="""auto e=transpose_padded_register({},7);if(!e.cells.empty()||e.padded!=0)return 1;auto z=transpose_padded_register({{},{}},5);if(!z.cells.empty())return 1;return 0;""",
        marker="out.present[c][r]=true", prompt_terms=("ragged", "zip longest", "fill value", "occupancy mask"),
        negative_old="out.present[c][r]=true;", negative_new="out.present[c][r]=false;",
        negative_description="erase provenance for every real input cell",
    ),
    _case(
        legacy_id="transpose-diet-diary", task_id="transpose-csr-to-csc",
        title="CSR To CSC Sparse Transpose",
        objective="transpose a canonical CSR matrix directly into canonical CSC arrays",
        profile="count-prefix-scatter compressed sparse conversion",
        function="csr_to_csc",
        types="struct CsrMatrix{int rows{};int cols{};std::vector<std::size_t> offsets;std::vector<int> columns;std::vector<int> values;};struct CscMatrix{bool valid{};int rows{};int cols{};std::vector<std::size_t> offsets;std::vector<int> rows_index;std::vector<int> values;};",
        params="const CsrMatrix& input", return_type="CscMatrix",
        body="""CscMatrix out{};if(input.rows<0||input.cols<0||input.offsets.size()!=static_cast<std::size_t>(input.rows)+1U||input.columns.size()!=input.values.size()||input.offsets.empty()||input.offsets.front()!=0U||input.offsets.back()!=input.values.size())return out;for(std::size_t i=1;i<input.offsets.size();++i)if(input.offsets[i]<input.offsets[i-1U])return out;out.offsets.assign(static_cast<std::size_t>(input.cols)+1U,0U);for(int col:input.columns){if(col<0||col>=input.cols)return CscMatrix{};++out.offsets[static_cast<std::size_t>(col)+1U];}for(std::size_t i=1;i<out.offsets.size();++i)out.offsets[i]+=out.offsets[i-1U];auto next=out.offsets;out.rows_index.resize(input.values.size());out.values.resize(input.values.size());for(int r=0;r<input.rows;++r)for(std::size_t p=input.offsets[r];p<input.offsets[r+1];++p){const std::size_t target=next[static_cast<std::size_t>(input.columns[p])]++;out.rows_index[target]=r;out.values[target]=input.values[p];}out.rows=input.cols;out.cols=input.rows;out.valid=true;return out;""",
        visible="""CsrMatrix m{2,3,{0,2,3},{0,2,1},{5,7,9}};auto r=csr_to_csc(m);if(!r.valid||r.rows!=3||r.cols!=2||r.offsets!=std::vector<std::size_t>{0,1,2,3}||r.rows_index!=std::vector<int>{0,1,0}||r.values!=std::vector<int>{5,9,7})return 1;return 0;""",
        hidden="""if(csr_to_csc({1,2,{0,1},{2},{4}}).valid)return 1;if(csr_to_csc({1,1,{1,1},{},{}}).valid)return 1;auto e=csr_to_csc({0,3,{0},{},{}});if(!e.valid||e.offsets.size()!=4)return 1;return 0;""",
        marker="auto next=out.offsets", prompt_terms=("CSR", "CSC", "prefix counts", "stable scatter"),
        negative_old="const std::size_t target=next[static_cast<std::size_t>(input.columns[p])]++;", negative_new="const std::size_t target=next[static_cast<std::size_t>((input.columns[p]+1)%input.cols)]++;",
        negative_description="scatter each nonzero into the following sparse column",
    ),
    _case(
        legacy_id="transpose-energy-meters", task_id="transpose-coordinate-coalesce",
        title="Coordinate Meter Coalescing Transpose",
        objective="transpose coordinate entries while summing duplicates and eliding zero totals",
        profile="validated coordinate swap with ordered-map coalescing",
        function="transpose_meter_entries",
        types="struct Entry{int row{};int col{};int value{};};struct CoordinateTranspose{bool valid{};int rows{};int cols{};std::vector<Entry> entries;std::size_t duplicates{};};",
        params="int rows, int cols, const std::vector<Entry>& entries", return_type="CoordinateTranspose",
        body="""CoordinateTranspose out{};if(rows<0||cols<0)return out;std::map<std::pair<int,int>,long long> sums;for(const auto& entry:entries){if(entry.row<0||entry.row>=rows||entry.col<0||entry.col>=cols)return out;auto key=std::make_pair(entry.col,entry.row);if(sums.count(key)!=0U)++out.duplicates;sums[key]+=entry.value;if(sums[key]>std::numeric_limits<int>::max()||sums[key]<std::numeric_limits<int>::min())return CoordinateTranspose{};}for(const auto& item:sums)if(item.second!=0)out.entries.push_back({item.first.first,item.first.second,static_cast<int>(item.second)});out.rows=cols;out.cols=rows;out.valid=true;return out;""",
        visible="""auto r=transpose_meter_entries(2,3,{{0,2,4},{1,0,7},{0,2,-1}});if(!r.valid||r.rows!=3||r.cols!=2||r.duplicates!=1||r.entries.size()!=2||r.entries[0].row!=0||r.entries[1].row!=2||r.entries[1].value!=3)return 1;return 0;""",
        hidden="""if(transpose_meter_entries(1,1,{{1,0,1}}).valid)return 1;auto z=transpose_meter_entries(1,1,{{0,0,2},{0,0,-2}});if(!z.valid||!z.entries.empty())return 1;return 0;""",
        marker="std::make_pair(entry.col,entry.row)", prompt_terms=("coordinate list", "coalesce", "zero elision", "canonical order"),
        negative_old="auto key=std::make_pair(entry.col,entry.row);", negative_new="auto key=std::make_pair(entry.row,entry.col);",
        negative_description="coalesce at the original rather than transposed coordinates",
    ),
    _case(
        legacy_id="transpose-exam-markbook", task_id="transpose-packed-bitboard",
        title="Packed Bitboard Transpose",
        objective="transpose an 8 by 8 packed bitboard without expanding it to a dense grid",
        profile="direct packed-bit row-column index permutation",
        function="transpose_bitboard",
        types="struct BitboardTranspose{std::uint64_t bits{};unsigned occupied{};};",
        params="std::uint64_t bits", return_type="BitboardTranspose",
        body="""BitboardTranspose out{};for(unsigned index=0;index<64U;++index)if((bits&(std::uint64_t{1}<<index))!=0U){const unsigned row=index/8U;const unsigned col=index%8U;const unsigned target=col*8U+row;out.bits|=std::uint64_t{1}<<target;++out.occupied;}return out;""",
        visible="""auto r=transpose_bitboard((std::uint64_t{1}<<1U)|(std::uint64_t{1}<<16U));if(r.occupied!=2||r.bits!=((std::uint64_t{1}<<8U)|(std::uint64_t{1}<<2U)))return 1;return 0;""",
        hidden="""if(transpose_bitboard(0).bits!=0)return 1;auto d=transpose_bitboard(std::uint64_t{1}<<27U);if(d.bits!=(std::uint64_t{1}<<27U))return 1;return 0;""",
        marker="col*8U+row", prompt_terms=("packed bits", "8 by 8", "index permutation", "no dense grid"),
        negative_old="const unsigned target=col*8U+row;", negative_new="const unsigned target=row*8U+col;",
        negative_description="leave every occupied bit at its original index",
    ),
    _case(
        legacy_id="transpose-factory-shifts", task_id="transpose-tiled-grid",
        title="Cache-Tiled Factory Grid Transpose",
        objective="transpose a rectangle in fixed cache tiles and report the tile visitation order",
        profile="blocked row-column traversal with clipped boundary tiles",
        function="transpose_tiled_grid",
        types="struct TileVisit{std::size_t row{};std::size_t col{};};struct TiledTranspose{bool valid{};std::vector<std::vector<int>> cells;std::vector<TileVisit> visits;std::size_t clipped_tiles{};};",
        params="const std::vector<std::vector<int>>& rows, std::size_t tile_size", return_type="TiledTranspose",
        body="""TiledTranspose out{};if(tile_size==0U||tile_size>64U)return out;if(rows.empty()){out.valid=true;return out;}const std::size_t width=rows.front().size();if(width==0U)return out;for(const auto& row:rows)if(row.size()!=width)return out;out.cells.assign(width,std::vector<int>(rows.size()));for(std::size_t br=0;br<rows.size();br+=tile_size)for(std::size_t bc=0;bc<width;bc+=tile_size){out.visits.push_back({br,bc});if(br+tile_size>rows.size()||bc+tile_size>width)++out.clipped_tiles;for(std::size_t r=br;r<std::min(rows.size(),br+tile_size);++r)for(std::size_t c=bc;c<std::min(width,bc+tile_size);++c)out.cells[c][r]=rows[r][c];}out.valid=true;return out;""",
        visible="""auto r=transpose_tiled_grid({{1,2,3},{4,5,6},{7,8,9}},2);if(!r.valid||r.cells!=std::vector<std::vector<int>>{{1,4,7},{2,5,8},{3,6,9}}||r.visits.size()!=4||r.visits[1].col!=2||r.clipped_tiles!=3)return 1;return 0;""",
        hidden="""if(transpose_tiled_grid({{1}},0).valid)return 1;if(transpose_tiled_grid({{1}},65).valid)return 1;if(transpose_tiled_grid({{1,2},{3}},1).valid)return 1;auto clipped=transpose_tiled_grid({{1,2,3,4}},3);if(!clipped.valid||clipped.visits.size()!=2||clipped.clipped_tiles!=2||clipped.cells[3][0]!=4)return 1;auto empty=transpose_tiled_grid({},8);if(!empty.valid||!empty.visits.empty())return 1;return 0;""",
        marker="br+=tile_size", prompt_terms=("cache tiles", "clipped boundary", "visitation order", "tile size"),
        negative_old="out.cells[c][r]=rows[r][c];", negative_new="out.cells[c][r]=rows[rows.size()-1U-r][c];",
        negative_description="reverse rows inside every visited tile",
    ),
    _case(
        legacy_id="transpose-freight-manifest", task_id="transpose-stream-batches",
        title="Streaming Freight Column Batches",
        objective="emit transposed columns in bounded-width resumable batches",
        profile="sequential column batching with explicit continuation offsets",
        function="transpose_stream_batches",
        types="struct ColumnBatch{std::size_t first_column{};std::vector<std::vector<int>> columns;};struct StreamTranspose{bool valid{};std::vector<ColumnBatch>batches;std::size_t next_offset{};};",
        params="const std::vector<std::vector<int>>& rows, std::size_t batch_width", return_type="StreamTranspose",
        body="""StreamTranspose out{};if(batch_width==0U)return out;if(rows.empty()){out.valid=true;return out;}const std::size_t width=rows.front().size();for(const auto& row:rows)if(row.size()!=width)return out;for(std::size_t first=0;first<width;first+=batch_width){ColumnBatch batch{};batch.first_column=first;for(std::size_t c=first;c<std::min(width,first+batch_width);++c){std::vector<int> column;for(const auto& row:rows)column.push_back(row[c]);batch.columns.push_back(std::move(column));}out.batches.push_back(std::move(batch));out.next_offset=std::min(width,first+batch_width);}out.valid=true;return out;""",
        visible="""auto r=transpose_stream_batches({{1,2,3,4,5},{6,7,8,9,10}},2);if(!r.valid||r.batches.size()!=3||r.batches[1].first_column!=2||r.batches[2].columns[0]!=std::vector<int>{5,10}||r.next_offset!=5)return 1;return 0;""",
        hidden="""if(transpose_stream_batches({{1}},0).valid)return 1;if(transpose_stream_batches({{1,2},{3}},1).valid)return 1;return 0;""",
        marker="first+=batch_width", prompt_terms=("bounded batches", "continuation offset", "column order", "batch width"),
        negative_old="first+=batch_width", negative_new="first+=1U",
        negative_description="advance one column and emit overlapping batches",
    ),
    _case(
        legacy_id="transpose-garden-plots", task_id="transpose-tensor-axes",
        title="Rank-Three Tensor Axis Permutation",
        objective="permute all three axes of a dense rank-three tensor with recomputed strides",
        profile="validated axis permutation and flat-stride coordinate remap",
        function="permute_tensor_axes",
        types="struct Tensor3{std::array<std::size_t,3>dims{};std::vector<int>values;};struct TensorTranspose{bool valid{};Tensor3 tensor;};",
        params="const Tensor3& tensor, const std::array<unsigned,3>& order", return_type="TensorTranspose",
        body="""TensorTranspose out{};std::array<bool,3>seen{};for(unsigned axis:order){if(axis>2U||seen[axis])return out;seen[axis]=true;}const std::size_t total=tensor.dims[0]*tensor.dims[1]*tensor.dims[2];if(total!=tensor.values.size())return out;for(std::size_t i=0;i<3U;++i)out.tensor.dims[i]=tensor.dims[order[i]];out.tensor.values.assign(total,0);for(std::size_t a=0;a<tensor.dims[0];++a)for(std::size_t b=0;b<tensor.dims[1];++b)for(std::size_t c=0;c<tensor.dims[2];++c){std::array<std::size_t,3>coord{a,b,c};const std::size_t source=(a*tensor.dims[1]+b)*tensor.dims[2]+c;const std::size_t target=(coord[order[0]]*out.tensor.dims[1]+coord[order[1]])*out.tensor.dims[2]+coord[order[2]];out.tensor.values[target]=tensor.values[source];}out.valid=true;return out;""",
        visible="""Tensor3 t{{2,3,1},{1,2,3,4,5,6}};auto r=permute_tensor_axes(t,{1,0,2});if(!r.valid||r.tensor.dims!=std::array<std::size_t,3>{3,2,1}||r.tensor.values!=std::vector<int>{1,4,2,5,3,6})return 1;return 0;""",
        hidden="""if(permute_tensor_axes({{1,1,1},{7}},{0,0,2}).valid)return 1;if(permute_tensor_axes({{2,2,1},{1}},{0,1,2}).valid)return 1;return 0;""",
        marker="coord[order[0]]", prompt_terms=("rank three", "axis permutation", "flat strides", "coordinate remap"),
        negative_old="out.tensor.values[target]=tensor.values[source];", negative_new="out.tensor.values[target]=tensor.values[(source+1U)%total];",
        negative_description="retain flattened source order instead of applying the axis permutation",
    ),
    _case(
        legacy_id="transpose-inventory-cycle", task_id="transpose-directed-graph",
        title="Directed Inventory Graph Transpose",
        objective="reverse every directed edge and build canonical incoming adjacency lists",
        profile="edge reversal with duplicate validation and sorted adjacency",
        function="transpose_graph",
        types="struct Edge{std::size_t from{};std::size_t to{};};struct GraphTranspose{bool valid{};std::vector<Edge>edges;std::vector<std::vector<std::size_t>>incoming;};",
        params="std::size_t vertex_count, const std::vector<Edge>& edges", return_type="GraphTranspose",
        body="""GraphTranspose out{};out.incoming.resize(vertex_count);std::set<std::pair<std::size_t,std::size_t>>seen;for(const auto& edge:edges){if(edge.from>=vertex_count||edge.to>=vertex_count||!seen.insert({edge.from,edge.to}).second)return GraphTranspose{};out.edges.push_back({edge.to,edge.from});out.incoming[edge.from].push_back(edge.to);}std::sort(out.edges.begin(),out.edges.end(),[](const Edge&a,const Edge&b){return std::tie(a.from,a.to)<std::tie(b.from,b.to);});for(auto& list:out.incoming)std::sort(list.begin(),list.end());out.valid=true;return out;""",
        visible="""auto r=transpose_graph(3,{{0,1},{2,1},{1,2}});if(!r.valid||r.edges.size()!=3||r.edges[0].from!=1||r.edges[0].to!=0||r.incoming[1]!=std::vector<std::size_t>{2})return 1;return 0;""",
        hidden="""if(transpose_graph(2,{{0,1},{0,1}}).valid)return 1;if(transpose_graph(1,{{0,1}}).valid)return 1;auto e=transpose_graph(0,{});if(!e.valid)return 1;return 0;""",
        marker="{edge.to,edge.from}", prompt_terms=("directed edges", "reverse", "incoming adjacency", "duplicate edge"),
        negative_old="out.edges.push_back({edge.to,edge.from});", negative_new="out.edges.push_back({edge.from,edge.to});",
        negative_description="preserve the original direction of every edge",
    ),
    _case(
        legacy_id="transpose-lab-readings", task_id="transpose-relation-index",
        title="Relation Index Inversion",
        objective="invert a many-to-many relation into sorted right-to-left groups with duplicate accounting",
        profile="ordered relation inversion with per-pair duplicate suppression",
        function="invert_relation_index",
        types="struct Relation{int left{};int right{};};struct RelationGroup{int right{};std::vector<int>lefts;};struct RelationTranspose{std::vector<RelationGroup>groups;std::size_t duplicates{};};",
        params="const std::vector<Relation>& relations", return_type="RelationTranspose",
        body="""RelationTranspose out{};std::map<int,std::set<int>>index;for(const auto& relation:relations)if(!index[relation.right].insert(relation.left).second)++out.duplicates;for(const auto& item:index)out.groups.push_back({item.first,std::vector<int>(item.second.begin(),item.second.end())});return out;""",
        visible="""auto r=invert_relation_index({{2,9},{1,8},{1,9},{2,9}});if(r.duplicates!=1||r.groups.size()!=2||r.groups[0].right!=8||r.groups[1].lefts!=std::vector<int>{1,2})return 1;return 0;""",
        hidden="""auto e=invert_relation_index({});if(!e.groups.empty())return 1;auto n=invert_relation_index({{-1,4},{3,-2}});if(n.groups.front().right!=-2)return 1;return 0;""",
        marker="index[relation.right]", prompt_terms=("many to many", "invert relation", "duplicate pair", "sorted groups"),
        negative_old="index[relation.right].insert(relation.left)", negative_new="index[relation.left].insert(relation.right)",
        negative_description="group by the original left endpoint",
    ),
    _case(
        legacy_id="transpose-library-loans", task_id="transpose-run-encoded-image",
        title="Run-Encoded Loan Image Transpose",
        objective="transpose a run-length row image and canonically re-encode every output row",
        profile="validated run decoding, coordinate transpose, and adjacent-run recompression",
        function="transpose_run_image",
        types="struct Run{int value{};std::size_t count{};};struct RunImage{std::size_t rows{};std::size_t cols{};std::vector<std::vector<Run>>encoded;};struct RunImageTranspose{bool valid{};RunImage image;std::size_t run_count{};};",
        params="const RunImage& image", return_type="RunImageTranspose",
        body="""RunImageTranspose out{};if(image.encoded.size()!=image.rows)return out;std::vector<std::vector<int>>dense(image.rows);for(std::size_t r=0;r<image.rows;++r){for(const auto& run:image.encoded[r]){if(run.count==0U)return RunImageTranspose{};dense[r].insert(dense[r].end(),run.count,run.value);}if(dense[r].size()!=image.cols)return RunImageTranspose{};}out.image.rows=image.cols;out.image.cols=image.rows;out.image.encoded.resize(image.cols);for(std::size_t c=0;c<image.cols;++c)for(std::size_t r=0;r<image.rows;++r){const int value=dense[r][c];auto& runs=out.image.encoded[c];if(!runs.empty()&&runs.back().value==value)++runs.back().count;else runs.push_back({value,1U});}for(const auto& row:out.image.encoded)out.run_count+=row.size();out.valid=true;return out;""",
        visible="""RunImage i{2,3,{{{1,2},{2,1}},{{1,1},{3,2}}}};auto r=transpose_run_image(i);if(!r.valid||r.image.rows!=3||r.image.encoded[0].size()!=1||r.image.encoded[0][0].count!=2||r.run_count!=5)return 1;return 0;""",
        hidden="""if(transpose_run_image({1,2,{{{4,1}}}}).valid)return 1;if(transpose_run_image({1,1,{{{4,0}}}}).valid)return 1;auto e=transpose_run_image({0,0,{}});if(!e.valid)return 1;return 0;""",
        marker="runs.back().value==value", prompt_terms=("run length", "decode", "recompress", "adjacent equal"),
        negative_old="if(!runs.empty()&&runs.back().value==value)++runs.back().count;", negative_new="if(false&&!runs.empty()&&runs.back().value==value)++runs.back().count;",
        negative_description="never merge adjacent equal values in an output row",
    ),
    _case(
        legacy_id="transpose-market-quotes", task_id="transpose-channel-planes",
        title="Interleaved Quote Channel Planes",
        objective="transpose an interleaved RGB rectangle into three planar transposed channels",
        profile="shape validation plus synchronized interleaved-to-planar remap",
        function="transpose_channels",
        types="struct Pixel{int red{};int green{};int blue{};};using Plane=std::vector<std::vector<int>>;struct ChannelTranspose{bool valid{};std::array<Plane,3>planes;std::array<int,3>minimum{};};",
        params="const std::vector<std::vector<Pixel>>& rows", return_type="ChannelTranspose",
        body="""ChannelTranspose out{};out.minimum.fill(std::numeric_limits<int>::max());if(rows.empty()){out.valid=true;out.minimum={0,0,0};return out;}const std::size_t width=rows.front().size();if(width==0U)return out;for(const auto& row:rows)if(row.size()!=width)return out;for(auto& plane:out.planes)plane.assign(width,std::vector<int>(rows.size()));for(std::size_t r=0;r<rows.size();++r)for(std::size_t c=0;c<width;++c){const auto p=rows[r][c];out.planes[0][c][r]=p.red;out.planes[1][c][r]=p.green;out.planes[2][c][r]=p.blue;out.minimum[0]=std::min(out.minimum[0],p.red);out.minimum[1]=std::min(out.minimum[1],p.green);out.minimum[2]=std::min(out.minimum[2],p.blue);}out.valid=true;return out;""",
        visible="""auto r=transpose_channels({{{1,9,5},{2,8,6}},{{3,7,4},{4,6,3}}});if(!r.valid||r.planes[0]!=Plane{{1,3},{2,4}}||r.planes[1][0]!=std::vector<int>{9,7}||r.minimum!=std::array<int,3>{1,6,3})return 1;return 0;""",
        hidden="""if(transpose_channels({{{1,2,3}},{{4,5,6},{7,8,9}}}).valid)return 1;auto e=transpose_channels({});if(!e.valid||e.minimum[0]!=0)return 1;return 0;""",
        marker="out.planes[2][c][r]=p.blue", prompt_terms=("interleaved", "planar channels", "synchronized", "channel minima"),
        negative_old="out.planes[1][c][r]=p.green;", negative_new="out.planes[1][c][r]=p.blue;",
        negative_description="copy blue samples into the green plane",
    ),
    _case(
        legacy_id="transpose-museum-visits", task_id="transpose-symmetric-triangle",
        title="Symmetric Triangle Expansion",
        objective="expand packed upper-triangle storage into transposed lower-column records",
        profile="packed triangular index traversal with mirrored-coordinate validation",
        function="transpose_symmetric_triangle",
        types="struct TriangleTranspose{bool valid{};std::vector<std::vector<int>>lower_columns;long long diagonal{};};",
        params="std::size_t size, const std::vector<int>& upper", return_type="TriangleTranspose",
        body="""TriangleTranspose out{};if(size>0U&&size>(std::numeric_limits<std::size_t>::max()-1U)/size)return out;const std::size_t expected=size*(size+1U)/2U;if(upper.size()!=expected)return out;std::vector<std::vector<int>>dense(size,std::vector<int>(size));std::size_t p=0;for(std::size_t r=0;r<size;++r)for(std::size_t c=r;c<size;++c){dense[r][c]=upper[p];dense[c][r]=upper[p];if(r==c)out.diagonal+=upper[p];++p;}out.lower_columns.resize(size);for(std::size_t c=0;c<size;++c)for(std::size_t r=c;r<size;++r)out.lower_columns[c].push_back(dense[r][c]);out.valid=true;return out;""",
        visible="""auto r=transpose_symmetric_triangle(3,{1,2,3,4,5,6});if(!r.valid||r.lower_columns!=std::vector<std::vector<int>>{{1,2,3},{4,5},{6}}||r.diagonal!=11)return 1;return 0;""",
        hidden="""if(transpose_symmetric_triangle(2,{1,2}).valid)return 1;auto e=transpose_symmetric_triangle(0,{});if(!e.valid||!e.lower_columns.empty())return 1;return 0;""",
        marker="dense[c][r]=upper[p]", prompt_terms=("packed upper triangle", "mirror", "lower columns", "diagonal"),
        negative_old="dense[c][r]=upper[p];", negative_new="dense[c][r]=0;",
        negative_description="discard every mirrored off-diagonal value",
    ),
    _case(
        legacy_id="transpose-network-probes", task_id="transpose-lazy-view",
        title="Lazy Probe Transposed View",
        objective="answer checked transposed-coordinate queries without materializing an output matrix",
        profile="inverse coordinate mapping over immutable source storage",
        function="make_transposed_view",
        types="struct Query{std::size_t row{};std::size_t col{};};struct LazyTranspose{bool valid{};std::size_t rows{};std::size_t cols{};std::vector<int>answers;std::size_t source_reads{};};",
        params="const std::vector<std::vector<int>>& rows, const std::vector<Query>& queries", return_type="LazyTranspose",
        body="""LazyTranspose out{};if(rows.empty()){if(!queries.empty())return out;out.valid=true;return out;}const std::size_t width=rows.front().size();if(width==0U)return out;for(const auto& row:rows)if(row.size()!=width)return out;out.rows=width;out.cols=rows.size();for(const auto& query:queries){if(query.row>=out.rows||query.col>=out.cols)return LazyTranspose{};out.answers.push_back(rows[query.col][query.row]);++out.source_reads;}out.valid=true;return out;""",
        visible="""auto r=make_transposed_view({{1,2,3},{4,5,6}},{{2,0},{0,1}});if(!r.valid||r.rows!=3||r.cols!=2||r.answers!=std::vector<int>{3,4}||r.source_reads!=2)return 1;return 0;""",
        hidden="""if(make_transposed_view({{1,2}},{{2,0}}).valid)return 1;if(make_transposed_view({},{{0,0}}).valid)return 1;auto e=make_transposed_view({},{});if(!e.valid)return 1;return 0;""",
        marker="rows[query.col][query.row]", prompt_terms=("lazy view", "inverse mapping", "queries", "no materialization"),
        negative_old="rows[query.col][query.row]", negative_new="rows[query.col][(query.row+1U)%width]",
        negative_description="shift every inverse-mapped source column by one",
    ),
    _case(
        legacy_id="transpose-river-samples", task_id="transpose-anti-diagonal",
        title="Anti-Diagonal River Reflection",
        objective="reflect a rectangular sample grid across its anti-diagonal",
        profile="dimension-swapping reverse-row reverse-column coordinate transform",
        function="reflect_anti_diagonal",
        types="struct AntiDiagonalTranspose{bool valid{};std::size_t source_rows{};std::size_t source_cols{};std::vector<std::vector<int>>cells;long long anti_sum{};std::size_t reflected{};};",
        params="const std::vector<std::vector<int>>& rows", return_type="AntiDiagonalTranspose",
        body="""AntiDiagonalTranspose out{};if(rows.empty()){out.valid=true;return out;}const std::size_t width=rows.front().size();if(width==0U)return out;for(const auto& row:rows)if(row.size()!=width)return out;out.source_rows=rows.size();out.source_cols=width;out.cells.assign(width,std::vector<int>(rows.size()));for(std::size_t r=0;r<rows.size();++r)for(std::size_t c=0;c<width;++c){out.cells[width-1U-c][rows.size()-1U-r]=rows[r][c];++out.reflected;}const std::size_t n=std::min(out.cells.size(),out.cells.front().size());for(std::size_t i=0;i<n;++i)out.anti_sum+=out.cells[i][out.cells.front().size()-1U-i];out.valid=true;return out;""",
        visible="""auto r=reflect_anti_diagonal({{1,2,3},{4,5,6}});if(!r.valid||r.source_rows!=2||r.source_cols!=3||r.cells!=std::vector<std::vector<int>>{{6,3},{5,2},{4,1}}||r.anti_sum!=8||r.reflected!=6)return 1;return 0;""",
        hidden="""if(reflect_anti_diagonal({{1,2},{3}}).valid)return 1;auto e=reflect_anti_diagonal({});if(!e.valid)return 1;return 0;""",
        marker="width-1U-c", prompt_terms=("anti diagonal", "reverse coordinates", "swapped dimensions", "anti sum"),
        negative_old="out.cells[width-1U-c][rows.size()-1U-r]=rows[r][c];", negative_new="out.cells[c][r]=rows[r][c];",
        negative_description="perform a main-diagonal transpose instead of anti-diagonal reflection",
    ),
    _case(
        legacy_id="transpose-seat-audit", task_id="transpose-banded-matrix",
        title="Banded Seat Matrix Transpose",
        objective="transpose compact diagonal-band storage while swapping lower and upper bandwidths",
        profile="band-coordinate reconstruction and transposed compact reindexing",
        function="transpose_banded",
        types="struct BandedMatrix{std::size_t size{};std::size_t lower{};std::size_t upper{};std::vector<int>values;};struct BandedTranspose{bool valid{};BandedMatrix matrix;std::size_t copied{};};",
        params="const BandedMatrix& matrix", return_type="BandedTranspose",
        body="""BandedTranspose out{};const std::size_t width=matrix.lower+matrix.upper+1U;if(width==0U||matrix.values.size()!=matrix.size*width)return out;out.matrix={matrix.size,matrix.upper,matrix.lower,std::vector<int>(matrix.size*width,0)};for(std::size_t r=0;r<matrix.size;++r)for(std::size_t slot=0;slot<width;++slot){const long long col=static_cast<long long>(r)+static_cast<long long>(slot)-static_cast<long long>(matrix.lower);if(col<0||col>=static_cast<long long>(matrix.size))continue;const std::size_t tr=static_cast<std::size_t>(col);const std::size_t tc=r;const std::size_t target_slot=tc+out.matrix.lower-tr;out.matrix.values[tr*width+target_slot]=matrix.values[r*width+slot];++out.copied;}out.valid=true;return out;""",
        visible="""BandedMatrix m{3,0,1,{1,2,3,4,5,0}};auto r=transpose_banded(m);if(!r.valid||r.matrix.lower!=1||r.matrix.upper!=0||r.matrix.values!=std::vector<int>{0,1,2,3,4,5}||r.copied!=5)return 1;return 0;""",
        hidden="""if(transpose_banded({2,1,0,{1}}).valid)return 1;auto e=transpose_banded({0,0,0,{}});if(!e.valid)return 1;return 0;""",
        marker="target_slot=tc+out.matrix.lower-tr", prompt_terms=("bandwidth", "diagonal storage", "swap lower upper", "compact reindex"),
        negative_old="out.matrix.values[tr*width+target_slot]=matrix.values[r*width+slot];", negative_new="out.matrix.values[tr*width+target_slot]=-matrix.values[r*width+slot];",
        negative_description="negate every copied band value during transposition",
    ),
    _case(
        legacy_id="transpose-survey-answers", task_id="transpose-common-rectangle",
        title="Common Rectangle Survey Transpose",
        objective="transpose only the common prefix rectangle of ragged survey rows and count ignored tails",
        profile="shortest-row width selection with deterministic tail accounting",
        function="transpose_common_rectangle",
        types="struct CommonTranspose{bool valid{};std::vector<std::vector<int>>cells;std::size_t ignored{};};",
        params="const std::vector<std::vector<int>>& rows", return_type="CommonTranspose",
        body="""CommonTranspose out{};if(rows.empty()){out.valid=true;return out;}std::size_t width=rows.front().size();for(const auto& row:rows)width=std::min(width,row.size());out.cells.assign(width,std::vector<int>(rows.size()));for(std::size_t r=0;r<rows.size();++r){out.ignored+=rows[r].size()-width;for(std::size_t c=0;c<width;++c)out.cells[c][r]=rows[r][c];}out.valid=true;return out;""",
        visible="""auto r=transpose_common_rectangle({{1,2,3},{4,5},{6,7,8,9}});if(!r.valid||r.cells!=std::vector<std::vector<int>>{{1,4,6},{2,5,7}}||r.ignored!=3)return 1;return 0;""",
        hidden="""auto z=transpose_common_rectangle({{1},{}});if(!z.valid||!z.cells.empty()||z.ignored!=1)return 1;auto e=transpose_common_rectangle({});if(!e.valid)return 1;return 0;""",
        marker="width=std::min(width,row.size())", prompt_terms=("common rectangle", "shortest row", "ignored tails", "ragged"),
        negative_old="out.ignored+=rows[r].size()-width;", negative_new="out.ignored+=0U;",
        negative_description="discard the required ignored-tail count",
    ),
    _case(
        legacy_id="transpose-training-load", task_id="transpose-block-sparse",
        title="Block-Sparse Training Transpose",
        objective="transpose sparse block coordinates and transpose each dense block internally",
        profile="two-level block-coordinate and in-block transpose",
        function="transpose_sparse_blocks",
        types="using Block=std::vector<std::vector<int>>;struct BlockEntry{int row{};int col{};Block values;};struct BlockTranspose{bool valid{};int block_rows{};int block_cols{};std::vector<BlockEntry>blocks;};",
        params="int block_rows, int block_cols, std::size_t block_size, const std::vector<BlockEntry>& blocks", return_type="BlockTranspose",
        body="""BlockTranspose out{};if(block_rows<0||block_cols<0||block_size==0U)return out;std::set<std::pair<int,int>>seen;for(const auto& entry:blocks){if(entry.row<0||entry.row>=block_rows||entry.col<0||entry.col>=block_cols||!seen.insert({entry.row,entry.col}).second||entry.values.size()!=block_size)return out;Block turned(block_size,std::vector<int>(block_size));for(std::size_t r=0;r<block_size;++r){if(entry.values[r].size()!=block_size)return BlockTranspose{};for(std::size_t c=0;c<block_size;++c)turned[c][r]=entry.values[r][c];}out.blocks.push_back({entry.col,entry.row,std::move(turned)});}std::sort(out.blocks.begin(),out.blocks.end(),[](const BlockEntry&a,const BlockEntry&b){return std::tie(a.row,a.col)<std::tie(b.row,b.col);});out.block_rows=block_cols;out.block_cols=block_rows;out.valid=true;return out;""",
        visible="""auto r=transpose_sparse_blocks(2,3,2,{{0,2,{{1,2},{3,4}}}});if(!r.valid||r.block_rows!=3||r.block_cols!=2||r.blocks[0].row!=2||r.blocks[0].col!=0||r.blocks[0].values!=Block{{1,3},{2,4}})return 1;return 0;""",
        hidden="""if(transpose_sparse_blocks(1,1,1,{{0,0,{{1}}},{0,0,{{2}}}}).valid)return 1;if(transpose_sparse_blocks(1,1,2,{{0,0,{{1},{2}}}}).valid)return 1;return 0;""",
        marker="turned[c][r]", prompt_terms=("sparse blocks", "two level", "internal transpose", "duplicate block"),
        negative_old="turned[c][r]=entry.values[r][c];", negative_new="turned[r][c]=entry.values[r][c];",
        negative_description="transpose block coordinates but leave each dense block unchanged",
    ),
    _case(
        legacy_id="transpose-weather-log", task_id="transpose-permutation-ledger",
        title="Permutation Matrix Cycle Ledger",
        objective="transpose a permutation matrix by constructing its inverse and canonical cycle ledger",
        profile="permutation validation, inverse construction, and visited-cycle decomposition",
        function="transpose_permutation",
        types="struct PermutationTranspose{bool valid{};std::vector<std::size_t>columns;std::vector<std::vector<std::size_t>>cycles;};",
        params="const std::vector<std::size_t>& columns", return_type="PermutationTranspose",
        body="""PermutationTranspose out{};const std::size_t n=columns.size();out.columns.assign(n,0U);std::vector<bool>seen(n,false);for(std::size_t r=0;r<n;++r){if(columns[r]>=n||seen[columns[r]])return PermutationTranspose{};seen[columns[r]]=true;out.columns[columns[r]]=r;}std::vector<bool>visited(n,false);for(std::size_t start=0;start<n;++start)if(!visited[start]){std::vector<std::size_t>cycle;std::size_t current=start;do{cycle.push_back(current);visited[current]=true;current=out.columns[current];}while(current!=start);out.cycles.push_back(std::move(cycle));}out.valid=true;return out;""",
        visible="""auto r=transpose_permutation({2,0,1,3});if(!r.valid||r.columns!=std::vector<std::size_t>{1,2,0,3}||r.cycles!=std::vector<std::vector<std::size_t>>{{0,1,2},{3}})return 1;return 0;""",
        hidden="""if(transpose_permutation({0,0}).valid)return 1;if(transpose_permutation({2,0}).valid)return 1;auto e=transpose_permutation({});if(!e.valid||!e.cycles.empty())return 1;return 0;""",
        marker="out.columns[columns[r]]=r", prompt_terms=("permutation matrix", "inverse", "cycle ledger", "duplicate column"),
        negative_old="out.columns[columns[r]]=r;", negative_new="out.columns[r]=columns[r];",
        negative_description="return the original permutation instead of its inverse",
    ),
)


if len(CASES) != 20:
    raise AssertionError(f"expected 20 transpose cases, got {len(CASES)}")
