"""One-to-one clean-room cases for the matrix-rotation remediation family."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RotationCase:
    legacy_id: str
    task_id: str
    title: str
    objective: str
    profile: str
    function: str
    types: str
    params: str
    return_type: str
    body: str
    visible: str
    hidden: str
    marker: str
    prompt_terms: tuple[str, ...]
    negative_old: str
    negative_new: str
    negative_description: str


def _case(**values: object) -> RotationCase:
    return RotationCase(**values)  # type: ignore[arg-type]


CASES = (
    _case(
        legacy_id="rotate-aerial-tiles",
        task_id="rotate-aerial-tiles",
        title="Aerial Tile Layer Rotation",
        objective="rotate a square survey grid in place with four-way layer cycles and report its north edge",
        profile="in-place concentric four-cycle square rotation",
        function="turn_survey_layers",
        types="using TileGrid = std::vector<std::vector<int>>; struct SurveyTurn { bool valid{}; int north_sum{}; };",
        params="TileGrid& tiles, unsigned quarter_turns",
        return_type="SurveyTurn",
        body="""SurveyTurn report{}; if (quarter_turns > 3U) return report; const std::size_t n = tiles.size(); for (const auto& row : tiles) if (row.size() != n) return report; for (unsigned turn = 0; turn < quarter_turns; ++turn) { for (std::size_t layer = 0; layer < n / 2U; ++layer) { const std::size_t last = n - 1U - layer; for (std::size_t offset = 0; offset < last - layer; ++offset) { const int top = tiles[layer][layer + offset]; tiles[layer][layer + offset] = tiles[last - offset][layer]; tiles[last - offset][layer] = tiles[last][last - offset]; tiles[last][last - offset] = tiles[layer + offset][last]; tiles[layer + offset][last] = top; } } } report.valid = true; if (!tiles.empty()) for (int value : tiles.front()) report.north_sum += value; return report;""",
        visible="""TileGrid grid{{1,2,3},{4,5,6},{7,8,9}}; auto r=turn_survey_layers(grid,1); if(!r.valid || r.north_sum!=12 || grid!=TileGrid{{7,4,1},{8,5,2},{9,6,3}}) return 1; return 0;""",
        hidden="""TileGrid g{{1,2},{3,4}}; auto r=turn_survey_layers(g,2); if(!r.valid || g!=TileGrid{{4,3},{2,1}}) return 1; TileGrid bad{{1,2},{3}}; auto copy=bad; if(turn_survey_layers(bad,1).valid || bad!=copy) return 1; if(turn_survey_layers(g,4).valid) return 1; return 0;""",
        marker="last - offset",
        prompt_terms=("in place", "concentric layers", "no partial mutation", "north edge"),
        negative_old="tiles[last - offset][layer] = tiles[last][last - offset];",
        negative_new="tiles[last - offset][layer] = tiles[layer + offset][last];",
        negative_description="break the four-way layer cycle by copying the right edge twice",
    ),
    _case(
        legacy_id="rotate-archive-shelves",
        task_id="rotate-rectangular-scan",
        title="Rectangular Archive Scan Rotation",
        objective="rotate a rectangular accession grid clockwise into swapped dimensions and retain a row-major checksum",
        profile="out-of-place rectangular coordinate remap",
        function="rotate_accession_scan",
        types="struct ScanTurn { bool valid{}; std::vector<std::vector<int>> cells; long long checksum{}; };",
        params="const std::vector<std::vector<int>>& rows",
        return_type="ScanTurn",
        body="""ScanTurn out{}; if (rows.empty()) { out.valid=true; return out; } const std::size_t width=rows.front().size(); if(width==0U) return out; for(const auto& row:rows) if(row.size()!=width) return out; out.cells.assign(width,std::vector<int>(rows.size())); for(std::size_t r=0;r<rows.size();++r) for(std::size_t c=0;c<width;++c) out.cells[c][rows.size()-1U-r]=rows[r][c]; long long weight=1; for(const auto& row:out.cells) for(int value:row) out.checksum += weight++*value; out.valid=true; return out;""",
        visible="""auto r=rotate_accession_scan({{1,2,3},{4,5,6}}); if(!r.valid || r.cells!=std::vector<std::vector<int>>{{4,1},{5,2},{6,3}} || r.checksum!=77) return 1; return 0;""",
        hidden="""if(rotate_accession_scan({{1,2},{3}}).valid) return 1; auto e=rotate_accession_scan({}); if(!e.valid || !e.cells.empty()) return 1; if(rotate_accession_scan({{}}).valid) return 1; return 0;""",
        marker="out.cells[c][rows.size()-1U-r]",
        prompt_terms=("rectangular", "swapped dimensions", "row-major checksum", "ragged"),
        negative_old="out.cells[c][rows.size()-1U-r]=rows[r][c];",
        negative_new="out.cells[c][r]=rows[r][c];",
        negative_description="transpose without reversing the destination column",
    ),
    _case(
        legacy_id="rotate-circuit-board",
        task_id="rotate-sparse-board-coordinates",
        title="Sparse Circuit Board Rotation",
        objective="rotate unique sparse component coordinates in a rectangular board and emit canonical row-major placement order",
        profile="validated sparse coordinate transform with canonical sort",
        function="rotate_sparse_board",
        types="struct Component { int row{}; int col{}; int value{}; }; struct SparseTurn { bool valid{}; int rows{}; int cols{}; std::vector<Component> parts; };",
        params="int rows, int cols, const std::vector<Component>& parts",
        return_type="SparseTurn",
        body="""SparseTurn out{}; if(rows<0 || cols<0) return out; std::set<std::pair<int,int>> seen; for(const auto& part:parts) { if(part.row<0 || part.row>=rows || part.col<0 || part.col>=cols || !seen.insert({part.row,part.col}).second) return out; out.parts.push_back({part.col,rows-1-part.row,part.value}); } std::sort(out.parts.begin(),out.parts.end(),[](const Component& a,const Component& b){return std::tie(a.row,a.col,a.value)<std::tie(b.row,b.col,b.value);}); out.rows=cols; out.cols=rows; out.valid=true; return out;""",
        visible="""auto r=rotate_sparse_board(2,3,{{0,0,7},{1,2,9}}); if(!r.valid || r.rows!=3 || r.cols!=2 || r.parts.size()!=2 || r.parts[0].row!=0 || r.parts[0].col!=1 || r.parts[1].row!=2 || r.parts[1].col!=0) return 1; return 0;""",
        hidden="""if(rotate_sparse_board(2,2,{{0,0,1},{0,0,2}}).valid) return 1; if(rotate_sparse_board(2,2,{{2,0,1}}).valid) return 1; auto e=rotate_sparse_board(0,3,{}); if(!e.valid || e.rows!=3 || e.cols!=0) return 1; return 0;""",
        marker="seen.insert",
        prompt_terms=("sparse", "unique coordinates", "row-major", "swapped bounds"),
        negative_old="out.parts.push_back({part.col,rows-1-part.row,part.value});",
        negative_new="out.parts.push_back({part.row,part.col,part.value});",
        negative_description="leave sparse coordinates unrotated",
    ),
    _case(
        legacy_id="rotate-chess-analysis",
        task_id="rotate-packed-occupancy-mask",
        title="Packed Occupancy Mask Rotation",
        objective="rotate an 8 by 8 packed occupancy mask clockwise without expanding it to a dense matrix",
        profile="direct packed-bit index permutation",
        function="rotate_occupancy_mask",
        types="struct MaskTurn { std::uint64_t bits{}; unsigned occupied{}; };",
        params="std::uint64_t bits",
        return_type="MaskTurn",
        body="""MaskTurn out{}; for(unsigned index=0;index<64U;++index) if((bits&(std::uint64_t{1}<<index))!=0U) { const unsigned row=index/8U; const unsigned col=index%8U; const unsigned target=col*8U+(7U-row); out.bits |= (std::uint64_t{1}<<target); ++out.occupied; } return out;""",
        visible="""auto r=rotate_occupancy_mask((std::uint64_t{1}<<0U)|(std::uint64_t{1}<<63U)); if(r.occupied!=2 || r.bits!=((std::uint64_t{1}<<7U)|(std::uint64_t{1}<<56U))) return 1; return 0;""",
        hidden="""auto r=rotate_occupancy_mask(0); if(r.bits!=0 || r.occupied!=0) return 1; auto one=rotate_occupancy_mask(std::uint64_t{1}<<27U); if(one.bits!=(std::uint64_t{1}<<28U)) return 1; return 0;""",
        marker="col*8U+(7U-row)",
        prompt_terms=("packed", "8 by 8", "bit index", "without expanding"),
        negative_old="const unsigned target=col*8U+(7U-row);",
        negative_new="const unsigned target=row*8U+col;",
        negative_description="copy each occupied bit to its original index",
    ),
    _case(
        legacy_id="rotate-escape-map",
        task_id="rotate-directional-vector-field",
        title="Directional Vector Field Rotation",
        objective="rotate a rectangular vector field spatially and rotate every vector component into the new frame",
        profile="spatial remap plus signed basis-vector transform",
        function="rotate_vector_field",
        types="struct VectorCell { int dx{}; int dy{}; }; struct FieldTurn { bool valid{}; std::vector<std::vector<VectorCell>> field; long long divergence_hint{}; };",
        params="const std::vector<std::vector<VectorCell>>& field",
        return_type="FieldTurn",
        body="""FieldTurn out{}; if(field.empty()){out.valid=true;return out;} const std::size_t width=field.front().size(); if(width==0U) return out; for(const auto& row:field) if(row.size()!=width) return out; out.field.assign(width,std::vector<VectorCell>(field.size())); for(std::size_t r=0;r<field.size();++r) for(std::size_t c=0;c<width;++c) { const auto v=field[r][c]; out.field[c][field.size()-1U-r]={-v.dy,v.dx}; out.divergence_hint += static_cast<long long>(c+1U)*v.dx-static_cast<long long>(r+1U)*v.dy; } out.valid=true; return out;""",
        visible="""auto r=rotate_vector_field({{{1,0},{0,1}}}); if(!r.valid || r.field.size()!=2 || r.field[0][0].dx!=0 || r.field[0][0].dy!=1 || r.field[1][0].dx!=-1 || r.field[1][0].dy!=0) return 1; return 0;""",
        hidden="""if(rotate_vector_field({{{1,2}},{{3,4},{5,6}}}).valid) return 1; auto e=rotate_vector_field({}); if(!e.valid) return 1; return 0;""",
        marker="{-v.dy,v.dx}",
        prompt_terms=("vector components", "new frame", "rectangular", "signed basis"),
        negative_old="out.field[c][field.size()-1U-r]={-v.dy,v.dx};",
        negative_new="out.field[c][field.size()-1U-r]={v.dx,v.dy};",
        negative_description="move vector cells without rotating their components",
    ),
    _case(
        legacy_id="rotate-factory-inspection",
        task_id="rotate-directional-glyph-map",
        title="Directional Glyph Map Rotation",
        objective="rotate a text map and remap arrow glyphs while preserving non-directional bytes",
        profile="rectangular byte-grid transform with symbol automaton",
        function="rotate_glyph_map",
        types="struct GlyphTurn { bool valid{}; std::vector<std::string> rows; std::size_t arrows{}; };",
        params="const std::vector<std::string>& rows",
        return_type="GlyphTurn",
        body="""GlyphTurn out{}; if(rows.empty()){out.valid=true;return out;} const std::size_t width=rows.front().size(); if(width==0U) return out; for(const auto& row:rows) if(row.size()!=width) return out; out.rows.assign(width,std::string(rows.size(),' ')); auto turn=[](char ch){if(ch=='^')return '>';if(ch=='>')return 'v';if(ch=='v')return '<';if(ch=='<')return '^';return ch;}; for(std::size_t r=0;r<rows.size();++r) for(std::size_t c=0;c<width;++c){const char ch=rows[r][c]; out.rows[c][rows.size()-1U-r]=turn(ch); if(ch=='^'||ch=='>'||ch=='v'||ch=='<') ++out.arrows;} out.valid=true; return out;""",
        visible="""auto r=rotate_glyph_map({"^.","<v"}); if(!r.valid || r.rows!=std::vector<std::string>{"^>","<."} || r.arrows!=3) return 1; return 0;""",
        hidden="""if(rotate_glyph_map({"ab","c"}).valid) return 1; auto e=rotate_glyph_map({}); if(!e.valid) return 1; if(rotate_glyph_map({""}).valid) return 1; return 0;""",
        marker="auto turn=[]",
        prompt_terms=("arrow glyphs", "non-directional bytes", "rectangular", "remap"),
        negative_old="if(ch=='^')return '>';",
        negative_new="if(ch=='^')return '^';",
        negative_description="leave north arrows unchanged after rotation",
    ),
    _case(
        legacy_id="rotate-garden-bed",
        task_id="rotate-oriented-tile-atlas",
        title="Oriented Tile Atlas Rotation",
        objective="rotate tile positions and compose each tile's intrinsic quarter-turn orientation",
        profile="object-layout permutation with modular metadata composition",
        function="rotate_tile_atlas",
        types="struct Tile { int id{}; unsigned orientation{}; }; struct AtlasTurn { bool valid{}; std::vector<std::vector<Tile>> tiles; std::vector<int> east_ids; };",
        params="const std::vector<std::vector<Tile>>& tiles, unsigned turns",
        return_type="AtlasTurn",
        body="""AtlasTurn out{}; if(turns>3U) return out; const std::size_t n=tiles.size(); for(const auto& row:tiles) if(row.size()!=n) return out; out.tiles=tiles; for(unsigned step=0;step<turns;++step){auto next=out.tiles; for(std::size_t r=0;r<n;++r) for(std::size_t c=0;c<n;++c){next[c][n-1U-r]=out.tiles[r][c]; next[c][n-1U-r].orientation=(out.tiles[r][c].orientation+1U)%4U;} out.tiles=std::move(next);} if(n>0U) for(const auto& row:out.tiles) out.east_ids.push_back(row.back().id); out.valid=true; return out;""",
        visible="""auto r=rotate_tile_atlas({{{1,0},{2,1}},{{3,2},{4,3}}},1); if(!r.valid || r.tiles[0][0].id!=3 || r.tiles[0][0].orientation!=3 || r.east_ids!=std::vector<int>{1,2}) return 1; return 0;""",
        hidden="""if(rotate_tile_atlas({{{1,0},{2,0}}},1).valid) return 1; if(rotate_tile_atlas({},4).valid) return 1; auto e=rotate_tile_atlas({},3); if(!e.valid) return 1; return 0;""",
        marker="orientation+1U",
        prompt_terms=("intrinsic orientation", "compose", "east edge", "square atlas"),
        negative_old="next[c][n-1U-r].orientation=(out.tiles[r][c].orientation+1U)%4U;",
        negative_new="next[c][n-1U-r].orientation=out.tiles[r][c].orientation;",
        negative_description="move tiles without composing their orientation",
    ),
    _case(
        legacy_id="rotate-ice-rink-drills",
        task_id="rotate-square-subwindow",
        title="Square Subwindow Rotation",
        objective="atomically rotate one selected square window inside a rectangular drill sheet",
        profile="bounded submatrix copy-back with untouched exterior",
        function="rotate_subwindow",
        types="using DrillGrid=std::vector<std::vector<int>>; struct WindowTurn { bool valid{}; long long diagonal{}; };",
        params="DrillGrid& grid, std::size_t top, std::size_t left, std::size_t size",
        return_type="WindowTurn",
        body="""WindowTurn out{}; if(grid.empty()) return out; const std::size_t width=grid.front().size(); if(width==0U) return out; for(const auto& row:grid) if(row.size()!=width) return out; if(size==0U || top>grid.size() || left>width || size>grid.size()-top || size>width-left) return out; std::vector<std::vector<int>> copy(size,std::vector<int>(size)); for(std::size_t r=0;r<size;++r) for(std::size_t c=0;c<size;++c) copy[c][size-1U-r]=grid[top+r][left+c]; for(std::size_t r=0;r<size;++r) for(std::size_t c=0;c<size;++c) grid[top+r][left+c]=copy[r][c]; for(std::size_t i=0;i<size;++i) out.diagonal+=grid[top+i][left+i]; out.valid=true; return out;""",
        visible="""DrillGrid g{{1,2,3},{4,5,6},{7,8,9}}; auto r=rotate_subwindow(g,0,1,2); if(!r.valid || g!=DrillGrid{{1,5,2},{4,6,3},{7,8,9}} || r.diagonal!=8) return 1; return 0;""",
        hidden="""DrillGrid g{{1,2},{3,4}}; auto before=g; if(rotate_subwindow(g,1,1,2).valid || g!=before) return 1; if(rotate_subwindow(g,0,0,0).valid) return 1; return 0;""",
        marker="copy[c][size-1U-r]",
        prompt_terms=("selected window", "untouched exterior", "atomic", "bounds"),
        negative_old="copy[c][size-1U-r]=grid[top+r][left+c];",
        negative_new="copy[r][c]=grid[top+r][left+c];",
        negative_description="copy the selected window without rotating it",
    ),
    _case(
        legacy_id="rotate-lab-sample-rack",
        task_id="rotate-perimeter-conveyor",
        title="Perimeter Conveyor Quarter Turn",
        objective="rotate only the perimeter positions of a rectangular rack while leaving its interior fixed",
        profile="clockwise perimeter extraction and cyclic shift",
        function="turn_perimeter",
        types="using Rack=std::vector<std::vector<int>>; struct PerimeterTurn { bool valid{}; std::vector<int> clockwise_after; };",
        params="Rack& rack",
        return_type="PerimeterTurn",
        body="""PerimeterTurn out{}; if(rack.size()<2U || rack.front().size()<2U) return out; const std::size_t rows=rack.size(), cols=rack.front().size(); for(const auto& row:rack) if(row.size()!=cols) return out; std::vector<std::pair<std::size_t,std::size_t>> pos; for(std::size_t c=0;c<cols;++c) pos.push_back({0,c}); for(std::size_t r=1;r<rows;++r) pos.push_back({r,cols-1U}); for(std::size_t c=cols-1U;c-->0U;) pos.push_back({rows-1U,c}); for(std::size_t r=rows-1U;r-->1U;) pos.push_back({r,0}); std::vector<int> values; for(auto p:pos) values.push_back(rack[p.first][p.second]); const std::size_t shift=(rows-1U); for(std::size_t i=0;i<pos.size();++i){const int value=values[(i+pos.size()-shift)%pos.size()]; rack[pos[i].first][pos[i].second]=value; out.clockwise_after.push_back(value);} out.valid=true; return out;""",
        visible="""Rack g{{1,2,3},{4,5,6},{7,8,9}}; auto r=turn_perimeter(g); if(!r.valid || g!=Rack{{7,4,1},{8,5,2},{9,6,3}} || r.clockwise_after.size()!=8) return 1; return 0;""",
        hidden="""Rack g{{1,2,3},{4,5,6}}; auto r=turn_perimeter(g); if(!r.valid || g!=Rack{{4,1,2},{5,6,3}}) return 1; Rack bad{{1,2},{3}}; auto before=bad; if(turn_perimeter(bad).valid || bad!=before) return 1; return 0;""",
        marker="const std::size_t shift=(rows-1U)",
        prompt_terms=("perimeter only", "interior fixed", "clockwise order", "cyclic shift"),
        negative_old="const std::size_t shift=(rows-1U);",
        negative_new="const std::size_t shift=0U;",
        negative_description="leave the perimeter cycle unshifted",
    ),
    _case(
        legacy_id="rotate-museum-floorplan",
        task_id="rotate-voxel-slice-stack",
        title="Voxel Slice Stack Rotation",
        objective="rotate each rectangular depth slice and reverse depth order for a camera-frame quarter turn",
        profile="three-dimensional slice remap with depth reversal",
        function="rotate_slice_stack",
        types="using Slice=std::vector<std::vector<int>>; struct StackTurn { bool valid{}; std::vector<Slice> slices; long long front_sum{}; };",
        params="const std::vector<Slice>& slices",
        return_type="StackTurn",
        body="""StackTurn out{}; if(slices.empty()){out.valid=true;return out;} const std::size_t rows=slices.front().size(); if(rows==0U) return out; const std::size_t cols=slices.front().front().size(); if(cols==0U) return out; for(const auto& slice:slices){if(slice.size()!=rows)return out;for(const auto& row:slice)if(row.size()!=cols)return out;} out.slices.resize(slices.size(),Slice(cols,std::vector<int>(rows))); for(std::size_t z=0;z<slices.size();++z) for(std::size_t r=0;r<rows;++r) for(std::size_t c=0;c<cols;++c) out.slices[slices.size()-1U-z][c][rows-1U-r]=slices[z][r][c]; for(const auto& row:out.slices.front()) for(int value:row) out.front_sum+=value; out.valid=true; return out;""",
        visible="""auto r=rotate_slice_stack({{{1,2},{3,4}},{{5,6},{7,8}}}); if(!r.valid || r.slices[0]!=Slice{{7,5},{8,6}} || r.slices[1]!=Slice{{3,1},{4,2}} || r.front_sum!=26) return 1; return 0;""",
        hidden="""if(rotate_slice_stack({{{1,2}},{{3}}}).valid) return 1; auto e=rotate_slice_stack({}); if(!e.valid) return 1; return 0;""",
        marker="slices.size()-1U-z",
        prompt_terms=("depth slices", "reverse depth", "rectangular", "front sum"),
        negative_old="out.slices[slices.size()-1U-z][c][rows-1U-r]=slices[z][r][c];",
        negative_new="out.slices[z][c][rows-1U-r]=slices[z][r][c];",
        negative_description="rotate slices without reversing depth order",
    ),
    _case(
        legacy_id="rotate-orchard-spray",
        task_id="rotate-row-run-encoding",
        title="Row Run Encoding Rotation",
        objective="rotate a row-run encoded raster and emit canonical runs for the rotated rows",
        profile="RLE validation, coordinate emission, and canonical recompression",
        function="rotate_row_runs",
        types="struct Run { int value{}; std::size_t count{}; }; using EncodedRows=std::vector<std::vector<Run>>; struct RunTurn { bool valid{}; std::size_t rows{}; std::size_t cols{}; EncodedRows encoded; };",
        params="std::size_t rows, std::size_t cols, const EncodedRows& encoded",
        return_type="RunTurn",
        body="""RunTurn out{}; if(encoded.size()!=rows) return out; std::vector<std::vector<int>> dense(rows); for(std::size_t r=0;r<rows;++r){for(const auto& run:encoded[r]){if(run.count==0U || dense[r].size()>cols-run.count)return out;dense[r].insert(dense[r].end(),run.count,run.value);}if(dense[r].size()!=cols)return out;} out.rows=cols;out.cols=rows;out.encoded.resize(cols); for(std::size_t nr=0;nr<cols;++nr) for(std::size_t nc=0;nc<rows;++nc){const int value=dense[rows-1U-nc][nr];auto& line=out.encoded[nr];if(!line.empty()&&line.back().value==value)++line.back().count;else line.push_back({value,1});} out.valid=true; return out;""",
        visible="""auto r=rotate_row_runs(2,3,{{{1,2},{2,1}},{{3,3}}}); if(!r.valid || r.rows!=3 || r.cols!=2 || r.encoded[0].size()!=2 || r.encoded[2][0].value!=3 || r.encoded[2][1].value!=2) return 1; return 0;""",
        hidden="""if(rotate_row_runs(1,2,{{{1,0},{2,2}}}).valid) return 1; if(rotate_row_runs(1,3,{{{1,2}}}).valid) return 1; auto e=rotate_row_runs(0,0,{}); if(!e.valid) return 1; return 0;""",
        marker="line.back().value==value",
        prompt_terms=("run encoded", "canonical runs", "zero count", "row widths"),
        negative_old="const int value=dense[rows-1U-nc][nr];",
        negative_new="const int value=dense[nc][nr];",
        negative_description="transpose decoded samples without reversing source rows",
    ),
    _case(
        legacy_id="rotate-puzzle-tile",
        task_id="rotate-rectangular-regions",
        title="Rectangular Region Rotation",
        objective="rotate half-open labeled rectangles within a canvas and preserve canonical label order",
        profile="half-open rectangle bound transform",
        function="rotate_regions",
        types="struct Region { int top{}; int left{}; int bottom{}; int right{}; std::string label; }; struct RegionTurn { bool valid{}; int rows{}; int cols{}; std::vector<Region> regions; };",
        params="int rows, int cols, const std::vector<Region>& regions",
        return_type="RegionTurn",
        body="""RegionTurn out{}; if(rows<0||cols<0)return out; for(const auto& region:regions){if(region.top<0||region.left<0||region.top>=region.bottom||region.left>=region.right||region.bottom>rows||region.right>cols)return out; out.regions.push_back({region.left,rows-region.bottom,region.right,rows-region.top,region.label});} std::sort(out.regions.begin(),out.regions.end(),[](const Region& a,const Region& b){return std::tie(a.label,a.top,a.left)<std::tie(b.label,b.top,b.left);});out.rows=cols;out.cols=rows;out.valid=true;return out;""",
        visible="""auto r=rotate_regions(4,6,{{1,2,3,5,"B"},{0,0,1,2,"A"}}); if(!r.valid || r.rows!=6 || r.cols!=4 || r.regions[0].top!=0 || r.regions[0].left!=3 || r.regions[1].top!=2 || r.regions[1].right!=3) return 1; return 0;""",
        hidden="""if(rotate_regions(2,2,{{1,0,1,2,"x"}}).valid) return 1; auto e=rotate_regions(0,0,{}); if(!e.valid) return 1; return 0;""",
        marker="rows-region.bottom",
        prompt_terms=("half-open", "rectangles", "swapped canvas", "label order"),
        negative_old="out.regions.push_back({region.left,rows-region.bottom,region.right,rows-region.top,region.label});",
        negative_new="out.regions.push_back(region);",
        negative_description="return original rectangle bounds",
    ),
    _case(
        legacy_id="rotate-quilt-block",
        task_id="rotate-polyline-waypoints",
        title="Polyline Waypoint Rotation",
        objective="rotate signed waypoints around the origin and recompute Manhattan segment length",
        profile="signed Cartesian point transform with polyline metric",
        function="rotate_waypoints",
        types="struct Point { long long x{}; long long y{}; }; struct PathTurn { bool valid{}; std::vector<Point> points; unsigned long long manhattan{}; };",
        params="const std::vector<Point>& points, unsigned turns",
        return_type="PathTurn",
        body="""PathTurn out{}; if(turns>3U)return out;out.points=points;for(auto& point:out.points)for(unsigned step=0;step<turns;++step){const long long old_x=point.x;point.x=point.y;point.y=-old_x;}for(std::size_t i=1;i<out.points.size();++i){auto distance=[](long long a,long long b){return static_cast<unsigned long long>(a>=b?a-b:b-a);};out.manhattan+=distance(out.points[i-1U].x,out.points[i].x)+distance(out.points[i-1U].y,out.points[i].y);}out.valid=true;return out;""",
        visible="""auto r=rotate_waypoints({{1,2},{4,6}},1); if(!r.valid || r.points[0].x!=2 || r.points[0].y!=-1 || r.points[1].x!=6 || r.points[1].y!=-4 || r.manhattan!=7) return 1; return 0;""",
        hidden="""if(rotate_waypoints({},4).valid) return 1; auto r=rotate_waypoints({{-2,3}},3); if(!r.valid || r.points[0].x!=-3 || r.points[0].y!=-2 || r.manhattan!=0) return 1; return 0;""",
        marker="point.y=-old_x",
        prompt_terms=("signed Cartesian", "origin", "Manhattan", "quarter turns"),
        negative_old="point.y=-old_x;",
        negative_new="point.y=old_x;",
        negative_description="reflect instead of clockwise rotating signed points",
    ),
    _case(
        legacy_id="rotate-radar-sector",
        task_id="rotate-lazy-grid-view",
        title="Lazy Rotated Grid View",
        objective="compose rotations as view state and answer coordinates without materializing a rotated grid",
        profile="lazy orientation state with inverse query mapping",
        function="make_rotated_view",
        types="struct ViewQuery { std::size_t row{}; std::size_t col{}; }; struct LazyView { bool valid{}; std::size_t rows{}; std::size_t cols{}; std::vector<int> values; };",
        params="const std::vector<std::vector<int>>& source, unsigned turns, const std::vector<ViewQuery>& queries",
        return_type="LazyView",
        body="""LazyView out{};if(turns>3U)return out;const std::size_t source_rows=source.size();const std::size_t source_cols=source.empty()?0U:source.front().size();for(const auto& row:source)if(row.size()!=source_cols)return out;out.rows=turns%2U==0U?source_rows:source_cols;out.cols=turns%2U==0U?source_cols:source_rows;for(const auto& query:queries){if(query.row>=out.rows||query.col>=out.cols)return LazyView{};std::size_t r=query.row,c=query.col,current_rows=out.rows,current_cols=out.cols;for(unsigned step=0;step<turns;++step){const std::size_t previous_rows=current_cols;const std::size_t previous_cols=current_rows;const std::size_t next_r=previous_rows-1U-c;c=r;r=next_r;current_rows=previous_rows;current_cols=previous_cols;}out.values.push_back(source[r][c]);}out.valid=true;return out;""",
        visible="""auto v=make_rotated_view({{1,2,3},{4,5,6}},1,{{0,0},{2,1}}); if(!v.valid || v.rows!=3 || v.cols!=2 || v.values!=std::vector<int>{4,3}) return 1; return 0;""",
        hidden="""auto v=make_rotated_view({{1,2},{3,4}},2,{{0,0},{1,1}}); if(!v.valid || v.values!=std::vector<int>{4,1}) return 1; if(make_rotated_view({{1,2}},1,{{2,0}}).valid) return 1; if(make_rotated_view({{1},{2,3}},1,{}).valid) return 1; return 0;""",
        marker="previous_rows-1U-c",
        prompt_terms=("lazy", "without materializing", "inverse mapping", "query bounds"),
        negative_old="const std::size_t next_r=previous_rows-1U-c;",
        negative_new="const std::size_t next_r=c;",
        negative_description="query the transposed rather than rotated source coordinate",
    ),
    _case(
        legacy_id="rotate-satellite-camera",
        task_id="compose-orientation-commands",
        title="Orientation Command Composition",
        objective="compose quarter turns and reflections into one dihedral orientation and map coordinates through it",
        profile="dihedral transform composition state machine",
        function="compose_orientation",
        types="struct Orientation { bool valid{}; unsigned turns{}; bool mirrored{}; int row{}; int col{}; };",
        params="int size, int row, int col, const std::string& commands",
        return_type="Orientation",
        body="""Orientation out{};if(size<=0||row<0||col<0||row>=size||col>=size)return out;int r=row,c=col;for(char command:commands){if(command=='R'){const int old_r=r;r=c;c=size-1-old_r;out.turns=(out.turns+1U)%4U;}else if(command=='M'){c=size-1-c;out.mirrored=!out.mirrored;}else return Orientation{};}out.row=r;out.col=c;out.valid=true;return out;""",
        visible="""auto r=compose_orientation(5,1,2,"RMR"); if(!r.valid || r.row!=1 || r.col!=2 || r.turns!=2 || !r.mirrored) return 1; return 0;""",
        hidden="""if(compose_orientation(3,0,0,"RX").valid) return 1; auto r=compose_orientation(3,0,0,"RRRR"); if(!r.valid || r.row!=0 || r.col!=0 || r.turns!=0) return 1; return 0;""",
        marker="out.mirrored=!out.mirrored",
        prompt_terms=("compose", "reflection", "dihedral", "command order"),
        negative_old="c=size-1-c;out.mirrored=!out.mirrored;",
        negative_new="out.mirrored=!out.mirrored;",
        negative_description="toggle reflection metadata without reflecting the coordinate",
    ),
    _case(
        legacy_id="rotate-solar-panel",
        task_id="rotate-stencil-kernel",
        title="Directional Stencil Kernel Rotation",
        objective="rotate an odd square convolution kernel and its signed anchor offset",
        profile="numeric kernel permutation with anchor transform",
        function="rotate_stencil",
        types="struct StencilTurn { bool valid{}; std::vector<std::vector<int>> weights; int anchor_row{}; int anchor_col{}; long long moment{}; };",
        params="const std::vector<std::vector<int>>& weights, int anchor_row, int anchor_col",
        return_type="StencilTurn",
        body="""StencilTurn out{};const std::size_t n=weights.size();if(n==0U||n%2U==0U)return out;for(const auto& row:weights)if(row.size()!=n)return out;if(anchor_row<0||anchor_col<0||anchor_row>=static_cast<int>(n)||anchor_col>=static_cast<int>(n))return out;out.weights.assign(n,std::vector<int>(n));for(std::size_t r=0;r<n;++r)for(std::size_t c=0;c<n;++c)out.weights[c][n-1U-r]=weights[r][c];out.anchor_row=anchor_col;out.anchor_col=static_cast<int>(n)-1-anchor_row;for(std::size_t r=0;r<n;++r)for(std::size_t c=0;c<n;++c)out.moment+=static_cast<long long>(out.weights[r][c])*(static_cast<long long>(r)-out.anchor_row);out.valid=true;return out;""",
        visible="""auto r=rotate_stencil({{1,2,3},{4,5,6},{7,8,9}},0,1); if(!r.valid || r.weights!=std::vector<std::vector<int>>{{7,4,1},{8,5,2},{9,6,3}} || r.anchor_row!=1 || r.anchor_col!=2) return 1; return 0;""",
        hidden="""if(rotate_stencil({{1,2},{3,4}},0,0).valid) return 1; if(rotate_stencil({{1}},1,0).valid) return 1; return 0;""",
        marker="out.anchor_col=static_cast<int>(n)-1-anchor_row",
        prompt_terms=("odd square", "anchor", "moment", "kernel"),
        negative_old="out.anchor_col=static_cast<int>(n)-1-anchor_row;",
        negative_new="out.anchor_col=anchor_row;",
        negative_description="rotate weights but not the anchor column",
    ),
    _case(
        legacy_id="rotate-storm-grid",
        task_id="rotate-embedded-route-graph",
        title="Embedded Route Graph Rotation",
        objective="rotate unique embedded graph nodes and headings while preserving indexed edges",
        profile="graph identity validation plus coordinate and heading transform",
        function="rotate_route_graph",
        types="struct RouteNode { int id{}; int row{}; int col{}; unsigned heading{}; }; struct Edge { int from{}; int to{}; }; struct GraphTurn { bool valid{}; int rows{}; int cols{}; std::vector<RouteNode> nodes; std::vector<Edge> edges; };",
        params="int rows, int cols, const std::vector<RouteNode>& nodes, const std::vector<Edge>& edges",
        return_type="GraphTurn",
        body="""GraphTurn out{};if(rows<0||cols<0)return out;std::set<int> ids;for(const auto& node:nodes){if(node.row<0||node.row>=rows||node.col<0||node.col>=cols||node.heading>3U||!ids.insert(node.id).second)return out;out.nodes.push_back({node.id,node.col,rows-1-node.row,(node.heading+1U)%4U});}for(const auto& edge:edges)if(ids.count(edge.from)==0U||ids.count(edge.to)==0U)return GraphTurn{};else out.edges.push_back(edge);std::sort(out.nodes.begin(),out.nodes.end(),[](const RouteNode&a,const RouteNode&b){return a.id<b.id;});out.rows=cols;out.cols=rows;out.valid=true;return out;""",
        visible="""auto r=rotate_route_graph(2,3,{{2,0,1,0},{1,1,2,3}},{{2,1}}); if(!r.valid || r.nodes[0].id!=1 || r.nodes[0].row!=2 || r.nodes[0].col!=0 || r.nodes[0].heading!=0 || r.edges.size()!=1) return 1; return 0;""",
        hidden="""if(rotate_route_graph(2,2,{{1,0,0,0}},{{1,2}}).valid) return 1; if(rotate_route_graph(2,2,{{1,0,0,0},{1,1,1,1}},{}).valid) return 1; return 0;""",
        marker="ids.count(edge.from)",
        prompt_terms=("graph node IDs", "headings", "edge endpoints", "canonical ID order"),
        negative_old="(node.heading+1U)%4U",
        negative_new="node.heading",
        negative_description="rotate node coordinates without rotating headings",
    ),
    _case(
        legacy_id="rotate-tactical-map",
        task_id="rotate-planar-channels",
        title="Planar Image Channel Rotation",
        objective="rotate equally shaped planar channels and compute a per-channel weighted checksum",
        profile="multi-plane shape validation and synchronized remap",
        function="rotate_channels",
        types="using Plane=std::vector<std::vector<int>>; struct ChannelTurn { bool valid{}; std::vector<Plane> planes; std::vector<long long> checksums; };",
        params="const std::vector<Plane>& planes",
        return_type="ChannelTurn",
        body="""ChannelTurn out{};if(planes.empty()){out.valid=true;return out;}const std::size_t rows=planes.front().size();if(rows==0U)return out;const std::size_t cols=planes.front().front().size();if(cols==0U)return out;for(const auto& plane:planes){if(plane.size()!=rows)return out;for(const auto& row:plane)if(row.size()!=cols)return out;}out.planes.assign(planes.size(),Plane(cols,std::vector<int>(rows)));out.checksums.assign(planes.size(),0);for(std::size_t p=0;p<planes.size();++p)for(std::size_t r=0;r<rows;++r)for(std::size_t c=0;c<cols;++c){out.planes[p][c][rows-1U-r]=planes[p][r][c];out.checksums[p]+=static_cast<long long>(p+1U)*planes[p][r][c];}out.valid=true;return out;""",
        visible="""auto r=rotate_channels({{{1,2},{3,4}},{{5,6},{7,8}}}); if(!r.valid || r.planes[0]!=Plane{{3,1},{4,2}} || r.planes[1]!=Plane{{7,5},{8,6}} || r.checksums!=std::vector<long long>{10,52}) return 1; return 0;""",
        hidden="""if(rotate_channels({{{1,2}},{{3},{4}}}).valid) return 1; auto e=rotate_channels({}); if(!e.valid) return 1; return 0;""",
        marker="out.planes.assign",
        prompt_terms=("planar channels", "equal shape", "synchronized", "per-channel checksum"),
        negative_old="out.planes[p][c][rows-1U-r]=planes[p][r][c];",
        negative_new="out.planes[p][r][c]=planes[p][r][c];",
        negative_description="leave each channel plane unrotated",
    ),
    _case(
        legacy_id="rotate-theater-lights",
        task_id="rotate-block-sparse-layout",
        title="Block Sparse Layout Rotation",
        objective="rotate square sparse blocks across a block grid and rotate each dense block internally",
        profile="two-level sparse block permutation and dense micro-rotation",
        function="rotate_block_layout",
        types="using Block=std::vector<std::vector<int>>; struct BlockEntry { int block_row{}; int block_col{}; Block values; }; struct BlockTurn { bool valid{}; std::vector<BlockEntry> blocks; };",
        params="int block_rows, int block_cols, std::size_t block_size, const std::vector<BlockEntry>& blocks",
        return_type="BlockTurn",
        body="""BlockTurn out{};if(block_rows<0||block_cols<0||block_size==0U)return out;std::set<std::pair<int,int>> seen;for(const auto& entry:blocks){if(entry.block_row<0||entry.block_row>=block_rows||entry.block_col<0||entry.block_col>=block_cols||!seen.insert({entry.block_row,entry.block_col}).second||entry.values.size()!=block_size)return out;Block turned(block_size,std::vector<int>(block_size));for(std::size_t r=0;r<block_size;++r){if(entry.values[r].size()!=block_size)return BlockTurn{};for(std::size_t c=0;c<block_size;++c)turned[c][block_size-1U-r]=entry.values[r][c];}out.blocks.push_back({entry.block_col,block_rows-1-entry.block_row,std::move(turned)});}std::sort(out.blocks.begin(),out.blocks.end(),[](const BlockEntry&a,const BlockEntry&b){return std::tie(a.block_row,a.block_col)<std::tie(b.block_row,b.block_col);});out.valid=true;return out;""",
        visible="""auto r=rotate_block_layout(2,3,2,{{0,1,{{1,2},{3,4}}}}); if(!r.valid || r.blocks[0].block_row!=1 || r.blocks[0].block_col!=1 || r.blocks[0].values!=Block{{3,1},{4,2}}) return 1; return 0;""",
        hidden="""if(rotate_block_layout(2,2,1,{{0,0,{{1}}},{0,0,{{2}}}}).valid) return 1; if(rotate_block_layout(1,1,2,{{0,0,{{1},{2}}}}).valid) return 1; return 0;""",
        marker="Block turned",
        prompt_terms=("sparse blocks", "internal rotation", "two-level", "duplicate block"),
        negative_old="turned[c][block_size-1U-r]=entry.values[r][c];",
        negative_new="turned[r][c]=entry.values[r][c];",
        negative_description="move block coordinates but leave dense blocks unrotated",
    ),
    _case(
        legacy_id="rotate-warehouse-pallets",
        task_id="rotate-quadtree-leaf-bounds",
        title="Quadtree Leaf Bound Rotation",
        objective="rotate aligned quadtree leaf squares inside a power-of-two canvas and retain Morton order",
        profile="power-of-two alignment validation and Morton-key ordering",
        function="rotate_quadtree_leaves",
        types="struct Leaf { int top{}; int left{}; int size{}; int value{}; }; struct LeafTurn { bool valid{}; std::vector<Leaf> leaves; std::vector<unsigned long long> morton; };",
        params="int canvas_size, const std::vector<Leaf>& leaves",
        return_type="LeafTurn",
        body="""LeafTurn out{};if(canvas_size<=0||(canvas_size&(canvas_size-1))!=0)return out;auto spread=[](unsigned value){unsigned long long result=0;for(unsigned bit=0;bit<32U;++bit)result|=static_cast<unsigned long long>((value>>bit)&1U)<<(2U*bit);return result;};for(const auto& leaf:leaves){if(leaf.size<=0||(leaf.size&(leaf.size-1))!=0||leaf.top<0||leaf.left<0||leaf.top+leaf.size>canvas_size||leaf.left+leaf.size>canvas_size||leaf.top%leaf.size!=0||leaf.left%leaf.size!=0)return out;Leaf turned{leaf.left,canvas_size-leaf.top-leaf.size,leaf.size,leaf.value};out.leaves.push_back(turned);out.morton.push_back(spread(static_cast<unsigned>(turned.left))|(spread(static_cast<unsigned>(turned.top))<<1U));}std::vector<std::size_t> order(out.leaves.size());std::iota(order.begin(),order.end(),0U);std::sort(order.begin(),order.end(),[&](std::size_t a,std::size_t b){return out.morton[a]<out.morton[b];});std::vector<Leaf> sorted;std::vector<unsigned long long> keys;for(auto i:order){sorted.push_back(out.leaves[i]);keys.push_back(out.morton[i]);}out.leaves=std::move(sorted);out.morton=std::move(keys);out.valid=true;return out;""",
        visible="""auto r=rotate_quadtree_leaves(8,{{0,0,4,1},{4,4,2,2}}); if(!r.valid || r.leaves.size()!=2 || r.leaves[0].top!=0 || r.leaves[0].left!=4 || r.leaves[1].top!=4 || r.leaves[1].left!=2) return 1; return 0;""",
        hidden="""if(rotate_quadtree_leaves(6,{}).valid) return 1; if(rotate_quadtree_leaves(8,{{1,0,2,1}}).valid) return 1; auto e=rotate_quadtree_leaves(8,{}); if(!e.valid) return 1; return 0;""",
        marker="spread(static_cast<unsigned>",
        prompt_terms=("power of two", "aligned leaves", "Morton", "half-open bounds"),
        negative_old="Leaf turned{leaf.left,canvas_size-leaf.top-leaf.size,leaf.size,leaf.value};",
        negative_new="Leaf turned{leaf.top,leaf.left,leaf.size,leaf.value};",
        negative_description="retain original quadtree leaf bounds",
    ),
)


if len(CASES) != 20:
    raise AssertionError(f"expected 20 matrix-rotation cases, got {len(CASES)}")
