"""One-to-one clean-room cases for maze-to-graph family remediation."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MazeGraphCase:
    legacy_id: str
    task_id: str
    title: str
    objective: str
    profile: str
    function: str
    types: str
    params: str
    return_type: str
    body: str
    visible: str
    hidden: str
    marker: str
    prompt_terms: tuple[str, ...]
    negative_old: str
    negative_new: str
    negative_description: str


def _case(**values: object) -> MazeGraphCase:
    return MazeGraphCase(**values)  # type: ignore[arg-type]


CASES = (
    _case(
        legacy_id="graph-mine-tunnels", task_id="tunnel-junction-contraction",
        title="Tunnel Junction Contraction",
        objective="contract maximal degree-two tunnel corridors into weighted edges between junction or terminal cells",
        profile="degree-two corridor contraction with canonical undirected weighted edges",
        function="contract_tunnels",
        types="struct TunnelEdge { int from{}; int to{}; int length{}; }; struct TunnelGraph { bool valid{}; std::vector<std::pair<int,int>> vertices; std::vector<TunnelEdge> edges; };",
        params="const std::vector<std::string>& rows", return_type="TunnelGraph",
        body="""TunnelGraph out{}; if(rows.empty()){out.valid=true;return out;} const int h=static_cast<int>(rows.size()),w=static_cast<int>(rows.front().size()); if(w==0)return out; for(const auto& row:rows)if(static_cast<int>(row.size())!=w)return out; auto open=[&](int r,int c){return r>=0&&r<h&&c>=0&&c<w&&rows[r][c]=='.';}; const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0}; std::vector<int> degree(static_cast<std::size_t>(h*w)); for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(open(r,c))for(int d=0;d<4;++d)degree[static_cast<std::size_t>(r*w+c)]+=open(r+dr[d],c+dc[d])?1:0; std::vector<int> id(static_cast<std::size_t>(h*w),-1); for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(open(r,c)&&degree[static_cast<std::size_t>(r*w+c)]!=2){id[static_cast<std::size_t>(r*w+c)]=static_cast<int>(out.vertices.size());out.vertices.push_back({r,c});} std::set<std::pair<int,int>> used; for(std::size_t v=0;v<out.vertices.size();++v){auto [r,c]=out.vertices[v];for(int d=0;d<4;++d){int pr=r,pc=c,nr=r+dr[d],nc=c+dc[d],len=1;if(!open(nr,nc))continue;while(id[static_cast<std::size_t>(nr*w+nc)]<0){int xr=-1,xc=-1;for(int k=0;k<4;++k){int ar=nr+dr[k],ac=nc+dc[k];if(open(ar,ac)&&(ar!=pr||ac!=pc)){xr=ar;xc=ac;break;}}pr=nr;pc=nc;nr=xr;nc=xc;++len;}int to=id[static_cast<std::size_t>(nr*w+nc)];std::pair<int,int> key{std::min(static_cast<int>(v),to),std::max(static_cast<int>(v),to)};if(used.insert(key).second)out.edges.push_back({key.first,key.second,len});}} std::sort(out.edges.begin(),out.edges.end(),[](const TunnelEdge&a,const TunnelEdge&b){return std::tie(a.from,a.to,a.length)<std::tie(b.from,b.to,b.length);}); out.valid=true; return out;""",
        visible="""auto g=contract_tunnels({"...","##.","..."}); if(!g.valid||g.vertices.size()!=2||g.edges.size()!=1||g.edges[0].length!=6)return 1;return 0;""",
        hidden="""auto e=contract_tunnels({});if(!e.valid||!e.vertices.empty())return 1;if(contract_tunnels({"..","."}).valid)return 1;auto j=contract_tunnels({"#.#","...","#.#"});if(!j.valid||j.vertices.size()!=5||j.edges.size()!=4)return 1;return 0;""",
        marker="degree[static_cast<std::size_t>(r*w+c)]!=2",
        prompt_terms=("degree-two corridor", "weighted contracted edge", "row-major terminal", "canonical undirected order"),
        negative_old="degree[static_cast<std::size_t>(r*w+c)]!=2",
        negative_new="degree[static_cast<std::size_t>(r*w+c)]>=0",
        negative_description="retain every walkable cell instead of contracting degree-two corridors",
    ),
    _case(
        legacy_id="graph-museum-rooms", task_id="gallery-door-region-graph", title="Gallery Door Region Graph",
        objective="label open gallery regions and connect distinct regions through door cells",
        profile="floor-region flood labelling followed by typed door incidence construction",
        function="build_gallery_graph",
        types="struct GalleryDoor { int first{}; int second{}; int row{}; int col{}; }; struct GalleryGraph { bool valid{}; int room_count{}; std::vector<int> room_area; std::vector<GalleryDoor> doors; };",
        params="const std::vector<std::string>& plan", return_type="GalleryGraph",
        body="""GalleryGraph out{};if(plan.empty()){out.valid=true;return out;}const int h=static_cast<int>(plan.size()),w=static_cast<int>(plan.front().size());if(w==0)return out;for(const auto&r:plan)if(static_cast<int>(r.size())!=w)return out;std::vector<int> label(static_cast<std::size_t>(h*w),-1);const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};for(int sr=0;sr<h;++sr)for(int sc=0;sc<w;++sc)if(plan[sr][sc]=='.'&&label[static_cast<std::size_t>(sr*w+sc)]<0){int id=out.room_count++;int area=0;std::queue<std::pair<int,int>>q;q.push({sr,sc});label[static_cast<std::size_t>(sr*w+sc)]=id;while(!q.empty()){auto [r,c]=q.front();q.pop();++area;for(int d=0;d<4;++d){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<h&&nc>=0&&nc<w&&plan[nr][nc]=='.'&&label[static_cast<std::size_t>(nr*w+nc)]<0){label[static_cast<std::size_t>(nr*w+nc)]=id;q.push({nr,nc});}}}out.room_area.push_back(area);}for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(plan[r][c]=='D'){std::set<int> touching;for(int d=0;d<4;++d){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<h&&nc>=0&&nc<w){int x=label[static_cast<std::size_t>(nr*w+nc)];if(x>=0)touching.insert(x);}}if(touching.size()!=2)return GalleryGraph{};auto it=touching.begin();int a=*it++,b=*it;out.doors.push_back({a,b,r,c});}else if(plan[r][c]!='.'&&plan[r][c]!='#')return GalleryGraph{};out.valid=true;return out;""",
        visible="""auto g=build_gallery_graph({"..#..","..D..","..#.."});if(!g.valid||g.room_count!=2||g.room_area!=std::vector<int>{6,6}||g.doors.size()!=1)return 1;if(build_gallery_graph({"D."}).valid)return 1;return 0;""",
        hidden="""auto e=build_gallery_graph({});if(!e.valid)return 1;if(build_gallery_graph({".X"}).valid)return 1;return 0;""",
        marker="touching.size()!=2", prompt_terms=("floor regions", "door incidence", "exactly two rooms", "row-major labels"),
        negative_old="if(touching.size()!=2)return GalleryGraph{};", negative_new="if(touching.empty())return GalleryGraph{};",
        negative_description="accept a door that does not separate exactly two distinct rooms",
    ),
    _case(
        legacy_id="graph-warehouse-aisles", task_id="aisle-segment-intersection-graph", title="Aisle Segment Intersection Graph",
        objective="represent maximal horizontal and vertical aisle runs as bipartite vertices joined at crossings",
        profile="maximal run extraction with crossing-induced bipartite incidence",
        function="index_aisle_segments",
        types="struct AisleCrossing { int horizontal{}; int vertical{}; int row{}; int col{}; }; struct AisleGraph { bool valid{}; int horizontal_count{}; int vertical_count{}; std::vector<AisleCrossing> crossings; };",
        params="const std::vector<std::string>& map", return_type="AisleGraph",
        body="""AisleGraph out{};if(map.empty()){out.valid=true;return out;}const int h=static_cast<int>(map.size()),w=static_cast<int>(map.front().size());if(w==0)return out;for(const auto&r:map)if(static_cast<int>(r.size())!=w)return out;std::vector<int> hs(static_cast<std::size_t>(h*w),-1),vs(static_cast<std::size_t>(h*w),-1);auto hp=[](char x){return x=='-'||x=='+';};auto vp=[](char x){return x=='|'||x=='+';};for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(hp(map[r][c])&&(c==0||!hp(map[r][c-1]))){int id=out.horizontal_count++;for(int x=c;x<w&&hp(map[r][x]);++x)hs[static_cast<std::size_t>(r*w+x)]=id;}for(int c=0;c<w;++c)for(int r=0;r<h;++r)if(vp(map[r][c])&&(r==0||!vp(map[r-1][c]))){int id=out.vertical_count++;for(int x=r;x<h&&vp(map[x][c]);++x)vs[static_cast<std::size_t>(x*w+c)]=id;}for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(map[r][c]=='+')out.crossings.push_back({hs[static_cast<std::size_t>(r*w+c)],vs[static_cast<std::size_t>(r*w+c)],r,c});else if(map[r][c]!='#'&&map[r][c]!='-'&&map[r][c]!='|')return AisleGraph{};out.valid=true;return out;""",
        visible="""auto g=index_aisle_segments({"#+#","-+-","#+#"});if(!g.valid||g.horizontal_count!=3||g.vertical_count!=1||g.crossings.size()!=3)return 1;return 0;""",
        hidden="""auto e=index_aisle_segments({});if(!e.valid)return 1;if(index_aisle_segments({"+","##"}).valid)return 1;auto g=index_aisle_segments({"--#--"});if(!g.valid||g.horizontal_count!=2||g.vertical_count!=0)return 1;return 0;""",
        marker="out.horizontal_count++", prompt_terms=("maximal horizontal run", "maximal vertical run", "bipartite", "crossing incidence"),
        negative_old="if(map[r][c]=='+')out.crossings.push_back", negative_new="if(map[r][c]=='#')out.crossings.push_back",
        negative_description="create incidence at walls instead of aisle crossings",
    ),
    _case(
        legacy_id="graph-cave-survey", task_id="cave-bridge-block-tree", title="Cave Bridge-Block Tree",
        objective="find bridge passages, remove them, and report the connected bridge-block tree",
        profile="Tarjan low-link bridge discovery followed by bridge-deleted component contraction",
        function="build_bridge_tree",
        types="struct CaveBridge { int a{}; int b{}; }; struct BridgeTree { bool valid{}; int vertex_count{}; int block_count{}; std::vector<CaveBridge> bridges; std::vector<CaveBridge> tree_edges; };",
        params="const std::vector<std::string>& cave", return_type="BridgeTree",
        body="""BridgeTree out{};if(cave.empty()){out.valid=true;return out;}const int h=static_cast<int>(cave.size()),w=static_cast<int>(cave.front().size());if(w==0)return out;for(const auto&r:cave)if(static_cast<int>(r.size())!=w)return out;std::vector<int> id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(cave[r][c]=='.')id[static_cast<std::size_t>(r*w+c)]=out.vertex_count++;else if(cave[r][c]!='#')return BridgeTree{};std::vector<std::vector<int>>adj(static_cast<std::size_t>(out.vertex_count));const int dr[2]={0,1},dc[2]={1,0};for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(id[static_cast<std::size_t>(r*w+c)]>=0)for(int d=0;d<2;++d){int nr=r+dr[d],nc=c+dc[d];if(nr<h&&nc<w&&id[static_cast<std::size_t>(nr*w+nc)]>=0){int a=id[static_cast<std::size_t>(r*w+c)],b=id[static_cast<std::size_t>(nr*w+nc)];adj[static_cast<std::size_t>(a)].push_back(b);adj[static_cast<std::size_t>(b)].push_back(a);}}std::vector<int>tin(static_cast<std::size_t>(out.vertex_count),-1),low=tin;int timer=0;std::set<std::pair<int,int>>cut;std::function<void(int,int)>dfs=[&](int v,int p){tin[static_cast<std::size_t>(v)]=low[static_cast<std::size_t>(v)]=timer++;for(int to:adj[static_cast<std::size_t>(v)])if(to!=p){if(tin[static_cast<std::size_t>(to)]>=0)low[static_cast<std::size_t>(v)]=std::min(low[static_cast<std::size_t>(v)],tin[static_cast<std::size_t>(to)]);else{dfs(to,v);low[static_cast<std::size_t>(v)]=std::min(low[static_cast<std::size_t>(v)],low[static_cast<std::size_t>(to)]);if(low[static_cast<std::size_t>(to)]>tin[static_cast<std::size_t>(v)])cut.insert(std::minmax(v,to));}}};for(int v=0;v<out.vertex_count;++v)if(tin[static_cast<std::size_t>(v)]<0)dfs(v,-1);for(auto [a,b]:cut)out.bridges.push_back({a,b});std::vector<int>block(static_cast<std::size_t>(out.vertex_count),-1);for(int seed=0;seed<out.vertex_count;++seed)if(block[static_cast<std::size_t>(seed)]<0){int k=out.block_count++;std::queue<int>q;q.push(seed);block[static_cast<std::size_t>(seed)]=k;while(!q.empty()){int v=q.front();q.pop();for(int to:adj[static_cast<std::size_t>(v)])if(!cut.count(std::minmax(v,to))&&block[static_cast<std::size_t>(to)]<0){block[static_cast<std::size_t>(to)]=k;q.push(to);}}}for(auto [a,b]:cut)out.tree_edges.push_back({block[static_cast<std::size_t>(a)],block[static_cast<std::size_t>(b)]});out.valid=true;return out;""",
        visible="""auto g=build_bridge_tree({"...","..#"});if(!g.valid||g.vertex_count!=5||g.bridges.size()!=1||g.block_count!=2)return 1;return 0;""",
        hidden="""auto e=build_bridge_tree({});if(!e.valid)return 1;if(build_bridge_tree({".x"}).valid)return 1;auto p=build_bridge_tree({"...."});if(!p.valid||p.bridges.size()!=3||p.block_count!=4)return 1;return 0;""",
        marker="low[static_cast<std::size_t>(to)]>tin", prompt_terms=("low-link", "bridge passage", "bridge-deleted block", "tree edge"),
        negative_old="if(low[static_cast<std::size_t>(to)]>tin[static_cast<std::size_t>(v)])", negative_new="if(low[static_cast<std::size_t>(to)]>=tin[static_cast<std::size_t>(v)])",
        negative_description="misclassify cycle edges as bridges by weakening the low-link inequality",
    ),
    _case(
        legacy_id="graph-subway-map", task_id="subway-labelled-track-graph", title="Labelled Subway Track Graph",
        objective="trace orthogonal track runs between labelled stations and retain one canonical station edge per run",
        profile="station-origin ray tracing through orientation-compatible track glyphs",
        function="trace_subway_tracks",
        types="struct TrackEdge { char first{}; char second{}; int length{}; }; struct SubwayGraph { bool valid{}; std::vector<char> stations; std::vector<TrackEdge> tracks; };",
        params="const std::vector<std::string>& diagram", return_type="SubwayGraph",
        body="""SubwayGraph out{};if(diagram.empty()){out.valid=true;return out;}const int h=static_cast<int>(diagram.size()),w=static_cast<int>(diagram.front().size());if(w==0)return out;for(const auto&r:diagram)if(static_cast<int>(r.size())!=w)return out;std::map<char,std::pair<int,int>>pos;for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=diagram[r][c];if(x>='A'&&x<='Z'){if(!pos.emplace(x,std::make_pair(r,c)).second)return SubwayGraph{};}else if(x!='#'&&x!='-'&&x!='|')return SubwayGraph{};}for(auto [name,p]:pos)out.stations.push_back(name);std::set<std::pair<char,char>>seen;const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};for(auto [name,p]:pos)for(int d=0;d<4;++d){int r=p.first+dr[d],c=p.second+dc[d],len=1;while(r>=0&&r<h&&c>=0&&c<w){char x=diagram[r][c];if(x>='A'&&x<='Z'){auto key=std::minmax(name,x);if(name!=x&&seen.insert(key).second)out.tracks.push_back({key.first,key.second,len});break;}if((dr[d]==0&&x!='-')||(dc[d]==0&&x!='|'))break;r+=dr[d];c+=dc[d];++len;}}std::sort(out.tracks.begin(),out.tracks.end(),[](const TrackEdge&a,const TrackEdge&b){return std::tie(a.first,a.second)<std::tie(b.first,b.second);});out.valid=true;return out;""",
        visible="""auto g=trace_subway_tracks({"A--B","####","C###"});if(!g.valid||g.stations!=std::vector<char>{'A','B','C'}||g.tracks.size()!=1||g.tracks[0].length!=3)return 1;auto wrong=trace_subway_tracks({"A","-","B"});if(!wrong.valid||!wrong.tracks.empty())return 1;return 0;""",
        hidden="""auto e=trace_subway_tracks({});if(!e.valid)return 1;if(trace_subway_tracks({"A-A"}).valid)return 1;auto g=trace_subway_tracks({"A","|","B"});if(!g.valid||g.tracks.size()!=1)return 1;return 0;""",
        marker="std::map<char,std::pair<int,int>>pos", prompt_terms=("labelled station", "orientation-compatible track", "ray trace", "canonical station edge"),
        negative_old="if((dr[d]==0&&x!='-')||(dc[d]==0&&x!='|'))break;", negative_new="if(x=='#')break;",
        negative_description="permit vertical glyphs on horizontal tracks and horizontal glyphs on vertical tracks",
    ),
    _case(
        legacy_id="graph-garden-paths", task_id="garden-visibility-graph", title="Garden Visibility Graph",
        objective="connect labelled garden markers that share an unobstructed row or column",
        profile="nearest-marker orthogonal visibility with blocker termination",
        function="build_garden_visibility",
        types="struct SightEdge { char from{}; char to{}; int gap{}; }; struct GardenGraph { bool valid{}; std::vector<char> markers; std::vector<SightEdge> sightlines; };",
        params="const std::vector<std::string>& garden", return_type="GardenGraph",
        body="""GardenGraph out{};if(garden.empty()){out.valid=true;return out;}const int h=static_cast<int>(garden.size()),w=static_cast<int>(garden.front().size());if(w==0)return out;for(const auto&r:garden)if(static_cast<int>(r.size())!=w)return out;std::map<char,std::pair<int,int>>p;for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=garden[r][c];if(x>='A'&&x<='Z'){if(!p.emplace(x,std::make_pair(r,c)).second)return GardenGraph{};}else if(x!='.'&&x!='#')return GardenGraph{};}for(auto [x,unused]:p){static_cast<void>(unused);out.markers.push_back(x);}std::set<std::pair<char,char>>seen;const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};for(auto [x,q]:p)for(int d=0;d<4;++d){int r=q.first+dr[d],c=q.second+dc[d],gap=0;while(r>=0&&r<h&&c>=0&&c<w&&garden[r][c]!='#'){char y=garden[r][c];if(y>='A'&&y<='Z'){auto key=std::minmax(x,y);if(seen.insert(key).second)out.sightlines.push_back({key.first,key.second,gap});break;}++gap;r+=dr[d];c+=dc[d];}}std::sort(out.sightlines.begin(),out.sightlines.end(),[](const SightEdge&a,const SightEdge&b){return std::tie(a.from,a.to)<std::tie(b.from,b.to);});out.valid=true;return out;""",
        visible="""auto g=build_garden_visibility({"A..B",".##.","C..D"});if(!g.valid||g.markers.size()!=4||g.sightlines.size()!=4)return 1;auto blocked=build_garden_visibility({"A#B"});if(!blocked.valid||!blocked.sightlines.empty())return 1;return 0;""",
        hidden="""auto e=build_garden_visibility({});if(!e.valid||!e.markers.empty())return 1;for(const auto&bad:std::vector<std::vector<std::string>>{{"AA"},{"A?"},{"A",".."}})if(build_garden_visibility(bad).valid)return 1;auto blocked=build_garden_visibility({"A#B"});if(!blocked.valid||blocked.markers.size()!=2||!blocked.sightlines.empty())return 1;return 0;""",
        marker="garden[r][c]!='#'", prompt_terms=("nearest marker", "orthogonal line of sight", "blocker termination", "canonical label pair"),
        negative_old="&&garden[r][c]!='#'", negative_new="&&garden[r][c]!='@'",
        negative_description="look through blocking hedges",
    ),
    _case(
        legacy_id="graph-data-center", task_id="rack-port-capacity-graph", title="Rack Port Capacity Graph",
        objective="join numbered racks through straight cable runs and retain the minimum endpoint port capacity",
        profile="labelled endpoint tracing with bottleneck-capacity edge aggregation",
        function="trace_rack_links",
        types="struct RackLink { int first{}; int second{}; int capacity{}; int length{}; }; struct RackGraph { bool valid{}; std::vector<int> racks; std::vector<RackLink> links; };",
        params="const std::vector<std::string>& floor", return_type="RackGraph",
        body="""RackGraph out{};if(floor.empty()){out.valid=true;return out;}const int h=static_cast<int>(floor.size()),w=static_cast<int>(floor.front().size());if(w==0)return out;for(const auto&r:floor)if(static_cast<int>(r.size())!=w)return out;std::map<int,std::pair<int,int>>rack;for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=floor[r][c];if(x>='1'&&x<='9'){int id=x-'0';if(!rack.emplace(id,std::make_pair(r,c)).second)return RackGraph{};}else if(x!='#'&&x!='-'&&x!='|')return RackGraph{};}for(auto [id,unused]:rack){static_cast<void>(unused);out.racks.push_back(id);}std::map<std::pair<int,int>,RackLink>links;const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};for(auto [id,p]:rack)for(int d=0;d<4;++d){int r=p.first+dr[d],c=p.second+dc[d],len=1;while(r>=0&&r<h&&c>=0&&c<w){char x=floor[r][c];if(x>='1'&&x<='9'){int other=x-'0';auto key=std::minmax(id,other);if(id!=other)links[key]={key.first,key.second,std::min(key.first,key.second),len};break;}if((dr[d]==0&&x!='-')||(dc[d]==0&&x!='|'))break;r+=dr[d];c+=dc[d];++len;}}for(auto [key,value]:links){static_cast<void>(key);out.links.push_back(value);}out.valid=true;return out;""",
        visible="""auto g=trace_rack_links({"2--7","####","5###"});if(!g.valid||g.racks!=std::vector<int>{2,5,7}||g.links.size()!=1||g.links[0].capacity!=2)return 1;return 0;""",
        hidden="""auto e=trace_rack_links({});if(!e.valid)return 1;if(trace_rack_links({"1-1"}).valid)return 1;auto g=trace_rack_links({"9","|","3"});if(!g.valid||g.links.size()!=1||g.links[0].capacity!=3)return 1;return 0;""",
        marker="std::min(key.first,key.second)", prompt_terms=("numbered rack", "straight cable", "bottleneck capacity", "parallel route aggregation"),
        negative_old="std::min(key.first,key.second)", negative_new="std::max(key.first,key.second)",
        negative_description="use the larger endpoint port rating instead of the bottleneck",
    ),
    _case(
        legacy_id="graph-ski-resort", task_id="ski-elevation-dag", title="Ski Elevation DAG",
        objective="orient adjacent numeric terrain cells strictly downhill and count reachable lodges at elevation zero",
        profile="strict-height directed acyclic graph with memoized terminal reachability",
        function="build_ski_dag",
        types="struct SkiArc { int from{}; int to{}; }; struct SkiDag { bool valid{}; int vertices{}; std::vector<SkiArc> arcs; std::vector<int> lodge_reach; };",
        params="const std::vector<std::string>& heights", return_type="SkiDag",
        body="""SkiDag out{};if(heights.empty()){out.valid=true;return out;}const int h=static_cast<int>(heights.size()),w=static_cast<int>(heights.front().size());if(w==0)return out;for(const auto&r:heights)if(static_cast<int>(r.size())!=w)return out;std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=heights[r][c];if(x>='0'&&x<='9')id[static_cast<std::size_t>(r*w+c)]=out.vertices++;else if(x!='#')return SkiDag{};}std::vector<std::vector<int>>adj(static_cast<std::size_t>(out.vertices));const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;for(int d=0;d<4;++d){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<h&&nc>=0&&nc<w){int b=id[static_cast<std::size_t>(nr*w+nc)];if(b>=0&&heights[nr][nc]<heights[r][c]){adj[static_cast<std::size_t>(a)].push_back(b);out.arcs.push_back({a,b});}}}}std::vector<std::set<int>>memo(static_cast<std::size_t>(out.vertices));std::vector<int>done(static_cast<std::size_t>(out.vertices));std::function<const std::set<int>&(int)>solve=[&](int v)->const std::set<int>&{if(done[static_cast<std::size_t>(v)])return memo[static_cast<std::size_t>(v)];done[static_cast<std::size_t>(v)]=1;int cell=-1;for(int k=0;k<h*w;++k)if(id[static_cast<std::size_t>(k)]==v){cell=k;break;}if(heights[cell/w][cell%w]=='0')memo[static_cast<std::size_t>(v)].insert(v);for(int to:adj[static_cast<std::size_t>(v)]){const auto&s=solve(to);memo[static_cast<std::size_t>(v)].insert(s.begin(),s.end());}return memo[static_cast<std::size_t>(v)];};for(int v=0;v<out.vertices;++v)out.lodge_reach.push_back(static_cast<int>(solve(v).size()));out.valid=true;return out;""",
        visible="""auto g=build_ski_dag({"21","10"});if(!g.valid||g.vertices!=4||g.arcs.size()!=4||g.lodge_reach[0]!=1)return 1;auto level=build_ski_dag({"11"});if(!level.valid||!level.arcs.empty())return 1;return 0;""",
        hidden="""auto e=build_ski_dag({});if(!e.valid||e.vertices!=0)return 1;auto invalid=[](const std::vector<std::string>&x){return build_ski_dag(x).valid;};if(invalid({"2x"})||invalid({"1","22"}))return 1;auto plateau=build_ski_dag({"111"});if(!plateau.valid||plateau.vertices!=3||!plateau.arcs.empty()||plateau.lodge_reach!=std::vector<int>{0,0,0})return 1;return 0;""",
        marker="heights[nr][nc]<heights[r][c]", prompt_terms=("strictly downhill", "acyclic", "memoized lodge set", "row-major vertex"),
        negative_old="heights[nr][nc]<heights[r][c]", negative_new="heights[nr][nc]<=heights[r][c]",
        negative_description="admit equal-height cycles into the downhill DAG",
    ),
    _case(
        legacy_id="graph-harbor-canals", task_id="canal-lock-state-graph", title="Canal Lock State Graph",
        objective="expand each navigable canal position by the open or closed state of a shared lock",
        profile="two-layer state expansion with explicit lock-toggle transitions",
        function="expand_canal_lock_states",
        types="struct CanalTransition { int from{}; int to{}; char action{}; }; struct CanalStateGraph { bool valid{}; int positions{}; int states{}; std::vector<CanalTransition> transitions; };",
        params="const std::vector<std::string>& canal", return_type="CanalStateGraph",
        body="""CanalStateGraph out{};if(canal.empty()){out.valid=true;return out;}const int h=static_cast<int>(canal.size()),w=static_cast<int>(canal.front().size());if(w==0)return out;for(const auto&r:canal)if(static_cast<int>(r.size())!=w)return out;std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=canal[r][c];if(x=='.'||x=='L')id[static_cast<std::size_t>(r*w+c)]=out.positions++;else if(x!='#')return CanalStateGraph{};}out.states=out.positions*2;const int dr[2]={0,1},dc[2]={1,0};for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;if(canal[r][c]=='L'){out.transitions.push_back({a*2,a*2+1,'T'});out.transitions.push_back({a*2+1,a*2,'T'});}for(int d=0;d<2;++d){int nr=r+dr[d],nc=c+dc[d];if(nr>=h||nc>=w)continue;int b=id[static_cast<std::size_t>(nr*w+nc)];if(b<0)continue;for(int state=0;state<2;++state){if((canal[r][c]=='L'||canal[nr][nc]=='L')&&state==0)continue;out.transitions.push_back({a*2+state,b*2+state,'M'});out.transitions.push_back({b*2+state,a*2+state,'M'});}}}out.valid=true;return out;""",
        visible="""auto g=expand_canal_lock_states({".L"});if(!g.valid||g.positions!=2||g.states!=4||g.transitions.size()!=4)return 1;return 0;""",
        hidden="""auto e=expand_canal_lock_states({});if(!e.valid)return 1;if(expand_canal_lock_states({"X"}).valid)return 1;auto g=expand_canal_lock_states({".."});if(!g.valid||g.transitions.size()!=4)return 1;return 0;""",
        marker="out.states=out.positions*2", prompt_terms=("two-layer state", "closed lock", "toggle transition", "movement preserves state"),
        negative_old="&&state==0", negative_new="&&state==2",
        negative_description="allow movement through a closed lock",
    ),
    _case(
        legacy_id="graph-fire-escape", task_id="fire-time-expanded-egress", title="Fire Time-Expanded Egress",
        objective="build safe occupant states by time after independently propagating fire arrival times",
        profile="hazard-first breadth-first arrival map plus bounded time-expanded occupancy graph",
        function="build_safe_egress_graph",
        types="struct TimedArc { int from{}; int to{}; }; struct EgressGraph { bool valid{}; int safe_states{}; int exits{}; std::vector<TimedArc> arcs; };",
        params="const std::vector<std::string>& floor, int horizon", return_type="EgressGraph",
        body="""EgressGraph out{};if(horizon<0)return out;if(floor.empty()){out.valid=true;return out;}const int h=static_cast<int>(floor.size()),w=static_cast<int>(floor.front().size());if(w==0)return out;for(const auto&r:floor)if(static_cast<int>(r.size())!=w)return out;const int inf=1000000;std::vector<int>fire(static_cast<std::size_t>(h*w),inf);std::queue<int>q;for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=floor[r][c];if(x=='F'){fire[static_cast<std::size_t>(r*w+c)]=0;q.push(r*w+c);}else if(x=='E')++out.exits;else if(x!='.'&&x!='S'&&x!='#')return EgressGraph{};}const int dr[5]={0,-1,0,0,1},dc[5]={0,0,-1,1,0};while(!q.empty()){int v=q.front();q.pop();int r=v/w,c=v%w;for(int d=1;d<5;++d){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<h&&nc>=0&&nc<w&&floor[nr][nc]!='#'&&fire[static_cast<std::size_t>(nr*w+nc)]==inf){fire[static_cast<std::size_t>(nr*w+nc)]=fire[static_cast<std::size_t>(v)]+1;q.push(nr*w+nc);}}}std::vector<int>sid(static_cast<std::size_t>((horizon+1)*h*w),-1);for(int t=0;t<=horizon;++t)for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(floor[r][c]!='#'&&floor[r][c]!='F'&&t<fire[static_cast<std::size_t>(r*w+c)])sid[static_cast<std::size_t>((t*h+r)*w+c)]=out.safe_states++;for(int t=0;t<horizon;++t)for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=sid[static_cast<std::size_t>((t*h+r)*w+c)];if(a<0)continue;for(int d=0;d<5;++d){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<h&&nc>=0&&nc<w){int b=sid[static_cast<std::size_t>(((t+1)*h+nr)*w+nc)];if(b>=0)out.arcs.push_back({a,b});}}}out.valid=true;return out;""",
        visible="""auto g=build_safe_egress_graph({"S.FE"},1);if(!g.valid||g.safe_states!=4||g.exits!=1||g.arcs.size()!=2)return 1;return 0;""",
        hidden="""if(build_safe_egress_graph({"S"},-1).valid)return 1;auto e=build_safe_egress_graph({},2);if(!e.valid)return 1;auto g=build_safe_egress_graph({"SF"},2);if(!g.valid||g.safe_states!=1)return 1;return 0;""",
        marker="t<fire[static_cast<std::size_t>(r*w+c)]", prompt_terms=("fire arrival", "time-expanded state", "wait edge", "strictly before hazard"),
        negative_old="t<fire[static_cast<std::size_t>(r*w+c)]", negative_new="t<=fire[static_cast<std::size_t>(r*w+c)]",
        negative_description="retain occupant states at the exact time fire arrives",
    ),
    _case(
        legacy_id="graph-irrigation-ditches", task_id="ditch-flow-condensation", title="Ditch Flow Condensation",
        objective="condense the directed graph formed by arrow-coded ditch cells and identify source components",
        profile="functional-grid graph Kosaraju condensation with source-component ordering",
        function="condense_ditch_flow",
        types="struct DitchCondensation { bool valid{}; int cells{}; int components{}; std::vector<int> component_of; std::vector<int> source_components; };",
        params="const std::vector<std::string>& ditches", return_type="DitchCondensation",
        body="""DitchCondensation out{};if(ditches.empty()){out.valid=true;return out;}const int h=static_cast<int>(ditches.size()),w=static_cast<int>(ditches.front().size());if(w==0)return out;for(const auto&r:ditches)if(static_cast<int>(r.size())!=w)return out;std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=ditches[r][c];if(x=='^'||x=='v'||x=='<'||x=='>')id[static_cast<std::size_t>(r*w+c)]=out.cells++;else if(x!='#')return DitchCondensation{};}std::vector<std::vector<int>>g(static_cast<std::size_t>(out.cells)),rg=g;for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;char x=ditches[r][c];int nr=r+(x=='v')-(x=='^'),nc=c+(x=='>')-(x=='<');if(nr>=0&&nr<h&&nc>=0&&nc<w){int b=id[static_cast<std::size_t>(nr*w+nc)];if(b>=0){g[static_cast<std::size_t>(a)].push_back(b);rg[static_cast<std::size_t>(b)].push_back(a);}}}std::vector<int>seen(static_cast<std::size_t>(out.cells)),order;std::function<void(int)>first=[&](int v){seen[static_cast<std::size_t>(v)]=1;for(int to:g[static_cast<std::size_t>(v)])if(!seen[static_cast<std::size_t>(to)])first(to);order.push_back(v);};for(int v=0;v<out.cells;++v)if(!seen[static_cast<std::size_t>(v)])first(v);out.component_of.assign(static_cast<std::size_t>(out.cells),-1);std::function<void(int)>second=[&](int v){out.component_of[static_cast<std::size_t>(v)]=out.components;for(int to:rg[static_cast<std::size_t>(v)])if(out.component_of[static_cast<std::size_t>(to)]<0)second(to);};for(auto it=order.rbegin();it!=order.rend();++it)if(out.component_of[static_cast<std::size_t>(*it)]<0){second(*it);++out.components;}std::vector<int>indegree(static_cast<std::size_t>(out.components));for(int v=0;v<out.cells;++v)for(int to:g[static_cast<std::size_t>(v)])if(out.component_of[static_cast<std::size_t>(v)]!=out.component_of[static_cast<std::size_t>(to)])++indegree[static_cast<std::size_t>(out.component_of[static_cast<std::size_t>(to)])];for(int k=0;k<out.components;++k)if(indegree[static_cast<std::size_t>(k)]==0)out.source_components.push_back(k);out.valid=true;return out;""",
        visible="""auto g=condense_ditch_flow({"><","^#"});if(!g.valid||g.cells!=3||g.components!=2||g.source_components.size()!=1)return 1;return 0;""",
        hidden="""auto e=condense_ditch_flow({});if(!e.valid)return 1;if(condense_ditch_flow({"x"}).valid)return 1;auto g=condense_ditch_flow({">"});if(!g.valid||g.components!=1||g.source_components!=std::vector<int>{0})return 1;return 0;""",
        marker="order.rbegin()", prompt_terms=("functional graph", "reverse postorder", "strong component", "condensation source"),
        negative_old="for(auto it=order.rbegin();it!=order.rend();++it)", negative_new="for(auto it=order.begin();it!=order.end();++it)",
        negative_description="run the reverse-graph pass in forward finish order",
    ),
    _case(
        legacy_id="graph-robot-factory", task_id="factory-conveyor-conflict-graph", title="Factory Conveyor Conflict Graph",
        objective="construct directed conveyor moves and connect sources that compete for the same destination",
        profile="arrow transition graph plus destination-bucket conflict projection",
        function="find_conveyor_conflicts",
        types="struct ConveyorMove { int from{}; int to{}; }; struct ConveyorConflict { int first_source{}; int second_source{}; int destination{}; }; struct FactoryGraph { bool valid{}; int belts{}; std::vector<ConveyorMove> moves; std::vector<ConveyorConflict> conflicts; };",
        params="const std::vector<std::string>& floor", return_type="FactoryGraph",
        body="""FactoryGraph out{};if(floor.empty()){out.valid=true;return out;}const int h=static_cast<int>(floor.size()),w=static_cast<int>(floor.front().size());if(w==0)return out;for(const auto&r:floor)if(static_cast<int>(r.size())!=w)return out;std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=floor[r][c];if(x=='^'||x=='v'||x=='<'||x=='>')id[static_cast<std::size_t>(r*w+c)]=out.belts++;else if(x!='#')return FactoryGraph{};}std::map<int,std::vector<int>>incoming;for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;char x=floor[r][c];int nr=r+(x=='v')-(x=='^'),nc=c+(x=='>')-(x=='<');if(nr>=0&&nr<h&&nc>=0&&nc<w){int b=id[static_cast<std::size_t>(nr*w+nc)];if(b>=0){out.moves.push_back({a,b});incoming[b].push_back(a);}}}for(auto [dest,sources]:incoming){std::sort(sources.begin(),sources.end());for(std::size_t i=0;i<sources.size();++i)for(std::size_t j=i+1;j<sources.size();++j)out.conflicts.push_back({sources[i],sources[j],dest});}out.valid=true;return out;""",
        visible="""auto g=find_conveyor_conflicts({">v","#^"});if(!g.valid||g.belts!=3||g.moves.size()!=3||g.conflicts.size()!=1)return 1;return 0;""",
        hidden="""auto e=find_conveyor_conflicts({});if(!e.valid)return 1;if(find_conveyor_conflicts({"."}).valid)return 1;auto g=find_conveyor_conflicts({">>"});if(!g.valid||g.moves.size()!=1||!g.conflicts.empty())return 1;return 0;""",
        marker="incoming[b].push_back(a)", prompt_terms=("directed conveyor", "destination bucket", "source conflict pair", "row-major belt id"),
        negative_old="incoming[b].push_back(a)", negative_new="incoming[a].push_back(a)",
        negative_description="bucket moves by their source rather than their competing destination",
    ),
    _case(
        legacy_id="graph-archive-stacks", task_id="archive-turn-cost-graph", title="Archive Turn-Cost Graph",
        objective="lift aisle positions by heading, assign movement cost one plus a turn penalty, and count arrivals by heading",
        profile="four-heading product graph with direction-dependent weighted transitions",
        function="build_archive_heading_graph",
        types="struct HeadingArc { int from{}; int to{}; int cost{}; }; struct ArchiveGraph { bool valid{}; int aisles{}; int heading_states{}; std::array<int,4> arrivals_by_heading{}; std::vector<HeadingArc> arcs; };",
        params="const std::vector<std::string>& stacks, int turn_penalty", return_type="ArchiveGraph",
        body="""ArchiveGraph out{};if(turn_penalty<0)return out;if(stacks.empty()){out.valid=true;return out;}const int h=static_cast<int>(stacks.size()),w=static_cast<int>(stacks.front().size());if(w==0)return out;for(const auto&r:stacks)if(static_cast<int>(r.size())!=w)return out;std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(stacks[r][c]=='.')id[static_cast<std::size_t>(r*w+c)]=out.aisles++;else if(stacks[r][c]!='#')return ArchiveGraph{};out.heading_states=out.aisles*4;const int dr[4]={-1,0,1,0},dc[4]={0,1,0,-1};for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;for(int heading=0;heading<4;++heading)for(int next=0;next<4;++next){int nr=r+dr[next],nc=c+dc[next];if(nr>=0&&nr<h&&nc>=0&&nc<w){int b=id[static_cast<std::size_t>(nr*w+nc)];if(b>=0){out.arcs.push_back({a*4+heading,b*4+next,1+(heading==next?0:turn_penalty)});++out.arrivals_by_heading[static_cast<std::size_t>(next)];}}}}out.valid=true;return out;""",
        visible="""auto g=build_archive_heading_graph({".."},4);if(!g.valid||g.aisles!=2||g.heading_states!=8||g.arcs.size()!=8||g.arcs[1].cost!=1||g.arrivals_by_heading!=std::array<int,4>{0,4,0,4})return 1;return 0;""",
        hidden="""if(build_archive_heading_graph({"."},-1).valid)return 1;auto e=build_archive_heading_graph({},2);if(!e.valid)return 1;auto g=build_archive_heading_graph({".#"},1);if(!g.valid||!g.arcs.empty())return 1;return 0;""",
        marker="heading==next?0:turn_penalty", prompt_terms=("heading product state", "turn penalty", "weighted transition", "arrivals by heading"),
        negative_old="heading==next?0:turn_penalty", negative_new="heading!=next?0:turn_penalty",
        negative_description="charge the turn penalty for straight travel instead of direction changes",
    ),
    _case(
        legacy_id="graph-camp-trails", task_id="trail-signpost-route-graph", title="Trail Signpost Route Graph",
        objective="trace arrow chains from labelled signposts to the next labelled signpost",
        profile="deterministic signpost-origin arrow automaton with cycle rejection",
        function="trace_signpost_routes",
        types="struct SignedRoute { char from{}; char to{}; int steps{}; }; struct TrailGraph { bool valid{}; std::vector<char> signs; std::vector<SignedRoute> routes; int lost_routes{}; };",
        params="const std::vector<std::string>& trails", return_type="TrailGraph",
        body="""TrailGraph out{};if(trails.empty()){out.valid=true;return out;}const int h=static_cast<int>(trails.size()),w=static_cast<int>(trails.front().size());if(w==0)return out;for(const auto&r:trails)if(static_cast<int>(r.size())!=w)return out;std::map<char,std::pair<int,int>>sign;for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=trails[r][c];if(x>='A'&&x<='Z'){if(!sign.emplace(x,std::make_pair(r,c)).second)return TrailGraph{};}else if(x!='^'&&x!='v'&&x!='<'&&x!='>'&&x!='#')return TrailGraph{};}for(auto [name,p]:sign){out.signs.push_back(name);const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};bool found=false;for(int d=0;d<4&&!found;++d){int r=p.first+dr[d],c=p.second+dc[d],steps=1;std::set<std::pair<int,int>>seen;while(r>=0&&r<h&&c>=0&&c<w&&seen.insert({r,c}).second){char x=trails[r][c];if(x>='A'&&x<='Z'){if(x!=name){out.routes.push_back({name,x,steps});found=true;}break;}if(x=='#')break;int nr=r+(x=='v')-(x=='^'),nc=c+(x=='>')-(x=='<');if(nr==r&&nc==c)break;r=nr;c=nc;++steps;}}if(!found)++out.lost_routes;}std::sort(out.routes.begin(),out.routes.end(),[](const SignedRoute&a,const SignedRoute&b){return std::tie(a.from,a.to)<std::tie(b.from,b.to);});out.valid=true;return out;""",
        visible="""auto g=trace_signpost_routes({"B","^","A","v","C"});if(!g.valid||g.signs!=std::vector<char>{'A','B','C'}||g.routes.size()!=1||g.routes[0].from!='A'||g.routes[0].to!='B'||g.routes[0].steps!=2)return 1;return 0;""",
        hidden="""auto e=trace_signpost_routes({});if(!e.valid)return 1;if(trace_signpost_routes({"AA"}).valid)return 1;auto g=trace_signpost_routes({"A#B"});if(!g.valid||g.lost_routes!=2)return 1;return 0;""",
        marker="seen.insert({r,c}).second", prompt_terms=("signpost origin", "arrow automaton", "cycle rejection", "lost route"),
        negative_old="&&seen.insert({r,c}).second", negative_new="&&seen.insert({0,0}).second",
        negative_description="use one constant cycle key instead of tracking visited arrow cells",
    ),
    _case(
        legacy_id="graph-radar-corridors", task_id="radar-range-visibility-graph", title="Radar Range Visibility Graph",
        objective="connect labelled beacons by unobstructed eight-direction visibility within a supplied range and report each beacon's nearest link distance",
        profile="bounded octilinear ray casting with nearest-beacon termination",
        function="build_radar_visibility",
        types="struct RadarLink { char first{}; char second{}; int distance{}; }; struct RadarGraph { bool valid{}; std::vector<char> beacons; std::vector<RadarLink> links; std::vector<std::pair<char,int>> nearest_distance; };",
        params="const std::vector<std::string>& sectors, int range", return_type="RadarGraph",
        body="""RadarGraph out{};if(range<1)return out;if(sectors.empty()){out.valid=true;return out;}const int h=static_cast<int>(sectors.size()),w=static_cast<int>(sectors.front().size());if(w==0)return out;for(const auto&r:sectors)if(static_cast<int>(r.size())!=w)return out;std::map<char,std::pair<int,int>>p;for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=sectors[r][c];if(x>='A'&&x<='Z'){if(!p.emplace(x,std::make_pair(r,c)).second)return RadarGraph{};}else if(x!='.'&&x!='#')return RadarGraph{};}for(auto [x,unused]:p){static_cast<void>(unused);out.beacons.push_back(x);}std::set<std::pair<char,char>>seen;for(auto [x,q]:p)for(int dr=-1;dr<=1;++dr)for(int dc=-1;dc<=1;++dc)if(dr!=0||dc!=0)for(int step=1;step<=range;++step){int r=q.first+dr*step,c=q.second+dc*step;if(r<0||r>=h||c<0||c>=w||sectors[r][c]=='#')break;char y=sectors[r][c];if(y>='A'&&y<='Z'){auto key=std::minmax(x,y);if(seen.insert(key).second)out.links.push_back({key.first,key.second,step});break;}}std::sort(out.links.begin(),out.links.end(),[](const RadarLink&a,const RadarLink&b){return std::tie(a.first,a.second)<std::tie(b.first,b.second);});for(char beacon:out.beacons){int nearest=0;for(const auto&link:out.links)if(link.first==beacon||link.second==beacon)nearest=nearest==0?link.distance:std::min(nearest,link.distance);out.nearest_distance.push_back({beacon,nearest});}out.valid=true;return out;""",
        visible="""auto g=build_radar_visibility({"A..","...","..B"},2);if(!g.valid||g.links.size()!=1||g.links[0].distance!=2||g.nearest_distance!=std::vector<std::pair<char,int>>{{'A',2},{'B',2}})return 1;return 0;""",
        hidden="""if(build_radar_visibility({"A"},0).valid)return 1;auto e=build_radar_visibility({},3);if(!e.valid)return 1;auto g=build_radar_visibility({"A#B"},3);if(!g.valid||!g.links.empty())return 1;return 0;""",
        marker="step<=range", prompt_terms=("eight directions", "bounded range", "nearest beacon", "nearest link distance", "blocking sector"),
        negative_old="step<=range", negative_new="step<range",
        negative_description="exclude beacons exactly at the inclusive range limit",
    ),
    _case(
        legacy_id="graph-hospital-halls", task_id="hospital-block-cut-forest", title="Hospital Block-Cut Forest",
        objective="decompose hall cells into biconnected blocks and connect articulation cells to their incident blocks",
        profile="Tarjan edge-stack biconnected decomposition with explicit block-cut incidence",
        function="build_hospital_block_cut_forest",
        types="struct BlockIncidence { int articulation{}; int block{}; }; struct HospitalForest { bool valid{}; int halls{}; std::vector<int> articulations; int blocks{}; std::vector<BlockIncidence> incidence; };",
        params="const std::vector<std::string>& hospital", return_type="HospitalForest",
        body="""HospitalForest out{};if(hospital.empty()){out.valid=true;return out;}const int h=static_cast<int>(hospital.size()),w=static_cast<int>(hospital.front().size());if(w==0)return out;for(const auto&r:hospital)if(static_cast<int>(r.size())!=w)return out;std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(hospital[r][c]=='.')id[static_cast<std::size_t>(r*w+c)]=out.halls++;else if(hospital[r][c]!='#')return HospitalForest{};std::vector<std::vector<int>>adj(static_cast<std::size_t>(out.halls));const int dr[2]={0,1},dc[2]={1,0};for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;for(int d=0;d<2;++d){int nr=r+dr[d],nc=c+dc[d];if(nr<h&&nc<w){int b=id[static_cast<std::size_t>(nr*w+nc)];if(b>=0){adj[static_cast<std::size_t>(a)].push_back(b);adj[static_cast<std::size_t>(b)].push_back(a);}}}}std::vector<int>tin(static_cast<std::size_t>(out.halls),-1),low=tin,is_art(static_cast<std::size_t>(out.halls));std::vector<std::pair<int,int>>stack;std::vector<std::set<int>>members;int timer=0;std::function<void(int,int)>dfs=[&](int v,int parent){tin[static_cast<std::size_t>(v)]=low[static_cast<std::size_t>(v)]=timer++;int children=0;for(int to:adj[static_cast<std::size_t>(v)])if(to!=parent){if(tin[static_cast<std::size_t>(to)]<0){stack.push_back({v,to});++children;dfs(to,v);low[static_cast<std::size_t>(v)]=std::min(low[static_cast<std::size_t>(v)],low[static_cast<std::size_t>(to)]);if(low[static_cast<std::size_t>(to)]>=tin[static_cast<std::size_t>(v)]){if(parent>=0||children>1)is_art[static_cast<std::size_t>(v)]=1;std::set<int>block;while(!stack.empty()){auto edge=stack.back();stack.pop_back();block.insert(edge.first);block.insert(edge.second);if(edge==std::make_pair(v,to))break;}members.push_back(block);}}else if(tin[static_cast<std::size_t>(to)]<tin[static_cast<std::size_t>(v)]){stack.push_back({v,to});low[static_cast<std::size_t>(v)]=std::min(low[static_cast<std::size_t>(v)],tin[static_cast<std::size_t>(to)]);}}};for(int v=0;v<out.halls;++v)if(tin[static_cast<std::size_t>(v)]<0){if(adj[static_cast<std::size_t>(v)].empty())members.push_back({v});else dfs(v,-1);}for(int v=0;v<out.halls;++v)if(is_art[static_cast<std::size_t>(v)])out.articulations.push_back(v);out.blocks=static_cast<int>(members.size());for(int b=0;b<out.blocks;++b)for(int v:members[static_cast<std::size_t>(b)])if(is_art[static_cast<std::size_t>(v)])out.incidence.push_back({v,b});out.valid=true;return out;""",
        visible="""auto g=build_hospital_block_cut_forest({"...","##."});if(!g.valid||g.halls!=4||g.articulations.size()!=2||g.blocks!=3)return 1;return 0;""",
        hidden="""auto e=build_hospital_block_cut_forest({});if(!e.valid)return 1;if(build_hospital_block_cut_forest({"x"}).valid)return 1;auto c=build_hospital_block_cut_forest({"..",".."});if(!c.valid||!c.articulations.empty()||c.blocks!=1)return 1;return 0;""",
        marker="std::vector<std::pair<int,int>>stack", prompt_terms=("edge stack", "biconnected block", "articulation cell", "block-cut incidence"),
        negative_old="if(parent>=0||children>1)", negative_new="if(parent>=0&&children>1)",
        negative_description="fail to mark ordinary non-root articulation vertices",
    ),
    _case(
        legacy_id="graph-orchard-roads", task_id="orchard-wrap-road-graph", title="Cylindrical Orchard Road Graph",
        objective="construct road adjacency with the left and right borders joined as a cylindrical seam",
        profile="four-neighbor road graph with explicit horizontal wrap and seam accounting",
        function="build_cylindrical_roads",
        types="struct OrchardRoadGraph { bool valid{}; int vertices{}; int edges{}; int seam_edges{}; int components{}; };",
        params="const std::vector<std::string>& orchard", return_type="OrchardRoadGraph",
        body="""OrchardRoadGraph out{};if(orchard.empty()){out.valid=true;return out;}const int h=static_cast<int>(orchard.size()),w=static_cast<int>(orchard.front().size());if(w==0)return out;for(const auto&r:orchard)if(static_cast<int>(r.size())!=w)return out;std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(orchard[r][c]=='.')id[static_cast<std::size_t>(r*w+c)]=out.vertices++;else if(orchard[r][c]!='#')return OrchardRoadGraph{};std::vector<std::vector<int>>adj(static_cast<std::size_t>(out.vertices));for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;const int nr=r+1;if(nr<h){int b=id[static_cast<std::size_t>(nr*w+c)];if(b>=0){++out.edges;adj[static_cast<std::size_t>(a)].push_back(b);adj[static_cast<std::size_t>(b)].push_back(a);}}int nc=(c+1)%w;int b=id[static_cast<std::size_t>(r*w+nc)];if(b>=0&&a!=b&&(c+1==w||a<b)){++out.edges;if(c+1==w)++out.seam_edges;adj[static_cast<std::size_t>(a)].push_back(b);adj[static_cast<std::size_t>(b)].push_back(a);}}std::vector<int>seen(static_cast<std::size_t>(out.vertices));for(int s=0;s<out.vertices;++s)if(!seen[static_cast<std::size_t>(s)]){++out.components;std::queue<int>q;q.push(s);seen[static_cast<std::size_t>(s)]=1;while(!q.empty()){int v=q.front();q.pop();for(int to:adj[static_cast<std::size_t>(v)])if(!seen[static_cast<std::size_t>(to)]){seen[static_cast<std::size_t>(to)]=1;q.push(to);}}}out.valid=true;return out;""",
        visible="""auto g=build_cylindrical_roads({".#."});if(!g.valid||g.vertices!=2||g.edges!=1||g.seam_edges!=1||g.components!=1)return 1;return 0;""",
        hidden="""auto e=build_cylindrical_roads({});if(!e.valid)return 1;if(build_cylindrical_roads({"x"}).valid)return 1;auto g=build_cylindrical_roads({".#",".#"});if(!g.valid||g.components!=1||g.seam_edges!=0)return 1;return 0;""",
        marker="int nc=(c+1)%w", prompt_terms=("cylindrical seam", "horizontal wrap", "undirected edge once", "component count"),
        negative_old="int nc=(c+1)%w;", negative_new="int nc=c+1; if(nc>=w) continue;",
        negative_description="drop the cylindrical seam and use planar horizontal adjacency",
    ),
    _case(
        legacy_id="graph-sewer-lines", task_id="sewer-glyph-port-graph", title="Sewer Glyph Port Graph",
        objective="validate reciprocal pipe-glyph ports before admitting pipe-cell edges",
        profile="glyph-to-port decoding with reciprocal-neighbor validation",
        function="decode_sewer_ports",
        types="struct SewerEdge { int first{}; int second{}; }; struct SewerGraph { bool valid{}; int pipes{}; std::vector<SewerEdge> edges; int dangling_ports{}; };",
        params="const std::vector<std::string>& sewer", return_type="SewerGraph",
        body="""SewerGraph out{};if(sewer.empty()){out.valid=true;return out;}const int h=static_cast<int>(sewer.size()),w=static_cast<int>(sewer.front().size());if(w==0)return out;for(const auto&r:sewer)if(static_cast<int>(r.size())!=w)return out;auto mask=[](char x){if(x=='|')return 5;if(x=='-')return 10;if(x=='L')return 3;if(x=='J')return 9;if(x=='7')return 12;if(x=='F')return 6;if(x=='+')return 15;return 0;};std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c)if(mask(sewer[r][c])!=0)id[static_cast<std::size_t>(r*w+c)]=out.pipes++;else if(sewer[r][c]!='#')return SewerGraph{};const int dr[4]={-1,0,1,0},dc[4]={0,1,0,-1},op[4]={2,3,0,1};for(int r=0;r<h;++r)for(int c=0;c<w;++c){int a=id[static_cast<std::size_t>(r*w+c)];if(a<0)continue;int ports=mask(sewer[r][c]);for(int d=0;d<4;++d)if((ports&(1<<d))!=0){int nr=r+dr[d],nc=c+dc[d];if(nr<0||nr>=h||nc<0||nc>=w||(mask(sewer[nr][nc])&(1<<op[d]))==0){++out.dangling_ports;continue;}int b=id[static_cast<std::size_t>(nr*w+nc)];if(a<b)out.edges.push_back({a,b});}}out.valid=out.dangling_ports==0;return out;""",
        visible="""auto g=decode_sewer_ports({"F7","LJ"});if(!g.valid||g.pipes!=4||g.edges.size()!=4||g.dangling_ports!=0)return 1;return 0;""",
        hidden="""auto e=decode_sewer_ports({});if(!e.valid)return 1;if(decode_sewer_ports({"x"}).valid)return 1;auto g=decode_sewer_ports({"-#"});if(g.valid||g.dangling_ports!=2)return 1;return 0;""",
        marker="(mask(sewer[nr][nc])&(1<<op[d]))==0", prompt_terms=("glyph port mask", "reciprocal port", "dangling port", "edge once"),
        negative_old="1<<op[d]", negative_new="1<<op[(d+1)%4]",
        negative_description="accept a neighboring pipe even when it lacks the reciprocal port",
    ),
    _case(
        legacy_id="graph-airport-concourse", task_id="concourse-gate-distance-graph", title="Concourse Gate Distance Graph",
        objective="compute shortest corridor distances between every reachable pair of labelled gates and count reachable peers per gate",
        profile="one breadth-first distance field per gate with canonical complete reachable gate graph",
        function="measure_gate_distances",
        types="struct GateDistance { char first{}; char second{}; int distance{}; }; struct GateReach { char gate{}; int count{}; }; struct ConcourseGraph { bool valid{}; std::vector<char> gates; std::vector<GateDistance> distances; std::vector<GateReach> reachable_gate_counts; };",
        params="const std::vector<std::string>& concourse", return_type="ConcourseGraph",
        body="""ConcourseGraph out{};if(concourse.empty()){out.valid=true;return out;}const int h=static_cast<int>(concourse.size()),w=static_cast<int>(concourse.front().size());if(w==0)return out;for(const auto&r:concourse)if(static_cast<int>(r.size())!=w)return out;std::map<char,int>gate;for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=concourse[r][c];if(x>='A'&&x<='Z'){if(!gate.emplace(x,r*w+c).second)return ConcourseGraph{};}else if(x!='.'&&x!='#')return ConcourseGraph{};}for(auto [name,start]:gate){out.gates.push_back(name);std::vector<int>dist(static_cast<std::size_t>(h*w),-1);std::queue<int>q;q.push(start);dist[static_cast<std::size_t>(start)]=0;while(!q.empty()){int v=q.front();q.pop();int r=v/w,c=v%w;const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};for(int d=0;d<4;++d){int nr=r+dr[d],nc=c+dc[d];if(nr>=0&&nr<h&&nc>=0&&nc<w&&concourse[nr][nc]!='#'&&dist[static_cast<std::size_t>(nr*w+nc)]<0){dist[static_cast<std::size_t>(nr*w+nc)]=dist[static_cast<std::size_t>(v)]+1;q.push(nr*w+nc);}}}int reachable=0;for(auto [other,target]:gate){if(other!=name&&dist[static_cast<std::size_t>(target)]>=0)++reachable;if(name<other&&dist[static_cast<std::size_t>(target)]>=0)out.distances.push_back({name,other,dist[static_cast<std::size_t>(target)]});}out.reachable_gate_counts.push_back({name,reachable});}out.valid=true;return out;""",
        visible="""auto g=measure_gate_distances({"A..",".#.","..B"});if(!g.valid||g.gates!=std::vector<char>{'A','B'}||g.distances.size()!=1||g.distances[0].distance!=4||g.reachable_gate_counts.size()!=2||g.reachable_gate_counts[0].gate!='A'||g.reachable_gate_counts[0].count!=1)return 1;return 0;""",
        hidden="""auto e=measure_gate_distances({});if(!e.valid||!e.reachable_gate_counts.empty())return 1;if(measure_gate_distances({"AA"}).valid)return 1;auto g=measure_gate_distances({"A#B"});if(!g.valid||!g.distances.empty()||g.reachable_gate_counts.size()!=2||g.reachable_gate_counts[1].gate!='B'||g.reachable_gate_counts[1].count!=0)return 1;return 0;""",
        marker="std::vector<int>dist", prompt_terms=("one distance field per gate", "shortest corridor", "reachable pair", "reachable peer count", "canonical gate pair"),
        negative_old="dist[static_cast<std::size_t>(v)]+1", negative_new="1",
        negative_description="record every reached cell at distance one rather than breadth-first path length",
    ),
    _case(
        legacy_id="graph-ice-caves", task_id="ice-slide-stop-graph", title="Ice Slide Stop Graph",
        objective="treat stable stopping cells as vertices, maximal straight ice slides as weighted directed edges, and count edges by direction",
        profile="directional maximal-slide simulation between friction or wall-adjacent stopping states",
        function="build_ice_slide_graph",
        types="struct IceSlide { int from{}; int to{}; int distance{}; }; struct IceGraph { bool valid{}; std::vector<std::pair<int,int>> stops; std::vector<IceSlide> slides; std::array<int,4> slides_by_direction{}; };",
        params="const std::vector<std::string>& cave", return_type="IceGraph",
        body="""IceGraph out{};if(cave.empty()){out.valid=true;return out;}const int h=static_cast<int>(cave.size()),w=static_cast<int>(cave.front().size());if(w==0)return out;for(const auto&r:cave)if(static_cast<int>(r.size())!=w)return out;auto open=[&](int r,int c){return r>=0&&r<h&&c>=0&&c<w&&(cave[r][c]=='I'||cave[r][c]=='S');};std::vector<int>id(static_cast<std::size_t>(h*w),-1);for(int r=0;r<h;++r)for(int c=0;c<w;++c){char x=cave[r][c];if(x!='I'&&x!='S'&&x!='#')return IceGraph{};if(x=='S'){id[static_cast<std::size_t>(r*w+c)]=static_cast<int>(out.stops.size());out.stops.push_back({r,c});}}const int dr[4]={-1,0,0,1},dc[4]={0,-1,1,0};for(std::size_t from=0;from<out.stops.size();++from){auto [r,c]=out.stops[from];for(int d=0;d<4;++d){int nr=r,nc=c,distance=0;while(open(nr+dr[d],nc+dc[d])){nr+=dr[d];nc+=dc[d];++distance;}if(distance>0){int to=id[static_cast<std::size_t>(nr*w+nc)];if(to>=0){out.slides.push_back({static_cast<int>(from),to,distance});++out.slides_by_direction[static_cast<std::size_t>(d)];}}}}out.valid=true;return out;""",
        visible="""auto g=build_ice_slide_graph({"SIS"});if(!g.valid||g.stops.size()!=2||g.slides.size()!=2||g.slides[0].distance!=2||g.slides_by_direction!=std::array<int,4>{0,1,1,0})return 1;return 0;""",
        hidden="""auto e=build_ice_slide_graph({});if(!e.valid)return 1;if(build_ice_slide_graph({"X"}).valid)return 1;auto g=build_ice_slide_graph({"SIS#S"});if(!g.valid||g.stops.size()!=3||g.slides.size()!=2)return 1;return 0;""",
        marker="while(open(nr+dr[d],nc+dc[d]))", prompt_terms=("stable stop", "maximal slide", "directed weighted edge", "slides by direction", "frictionless cell"),
        negative_old="while(open(nr+dr[d],nc+dc[d]))", negative_new="if(open(nr+dr[d],nc+dc[d]))",
        negative_description="advance only one ice cell instead of simulating a maximal slide",
    ),
)
