"""Distinct v2 cases for the general-calendar-arithmetic remediation."""

from __future__ import annotations


# Each row is passed to moonlight_calendar_arithmetic_aider_tasks._task.
CASES = (
    ("calendar-subscription-cycle", "SubscriptionCycle", "Select the earliest next anchored renewal across subscriber policies.", r'''#ifndef CALENDAR_SUBSCRIPTION_CYCLE_H
#define CALENDAR_SUBSCRIPTION_CYCLE_H
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class SubscriptionCycle{public:struct Subscriber{std::string id;CivilDate anchor;int cadence_months;};struct Due{std::string id;CivilDate day;bool clamped=false;};struct Report{bool valid=false;Due selected;std::vector<Due> projected;};Report next_due(const std::vector<Subscriber>&,int completed_cycles)const;};}
#endif
''', r'''SubscriptionCycle::Report SubscriptionCycle::next_due(const std::vector<Subscriber>&xs,int completed)const{if(completed<0)return{};std::set<std::string>ids;Report out{true,{},{}};for(const auto&s:xs){if(s.id.empty()||!valid(s.anchor)||s.cadence_months<=0||!ids.insert(s.id).second)return{};long long steps=static_cast<long long>(completed+1)*s.cadence_months;CivilDate d=add_months(s.anchor,steps,s.anchor.day);if(!valid(d))return{};out.projected.push_back({s.id,d,d.day!=s.anchor.day});}if(xs.empty())return out;out.selected=*std::min_element(out.projected.begin(),out.projected.end(),[](const Due&a,const Due&b){int c=cmp(a.day,b.day);return c<0||(c==0&&a.id<b.id);});return out;}/*REFERENCE*/''', r'''int main(){using C=curriculum::SubscriptionCycle;C c;auto r=c.next_due({{"z",{2024,1,31},1},{"a",{2024,1,20},2}},0);return r.valid&&r.selected.id=="z"&&r.selected.day==curriculum::CivilDate{2024,2,29}?0:1;}\n''', r'''int main(){curriculum::SubscriptionCycle c;auto r=c.next_due({{"a",{2024,1,31},1}},1);if(!r.valid||!(r.selected.day==curriculum::CivilDate{2024,3,31}))return 1;return c.next_due({{"a",{2024,1,1},1},{"a",{2024,2,1},2}},0).valid?2:0;}\n''', r'''int main(){curriculum::SubscriptionCycle c;for(int k=0;k<24;++k)if(!c.next_due({{"x",{2000,2,29},12}},k).valid)return 1;return c.next_due({},0).valid?0:2;}\n''', "Project each unique subscriber directly from its original anchor. Select the earliest projected date and break ties by smaller ID. Empty input is valid; invalid input is atomic."),
    ("calendar-harvest-plan", "HarvestPlan", "Migrate crop windows while preserving civil-day duration.", r'''#ifndef CALENDAR_HARVEST_PLAN_H
#define CALENDAR_HARVEST_PLAN_H
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class HarvestPlan{public:struct Window{std::string crop;CivilDate planting;CivilDate harvest;};struct Entry{std::string crop;CivilDate planting;CivilDate harvest;int duration_days=0;bool valid=false;};std::vector<Entry> migrate(const std::vector<Window>&,int season_months)const;};}
#endif
''', r'''std::vector<HarvestPlan::Entry> HarvestPlan::migrate(const std::vector<Window>&xs,int months)const{std::vector<Entry>out;if(months<0)return out;for(const auto&w:xs){if(w.crop.empty()||!valid(w.planting)||!valid(w.harvest)||cmp(w.planting,w.harvest)>0){out.push_back({w.crop,{},{},0,false});continue;}long long span=ord(w.harvest)-ord(w.planting);CivilDate begin=add_months(w.planting,months,w.planting.day);CivilDate end=add_days(begin,span);out.push_back({w.crop,begin,end,static_cast<int>(span),valid(begin)&&valid(end)});}return out;}/*REFERENCE*/''', r'''int main(){curriculum::HarvestPlan p;auto r=p.migrate({{"peas",{2024,1,31},{2024,2,29}}},1);return r.size()==1&&r[0].harvest==curriculum::CivilDate{2024,3,29}&&r[0].duration_days==29?0:1;}\n''', r'''int main(){curriculum::HarvestPlan p;auto r=p.migrate({{"x",{2024,3,1},{2024,2,1}}},2);return r.size()==1&&!r[0].valid&&p.migrate({},0).empty()?0:1;}\n''', r'''int main(){curriculum::HarvestPlan p;auto r=p.migrate({{"a",{2024,1,31},{2024,3,31}}},1);return r.size()==1&&r[0].duration_days==60&&r[0].harvest==curriculum::CivilDate{2024,4,29}?0:1;}\n''', "Shift only the planting anchor by non-negative months, then reconstruct harvest from the original ordinal duration. Invalid rows remain visible."),
    ("calendar-clinic-followup", "ClinicFollowup", "Allocate recurring follow-ups around merged blackout spans.", r'''#ifndef CALENDAR_CLINIC_FOLLOWUP_H
#define CALENDAR_CLINIC_FOLLOWUP_H
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class ClinicFollowup{public:struct Plan{std::string patient;CivilDate start;int interval_days;int count;CivilDate horizon;};struct Blackout{CivilDate begin;CivilDate end;};struct Report{bool valid=false;std::vector<CivilDate>appointments;};Report allocate(const Plan&,const std::vector<Blackout>&)const;};}
#endif
''', r'''ClinicFollowup::Report ClinicFollowup::allocate(const Plan&p,const std::vector<Blackout>&raw)const{if(p.patient.empty()||!valid(p.start)||!valid(p.horizon)||p.interval_days<=0||p.count<0||cmp(p.start,p.horizon)>0)return{};std::vector<std::pair<long long,long long>>spans;for(auto b:raw){if(!valid(b.begin)||!valid(b.end)||cmp(b.begin,b.end)>0)return{};spans.push_back({ord(b.begin),ord(b.end)});}std::sort(spans.begin(),spans.end());std::vector<std::pair<long long,long long>>merged;for(auto s:spans){if(merged.empty()||s.first>merged.back().second+1)merged.push_back(s);else merged.back().second=std::max(merged.back().second,s.second);}Report out{true,{}};long long previous=ord(p.start);for(int i=1;i<=p.count;++i){long long candidate=std::max(ord(p.start)+static_cast<long long>(i)*p.interval_days,previous+1);for(auto s:merged)if(candidate>=s.first&&candidate<=s.second)candidate=s.second+1;if(candidate>ord(p.horizon))break;out.appointments.push_back(civil(candidate));previous=candidate;}return out;}/*REFERENCE*/''', r'''int main(){using C=curriculum::ClinicFollowup;C c;auto r=c.allocate({"p",{2024,2,27},1,3,{2024,3,5}},{{{2024,2,28},{2024,2,29}}});return r.valid&&r.appointments[0]==curriculum::CivilDate{2024,3,1}&&r.appointments[1]==curriculum::CivilDate{2024,3,2}?0:1;}\n''', r'''int main(){using C=curriculum::ClinicFollowup;C c;auto r=c.allocate({"p",{2024,1,1},2,4,{2024,1,5}},{{{2024,1,3},{2024,1,4}}});return r.valid&&r.appointments.size()==1&&r.appointments[0]==curriculum::CivilDate{2024,1,5}?0:1;}\n''', r'''int main(){using C=curriculum::ClinicFollowup;C c;auto r=c.allocate({"p",{2000,2,27},1,2,{2000,3,2}},{{{2000,2,28},{2000,2,28}},{{2000,2,29},{2000,2,29}}});return r.appointments.size()==2&&r.appointments[1]==curriculum::CivilDate{2000,3,2}?0:1;}\n''', "Merge overlapping or adjacent blackouts. Each nominal recurrence searches forward to the first free day and stops at the inclusive horizon."),
    ("calendar-inventory-expiry", "InventoryExpiry", "Classify inventory with explicit recall/expiry precedence.", r'''#ifndef CALENDAR_INVENTORY_EXPIRY_H
#define CALENDAR_INVENTORY_EXPIRY_H
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class InventoryExpiry{public:enum class State{active,expiring,expired,recalled,invalid};struct Product{std::string id;CivilDate made;int shelf_months;bool recalled;CivilDate recall_day;};struct Entry{std::string id;CivilDate expiry;State state=State::invalid;};std::vector<Entry>classify(const std::vector<Product>&,CivilDate,int warning_days)const;};}
#endif
''', r'''std::vector<InventoryExpiry::Entry> InventoryExpiry::classify(const std::vector<Product>&xs,CivilDate now,int warning)const{std::vector<Entry>out;if(!valid(now)||warning<0)return out;std::set<std::string>ids;for(auto p:xs){Entry e{p.id,{},State::invalid};if(p.id.empty()||!ids.insert(p.id).second||!valid(p.made)||p.shelf_months<=0||(p.recalled&&!valid(p.recall_day))){out.push_back(e);continue;}e.expiry=add_months(p.made,p.shelf_months,p.made.day);if(p.recalled&&cmp(p.recall_day,now)<=0)e.state=State::recalled;else if(cmp(e.expiry,now)<0)e.state=State::expired;else if(ord(e.expiry)-ord(now)<=warning)e.state=State::expiring;else e.state=State::active;out.push_back(e);}std::stable_sort(out.begin(),out.end(),[](const Entry&a,const Entry&b){return a.id<b.id;});return out;}/*REFERENCE*/''', r'''int main(){using C=curriculum::InventoryExpiry;C c;auto r=c.classify({{"lot",{2024,1,31},1,true,{2024,2,20}}},{2024,2,29},7);return r[0].state==C::State::recalled?0:1;}\n''', r'''int main(){using C=curriculum::InventoryExpiry;C c;auto r=c.classify({{"b",{2024,1,1},1,false,{}},{"a",{2024,1,1},3,false,{}}},{2024,2,1},0);return r[0].id=="a"&&r[1].state==C::State::expiring?0:1;}\n''', r'''int main(){using C=curriculum::InventoryExpiry;C c;auto r=c.classify({{"x",{2000,2,29},12,false,{}}},{2001,2,28},0);return r[0].expiry==curriculum::CivilDate{2001,2,28}&&r[0].state==C::State::expiring?0:1;}\n''', "Sort unique IDs. Effective recall precedes expiry; expiry before as-of is expired and the inclusive warning distance is expiring. Invalid rows remain visible."),
    ("calendar-contract-amendment", "ContractAmendment", "Replay an amendment ledger transactionally.", r'''#ifndef CALENDAR_CONTRACT_AMENDMENT_H
#define CALENDAR_CONTRACT_AMENDMENT_H
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class ContractAmendment{public:enum class Kind{set_end,extend_days};struct Amendment{int sequence;CivilDate effective;Kind kind;CivilDate new_end;int days;};struct Report{bool valid=false;CivilDate begin;CivilDate end;int rejected=-1;};Report replay(CivilDate,CivilDate,const std::vector<Amendment>&)const;};}
#endif
''', r'''ContractAmendment::Report ContractAmendment::replay(CivilDate begin,CivilDate end,const std::vector<Amendment>&input)const{CivilDate original=end;if(!valid(begin)||!valid(end)||cmp(begin,end)>0)return{};auto rows=input;std::sort(rows.begin(),rows.end(),[](auto a,auto b){return a.sequence<b.sequence;});std::set<int>seq;CivilDate prior=begin;for(auto a:rows){if(a.sequence<=0||!seq.insert(a.sequence).second||!valid(a.effective)||cmp(a.effective,prior)<0||(a.kind==Kind::set_end&&!valid(a.new_end))||(a.kind==Kind::extend_days&&a.days<=0))return{false,begin,original,a.sequence};prior=a.effective;}CivilDate current=end;for(auto a:rows){CivilDate candidate=a.kind==Kind::set_end?a.new_end:add_days(current,a.days);if(!valid(candidate)||cmp(candidate,begin)<0||cmp(a.effective,current)>0)return{false,begin,original,a.sequence};current=candidate;}return{true,begin,current,-1};}/*REFERENCE*/''', r'''int main(){using C=curriculum::ContractAmendment;C c;auto r=c.replay({2024,1,1},{2024,1,31},{{2,{2024,1,10},C::Kind::extend_days,{},2},{1,{2024,1,5},C::Kind::set_end,{2024,2,10},0}});return r.valid&&r.end==curriculum::CivilDate{2024,2,12}?0:1;}\n''', r'''int main(){using C=curriculum::ContractAmendment;C c;auto r=c.replay({2024,1,1},{2024,1,31},{{1,{2024,1,5},C::Kind::extend_days,{},2},{2,{2024,1,4},C::Kind::extend_days,{},2}});return !r.valid&&r.end==curriculum::CivilDate{2024,1,31}&&r.rejected==2?0:1;}\n''', r'''int main(){using C=curriculum::ContractAmendment;C c;auto r=c.replay({2000,2,28},{2000,2,29},{{1,{2000,2,28},C::Kind::extend_days,{},1}});return r.valid&&r.end==curriculum::CivilDate{2000,3,1}?0:1;}\n''', "Validate the complete sequence/effective-date ledger first, then replay on a local period. Any failure returns the original end and rejected sequence."),
    ("calendar-vacation-allocation", "VacationAllocation", "Charge leave against year-partitioned balances.", r'''#ifndef CALENDAR_VACATION_ALLOCATION_H
#define CALENDAR_VACATION_ALLOCATION_H
#include <map>
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class VacationAllocation{public:struct Request{std::string employee;CivilDate begin;CivilDate end;};struct Report{bool valid=false;std::map<int,int>charged;std::map<int,int>balances_after;};Report charge(const Request&,const std::map<int,int>&,const std::vector<CivilDate>&)const;};}
#endif
''', r'''VacationAllocation::Report VacationAllocation::charge(const Request&r,const std::map<int,int>&balances,const std::vector<CivilDate>&closures)const{if(r.employee.empty()||!valid(r.begin)||!valid(r.end)||cmp(r.begin,r.end)>0)return{};for(auto b:balances)if(b.second<0)return{};std::set<long long>closed;for(auto d:closures)if(!valid(d)||!closed.insert(ord(d)).second)return{};Report out{true,{},balances};for(long long z=ord(r.begin);z<=ord(r.end);++z){CivilDate d=civil(z);if(!closed.count(z))++out.charged[d.year];}for(auto c:out.charged){auto it=out.balances_after.find(c.first);if(it==out.balances_after.end()||it->second<c.second)return{};}for(auto c:out.charged)out.balances_after[c.first]-=c.second;return out;}/*REFERENCE*/''', r'''int main(){curriculum::VacationAllocation v;auto r=v.charge({"e",{2023,12,31},{2024,1,2}},{{2023,1},{2024,2}},{{2024,1,1}});return r.valid&&r.charged[2023]==1&&r.charged[2024]==1?0:1;}\n''', r'''int main(){curriculum::VacationAllocation v;auto r=v.charge({"e",{2024,2,28},{2024,3,1}},{{2024,3}},{{2024,2,29}});return r.valid&&r.charged[2024]==2?0:1;}\n''', r'''int main(){curriculum::VacationAllocation v;auto a=v.charge({"e",{1900,2,28},{1900,3,1}},{{1900,2}},{});auto b=v.charge({"e",{2000,2,28},{2000,3,1}},{{2000,3}},{});return a.valid&&a.charged[1900]==2&&b.valid&&b.charged[2000]==3?0:1;}\n''', "Iterate the inclusive span, exclude unique closures, and charge each remaining day to its calendar year. Validate every balance before any debit."),
    ("calendar-maintenance-rotation", "MaintenanceRotation", "Find the first anchored recurring service at or after as-of.", r'''#ifndef CALENDAR_MAINTENANCE_ROTATION_H
#define CALENDAR_MAINTENANCE_ROTATION_H
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class MaintenanceRotation{public:struct Machine{std::string id;CivilDate anchor;int interval_months;};struct Entry{std::string id;CivilDate next_due;int missed=0;bool valid=false;};std::vector<Entry>inspect(const std::vector<Machine>&,CivilDate)const;};}
#endif
''', r'''std::vector<MaintenanceRotation::Entry> MaintenanceRotation::inspect(const std::vector<Machine>&xs,CivilDate now)const{std::vector<Entry>out;if(!valid(now))return out;std::set<std::string>ids;for(auto m:xs){if(m.id.empty()||!valid(m.anchor)||m.interval_months<=0||!ids.insert(m.id).second){out.push_back({m.id,{},0,false});continue;}int occurrence=1,missed=0;CivilDate due=add_months(m.anchor,static_cast<long long>(occurrence)*m.interval_months,m.anchor.day);while(valid(due)&&cmp(due,now)<0){++missed;++occurrence;due=add_months(m.anchor,static_cast<long long>(occurrence)*m.interval_months,m.anchor.day);}out.push_back({m.id,due,missed,valid(due)});}return out;}/*REFERENCE*/''', r'''int main(){curriculum::MaintenanceRotation m;auto r=m.inspect({{"x",{2024,1,31},1}},{2024,3,1});return r[0].next_due==curriculum::CivilDate{2024,3,31}&&r[0].missed==1?0:1;}\n''', r'''int main(){curriculum::MaintenanceRotation m;auto r=m.inspect({{"x",{2023,1,31},1}},{2023,3,30});return r[0].next_due==curriculum::CivilDate{2023,3,31}?0:1;}\n''', r'''int main(){curriculum::MaintenanceRotation m;auto r=m.inspect({{"x",{2000,2,29},12}},{2004,2,28});return r[0].next_due==curriculum::CivilDate{2004,2,29}&&r[0].missed==3?0:1;}\n''', "Project each occurrence directly from the original anchor. Count due dates strictly before as-of as missed; equality is next due."),
    ("calendar-licence-grace", "LicenceGrace", "Classify submissions across inclusive policy boundaries.", r'''#ifndef CALENDAR_LICENCE_GRACE_H
#define CALENDAR_LICENCE_GRACE_H
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class LicenceGrace{public:enum class State{active,grace,reinstatement_required,invalid};struct Policy{int grace_days;int reinstatement_months;};struct Report{State state=State::invalid;CivilDate grace_end;CivilDate reinstatement_end;};Report evaluate(CivilDate,CivilDate,Policy)const;};}
#endif
''', r'''LicenceGrace::Report LicenceGrace::evaluate(CivilDate expiry,CivilDate submitted,Policy p)const{if(!valid(expiry)||!valid(submitted)||p.grace_days<0||p.reinstatement_months<0)return{};CivilDate grace=add_days(expiry,p.grace_days),rein=add_months(grace,p.reinstatement_months,grace.day);if(!valid(grace)||!valid(rein))return{};State s=cmp(submitted,expiry)<=0?State::active:cmp(submitted,grace)<=0?State::grace:cmp(submitted,rein)<=0?State::reinstatement_required:State::invalid;return{s,grace,rein};}/*REFERENCE*/''', r'''int main(){using C=curriculum::LicenceGrace;C c;auto r=c.evaluate({2024,2,28},{2024,3,1},{2,1});return r.state==C::State::grace?0:1;}\n''', r'''int main(){using C=curriculum::LicenceGrace;C c;auto a=c.evaluate({2024,1,31},{2024,2,2},{2,1}),b=c.evaluate({2024,1,31},{2024,2,3},{2,1});return a.state==C::State::grace&&b.state==C::State::reinstatement_required?0:1;}\n''', r'''int main(){using C=curriculum::LicenceGrace;C c;auto r=c.evaluate({2000,2,29},{2001,2,28},{0,12});return r.reinstatement_end==curriculum::CivilDate{2001,2,28}?0:1;}\n''', "Expiry, grace end, and reinstatement end are inclusive in their respective tiers. Later or invalid input is invalid."),
    ("calendar-release-train", "ReleaseTrain", "Propagate shifted milestones through a dependency DAG.", r'''#ifndef CALENDAR_RELEASE_TRAIN_H
#define CALENDAR_RELEASE_TRAIN_H
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class ReleaseTrain{public:struct Milestone{std::string id;CivilDate day;std::vector<std::string>predecessors;};struct Shifted{std::string id;CivilDate day;};struct Report{bool valid=false;std::vector<Shifted>ordered;std::vector<std::string>collisions;};Report propagate(const std::vector<Milestone>&,int)const;};}
#endif
''', r'''ReleaseTrain::Report ReleaseTrain::propagate(const std::vector<Milestone>&xs,int months)const{if(months<0)return{};std::map<std::string,int>idx;for(int i=0;i<static_cast<int>(xs.size());++i)if(xs[i].id.empty()||!valid(xs[i].day)||!idx.emplace(xs[i].id,i).second)return{};std::vector<int>degree(xs.size());std::vector<std::vector<int>>edges(xs.size());for(int i=0;i<static_cast<int>(xs.size());++i){std::set<std::string>seen;for(auto p:xs[i].predecessors){auto it=idx.find(p);if(it==idx.end()||it->second==i||!seen.insert(p).second)return{};++degree[i];edges[it->second].push_back(i);}}std::set<std::pair<std::string,int>>ready;for(int i=0;i<static_cast<int>(xs.size());++i)if(!degree[i])ready.insert({xs[i].id,i});std::vector<CivilDate>shifted(xs.size());Report out{true,{},{}};while(!ready.empty()){int u=ready.begin()->second;ready.erase(ready.begin());CivilDate d=add_months(xs[u].day,months,xs[u].day.day);for(auto p:xs[u].predecessors){CivilDate minimum=add_days(shifted[idx[p]],1);if(cmp(d,minimum)<0)d=minimum;}shifted[u]=d;out.ordered.push_back({xs[u].id,d});for(int v:edges[u])if(!--degree[v])ready.insert({xs[v].id,v});}if(out.ordered.size()!=xs.size())return{};std::map<long long,std::vector<std::string>>by;for(auto m:out.ordered)by[ord(m.day)].push_back(m.id);for(auto row:by)if(row.second.size()>1)out.collisions.insert(out.collisions.end(),row.second.begin(),row.second.end());return out;}/*REFERENCE*/''', r'''int main(){using C=curriculum::ReleaseTrain;C c;auto r=c.propagate({{"build",{2024,1,31},{}},{"ship",{2024,1,31},{"build"}}},1);return r.valid&&r.ordered[1].day==curriculum::CivilDate{2024,3,1}?0:1;}\n''', r'''int main(){using C=curriculum::ReleaseTrain;C c;return c.propagate({{"a",{2024,1,1},{"b"}},{"b",{2024,1,2},{"a"}}},1).valid?1:0;}\n''', r'''int main(){using C=curriculum::ReleaseTrain;C c;auto r=c.propagate({{"a",{2000,2,29},{}},{"b",{2001,2,27},{"a"}}},12);return r.valid&&r.ordered[1].day==curriculum::CivilDate{2002,2,27}?0:1;}\n''', "Topologically select ready milestones by ID, shift original dates, and push each dependent to at least one day after every predecessor. Cycles reject atomically."),
    ("calendar-lease-portfolio", "LeasePortfolio", "Aggregate occupancy with an ordinal difference sweep.", r'''#ifndef CALENDAR_LEASE_PORTFOLIO_H
#define CALENDAR_LEASE_PORTFOLIO_H
#include <string>
#include <vector>
namespace curriculum{struct CivilDate{int year=0;int month=0;int day=0;};inline bool operator==(CivilDate a,CivilDate b){return a.year==b.year&&a.month==b.month&&a.day==b.day;}class LeasePortfolio{public:struct Lease{std::string id;CivilDate begin;CivilDate end;};struct Report{bool valid=false;int occupied_days=0;int overlap_days=0;int gap_days=0;int peak=0;};Report summarize(const std::vector<Lease>&)const;};}
#endif
''', r'''LeasePortfolio::Report LeasePortfolio::summarize(const std::vector<Lease>&xs)const{if(xs.empty())return{true,0,0,0,0};std::set<std::string>ids;std::map<long long,int>delta;long long first=std::numeric_limits<long long>::max(),last=std::numeric_limits<long long>::min();for(auto l:xs){if(l.id.empty()||!valid(l.begin)||!valid(l.end)||cmp(l.begin,l.end)>0||!ids.insert(l.id).second)return{};long long b=ord(l.begin),e=ord(l.end);++delta[b];--delta[e+1];first=std::min(first,b);last=std::max(last,e);}Report out{true,0,0,0,0};int active=0;auto it=delta.begin();for(long long day=first;day<=last;++day){while(it!=delta.end()&&it->first==day){active+=it->second;++it;}if(active)++out.occupied_days;else ++out.gap_days;if(active>=2)++out.overlap_days;out.peak=std::max(out.peak,active);}return out;}/*REFERENCE*/''', r'''int main(){curriculum::LeasePortfolio p;auto r=p.summarize({{"a",{2024,1,1},{2024,1,3}},{"b",{2024,1,3},{2024,1,5}}});return r.valid&&r.occupied_days==5&&r.overlap_days==1&&r.peak==2?0:1;}\n''', r'''int main(){curriculum::LeasePortfolio p;auto r=p.summarize({{"a",{2024,1,1},{2024,1,1}},{"b",{2024,1,3},{2024,1,3}}});return r.valid&&r.gap_days==1?0:1;}\n''', r'''int main(){curriculum::LeasePortfolio p;auto r=p.summarize({{"a",{2000,2,28},{2000,3,1}},{"b",{2000,2,29},{2000,2,29}},{"c",{2000,2,29},{2000,2,29}}});return r.occupied_days==3&&r.overlap_days==1&&r.peak==3?0:1;}\n''', "Inclusive leases feed one difference sweep. Occupied means active at least one, overlap at least two regardless of multiplicity, and gap zero. Empty input is valid."),
)


PROFILES = {
    "calendar-subscription-cycle": ("anchor-preserving month projection and earliest-due reduction", "std::min_element"),
    "calendar-harvest-plan": ("ordinal duration reconstruction after one shifted anchor", "long long span"),
    "calendar-clinic-followup": ("blackout interval merge and forward free-day search", "merged"),
    "calendar-inventory-expiry": ("recall-first event precedence classification", "State::recalled"),
    "calendar-contract-amendment": ("full validation followed by transactional ledger replay", "CivilDate original"),
    "calendar-vacation-allocation": ("year-partitioned inclusive span debit", "charged"),
    "calendar-maintenance-rotation": ("direct anchored recurrence search and missed count", "occurrence"),
    "calendar-licence-grace": ("inclusive ordered policy tier construction", "reinstatement_end"),
    "calendar-release-train": ("ID-stable topological dependency propagation", "degree"),
    "calendar-lease-portfolio": ("ordinal difference sweep for occupancy and gaps", "delta"),
}


NEGATIVE_MUTATIONS = {
    "calendar-subscription-cycle": ("add_months(s.anchor,steps,s.anchor.day)", "add_months(s.anchor,steps,std::min(s.anchor.day,28))", "loses the original month-end anchor"),
    "calendar-harvest-plan": ("CivilDate end=add_days(begin,span);", "CivilDate end=add_months(w.harvest,months,w.harvest.day);", "shifts both endpoints instead of preserving duration"),
    "calendar-clinic-followup": ("candidate=s.second+1", "candidate=s.first-1", "moves a blocked appointment backward"),
    "calendar-inventory-expiry": ("if(p.recalled&&cmp(p.recall_day,now)<=0)e.state=State::recalled;else if(cmp(e.expiry,now)<0)", "if(cmp(e.expiry,now)<0)e.state=State::expired;else if(p.recalled&&cmp(p.recall_day,now)<=0)", "tests expiry before effective recall"),
    "calendar-contract-amendment": ("||cmp(a.effective,prior)<0", "||false", "accepts decreasing effective dates instead of rejecting the ledger atomically"),
    "calendar-vacation-allocation": ("if(!closed.count(z))++out.charged[d.year];", "if(closed.count(z))++out.charged[d.year];", "charges closures instead of excluding them"),
    "calendar-maintenance-rotation": ("++missed;++occurrence;due=add_months(m.anchor,static_cast<long long>(occurrence)*m.interval_months,m.anchor.day);", "++missed;++occurrence;due=add_months(due,m.interval_months,due.day);", "chains from clamped occurrences"),
    "calendar-licence-grace": ("cmp(submitted,grace)<=0?State::grace", "cmp(submitted,grace)<0?State::grace", "excludes the inclusive grace endpoint"),
    "calendar-release-train": ("if(cmp(d,minimum)<0)d=minimum;", "if(cmp(d,minimum)<0)d=d;", "does not propagate predecessor order"),
    "calendar-lease-portfolio": ("if(active>=2)++out.overlap_days;", "if(active==2)++out.overlap_days;", "misses overlap with three active leases"),
}
